### ISSUE TITLE
Variable expansion in strings

### ISSUE THREAD

**Issue by michalfita** [casey/just#1012]
At the moment to use content of one variable in string assigned to another variable I have to:
```
VARIABLE := "content"
SINGLE := 'single ' + VARIABLE
MULTI := """
    multi """ + VARIABLE + """
"""

@default:
    echo SINGLE {{SINGLE}}
    echo MULTI {{MULTI}}
```
what is more complex cases is very hard to read and non-trivial to write.

The output is:
```
$ just
SINGLE single content
MULTI multi content
```

I'd like to achieve the same with:
```
VARIABLE := "content"
SINGLE := "single {{VARIABLE}}"
MULTI := """
    multi {{VARIABLE}}
"""

@default:
    echo SINGLE {{SINGLE}}
    echo MULTI {{MULTI}}
```
but at the moment the output is:
```
just
SINGLE single {{VARIABLE}}
MULTI multi {{VARIABLE}}
```

Is this fixable?

**Comment by casey** [comment]
This has been a longstanding feature request, but hasn't been implemented yet. See #11 for the issue, and #822 for the PR.
