### ISSUE TITLE
Ignore byte order mark in source files

### ISSUE THREAD

**Issue by casey** [casey/just#1017]
Someone had a byte order mark in their justfile, which the parser doesn't like.

We should:

- Disallow byte order marks, and have a better error message
- Allow byte order marks and print a warning
- Allow byte order marks and not print a warning

**Comment by runeimp** [comment]
Some apps always create a BOM for UTF-8 docs. A warning would be odd to me because it's part of UTF-8 and really only exists to confirm the file is UTF-8 instead of just ASCII. It's pretty easy to skip-over though. So I'd say allow BOM and without any warnings.

**Comment by casey** [comment]
Sounds reasonable to me. Merging #1021 to ignore leading BOMs.
