### ISSUE TITLE
Variable `PATH` is defined in terms of itself

### ISSUE THREAD

**Issue by jchook** [casey/just#1024]
Experimenting moving from `yarn` package.json scripts to `just`. 

Yarn automatically adds ./node_modules/.bin to the executable search PATH. To replicate this in just, I tried:

```just
export PATH := ("./node_modules/.bin:" + env_var(PATH))
```
However, just doesn't like this and reports "error: Variable \`PATH\` is defined in terms of itself".

Does just provide a way to update `$PATH` in a global way?

**Comment by casey** [comment]
The argument to `env_var` should be a string, not an identifier, like so:

```
export PATH := "./node_modules/.bin:" + env_var("PATH")
```

Let me know if that works, and feel free to reopen if it doesn't!
