### ISSUE TITLE
Can't run Recipe with Subsequent Dependencies only 

### ISSUE THREAD

**Issue by ykis-0-0** [casey/just#1026]
I used this `justfile`:

```make
default:
  just --list

animate: && (render 'animate')
  mkdir -p {{invocation_directory()}}/frames_$(date '+%Y-%m-%d %H:%m:%S %Z')

render type=single:
  cd {{invocation_directory()}}; povray project.ini project.ini[{{type}}]
```

then I ran `just animate`, and I got:
```
5e6ee525c46c:/workspaces/POV-Ray/$ just animate
error: Unknown start of token:
  |
4 | animate: && (render 'animate')
  |          ^
5e6ee525c46c:/workspaces/POV-Ray/$
```

Is such usage supported or will be supported?
If it won't be added would you please shed some light on an alternative solution?
Thank you very much!

N.B.: If it's relevant I'm running `just` from `apk-tools` on Alpine 3.14.3 in Docker :-)

**Comment by ykis-0-0** [comment]
Sorry, I have found out that the version supplied on `apk-tools` is on `v0.9.5`
I have tried again on `v0.10.3`, and the error is gone, thank you very much!

**Comment by casey** [comment]
@ykis-0-0 No worries, glad you got it working, and good to hear that someone is using subsequent dependencies!
