### ISSUE TITLE
`just-nix` plans

### ISSUE THREAD

**Issue by blaggacao** [casey/just#1038]
@casey Hi! Long time no see!

@kamadorueda is prototyping a couple of interesting things at https://github.com/on-nix/ and we have been discussing the possibility of extending `just` to exhibit a nix interface
into specially prepared `**/task.nix` contract files.

The general (incipient) idea would be that we can point in `Justfile` to an attribute of a nix evaluation that would then provide an attribute set of `just`-runnable tasks back to `just` according to  a well-defined interface.

If an entire repo automation shall be driven by such task runner (`just-nix`), we also are considering a fuzzy-search frontend to quickly search the task list.

[`makes`](https://github.com/fluidattacks/makes) has prototyped such an UX in combination with a strict naming scheme that identifies all tasks _mandatorily_ by a relpath to the repo root, such as for example `m . /patroni/enterPsqlOnLeader`, a task that is defined (& fully auditable) at `makes/patroni/enterPsqlOnLeader/*`.

I wanted to open this issue to let you know and make this a shared brainstorming of sort so that we make sure we have your feedback before even starting.

Cheers!

**Comment by blaggacao** [comment]
Visual of current `makes` tui - as used in repos with upwards of 300 individual tasks.
![image](https://user-images.githubusercontent.com/7548295/143923319-5097e71e-5d0f-423d-bbf3-62888ce2b29b.png)

**Comment by casey** [comment]
That's very cool! I'm not sure I understand how `just` and `nix` would integrate. Would `just` expose recipes to `nix`, or would things from `nix` be exposed to `just`?

**Comment by blaggacao** [comment]
In my current ideation, jobs from nix would be exposed to just.

**Comment by blaggacao** [comment]
With today's release of https://github.com/divnix/std by a good friend of mine, it seems to be about the right time to prototype a `just` "Organelle".

`just` could be instructed to consume all _runnables_ below `outputs.just.${system}.*` of the `flake.nix`'s outputs, in addition to what's in `Justfile`.

Maybe a little `just` organelle library could be in order to make some things a little easier, e.g. have a unified and consistent interface into `binWriter` functions (always lint-checked).

/cc @kamadorueda

**Comment by casey** [comment]
> In my current ideation, jobs from nix would be exposed to just.

What is the advantage of running these jobs from `just`, instead of running them directly?

**Comment by blaggacao** [comment]
> What is the advantage of running these jobs from just, instead of running them directly?

"Directly" can mean in reality a couple of things, most prominently, via the `nix run` CLI interface, but also other CLI frontends are emerging for different use cases.

`just` is a well established task runner and has a pretty neat and familiar UX for a lot of devs.

I, therefore, see workflows play out where devs can prototype scripts in plain `Justfiles` which then can gradually be made reproducible via nix.

On the other hand, devops teams can deliver tooling right into the `just` frontends across various repos from a central location.

Another aspect is that most of the time only roughly 10% of flake outputs are ment to be runnables in the sense of a repo task runner, so the `just` frontend can act as a good filter and hide the noise to the average developer.

**Comment by blaggacao** [comment]
Maybe you'd be open to ideas to invoke just as a role to further filter tasks?

Maybe it's not the most useful idea, but I had thought about something like:

- `just --as dev`
- `just --as devops`
- `just --as pm` (projectmanager)

If we can come up with an elegant way to pre-filter on metadata we can further reduce the noise and boost any repo's onboarding experience. (`just --as newcomer`)

**Comment by casey** [comment]
I think I would need to see a concrete example, as simple as possible with as few moving pieces as possible, to understand the value proposition, as well as understand how difficult it would be to implement. I still don't understand if just would call nix or nix would call just, and what the actual concrete things are that the developer would do, i.e. files he would create and commands he would run.

My current feeling is that it sounds complicated (it would be a large change to the codebase to allow two sources of tasks, i.e. justfile recipes as well as nix expresssions) and I'm not sure if it would provide enough benefit to be useful. It would only be usable to the subset of people who use nix, and then an even smaller subset who knew about and took advantage of this integration.

And thinking about it more, I think even if it was definitely useful, I wouldn't want to do a specific integration with `nix`, but would rather some kind of more general plugin system, which allowed drawing additional commands from some other source.

**Comment by blaggacao** [comment]
> but would rather some kind of more general plugin system, which allowed drawing additional commands from some other source.

That sounds about perfect! I'd have a strong & urgent motivation to implement such a plugin for flakes. :+1: - task libraries &mdash; enabled by this &mdash; are a huge plus in reusablity.

**Comment by blaggacao** [comment]
Here is an example of how a project could expose just tasks:

https://github.com/input-output-hk/bitte-cells/blob/WIP-cardano/cells/cardano/justTasks.nix

I think `just` also would require the equivalent of a task comment (=description) as some sort of "contract" attribute on every task. Running such task is then actually rather simple and equivalent to:

`nix run .#justTasks.<current system>.cardano-node-2nix`

A contract could look like so:

```nix
# outputs of a nix flake:
{ justTasks.${system} = {
    task-name = {
      description = "foo";
      runnable = builtins.derivation ...; # TL;DR; a typical nix runnable
    };
  };
}
# runnable as: nix run .#justTasks.<current system>.task-name.runnable
```

**Comment by blaggacao** [comment]
We now ended up "rendering" Justfiles from their source task specifications (in Nix).

This has the added advantage that a consumer can still greet and read a familiar `Justfile`.

This bridges the gap into the DevOps lingua franca world of Nix for the un-initiated. Which probably is the whole point of the exercise:

https://github.com/divnix/std/issues/118

Hence, I can close this particular issue.

Thank you for the discussion! I hope the plugin system idea might come up again in the future.

**Comment by jmgilman** [comment]
The "rendering" is, however, not very pretty. It would be great if we could consider support for going from JSON -> Justfile (see #1331).
