### ISSUE TITLE
Install Script stopped working

### ISSUE THREAD

**Issue by ykis-0-0** [casey/just#1042]
When the `aarch64` binaries are updated to use `musl` in #1037,
the [latest release](https://github.com/casey/just/releases/tag/0.10.4) still uses `just-0.10.4-aarch64-unknown-linux-gnu.tar.gz` as the filename
rather than `just-0.10.4-aarch64-unknown-linux-musl.tar.gz`

This made the install script at `https://just.systems/install.sh` failed.

**Comment by casey** [comment]
Thanks for reporting this, and sorry for the breakage!

I'm in the process of releasing 0.10.5, which will have the new binaries:

https://github.com/casey/just/pull/1043
