### ISSUE TITLE
Does a child directory with it's own justfile allow running recipes from parent?

### ISSUE THREAD

**Issue by asdf8dfafjk** [casey/just#1048]
Related to #761 (creating new for ease of discussion)

Hi, say my directory structure is as following:

```
foo/
	.justfile (recipes a, b)
	bar/
		.justfile (recipes c, d)
```

Doing a `just b` inside bar doesn't currently work for me. I wonder if it's only me? And if not, is this something you think might be a useful addition? If you think it would be useful, and would be kind enough to point me to the files that need to be changed (should be hopefully a quick couple of minutes) I'd be very interested in submitting a PR. I'd also be interested in spending time designing if you'd like to implement some ideas from #761.

**Comment by casey** [comment]
I'm not sure I understand, is `bar` a child directory of `foo`?

**Comment by asdf8dfafjk** [comment]
Yes it is, I somehow missed the backticks.

**Comment by asdf8dfafjk** [comment]
Duplicate of #1036, sorry
