### ISSUE TITLE
Windows + sh + join function incompatibility

### ISSUE THREAD

**Issue by torkleyy** [casey/just#1051]
I'm using the `join` function to generate all my paths, but when trying to use the `justfile` on Windows alle the paths are messed up because

1. `join` uses native path separators
2. the default shell expects forward slashes

What would be the best solution for this problem?

One option would be to add a `join_unix` which uses forward slashes.

**Comment by casey** [comment]
Ahh, that's unfortunate. Perhaps I should have made `join` use `/`, regardless of the platform, since I think Windows supports them anyways, and that's the only platform that uses backslashes.

`join_unix` isn't very elegant, but I wouldn't be opposed to adding it.

**Comment by torkleyy** [comment]
Yeah, I agree. Maybe it would be better to add an option that changes the behavior of `join`?

**Comment by casey** [comment]
That's not a bad idea, although it would mean that you couldn't use join with `/` and `\` in the same justfile.

Maybe `join_with(sep, args…)` is a good idea, so if you don't want native path separators, you just pass in the separator you want.

**Comment by casey** [comment]
We added an `/` operator, which can be used to join paths with `/`.
