### ISSUE TITLE
How to pass on command line arguments unchanged?

### ISSUE THREAD

**Issue by mpdude** [casey/just#1054]
Please consider this `Justfile`:

```justfile
test *args='':
    bash -c 'while (( "$#" )); do echo - $1; shift; done' -- "{{args}}"
```

When running:

`$ just test first "second arg" third`

... I get ...

`- first second arg third`

What syntax should I use for `{{args}}` in the `Justfile` to pass on arguments unchanged, i. e. to get as result:

```
- first
- second arg
- third
```

🤷🏻‍♂️

**Comment by casey** [comment]
The best thing to do is to turn on `positional-arguments`, which passes positional arguments to each recipe line, which avoids unwanted splitting:

```
set positional-arguments

test *args='':
    bash -c 'while (( "$#" )); do echo - $1; shift; done' -- "$@"
```

This works for me, but feel free to reopen if it doesn't work for your use case!

**Comment by mpdude** [comment]
Will try, thanks!

Probably `"$@"` is what I should have been trying (and know from bash), but did not notice it in the README.
