### ISSUE TITLE
Wrong exit code when using PowerShell shebang

### ISSUE THREAD

**Issue by michidk** [casey/just#1060]
I sadly don't have the time to investigate this further, but it seems like the code evaluating the exit codes when a shebang was specified has a bug:

Running the following code (in the `test` module of `justfile.rs`):
```rust
  #[cfg(target_os = "windows")]
  run_error! {
    name: run_powershell,
    src: "
      a:
        exit 200
    ",
    args: ["--shell", "powershell.exe", "--shell-arg", "-c", "a"],
    error: Code {
      code,
      ..
    },
    check: {
      assert_eq!(code, 200);
    }
  }
```
Runs fine and the check passes.

```rust
  #[cfg(target_os = "windows")]
  run_error! {
    name: run_shebang_powershell,
    src: "
      a:
        #!powershell.exe
        exit 200
    ",
    args: ["a"],
    error: Code {
      code,
      ..
    },
    check: {
      assert_eq!(code, 200);
    }
  }
```
Fails, because the exit code is 1.

The combination of both examples (`--shell powershell` + shebang) reports 1 as well.

**Comment by michidk** [comment]
A similar problem (if not the same) seems to be with the backticks
```rust
  run_error! {
    name: backtick_code,
    src: "
      a:
       echo {{`f() { return 100; }; f`}}
    ",
    args: ["--shell", "powershell.exe", "--shell-arg", "-c", "a"],
    error: Error::Backtick {
      token,
      output_error: OutputError::Code(code),
    },
    check: {
      assert_eq!(code, 100);
      assert_eq!(token.lexeme(), "`f() { return 100; }; f`");
    }
  }
```
Will also fail because it returns the exit code 1 instead of 100.

EDIT: using `exit` instead of `return` yields the same result.

**Comment by casey** [comment]
Is this just the way that powershell reports error codes? I.e. if you do `return 100`, does powershell report the error code as 1 or 100?

**Comment by michidk** [comment]
> Is this just the way that powershell reports error codes? I.e. if you do `return 100`, does powershell report the error code as 1 or 100?

I'm no PowerShell pro myself, but seems like it behaves similarly like on Linux:
![image](https://user-images.githubusercontent.com/3979930/147913412-13cfd48a-5c1e-4991-9be6-988392809397.png)

**Comment by casey** [comment]
Gotcha, can you open a draft PR with a failing test?

**Comment by michidk** [comment]
The aforementioned failing test (`run_shebang_powershell`) is now in my new PR here: https://github.com/casey/just/pull/1066/files#diff-7f1715f83f401c5a708de4c89128b39d561b79907de38aa51ecbc421790d5a8aR511
The second failing test (`backtick_code`): https://github.com/casey/just/pull/1066/files#diff-7f1715f83f401c5a708de4c89128b39d561b79907de38aa51ecbc421790d5a8aR529

As you can see, those tests are indeed failing:
https://github.com/casey/just/runs/4700129707?check_suite_focus=true
```
---- justfile::tests::backtick_code stdout ----
thread 'justfile::tests::backtick_code' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `100`', src\justfile.rs:541:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- justfile::tests::run_shebang_powershell stdout ----
thread 'justfile::tests::run_shebang_powershell' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `200`', src\justfile.rs:524:7
```

EDIT:
This test also fails (`export_failure_powershell`) https://github.com/casey/just/pull/1066/files#diff-7f1715f83f401c5a708de4c89128b39d561b79907de38aa51ecbc421790d5a8aR547:
```
---- justfile::tests::export_failure_powershell stdout ----
thread 'justfile::tests::export_failure_powershell' panicked at 'Expected runtime error: ()', src\justfile.rs:547:3
```

**Comment by casey** [comment]
I think this one is working as intended, powershell just doesn't return the right exit code.
