### ISSUE TITLE
Export_failure test fails on Windows with Powershell

### ISSUE THREAD

**Issue by michidk** [casey/just#1061]
Regarding the `export_failure` unit test here: https://github.com/casey/just/blob/master/src/justfile.rs#L645

When running the code with `args: ["--quiet", "--shell", "powershell.exe", "--shell-arg", "-c", "wut"],` on Windows the test will fail, because no `Code` runtime error will occur.

I am not sure why it would fail on Linux either, maybe someone can elaborate what the purpose of this test is.

**Comment by casey** [comment]
Is this failing on master?

**Comment by michidk** [comment]
> Is this failing on master?

Yes it fails on the most recent commit on master (125801e7e94cd8414ae10014940d3fd4ca05e969).

**Comment by casey** [comment]
I'm not sure I understand, this recent test run passed on windows: https://github.com/casey/just/runs/4686879325?check_suite_focus=true

**Comment by michidk** [comment]
> I'm not sure I understand, this recent test run passed on windows: [casey/just/runs/4686879325?check_suite_focus=true](https://github.com/casey/just/runs/4686879325?check_suite_focus=true)

But not with the following args `args: ["--quiet", "--shell", "powershell.exe", "--shell-arg", "-c", "wut"]`

**Comment by michidk** [comment]
I think the export feature is not yet compatible with PowerShell.

**Comment by casey** [comment]
That's okay, not all tests are expected to be compatible with PowerShell, since a lot of them use shell-specific constructs.

**Comment by michidk** [comment]
Okay I was just worried that this feature wouldn't work with PowerShell at all, because it uses no sh/linux specific constructs in that test as far as I can see.

I published the unit test here: https://github.com/casey/just/pull/1066/files#diff-7f1715f83f401c5a708de4c89128b39d561b79907de38aa51ecbc421790d5a8aR547
as you can see its failing: https://github.com/casey/just/runs/4700129707?check_suite_focus=true

```
---- justfile::tests::export_failure_powershell stdout ----
thread 'justfile::tests::export_failure_powershell' panicked at 'Expected runtime error: ()', src\justfile.rs:547:3
```

**Comment by casey** [comment]
Okay, sweet, that's for clarifying, I didn't understand what the issue was. I'll leave #1060 open to track the issue.

**Comment by michidk** [comment]
I think this is a different issue than #1060. #1060 is about the exit code this one is about the export feature.

**Comment by casey** [comment]
Ahhhh, okay, my bad, again, totally misunderstood. I think that this is not a bug. The test is checking that `baz` is not exported, and that trying to evaluate `$baz` is an error. However, the only reason this is an error is because we pass `-u` to the shell by default, which makes evaluating undefined variables an error. By default, does powershell treat evaluating undefined variables as an error? If not, it probably needs to be passed an additional flag, analogous to `-u`.

**Comment by michidk** [comment]
I don't think there is such a flag in powershell

**Comment by casey** [comment]
I opened #1071 to track setting strict mode when `windows-powershell` is set.
