### ISSUE TITLE
export_assignment_backtick fails when run with PowerShell on Windows

### ISSUE THREAD

**Issue by michidk** [casey/just#1062]
The unit test `export_assignment_backtick` (https://github.com/casey/just/blob/master/src/evaluator.rs#L326) fails (or to be specific: never terminates without user input) on Windows when executing with PowerShell (args: `args: ["--quiet", "--shell", "powershell.exe", "--shell-arg", "-c", "recipe"],`):
The user gets a prompt asking for user input that looks like this: `InputObject[0]: `
If the user presses enter, the test fails because no runtime error occurred during the execution. This behaviour might be similar to https://github.com/casey/just/issues/1061.

**Comment by casey** [comment]
I think it's okay if not all tests work on powershell. Changing the shell will cause many tests to fail, since presumably powershell is extremely different. We can just add a single test that checks that `set windows-powershell := true` works, and not worry about the rest.
