### ISSUE TITLE
Any way to stop running the main recipe when its dependency fails?

### ISSUE THREAD

**Issue by hustcer** [casey/just#1065]
In the following `Justfile`, if `build` fails is there any way to make `test` never run? Thanks

```bash
build:
    cc main.c foo.c bar.c -o main

test: build
    ./test
```

**Comment by casey** [comment]
Hi! This should already be the case, if `cc` returns a nonzero exit code,
test should never run. Is this not the case?

**Comment by hustcer** [comment]
> Hi! This should already be the case, if `cc` returns a nonzero exit code, test should never run. Is this not the case?

I found that it didn't work for me because I'm using nushell, and there is a related issue [here](https://github.com/nushell/nushell/issues/3817). It's lucky that using `exit ($code) --now` will stop the main recipe from running. Thanks again.

**Comment by casey** [comment]
Nice, glad you got it working!
