### ISSUE TITLE
Recommended default indentation

### ISSUE THREAD

**Issue by pickfire** [casey/just#1070]
I see some examples in just project using 2 spaces and some using 4 spaces, which is the recommended spacing? Is there like a recommended one like rust or there is none and totally up to the developer?

I was asking here because I added tree-sitter-just to helix and wanted to set the default indentation and I don't see a consistent indentation across the project. https://github.com/helix-editor/helix/pull/1468

**Comment by kenden** [comment]
Support for just was just added in Helix
https://github.com/helix-editor/helix/blob/master/CHANGELOG.md?plain=1#L93

**Comment by casey** [comment]
I like two spaces and use them for the readme and the main project justfile, so I guess that's the recommended indentation.
