### ISSUE TITLE
Query current recipe name

### ISSUE THREAD

**Issue by mihaigalos** [casey/just#1072]
Hi, this is a feature request for reflection on the rule name.
Let me know what you think and if I could even get involved.

Example:

```justfile
foo:
    echo This is rule {{ builtin_rule_name }}
```

Expected result:
```bash
$ just foo
This is rule foo
```

**Comment by bew** [comment]
I'm curious, how would you use that?

**Comment by mihaigalos** [comment]
Would increase cohesion and reduce coupling:
```justfile
test: build
    #!/bin/bash
    for test in $(grep ^_test_ Justfile | cut -d':' -f1);
    do
        just $test && true || err "Stopping."
    done

_print_test_parameters test_name params:
    echo test_name params

_test_A:
    _print_test_parameters {{ builtin_rule_name }} "data_A"

_test_B:
    _print_test_parameters {{ builtin_rule_name }} "data_B"
```

**Comment by casey** [comment]
Thanks for the feature request!

I'm not sure I understand the use case. In the example you gave, is the purpose to print the test name and arguments before they run?

**Comment by mihaigalos** [comment]
No real "test" actually taking place, just the name starting with `_test`.
It would print the test names and args before actually running the test, yes.

The use case would be automatically propagating the recipe info to another recipe to:
* reduce duplication (coupling to a hard-coded recipe name).
  * don't need to write:
  ```justfile
  _test_A:
      echo _test_A "data_A"
  ```
* increase cohesion (similar structure and behavior aggregated together).

**Comment by casey** [comment]
I'm not sure I see the advantage, to me, this:

```
_test_A:
    echo _test_A "data_A"
```

Seems much less complicated than:

```
  _print_test_parameters {{ builtin_rule_name }} "data_A"
```

Also, you can't call recipes directly in a recipe body, so you would have to write:

```
  just _print_test_parameters {{ builtin_rule_name }} "data_A"
```

**Comment by mihaigalos** [comment]
Let me start over.

[Here](https://github.com/mihaigalos/aim/blob/7c48e9e564c01fcaa75b9d4432f725f1331c2224/test/https/Justfile#L80) I have multiple duplication of `_test_curl_put_binary_file`.
This violates a couple of principles and is error-prone.

Therefore, I would like every `_test` to start with the 1st line saying something like:
`test_name={{ name_of_test }}` and then use `$test_name` everywhere in the test body.

Does that make more sense? I wanted to provide a minimal example but perhaps am very tired now.

**Comment by casey** [comment]
> [Here](https://github.com/mihaigalos/aim/blob/7c48e9e564c01fcaa75b9d4432f725f1331c2224/test/https/Justfile#L80) I have multiple duplication of `_test_curl_put_binary_file`. This violates a couple of principles and is error-prone.

I think I might be missing something, but I only see one definition of [_test_curl_put_binary_file](https://github.com/mihaigalos/aim/blob/7c48e9e564c01fcaa75b9d4432f725f1331c2224/test/https/Justfile#L80). What is being duplicated?

**Comment by mihaigalos** [comment]
The name of the test is duplicated in the test body.
This repeats with each test.

**Comment by casey** [comment]
> The name of the test is duplicated in the test body. This repeats with each test.

Gotcha, that makes sense. There is actually a workaround for this. The `position-arguments` setting passes the name of the recipe as the first argument, so this works:

```
set positional-arguments

test-name:
  echo $0
```

In the case of shebang recipes, it passes the full path to the script, which isn't ideal, however you could extract the last component.

Does that work?

**Comment by mihaigalos** [comment]
Yes, this definitely helps. I get:
```bash
/tmp/justTbPuSj/_test_curl_put_binary_file
```
So getting only the recipe/target name is a slice of that:
```bash
echo $0 | awk -F"/" '{print $NF}'
```

Thank you! We can close this issue if you also think so.

**Comment by casey** [comment]
Nice, glad we found a solution!

You should also be able to do:

```
basename $0
```
