### ISSUE TITLE
Builtin-in function to fail/panic?

### ISSUE THREAD

**Issue by kaimast** [casey/just#1073]
Maybe there is a way to do this already, but I was hoping to have an easy way to make the justfile failed on unsupported configurations.

For example if an OS is not supported, can I do something like this:
```
target := if os() == "linux" {
      "x86_64-unknown-linux-gnu"
} else if os() == "macos" {
     "x86_64-apple-darwin"
} else {
    panic("Unsupported operating system")
}
```

Such a `panic`-function should ideally print to stderr and return an error code != 0.

**Comment by casey** [comment]
There isn't a panic function, but there is a nice hack:

```
target := if os() == "linux" {
  "foo"
} else {
  `exit 1 # unsupported OS`
}
```

The backtick will return status code 1, so the `just` will stop evaluation.

**Comment by chamons** [comment]
Being able to error about invalid configurations, such as a missing environmental variable, is a feature I really miss.

I'll try casey's hack to tide me over.

**Comment by casey** [comment]
This would be a good first issue. I think a function that takes a single argument, and always returns an error containing that argument, would be pretty easy. The name could be `error`.

**Comment by chamons** [comment]
I'll take a stab at this.

**Comment by chamons** [comment]
Done - https://github.com/casey/just/pull/1118
