### ISSUE TITLE
Upgrade to Clap 4.0

### ISSUE THREAD

**Issue by casey** [casey/just#1084]
I started on this but gave up. The migration to Clap 3.0 itself wasn't too hard, but the completion scripts have changed enough that all `just`'s custom completion patches now don't apply cleanly. 

The upgrade to Clap 3.0 will have to wait until:

- Someone fixes the completion scripts. (Which would be awesome!)
- Clap implements dynamic completion support, which would allow calling back into the `just` binary to get variables and recipe names: https://github.com/clap-rs/clap/issues/1232
- There is a critical vulnerability in Clap 2 or some feature we really want, at which point I'll just upgrade and the completion scripts will all break, and so we'll revert back to not having variable and recipe completion support.

**Comment by casey** [comment]
Another point in favor of doing this is there's now a crate for [generating man pages for clap 3.0 apps](https://crates.io/crates/clap_mangen). It would be nice to retire the help2man generated man page, which is pretty crappy, and requires a feature just to massage the help output into the right format.

**Comment by tpoliaw** [comment]
>Someone fixes the completion scripts. (Which would be awesome!)

I've just been working on custom completion scripts for a project I'm working on so could have a look at this while I still have an idea how it works if you want.

Is there a branch/patch somewhere for the code migration part?

**Comment by casey** [comment]
> Is there a branch/patch somewhere for the code migration part?

Yup! It's here: https://github.com/casey/just/tree/upgrade-clap

I started trying to fix the completion scripts, but I gave up quickly, and I'm not sure if the changes I made have the correct behavior.

If it's more than a little painful, then I'm not sure you should spend a ton of time on it. I think the current approach of patching the auto-generated completion scripts is probably unmaintainable in the long term, and we'll eventually want to phase it out in favor of something better: https://github.com/clap-rs/clap/issues/1232

**Comment by casey** [comment]
Finally merged!
