### ISSUE TITLE
Convert readme to markdown

### ISSUE THREAD

**Issue by casey** [casey/just#1087]
Now that GitHub auto-generates a table of contents, I think asciidoc has outlived its usefulness, and I should convert the readme to markdown so I don't have to remember the asciidoc syntax.

**Comment by kenden** [comment]
> Now that GitHub auto-generates a table of contents

@casey Now that the [README.md](https://github.com/casey/just/blob/4882b5aac05efa7ddc1af4a60db1a82e7583c641/README.md) is in markdown, is the table of contents coming back? I find it helpful to navigate the docs and don't see it anymore, am I missing it?

**Comment by casey** [comment]
GitHub actually automatically generates a table of contents now, but it can be hard to find. There's a button that opens a drop-down menu, which has a search bar to search for individual sections.

<img width="701" alt="Screen Shot 2022-02-09 at 1 47 21 PM" src="https://user-images.githubusercontent.com/1945/153295712-e35b742c-5dd5-4a2e-9c0c-f22056b97a62.png">

**Comment by casey** [comment]
(It's the icon to the left of `README.md`.)

**Comment by kenden** [comment]
@casey thank you!
I just saw a README.me with the text:
`Feeling lost? Use the GitHub TOC!)`, here: https://github.com/nanotee/nvim-lua-guide

Do you think this would be a good idea to add this here too?

**Comment by casey** [comment]
Sounds reasonable to me, I just opened #1096 to add an arrow pointing to the table of contents.
