### ISSUE TITLE
`path_exists()` Path manipulation function

### ISSUE THREAD

**Issue by heavelock** [casey/just#1102]
Hi! Do you think it would be beneficial to add `path_exists()` to a path manipulation function assortment?

Edit: I added that function, I will submit a PR tomorrow.

**Comment by casey** [comment]
This would be a good addition. I've intentionally avoided adding any boolean functions so far, to avoid having to figure out what they return (since the only type is string, there are no bools in the language).

I'd be okay adding `path_exists` and having it return the strings `true` and `false`.

**Comment by casey** [comment]
We should also consider using the empty string for `false`. Bash considers the empty string to be false, and anything else to be true.

**Comment by heavelock** [comment]
Yeah, I did think exactly about those values to be returned. Simple, effective and natural since it's an output of `bool_value.to_string()`. 

With different values it's always a bit slippery. On one hand it makes sense from compatibility reason but on the other hand it can get to unclear and seemingly wrong behaviors in some cases.
