### ISSUE TITLE
Feature request: Add systemwide justfile option

### ISSUE THREAD

**Issue by cysp74** [casey/just#1120]
That would be beneficial in enterprise/corporate environment if justfile had systemwide (eg. /etc/justfile) location with and read as first + override any other justfile.
 
My suggestions at first iterations is:
Search priority for justfile:
1. /etc/justfile
2. /usr/share/just/justfile
3. /usr/local/etc/justfile
4. /etc/xdg/justfile

If justfile couldn't be found locations above, the just can search at local dir.

2nd iteration (better):
Justfile stored locations above can store recipes that override recipes in justfile in local directory.

Ty.

**Comment by casey** [comment]
Thank you for the issue!

You could place a justfile in `/justfile`, and it would be found from any subdirectory. You could also place a justfile in `/root/justfile`, and it would work whenever you were in root's home directory. The behavior of programs like bash which search particular directories in a particular order for config files is weird, so I wouldn't want to replicate that.

It would be surprising if a systemwide justfile took priority over one found in the normal way. Similarly, I think it would be surprising if a global justfile overrode local justfile recipes.

Recipe overriding the other way, where if a local justfile recipe is missing, `just` will look in an outer justfile, is covered in #1036.
