### ISSUE TITLE
`HOSTNAME` environment variable not set in recipes

### ISSUE THREAD

**Issue by bradleyharden** [casey/just#1129]
Hi,

I recently encountered a bug in one of my recipes. It turned out to be caused by the fact that the `HOSTNAME` environment variable is not set within recipes. I can think of three possible reasons for this:
- It is a `bash` behavior that I don't understand
- It is an intentional decision of `just` for a reason I don't understand
- It's a bug

I did a quick search on Google (re: `bash`) and in the `just` issues, but I didn't see anything, so I thought I would ask.

```bash
$ cat Justfile
test:
    env

$ just test | grep HOSTNAME
# Nothing here...
```

**Comment by casey** [comment]
Interesting! It looks like the `HOSTNAME` variable is set in `bash`, but isn't exported, so it isn't available to child processes:

https://superuser.com/questions/132489/hostname-environment-variable-on-linux

So this isn't `just`-specific.

**Comment by bradleyharden** [comment]
I swear I did try to Google this, but I didn't see anything that looked immediately relevant.

However, I think it might make sense to leave this issue open, because the natural solution:

```
export HOSTNAME := env_var('HOSTNAME')
```

gives

```
error: Call to function `env_var` failed: environment variable `HOSTNAME` not present
  |
3 | export HOSTNAME := env_var('HOSTNAME')
  |
```

I can use

```
export HOSTNAME := `hostname`
```

but that seems less than ideal and easily confusing.

The only other workaround is to convert the recipe into a bash script and export it there:

```
test:
    #!/bin/bash
    export HOSTNAME
    env
```

I'm not sure what the best solution is. Maybe query the `HOSTNAME` separately and manually add it to `env_var`?

**Comment by casey** [comment]
Calling `hostname` doesn't seem too bad to me. `just` can be used with many different shells, so I don't think it would be a good policy in general to try to compensate to much for shell-specific weirdness.
