### ISSUE TITLE
zsh completion lists variables along with recipes

### ISSUE THREAD

**Issue by binyamin** [casey/just#1133]
### Expected
When using ZSH, I expect `just <tab>` to list just the available recipes, just like it does when using Bash.

### Actual
It lists all environment variables and just variables defined within the justfile. It does _not_ list environment variables defined in a "dotenv" file.

---
Thank you for maintaining this over time. It's one thing to start a project; it's an entirely different thing to keep it up for 5½ years (a0d5b83a8008c4fec292fbacde61240141554fc3). I don't know how you do it.

**Comment by casey** [comment]
Can you share a copy of your justfile, along with a screenshot of what you see when you type `just <tab>` in your terminal?

> Thank you for maintaining this over time. It's one thing to start a project; it's an entirely different thing to keep it up for 5½ years (https://github.com/casey/just/commit/a0d5b83a8008c4fec292fbacde61240141554fc3). I don't know how you do it.

You bet! It's actually not so bad. I always fix bugs and respond to questions, and that isn't very hard. There are huge features that should be implemented, but I don't pressure myself to implement them, since I know doing that would burn me out pretty quickly.

**Comment by binyamin** [comment]
```make
# justfile
_default:
    @just --list

src := "src"
dest := "out"

serve:
    vite

build:
    vite build
```

```console
$ just
build  dest   serve  src  
```

**Comment by binyamin** [comment]
![visual representation of the comment above](https://user-images.githubusercontent.com/39805353/160467512-8e4cd29b-05b2-4486-bff3-ddf62b533fc0.png)

**Comment by casey** [comment]
Thanks for the details! Pinging @heyrict, who wrote the expanded zsh completion scripts.

**Comment by heyrict** [comment]
> It does not list environment variables defined in a "dotenv" file

Afaik this is the expected behavior. You may work around that by using [other plugins](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/dotenv/dotenv.plugin.zsh)

> It lists all environment variables and just variables defined within the justfile

Not a bug. The completion style depends on *your configuration*. Try adding the following lines to your `zshrc`, which should group the completion by recipes and variables:

```zsh
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format "%U%B%d%b%u"
```

**Comment by binyamin** [comment]
@heyrict Thanks. How would I print only the commands?

**Comment by heyrict** [comment]
@binyamin Try applying this patch to your `_just` completion script

```patch
--- /usr/share/zsh/site-functions/_just 2022-03-30 03:22:57.000000000 +0800
+++ _just   2022-04-06 17:07:03.102754922 +0800
@@ -114,9 +114,6 @@
 _just_commands() {
     [[ $PREFIX = -* ]] && return 1
     integer ret=1
-    local variables; variables=(
-        ${(s: :)$(_call_program commands just --variables)}
-    )
     local commands; commands=(
         ${${${(M)"${(f)$(_call_program commands just --list)}":#    *}/ ##/}/ ##/:Args: }
     )
@@ -126,7 +123,6 @@
             *) _message 'value' && ret=0 ;;
         esac
     else
-        _describe -t variables 'variables' variables -qS "=" && ret=0
         _describe -t commands 'just commands' commands "$@"
     fi
```

**Comment by binyamin** [comment]
@heyrict perfect, thank you.
@casey Should I close this now? I still don't think this is expected behavior.

**Comment by casey** [comment]
Heyrict is the zsh completion script expert around here, so if he thinks it's expected behavior, I'm inclined to believe him. Is it not?

**Comment by heyrict** [comment]
@binyamin  Please check [this section](https://github.com/casey/just/#setting-variables-from-the-command-line) in case you still think that is not expected. `just os=plan9 test` is a valid command to set variables, and the completion script won't know if you mean to type variables or recipes at the stage of `just <Tab>`.

**Comment by binyamin** [comment]
@heyrict thank you, I must have missed that section
