### ISSUE TITLE
Feature Idea: allow for substitution when creating variables

### ISSUE THREAD

**Issue by twolodzko** [casey/just#1134]
The documentation says

> Variables, strings, concatenation, and substitution using {{…}} are supported:
> 
> ```
> version := "0.2.7"
> tardir  := "awesomesauce-" + version
> tarball := tardir + ".tar.gz"
> ```

But why substitution can't be a part of it, so the code simplifies to:

```
version := "0.2.7"
tardir  := "awesomesauce-{{version}}"
tarball := "{{tardir}}.tar.gz"
```

It makes it more consistent because the same syntax can be used for both creating variables and the recipes.

**Comment by mmstick** [comment]
Yeah, this is currently somewhat awkward

```
TARGET_BIN := DESTDIR + bindir + '/' + ID
TARGET_DBUS_CONF := DESTDIR + sysconfdir + '/dbus-1/systemd./' + ID + '.conf'
TARGET_SYSTEMD_SERVICE := DESTDIR + libdir + '/systemd/system/' + ID + '.service'
TARGET_SESSION_SERVICE := DESTDIR + libdir + '/systemd/user/' + ID_LOCAL + '.service'
```

Equivalent Makefile:

```
TARGET_BIN = "$(DESTDIR)$(bindir)/$(ID)"
TARGET_DBUS_CONF = "$(DESTDIR)$(sysconfdir)/dbus-1/system.d/$(ID).conf"
TARGET_SYSTEMD_SERVICE = "$(DESTDIR)$(libdir)/systemd/system/$(ID).service"
TARGET_SESSION_SERVICE = "$(DESTDIR)$(libdir)/systemd/user/$(ID_LOCAL).service"
```

**Comment by casey** [comment]
Check #11. Someone will implement it some day!
