### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by mmstick** [casey/just#1143]
Ways to fund development would be nice to have for those of us who want to depend on this for work projects.

**Comment by casey** [comment]
Are there specific features `just` needs for the projects you'd like to use it on?

**Comment by mmstick** [comment]
I am in the process of converting some projects, but would like to sponsor what I depend on.

**Comment by casey** [comment]
I'm not opposed to getting money, but honestly, being sponsored wouldn't increase the amount of time I work on Just, which is why I haven't done it. Just definitely isn't going away any time soon, regardless of sponsorship.

**Comment by mrchantey** [comment]
For me its about having a way to say thank you, until there is a donate button i'll use my `justfile`:

```
main-devs := 'casey hustcer'

@thank-devs:
	for dev in {{main-devs}}; do \
		echo thankyou $dev!; \
	done
```

**Comment by casey** [comment]
Going to close this, although I do accept sponsorship on GitHub, it's really more for fun, and having people use `just` is more than enough motivation to work on it ^_^
