### ISSUE TITLE
String interpolation for recipe parameter defaults does not seem to work

### ISSUE THREAD

**Issue by jenisys** [casey/just#1145]
The string interpolation ``"{{some_function()}}"`` does not seem to work for the default value of recipe parameters.

## DOES NOT WORK

```makefile
# -- FILE: justfile
info OS="{{os()}}":
    @echo "OS={{OS}}"
```

If I run `just info`:

```bash
$ just info
OS={{os()}}

# NOTE: The function is not called, the string part is not replaced w/ the function call return-value.
```

## WORKS

If I run `just info` (on platform: macOS/Darwin):

```bash
$ just info
OS=macos
```
 with:
```makefile
# -- FILE: justfile
info OS=os():
    @echo "OS={{OS}}"
```

**Comment by casey** [comment]
String interpolation inside of strings and backticks hasn't been implemented, this is tracked in #11.
