### ISSUE TITLE
Invocation directory changes when invoking in other directories via /

### ISSUE THREAD

**Issue by anacrolix** [casey/just#1146]
When [invoking justfiles in other directories](https://github.com/casey/just#invoking-justfiles-in-other-directories) via slashes in the recipe name, the invocation directory is also changed. For `just other/dir/` the expected behaviour is equivalent to `just -f other/dir/justfile -d .`, but instead it does `cd other/dir && just recipe`. Similarly I would expect `just other/dir/recipe` to do `just -f other/dir/justfile -d . recipe`.

**Comment by casey** [comment]
If I'm understanding correctly, the behavior you're describing is the intended behavior. This is required in order for just recipes to work when called via a slash, and without a slash.

For example, if there's a subdirectory `foo` which contains a file `foo/bar` and a justfile `foo/justfile`, and the `justfile` contains:

```
default:
  cat bar
```

Then the working directory must be `foo`, whether it's called with `just foo/default` or `cd foo && just default`.

**Comment by anacrolix** [comment]
I think specifically my expectation is that `invocation_directory()` return the location the command was started from. The slash invocation doesn't do this, so even if I write my justfile to use `invocation_directory()` where I want to use the working directory, I can't. If i want to do something relative to the justfile location, I have `justfile_directory()`, but `invocation_directory()` is rendered useless.

**Comment by casey** [comment]
Ah, okay, I misunderstood, I didn't realize you were referring to the `invocation_directory()` function, and not the current working directory.

I'm having trouble reproducing this issue. I did the following:

```
$ pwd
/Users/rodarmor/tmp/invocation
$ mkdir foo
$ printf 'default:\n @echo {{invocation_directory()}}' > foo/justfile                                                                                                                 $ just foo/                                                                                                                                                                           /Users/rodarmor/tmp/invocation
```

The invocation directory looks correct here, it's the original directory, not `foo`.

**Comment by anacrolix** [comment]
Yeah I don't have an issue here anymore, I'm not sure how I got it confused. If it comes up again, I'll reopen. Thanks!

**Comment by casey** [comment]
Nice, glad it's working!
