### ISSUE TITLE
Not display the command in output

### ISSUE THREAD

**Issue by wangxiaoying** [casey/just#1153]
For example in my just file I have a simple command:
```
cat1 qid:
    cat q{{qid}}.sql | sed 's/xxx/yyy/g'
```

And the output of running `just cat1 16` is:
```
cat q16.sql | sed 's/xxx/yyy/g'
select
	*
from
	yyy
```

Is it possible to not display the first line `cat q16.sql | sed 's/xxx/yyy/g'` from my output?

I have tried to use `just cat1 16 | sed '1d'`, but the result only remove the first line of the file instead of the command, like this:
```
cat q16.sql | sed 's/xxx/yyy/g'
	*
from
	yyy
```

The reason I want this feature is because then I can simply copy the output. For example Warp terminal provides this copy output feature so I could copy the result with simple hotkeys:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/5569610/163453484-7e354d0f-cf4a-4d4d-98e1-c2e0a44829c1.png">

**Comment by casey** [comment]
> Is it possible to not display the first line cat q16.sql | sed 's/xxx/yyy/g' from my output?

Yes! Add a `@` before a line to suppress echoing that command:

```
cat1 qid:
    @cat q{{qid}}.sql | sed 's/xxx/yyy/g'
```

Or before the recipe name to suppress echoing all commands:

```
@cat1 qid:
    cat q{{qid}}.sql | sed 's/xxx/yyy/g'
```

Let me know if that works!

**Comment by wangxiaoying** [comment]
@casey Thanks for the quick reply. It works perfectly!
