### ISSUE TITLE
[idea] ansii text helpers

### ISSUE THREAD

**Issue by eshepelyuk** [casey/just#1156]
Hello

Just an idea
I consider it would be useful to have some new helpers to be able to print coloured messages from just receipes easily, without diving into cryptic ANSI 3scape sequences.

Maybe a new function ?
Maybe someone can suggest existing tool to simplify this and use from the receipe ?

**Comment by casey** [comment]
I like this idea. It could take the form of a function that would color text by prepending and appending the right ansi escape codes. Like so: `red("foo")`

**Comment by ievgenii-shepeliuk** [comment]
> I like this idea. It could take the form of a function that would color text by prepending and appending the right ansi escape codes. Like so: `red("foo")`
And it also can have some flags, like bright color, bold etc ?

**Comment by eshepelyuk** [comment]
> I like this idea. It could take the form of a function that would color text by prepending and appending the right ansi escape codes. Like so: `red("foo")`

And it also can have some flags, like bright color, bold etc ?
I was also thinking maybe you can also implement support for ASCII banners using [FIGlet fonts](http://www.jave.de/figlet/fonts.html) or similar.

**Comment by runeimp** [comment]
I recommend namespacing the color functions, i.e.: `color_red()` to avoid confusion with other potential color themed function named such as a `red_tape()` function that emails a bureaucrat every time the function is called or updates a legal document in some way. Or `blue_moon()` that outputs a blue moon emoji or some such, etc.

Or having a single `color()` function that accepts the name of the color or hex value as the first argument then the string to color as the second argument. Is there a ncurses (rcurses?) for Rust that is safe? I know there is a wrapper. Definitely want a library for that as it's quite the mine field. Especially if you want any of it to work on Windows in CMD, PowerShell, and/or Terminal or 3rd party, multi-platform terminals such as KiTTY, etc.

**Comment by gurgeous** [comment]
I want this too. Currently we use a recipe for this:

```
banner *ARGS:
  @echo "\n\033[42;37;1m----- {{ARGS}} -----\033[0m"
```

Example:

`@just banner build archive`

Feels clunky, though.

**Comment by VladimirMarkelov** [comment]
> Or having a single `color()` function that accepts the name of the color or hex value as the first argument then the string to color as the second argument. Is there a ncurses (rcurses?) for Rust that is safe?

I think ncurses is overkill. A smaller and simple library is enough, e.g. https://docs.rs/termcolor/latest/termcolor/
