### ISSUE TITLE
absolute_path is not relative to invocation directory

### ISSUE THREAD

**Issue by mortoray** [casey/just#1159]
`absolute_path` is resolving relative to the justfile directory and not the invocation directory.  

The docs indicate it should be relative to the invocation directory: 

> absolute_path(path) - Absolute path to relative path in the invocation directory. absolute_path("./bar.txt") in directory /foo is /foo/bar.txt.

I'm comparing `PATH := absolute_path(".")` vs `PATH: = invocation_directory()` and getting different results, with absolute_path pointing to the location of my justfile.

just 1.1.2

----

As a workaround I'm using a sequence of expressions, instead of `absolute_path('..')` I'm using `absolute_path(join(invocation_directory(),'..'))`

**Comment by casey** [comment]
Thanks for reporting this! I think the docs may actually be wrong. Since just cd's to the justfile directory, it seems like a function just called `absolute_path` should resolve the path relative to the justfile directory.

**Comment by KevinMGranger** [comment]
The docs say `working directory`, but I still interpreted that as the working directory from which `just` was invoked, not hte directory containing the Justfile. Maybe it should say `directory containing the Justfile`?
