### ISSUE TITLE
Issue with string arguments

### ISSUE THREAD

**Issue by deckarep** [casey/just#116]
This applies to OSX but is likely a general question:

Given a recipe such as:
```sh
goog query:
  @open http://google.com/search?q={{query}}
```
It would seem this can't be invoked with a single string argument that has spaces within it as in the following:

```sh
just goog "how to train your dragon"
```

Is there a way to accomplish this that I'm missing?  Thanks again.

**Comment by casey** [comment]
Good question!

Just inserts variables into recipes just like a template engine, by substituting the text directly.

Given the recipe:

``` make
goog query:
  @open http://google.com/search?q={{query}}
```

When you do:

```
$ just goog "how to train your dragon"
```

That's turning into:

```
# notice the spaces
open http://google.com/search?q=how to train your dragon
```

Which gets parsed by the shell as five arguments to open, not a single query string as was intended.

You can fix this by changing your recipe to be as follows:

``` make
goog query:
  @open 'http://google.com/search?q={{query}}'
```

I think this will probably be a common gotcha that people will run into, so I'll add something to the readme.

**Comment by deckarep** [comment]
Ah got it! Thanks I'm glad there is a solution then!

**Comment by casey** [comment]
You bet!
