### ISSUE TITLE
add easy way to opt out of janus

### ISSUE THREAD

**Issue by ghost** [casey/just#1163]
can an easy way for user to opt out be added to this, or this section moved to the top of the readme? might be very important to some people that this not track their stuff for privacy reasons.

https://github.com/casey/just#janus

**Comment by casey** [comment]
Janus only includes content from public repositories though, so it only looks at things that are already public.

**Comment by casey** [comment]
It's not important for the justfiles to be mirrored in the janus repo though, so I've purged them.

**Comment by ghost** [comment]
even if already public secrets could be accidentally uploaded by users which janus would capture. either way the readme here is unclear since the wording implies its on demand as requested not automated and should still be moved up so its more clear to users
