### ISSUE TITLE
Ability to return boolean values in conditional

### ISSUE THREAD

**Issue by mvgijssel** [casey/just#1168]
I have defined the following variable in my justfile:

```
is_ci := if env_var_or_default("CI", "false") == "true" { true } else { false }
```

which breaks with the following error

```
error: Variable `true` not defined
  |
3 | is_ci := if env_var_or_default("CI", "false") == "true" { true } else { false }
  |
```

I would expect that I'm able to store a conditional boolean result within a justfile variable.

**Comment by casey** [comment]
Booleans aren't yet supported, string is the only type, so you'll have to do:

```
is_ci := env_var_or_default("CI", "false")
```
