### ISSUE TITLE
Run just recurisve preserving command-line arguments (in particular invocation_dir)

### ISSUE THREAD

**Issue by mortoray** [casey/just#1169]
I need a way to run just recursively such that it respects the initial invocation arguments. As it is now, I can't properly run sub-commands via just. For example, if I have this justfile in the `/tmp` directory:

```
show-path:
   echo {{invocation_directory()}}
      
show-path-recurse:
	just show-path
```

Say I am in the `/src` directory and run `just -f /tmp/justfile show-path`, it emits `/src` as expected. However, if I run `just -f /tmp/justfile show-path-recruse` I get `/tmp` as the output, which is not what is wanted.

I need a way to invoke just recursively so that it preserves the calling environment.  OR, perhaps better, a way to directly call other targets in the same justfile -- which I think would be clearer as to what is intended.

----

The present workaround I have is a bit verbose, and it certainly doesn't capture the entire calling environment (other CLI options), but it does get the working directory set.

```
show-path-recurse:
	cd {{invocation_directory()}} && just --justfile {{justfile()}} show-path
```

**Comment by mortoray** [comment]
Note: I tried using `--working-directory` but that doesn't appear to change the invocation directory. This complicates the code since, as far as I can tell, I then can't create an alias for this command.

```
SUB_JUST := cd {{invocation_directory()}} && just --justfile {{justfile()}}
```

Because these create variables, and not command fragments. Thus I don't see an option other than to copy-paste the verbose syntax each place I wish to do a sub-just call.

**Comment by casey** [comment]
This is pretty hard to get right, since there's a bunch of state that you'd have to pass, including command line arguments and variable values which might be the result of non-deterministic shebangs.

You're probably trying to do something more complex, but for the example you gave, you can use a dependency:

```
show-path:
   echo {{invocation_directory()}}
      
show-path-recurse: show-path
```

You can also use the `&&` to run a recipe after another recipe:

```
show-path:
   echo 'second!'
      
show-path-recurse: && show-path
  echo first!
```

So the only thing that isn't well supported is calling recipes in the middle of another recipe.

**Comment by mortoray** [comment]
Yeah, I do both call in the middle of a recipe and in a few places have additional parameters to the recipe, thus neither of the above options will work. :/

**Comment by casey** [comment]
You can pass arguments to dependencies:

```
foo msg:
   echo {{msg}}
      
bar: && (foo "bar")
```

Does that help? With some refactoring, I think you can express a lot of patterns with use of dependencies, but it's not idiomatic.
