### ISSUE TITLE
Install script is no longer working

### ISSUE THREAD

**Issue by logachev** [casey/just#1171]
Installation script from the Readme is no longer working:

```
curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
```

It looks like `https://github.com/casey/just/releases/latest` returns nothing, so `$tag` is invalid.

I didn't find any github docs about it, but saw some places would use this url instead: `https://api.github.com/repos/casey/just/releases/latest`.. Can it be some sort of deprecation of old API in favor to a new one?

Error output:
```
root@9f4e1c04e525:/# curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
install: Repository:  https://github.com/casey/just
install: Crate:       just
install: Tag:
install: Target:      x86_64-unknown-linux-musl
install: Destination: /root/bin
install: Archive:     https://github.com/casey/just/releases/download//just--x86_64-unknown-linux-musl.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by casey** [comment]
Thanks for the detailed issue! I opened #1172 with a fix, using the API URL as you suggested.
