### ISSUE TITLE
Dependency executed twice when order changes

### ISSUE THREAD

**Issue by ckstevenson** [casey/just#1173]
Perhaps a bug, or I am the bug, but I cannot get `just` to handle dependency execution like it does in the docs. The docs state "Dependencies will always run first, even if they are passed after a recipe that depends on them" and then shows: 
```$ just test build
cc main.c foo.c bar.c -o main
./test
testing… all tests passed!
```
In this case, `build` is only ran once.

If I replicate this, but with some simple `echo` commands, I get the dependency being executed twice:
```
build:
    echo "building something"

test: build
    echo "testing something"
```
```
$ just test build
echo "building something"
building something
echo "testing something"
testing something
echo "building something"
building something
```
To get the intended behavior, I have to call `build` before `test`:
```
$just build test
echo "building something"
building something
echo "testing something"
testing something
```

The end goal is to have multiple recipes have the same dependency but only execute said dependency once, irregardless of order. Since the docs seem to show it being possible, I am wondering if I am the bug?

**Comment by casey** [comment]
Nice catch! I'm surprised also, I would have expected the behavior documented in the readme. I tested old revisions, and it looks like it was never the case that it worked that way.

I created this justfile:

```
foo: bar
  @echo foo

bar:
  @echo bar
```

And ran `just foo foo`. All versions of just that I could find printed out:

```
bar
foo
foo
```

So `foo` always runs twice, but `bar` only runs once. This seems like a bug to me. Either top level arguments should be treated as complete invocations and run their dependencies every time they're called. Or they should only run if they haven't been run before.

I'm leaning towards making it so it behaves as it's documented in the readme. `just foo foo` would run `bar`, then `foo`, then terminate.

**Comment by casey** [comment]
Make only runs foo once:

```
$ make foo foo
bar
foo
make: `foo' is up to date.
```

**Comment by ckstevenson** [comment]
Yep, the Make behavior was a check of ours before migrating to just. I'd vote for keeping the functionality the same, for whatever that's worth :). At least in our case we may invoke several recipes with the same dependency which only needs to run once.

In any case, we will use continue to migrate to just. It's just too slick not to ;)

**Comment by casey** [comment]
Fixed! I'm in the process of publishing 1.1.3 with the change.

**Comment by ckstevenson** [comment]
> Fixed! I'm in the process of publishing 1.1.3 with the change.

Legend! I'll give it a test sometime today.

**Comment by ckstevenson** [comment]
And it works!

**Comment by casey** [comment]
Nice!
