### ISSUE TITLE
Support “subdirectory/recipe” notation in recipe dependencies

### ISSUE THREAD

**Issue by eigengrau** [casey/just#1184]
I notice that, inside a Just recipe, it is possible to explicitly delegate to recipes declared in sub- or super-directory Justfiles, by invoking Just recursively, as in:

```
foo:
    @just subdir/bar
    @just ../quux
```

While this feature may have been intended more for interactive use (since in Justfiles one may just as well type `@just --justfile subdir/Justfile bar` (…or maybe introduce `--justdir` to make it less clumsy), this made me wonder whether it would make sense to support this “short-cut” notation as part of a recipe’s dependencies, so that one could write:

```
foo: subdir/bar ../quux
```

(I guess if dependencies of type _file_ – à la Make – ever become a thing this notation may prove confusing, though, or one may prefer a different symbol over the slash)

Thanks for building Just!

**Comment by casey** [comment]
I think this is mostly covered by #383, since I think it would be done best as some kind of module system.

> Thanks for building Just!

You are most welcome!

**Comment by eigengrau** [comment]
> I think this is mostly covered by https://github.com/casey/just/issues/383, since I think it would be done best as some kind of module system.

Thanks for the pointer. The headline sounds enticing, I’ll check it out.
