### ISSUE TITLE
It would be amazing to have commands executed on error

### ISSUE THREAD

**Issue by frederikhors** [casey/just#1187]
It would be amazing to have commands executed on error.

**Comment by casey** [comment]
Can you give an example?

**Comment by frederikhors** [comment]
If I'm executing a list of commands and one of them throws an error exiting from the recipe I would like to execute another recipe to - example - clean up some files.

**Comment by deadbaed** [comment]
I am also interested in this, my use case would be:
- run recipe, get the exit status
- if status is 0, dont do anything
- if status is different than 0, run another recipe

**Comment by casey** [comment]
Check out #1582.
