### ISSUE TITLE
Why this command throws with "Call to unknown function `error`"?

### ISSUE THREAD

**Issue by frederikhors** [casey/just#1188]
Why this command throws with the below error?

```
{{ if `git status` != "" { error("pending changes on files") } else { "" } }}
```

```
error: Call to unknown function `error`
   |
   |   {{ if `git status` != "" { error("pending changes on files") } else { "" } }}
```

**Comment by casey** [comment]
What version of `just` are you running? `error` was added in 1.1.0, so if you're running an earlier version of `just` it won't be available.

**Comment by frederikhors** [comment]
Wow! I have not noticed! I'm using the 0.11.2 because on chocolatey this is the latest one!

We need to update this: https://github.com/michidk/just-choco.
