### ISSUE TITLE
FR: auto-upgrade

### ISSUE THREAD

**Issue by frederikhors** [casey/just#1189]
It would be amazing if Just can just update itself with a command like: `just self update`!

**Comment by akshaybabloo** [comment]
This I believe is difficult to do it. And also come with a security risk. GoHugo tried to do this some time ago but didn't do it (can't seem to find the ticket of their GitHub repo). IMO let the package manage take care of this

**Comment by casey** [comment]
I think self-update would definitely be cool, but I think that it's probably not worth it, on balance. There's a rust crate that provides self-update functionality, but it pulled in a lot of dependencies, and increased compile times a fair bit, see #1226. I think the main downside for me is that if `just` is installed with a package manager, self-update will do the wrong thing.
