### ISSUE TITLE
update Nix install instructions

### ISSUE THREAD

**Issue by risingBirdSong** [casey/just#1192]
I think the current install instructions are specific to nixOs. Regular nix I think should install like this? 
`nix-env -iA nixpkgs.just`

**Comment by casey** [comment]
I think you're right. Would you mind open a PR with the fix? No worries if not.

**Comment by risingBirdSong** [comment]
yes I would like help update this, thanks. I may need some help though if you don't mind. I cloned the repo, created a branch, updated the readme with the changes and attempted to push the branch here.. but got a permissions error

remote: Permission to casey/just.git denied to risingBirdSong.
fatal: unable to access 'https://github.com/casey/just.git/': The requested URL returned error: 403

What is the correct approach to submitting the PR here?

Thanks and great software, i'm enjoying using it :)

**Comment by casey** [comment]
> yes I would like help update this, thanks. I may need some help though if you don't mind.

Of course!

> What is the correct approach to submitting the PR here?

You'll need to fork the repo on github with the "fork" button in the upper right hand corner. Then push the branch with the changes to your fork, and then open a PR to merge it in. Feel free to ask more questions if you can't get it to work.

> Thanks and great software, i'm enjoying using it :)

Thank you! Great to hear :)

**Comment by risingBirdSong** [comment]
great thanks! I was just missing the fork part. I've created the PR. Thanks for the help and the library :) 
https://github.com/casey/just/pull/1194

**Comment by casey** [comment]
Thank you, merged! Sorry about the insane table formatting 😅
