### ISSUE TITLE
How to share `Environment Variables (eg: python venv)` between recipes?

### ISSUE THREAD

**Issue by mokeyish** [casey/just#1216]
How to share `Environment Variables (eg: python venv)` between recipes?

```just
# create venv 
venv:
  #!/usr/bin/env bash
  [ ! -f 'venv' ]&& python -m venv venv
  source venv/bin/activate


# install dependencies.
dev: venv
  #!/usr/bin/env bash
  which python 
  pip install -r requirements.txt
```

**Comment by casey** [comment]
There is no good way to share environment variables between recipes.

Instead of sourcing the venv, can you run the venv binaries directly?

```
venv:
  [ ! -f 'venv' ]&& python -m venv venv

dev: venv
  venv/bin/pip install -r requirements.txt
```

Or can you add `venv/bin` to your path?

```
export PATH = "venv/bin:" + env_var("PATH") 

venv:
  [ ! -f 'venv' ]&& python -m venv venv

dev: venv
  pip install -r requirements.txt
```

I haven't used python virtual environments much, so I'm not sure if either of these approaches work.

**Comment by mokeyish** [comment]
Thanks, it should work.

**Comment by casey** [comment]
@mokeyish Which solution do you think is best, adding `venv/bin` to `PATH`, or executing the binaries in it directly? This specific question comes up a lot, so I'd like to add the best solution to the readme.

**Comment by mokeyish** [comment]
I think the second solution is better, It's simple than the first one.

Will you add  feature `share Environment Variables` to just?

**Comment by casey** [comment]
> I think the second solution is better, It's simple than the first one.

Thanks, I'll note it in the readme.

>Will you add feature share Environment Variables to just?

Unfortunately I don't think there's a reasonable way to implement it. If someone comes up with a good strategy for implementing it, I'd definitely consider it.

**Comment by mokeyish** [comment]
> Unfortunately I don't think there's a reasonable way to implement it. If someone comes up with a good strategy for implementing it, I'd definitely consider it.

 - Generate all command in recipes into a bash srcipt dynamiclly？
 - subprocess?
 
Do you think?
