### ISSUE TITLE
[docs] Links not working in just book

### ISSUE THREAD

**Issue by JurrianFahner** [casey/just#1225]
The links are not working correct in the book on https://just.systems/man/en/.
The links do work correctly in the [readme.md](https://github.com/casey/just/blob/master/README.md)

It's due to the fact that html anchors are used and the book is splitted over several html files. 

I think there are two ways to fix it:
1. Don't split the readme in separate files (so the links keep working). 
2. Rewrite all links so they link properly to the right places in the manual.

**Comment by casey** [comment]
Thanks for reporting this! I changed the script that builds the book sources to rewrite all the links so that they point to the right place. (It was surprisingly hard 😭.) But it should work now!
