### ISSUE TITLE
trim_start_match(p1, p2)

### ISSUE THREAD

**Issue by MadBomber** [casey/just#1228]
Here is a sequence from by bash shell.
First thing is a cat of the justfile that demos the error condition
just version is 1.2.0

<pre>
20:17:28 3.1.2p20  s5:Downloads $ cat trim_start_match_error.just
# trim_start_match_error.just

set positional-arguments    := true
set allow-duplicate-recipes := true
set dotenv-load             := false

me          := justfile()
home        := "$HOME"
backup_dir  := "$JUST_BACKUP_DIR"
backup_file := trim_start_match(me, home)
my_backup   := backup_dir + backup_file

# Show error replacing home dir path with backup dir path
@test:
  echo "me          -=> {{me}}"
  echo "home        -=> {{home}}"
  echo "backup_file -=> {{backup_file}}"
  echo "backup_dir  ==> {{backup_dir}}"
  echo "my_backup   -=> {{my_backup}}"

20:17:34 3.1.2p20  s5:Downloads $ just --version
just 1.2.0

20:17:39 3.1.2p20  s5:Downloads $ just -f trim_start_match_error.just
me          -=> /Users/dewayne/Downloads/trim_start_match_error.just
home        -=> /Users/dewayne
backup_file -=> /Users/dewayne/Downloads/trim_start_match_error.just
backup_dir  ==> /Users/dewayne/.just_backup
my_backup   -=> /Users/dewayne/.just_backup/Users/dewayne/Downloads/trim_start_match_error.just

20:17:47 3.1.2p20  s5:Downloads $ just --version
just 1.2.0
</pre>

The problem is that the variable "my_backup" still contains the string for the variable "home" which was expected to be trim'ed out by the trim_start_match() function.

**Comment by casey** [comment]
I think the issue is that `trim_start_match` is being passed the string `"$HOME"` as the second argument. Just doesn't automatically interpolate variable values, so you'll need to do something like this:

```
home        := env_var("HOME")
backup_dir  := env_Var("JUST_BACKUP_DIR")
```

Let me know if that works!

**Comment by MadBomber** [comment]
yes it worked as expected.  Now I'm a little preplexed about the the differences between:

v1 := "$HOME"
v2 := '$HOME'
v3 := env_var('HOME')

with v1 and v2.  my expectation was that v1 would have the value of the system environment variable where as v2 would not.  What I understand from your explanation is that both v1 and v2 have the same value despite the difference in the quotes.

Feel free to close this issue.

**Comment by casey** [comment]
> yes it worked as expected

Nice!

> with v1 and v2. my expectation was that v1 would have the value of the system environment variable where as v2 would not. What I understand from your explanation is that both v1 and v2 have the same value despite the difference in the quotes.

That's correct, variable lookup only happens with `env_var`, and not within single or double quoted strings. This is definitely confusion, given the behavior of the shell.
