### ISSUE TITLE
How to implement a FAKE module system

### ISSUE THREAD

**Issue by MadBomber** [casey/just#1232]
@casey  I think you may have mentioned something like this before...

We can emulate a module system with the current v1.2.0 version with a few conventions

Consider this directory structure:

<pre>
just_modules_test/
├── aaa
│   └── justfile
├── bbb
│   └── justfile
└── justfile
</pre>

Here are the contents of the three justfiles ...

<pre>
just_modules_test $ cat justfile
# ~/temp/just_modules_test/justfile

module_aaa := justfile_directory() + "/aaa/justfile"
module_bbb := justfile_directory() + "/bbb/justfile"

# Available Tasks
@list:
  echo "testing fake module concept ..."
  just --list

# All Available Tasks including from Modules
@list_all: list aaa bbb

# Module aaa magic
@aaa what='' args='':
  just -f {{module_aaa}} {{what}} {{args}}

# module bbb magic
@bbb what='' args='':
  just -f {{module_bbb}} {{what}} {{args}}

just_modules_test $ cat aaa/justfile

# Module aaa
aaa:
  echo 'welcome to module aaa'
  just --list

xyzzy thing='lion':
  echo "Magic for aaa"
  echo "... watch me pull a {{thing}} out of my hat."

just_modules_test $ cat bbb/justfile

# Module bbb
bbb:
  echo 'welcome to module bbb'
  just --list

# Do something magical
xyzzy thing='rabbit':
  echo "Magic for bbb"
  echo "... watch me pull a {{thing}} out of my hat."

</pre>

Here are the results when I execute just out of the just_modules_test directory ...

<pre>
just_modules_test $ just
testing fake module concept ...
Available recipes:
    aaa what='' args='' # Module aaa magic
    bbb what='' args='' # module bbb magic
    list                # Available Tasks
    list_all            # All Available Tasks including from Modules

just_modules_test $ just list_all
testing fake module concept ...
Available recipes:
    aaa what='' args='' # Module aaa magic
    bbb what='' args='' # module bbb magic
    list                # Available Tasks
    list_all            # All Available Tasks including from Modules
echo 'welcome to module aaa'
welcome to module aaa
just --list
Available recipes:
    aaa                # Module aaa
    xyzzy thing='lion'
echo 'welcome to module bbb'
welcome to module bbb
just --list
Available recipes:
    bbb                  # Module bbb
    xyzzy thing='rabbit' # Do something magical

just_modules_test $ just aaa
echo 'welcome to module aaa'
welcome to module aaa
just --list
Available recipes:
    aaa                # Module aaa
    xyzzy thing='lion'

just_modules_test $ just aaa xyzzy
echo "Magic for aaa"
Magic for aaa
echo "... watch me pull a lion out of my hat."
... watch me pull a lion out of my hat.

just_modules_test $ just aaa xyzzy rabbit
echo "Magic for aaa"
Magic for aaa
echo "... watch me pull a rabbit out of my hat."
... watch me pull a rabbit out of my hat.

just_modules_test $ just bbb
echo 'welcome to module bbb'
welcome to module bbb
just --list
Available recipes:
    bbb                  # Module bbb
    xyzzy thing='rabbit' # Do something magical

just_modules_test $ just bbb xyzzy
echo "Magic for bbb"
Magic for bbb
echo "... watch me pull a rabbit out of my hat."
... watch me pull a rabbit out of my hat.

just_modules_test $ just bbb xyzzy 'Lovely female'
error: Justfile does not contain recipe `female`.
error: Recipe `bbb` failed on line 22 with exit code 1

just_modules_test $ just bbb xyzzy monkey
echo "Magic for bbb"
Magic for bbb
echo "... watch me pull a monkey out of my hat."
... watch me pull a monkey out of my hat.
</pre>

**Comment by runeimp** [comment]
Would be nice to have this setup as an example in the repo or at least be referenced in the README

**Comment by MadBomber** [comment]
I just release v1.2.3 of `justprep` that implements this fake module convention.  I've also started loading its Github Wiki with documentation for `justprep` since I can't seem to get its README.md file under control.

Here is the URL for the Wiki;
https://github.com/MadBomber/justprep/wiki

BTW the implementation is much cleaner than the example I originally posted here.

**Comment by casey** [comment]
We now have a real module system! Thanks again @MadBomber for providing a great stopgap.

**Comment by MadBomber** [comment]
My pleasure @casey you have a great project that I use every day.  I am happy to completely retire my `justprep` preprocessor since `just` now has real modules and a real include system.
