### ISSUE TITLE
Lazy variables

### ISSUE THREAD

**Issue by olekslitus** [casey/just#1233]
I would love to be able to make some or all of the variables to be lazy and only get assigned when called.
This would help only raise error, when user is trying to execute one command that is not legitimate on this platform,
yet give them ability to use others.

Examples of how to achieve this:

New syntax for variable declaration:
```
install TARGET:
    {{~install}} TARGET

~install := if path_exists('/etc/debian_version') {
    'dpkg -i'
} else if path_exists('/etc/redhat-release') {
    'rpm -U'
} else {
    error('Your distro is not supported')
}
```

New config:
```
set lazy_vars
```

**Comment by casey** [comment]
Let me know if you think this is covered by #953.

**Comment by olekslitus** [comment]
Hmmm, I think making the assignment itself lazy would solve #953 in a nicer and more consistent way. In practice I do not want all backticks to be lazy, only top level ones, which are assigned into vars. At this point it would be better to make all vars lazy in my opinion.

**Comment by casey** [comment]
I think you're right that assignments in general should be lazy, not just backticks. It's more useful and more general. I updated the title in #953 to reflect this, and we can use #953 as the tracking issue.
