### ISSUE TITLE
Lambda function

### ISSUE THREAD

**Issue by stevefan1999-personal** [casey/just#1234]
It would be cool if we can have lambda functions

```just
workspace := `$env.PWD`
out_dir_prefix := workspace + '/out'
out_dir_profile := fn (profile) => clean(join(out_dir_prefix, profile))

build-kern profile='dev':
    cargo build -Z unstable-options --profile {{profile}} --out-dir {{out_dir_profile(profile)}}
```

Related: #799  #277

**Comment by casey** [comment]
There's actually an issue and PR for custom functions: #1059 and #1060. Would that cover your use-case? Lambdas are unlikely to be implemented any time soon, because they would complicate the type system.

**Comment by stevefan1999-personal** [comment]
@casey Agreed...I tried implementing Hindley-Milner Type Inference on my own and it is exceedingly difficult for me...And HM is almost a must for lambdas. I didn't thought just implemented a strongly typed system though.

Closing this as a duplicate

**Comment by casey** [comment]
> @casey Agreed...I tried implementing Hindley-Milner Type Inference on my own and it is exceedingly difficult for me...And HM is almost a must for lambdas. I didn't thought just implemented a strongly typed system though.

Just *sort of* has a static type system. There is only one type, that of "string", but static analysis is performed to make sure that all variables exist.
