### ISSUE TITLE
Publish new versions to snap store automatically

### ISSUE THREAD

**Issue by casey** [casey/just#1249]
We should publish a new version of `just` to the snap store automatically, probably by adding a job to the `release` GitHub Actions workflow. Since creating the snap package, I no longer have a debian box, so doing it automatically on snap is going to be the best way to keep it up-to-date going forward.

**Comment by nk9** [comment]
It looks like this one would do the trick? https://github.com/marketplace/actions/snapcraft-action Credentials for the app's Snapcraft account need to be set in the repo's Secrets.

**Comment by casey** [comment]
That looks very promising. If it's possible to do it without an action, that would be a little better. I wouldn't want to use an action if it's only a few lines to do it manually, but if it's more than that, an action is definitely the way to go.

**Comment by nk9** [comment]
I don't use Snapcraft, and since I usually use an M1 Mac, it looks like I'm not able to at the moment. https://github.com/canonical/multipass/issues/2399 So I won't be able to test this myself.

**Comment by LyzardKing** [comment]
Hi @casey . This should be doable without a github action, and using instead the snapcraft build system.
On the snapcraft page you can link to the github repo, and it will rebuild on every commit.

**Comment by impredicative** [comment]
I don't know why `snap` is still kept in the readme if it's not been updated in years. Someone can accidentally install an old version of `just` via `snap`, then wonder why it doesn't work right.

**Comment by endothermicdev** [comment]
I just installed v1.2.0 via snap, which was incompatible with [warnet](https://github.com/bitcoin-dev-project/warnet).  Either removing it from the docs or publishing to snap automatically would be nice.

**Comment by lucabello** [comment]
Hey @casey, I use `just` a lot in my personal projects and would love to be able to `snap install` it.

Would you be open to me submitting a PR with the necessary modifications to make that happen?

**Comment by casey** [comment]
@lucabello Thank you for the offer! Ubuntu 24.04 and later, as well as Debian 13 (unreleased) both have `just` in their normal package repositories, so you can `apt install just`. Is there any avantage to continuing to maintain the snap?

Snap is a huge pain if you don't use Ubuntu, which I don't, so after I initially published it, it has sadly languished.

I'm hesitant to try to automatically submit new versions in GitHub actions on release, because it will inevitably break and be fiddly.

I think the ideal case is probably to pass the snap package off to someone else who will maintain it. That being said, it might be best just to retire it, given that new versions of Ubuntu, and soon Debian, will have just in apt.

**Comment by lucabello** [comment]
The main reason for me is that Ubuntu 24.04 (the latest LTS) has version `1.21.0-1`, and I use many features from newer versions. I would also like to run it on Ubuntu 22.04 VMs have pre-build steps in those environments.

I don't think the maintenance burden would be too high, but I understand if don't have an interest in maintaining it, and given that `just` is available in `pypi`, I can still install the latest version via `pipx`.

If you'd rather pass the snap package off though, I'd be happy to look into how the transfer process works and maintain it in a separate repo for the foreseeable future :)

**Comment by casey** [comment]
I think probably using the `pypi` package is best. Another option is always to build it from source using `cargo`, which will guarantee you always have access to the latest version. I don't think `just` has any dependencies on Linux, so if your system has rust, you can compile and install it with `cargo install just`.

I'm going to close this issue, since I think publishing new versions to the snap store is definitely not going to happen any time soon 😅

**Comment by impredicative** [comment]
There is a benefit to `snap` over `apt`, which is that `snap` packages, once installed, are kept updated without any effort.

In any case, `snap` is not so useful when running `just` in a container or devcontainer, as the container is very unlikely to be Ubuntu.

**Comment by lucabello** [comment]
@casey It's ultimately your decision, but if you're going to retire the `snap`, you might as well transfer it to me — it's pretty much the same effect, but it would save me some steps in either publishing under another name (e.g. `rust-just`), or (if you retired it) under the same name but going through the review process for a `--classic` snap again.

To give you an example of how this would look like, something similar has been done for the `astral-uv` project: [Upstream](https://docs.astral.sh/uv/), [Snapcraft page](https://snapcraft.io/astral-uv), [snap repo](https://github.com/lengau/uv-snap).

The way I see it, this gives you an additional installation option with really no overhead (since I would maintain the snap repo); the only thing you'd be asked to do is to leave a comment on a Discourse post to confirm that everything is above board.

**Comment by casey** [comment]
@lucabello I'd normally be a bit hesitant to transfer a package that I used to maintain to someone else, for fear that the new maintainer might do something nefarious. But I see you work at Canonical, and I don't think they employ many nefarious hackers. I sent you an email to your `@canonical.com` email address, just to confirm that you work there. Can you reply to confirm and let me know how transferring a snap works?

**Comment by lucabello** [comment]
For anyone interested, I was kindly handed over the snap package, so you can now `snap install just` and get `1.37.0`!

https://snapcraft.io/just
