### ISSUE TITLE
build-book needs to install dependency of mdbook

### ISSUE THREAD

**Issue by TopherIsSwell** [casey/just#1258]
if you don't have the `mdbook` binary installed, the `build-book` target fails. I would make a PR to just run `cargo install mdbook` (which fixes the problem), however, there's half a dozen places this could go. So this is really a design problem more than a technical one.
- You could put it in the `build-book` target. 
  - but you might want to avoid running the install every time. 
    - I would normally address this with something like `[[ -x $(which mdbook 2> /dev/null) ]] || cargo install mdbook` but that builds a dependency on bash and a *nix environment, which is probably undesirable. 
- You could put it in the `install-dev-dependencies` target
  - But that might irritate developers that just want dependencies for the binary and extend CI builds and so on.
- You could build a new target like `install-all-dev-dependencies` or `install-book-dev-dependencies` and put it in there.
- There are probably other places you could put it that I can't conceive of because I'm not familiar with the project. 

Thought I'd throw this out there. It's a minor problem, but one I can't just push a quick fix to unless I know the what the maintainers would prefer.

**Comment by TopherIsSwell** [comment]
update: Sorry, I forgot. You would also need to `cargo install mdbook-linkcheck`

**Comment by casey** [comment]
I think it's fine to put it in the `install-dev-deps` recipe. The recipe is mostly for documentation purposes, so it's fine if people have to copy out lines and only run some of it if they don't want everything.

**Comment by TopherIsSwell** [comment]
Added pull request #1259
