### ISSUE TITLE
change working directory of calling shell

### ISSUE THREAD

**Issue by sguimmara** [casey/just#1261]
I'm planning to use just to help me navigate the filesystem.

For example:

```shell
just sandbox
```
Would use a chooser to locate a particular folder in my `sandbox` directory, then cd into it. However, `cd` in a recipe only effects the subshell executing the recipe, not my own shell. I'm still stuck in `$HOME`.

Is there a way to do that ?

**Comment by casey** [comment]
This is very a common limitation to run into. A unix process can only change the working directory of the current process, not of a parent process or subprocess.

A common way to get around this is to use an alias, for example:

```
alias sandbox="cd `cd sandbox && fzf`"
```

Aliases run in the current shell's process, so they can modify the current working directory, just like `cd` itself.

**Comment by sguimmara** [comment]
Yes, I already had an alias for that, but I was hoping to be able to do it with just, for consistency sake. Thanks for the explanation ! closing

**Comment by casey** [comment]
> Thanks for the explanation

You bet!
