### ISSUE TITLE
Allow unsetting environment variables

### ISSUE THREAD

**Issue by nickbabcock** [casey/just#1263]
Just has support for setting environment variables:

```
export RUST_BACKTRACE := "1"

test:
    cargo test
```

But does not support unsetting environment variables

```
unset RUST_BACKTRACE

test:
    cargo test
```

In the ideal scenario, the environment variable has an equivalent value to being unset (0 in the case for `RUST_BACKTRACE`)

Unfortunately, some programs, crates, and/or libraries treat an unset environment variable different than even an empty string, so it would be helpful to be able to unset these at the global level instead of remembering to sprinkle in the manual method everywhere:

```
test:
    #!/bin/bash -x
    unset RUST_BACKTRACE
    cargo test
```

**Comment by casey** [comment]
This definitely seems useful, and the `unset FOO` seems reasonable. The best way to implement this is probably with a new `Item` variant, `Item::Unset(String)`, which causes exported variables to be unset.

**Comment by neunenak** [comment]
Should be closeable now with https://github.com/casey/just/pull/2098
