### ISSUE TITLE
Comments within the body of a just recipe should be ignored

### ISSUE THREAD

**Issue by neunenak** [casey/just#1274]
If I have a justfile like:

```
some-recipe argument:
    # Here is a comment
    @echo "hello"
    # Another comment
    @echo {{argument}}

```

When I run it I get the output:

```
just some-recipe "some text"
# Here is a comment
hello
# Another comment
some text
```

I can make the printing of those comments go away by adding a `@` in front of them, but it would be nice if just interpreted comments within a just recipe as comments and completely ignored them. 

I think what might be happening here is that the comment lines are each getting echoed by just and then passed to a shell invocation, where they do absolutely nothing because sh and just have the same syntax for comments.

**Comment by casey** [comment]
> I think what might be happening here is that the comment lines are each getting echoed by just and then passed to a shell invocation, where they do absolutely nothing because sh and just have the same syntax for comments.

This is exactly right. We could not echo lines starting with `#`, but it's possible to change the interpreter, and different interpreters might have different comment syntaxes, and `#` at the beginning of the line might be significant.

Also, people might be relying on this behavior, i.e. using the echoing of a comment line to see what a recipe is doing.

One thing that comes to mind is adding an optional setting that allows specifying a regex, where lines matching that regex are not echoed:

```
set quiet-lines := "#.*"
```
