### ISSUE TITLE
`windows-shell` does not work as well as `windows-powershell` on cross-platform justfiles

### ISSUE THREAD

**Issue by chamons** [casey/just#1279]
I have a trivial Justfile I'd like to share on macOS and Windows:

```
watch:
    npx tailwindcss -i ./styles/styles.css -o ./static/styles.css --watch

serve:
    zola serve
```

However, I need it to work on Windows with powershell, so I tried the new `windows-shell`:

```
set windows-shell := ["powershell.exe", "-c"]

...
```

But when I run that on macOS I get:

```
error: Unknown setting `windows-shell`
  |
1 | set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]
```

But this works:
```
set windows-powershell := true

...
```

But the documentation states:

> set windows-powershell uses the legacy powershell.exe binary, and is no longer recommended

**Comment by casey** [comment]
Hi @chamons! I think the `just` you have on MacOS is older than the one you have on Windows. `windows-shell` was added a few versions after `windows-powershell`, so you probably have a version with the latter but not the former.

**Comment by chamons** [comment]
Yep, that was it! Sorry for the trouble.

**Comment by casey** [comment]
No worries, glad it's working!
