### ISSUE TITLE
Install script does not work on Raspberry Pi Zero

### ISSUE THREAD

**Issue by michidk** [casey/just#1284]
Running the script (the first time) returns the following error:
```sh
pi@raspberrypi:~ $ curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to DEST
install: error: Could not determine target from output of `uname -m`-`uname -s`, please use `--target`: armv6l-Linux
```

Running it again or with sudo won't return anything:
```sh
pi@raspberrypi:~ $ curl --proto '=https' --tlsv1.2 -sS^Chttps://just.systems/install.sh | bash -s -- --to DEST
pi@raspberrypi:~ $ sudo curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to DEST
pi@raspberrypi:~ $ 
```

OS/Arch:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux
```

**Comment by casey** [comment]
Interesting! I'm not familiar with the `armv6l` target. We have an `aarch64-Linux` target. If someone can figure out how to build on GitHub Actions CI for armv6l, then we can add it to the release script and publish binaries that will work on the zero.

**Comment by Dygear** [comment]
For what it's worth, this does work on a Raspberry Pi 5 (armv8, aarch64). The install script uses the musl variant. Needed this to be able to compile Cosmic on the Raspberry Pi 5.

**Comment by YDX-2147483647** [comment]
Some information in [Platform Support - The rustc book](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools):

> Support for different platforms ("targets") are organized into three tiers, each with a different set of guarantees.

- `arm-unknown-linux-gnueabi` (ARMv6 Linux, kernel 3.2, glibc 2.17) is a tier 2 target (guaranteed to build).
- `arm-unknown-linux-musleabi` (ARMv6 Linux with MUSL) is a tier 2 target (guaranteed to build), but without host tools.
- `aarch64-unknown-linux-gnu` (ARM64 Linux, kernel 4.1, glibc 2.17+) is a tier 1 target (guaranteed to work). _(This is what Dygear mentioned)_

Besides,

- I sometimes cross compile from `x86_64-pc-windows-msvc` to `aarch64-unknown-linux-musl` (ARM64 Linux with MUSL) with `linker = "rust-lld"`. Although `aarch64-unknown-linux-musl` is a tier 2 target, it always works. _(We already have this target)_
- `aarch64-unknown-linux-gnu` is a tier 1 target, but it needs glibc 2.17+. (musl is statically linked, therefore glibc does not matter)

**Question**: What is the glibc verion on Raspberry Pi Zero? You can check it by `ldd --version`. It determines whether we must use musl or not.

**Edit**: Please see #1715.

**Comment by YDX-2147483647** [comment]
After  #1715 is merged, I guess `--target arm-unknown-linux-musleabihf` should work and we can closed this issue?

**Comment by Dygear** [comment]
You can also just run `cargo install just` and it will also work. So I say close it.
