### ISSUE TITLE
How to use variables in commands with backticks?

### ISSUE THREAD

**Issue by PotatoesFall** [casey/just#1292]
I read the README and couldn't find this. If I missed it, apologies.

In Makefile, I could do this:
```makefile
GIT_COMMIT := $(shell git rev-parse --short HEAD)
GIT_TIME := $(shell git show -s --format=%ci $(GIT_COMMIT) | tr -d '\n')
```

In `just`, I understand that backticks can be used to save the output of a command:
```justfile
GIT_COMMIT := `git rev-parse --short HEAD`
GIT_TIME := `git show -s --format=%ci $(GIT_COMMIT) | tr -d '\n'`
```

however, the second command fails with `/usr/bin/sh: GIT_COMMIT: command not found`

The {{}} syntax also doesn't work here, how can I use a variable in a command?

**Comment by runeimp** [comment]
My guess is that all or multiple lines like that are processed concurrently or at least not in order. Though @casey would know for sure. 😇

**Comment by casey** [comment]
So a few things are preventing this from working. First, `just` variables are distinct from shell variables, so you'll need to use the `export` keyword to export them:

```
export GIT_COMMIT := `git rev-parse --short HEAD`
export GIT_TIME := `git show -s --format=%ci $(GIT_COMMIT) | tr -d '\n'`
```

However, assignments are not processed in the order that they appear in a source file, so exported variables aren't available in backticks within the same scope, so `GIT_COMMIT` still wouldn't be available to the backtick assigned to `GIT_TIME`.

Hopefully we'll eventually support some kind of syntax that allows this, perhaps #799 or #822, but it might be a while! Sorry I don't have better news!

**Comment by PotatoesFall** [comment]
Ah okay that's clear, thanks. I'm sure I'll find another solution for my problem :)

**Comment by melMass** [comment]
Sorry to bump an old issue but just to be sure, this is not possible to escape variables directly either right?

```sh
root := `{{justfile_directory() / ".."}} | path expand`
```

(I use nushell here but you can replace the idea with `realpath {{justfile_directory() / ".."}`

EDIT: actually in my case the execution pwd in in fact justfile_directory.. so unrelated but this works fine: ``root := `".." | path expand` ``

**Comment by casey** [comment]
That's correct, interpolations in backticks aren't supported.

**Comment by pniederlag** [comment]
to bad... still true in 2024 ?

**Comment by runiq** [comment]
You can use the `shell()` function, which just takes a string, which you can construct the usual way. For example:

```just
FILE := "/etc/os-release"
CONTENTS := shell("cat " + FOO)

# Shows the contents of the file whose name is in the variable FILE
show-file:
    echo {{CONTENTS}}
```

**Comment by casey** [comment]
There are a few other ways to make this nicer:

```just
FILE := "/etc/os-release"

# shell can take arguments:
CONTENTS := shell("cat", FOO)

# f strings support formatting:
CONTENTS := shell(f"cat {{FOO}}")
```
