### ISSUE TITLE
Allow configuring tempdir

### ISSUE THREAD

**Issue by casey** [casey/just#1300]
Sometimes TMPDIR is set to an invalid value, for example see #1269. To allow users to work around this, it should be possible to configure which tmpdir a justfile uses. A setting seems like the best approach:

```
set tmpdir := "foo"
```

It should be joined with the working directory, so it can be relative or absolute.

**Comment by Smurphy000** [comment]
Hey @casey I'd be interested in implementing this if you have any pointers (familiarizing myself with the repo). Also I will not have time to start on this until next week if anybody else wants to pick this up before then.

**Comment by casey** [comment]
Hi @Smurphy000, awesome! My suggestion would be to write the tests first. You can even open a draft PR with just the tests, and I can confirm that they look good. Then you can work backwards and implement the feature. First you'll get parse errors, so parse the setting, then you'll have to implement it. The actual change will be in `Recipe::run_shebang`, where the script temporary file is created.

**Comment by casey** [comment]
Implemented in #1369!
