### ISSUE TITLE
Support for `.just.config` for command-line arguments

### ISSUE THREAD

**Issue by DeeGeeMan** [casey/just#1307]
It would be beneficial if users could set some of the command-line arguments inside a `.just.config` file.

```
{
   color: "never",
   dotenvPath: "./",
   dotenvFilename: ".env.default"
}
```

**Comment by casey** [comment]
Agreed! Although this is a dupe of #395. Note that only things which don't lead to breakages if they're missing can be allowed inside of `.just.config` files, since otherwise users would write justfiles that wouldn't work without the config.
