### ISSUE TITLE
Conditionals for parameters?

### ISSUE THREAD

**Issue by frederikhors** [casey/just#1309]
I'm having trouble using the below code.

Is it possible to use it or something like this?

```justfile
clear what:
  if {{what}} != "" {
    just clear_{{what}}
  } else {
    just clear_1
    just clear_2
  }

clear_1:
  clear 1

clear_2:
  clear 2
```

**Thanks.**

**Comment by casey** [comment]
Yooooooooo. The code you posted is currently the only way to do this. Just currently plans out what recipes will execute ahead of time, i.e. it doesn't make decisions based on runtime data.

I think we could implement a simple version of this, which executed dependencies or not depending on some conditional:

```
# only execute `bar a` if `a == "foo"`
foo a: (?a == "foo" => bar a) # incredibly shitty syntax, but has to be unambiguous with normal dependency

bar a:
  echo {{a}}
```

But we couldn't do something like `bar: foo_{{variable}}`, because just needs to plan the whole execution ahead of time.

**Comment by frederikhors** [comment]
Ok. Thanks. I don't need it anymore. I'm switching to use PowerShell directly.

**Comment by frederikhors** [comment]
Feel free to close this of you need.

**Comment by runeimp** [comment]
@casey  how is this possible? I've never been able to get Just's conditional code to work within a recipe.

**Comment by casey** [comment]
@runeimp It's not possible, I just closed it because the the original requestor didn't need it any more. I'm definitely open to reopening it, although I still can't think of a decent syntax for it.

**Comment by indietyp** [comment]
I'd love to get this reopened. Something like this could be beneficial in cases where one wants to, e.g. only run commands if in CI.

How about something similar to the snippet posted below? This would increase reusability and readability by moving it outside the recipe declaration.

~~~just
in_ci := env_var_or_default('CI', "0")

foo a:
	...

[conditional(in_ci == "1")]
foo-ci a: foo a

bar a: (foo-ci a)
	...
~~~

Another possibility would be (tho controversial)

~~~just
in_ci := env_var_or_default('CI', "0")

is-ci? in_ci == 1
# alternative syntax: "fn is-ci():", "is-ci():", etc.
# or: is-ci := () -> in_ci == 1

foo a:
	...

bar a: (is-ci foo a)
# alternative: bar a: (?is-ci foo a)
~~~

where only if the function recipe (?) `is-ci` evaluates to true the recipe mentioned after is executed.

**Comment by runeimp** [comment]
@indietyp I like the idea. But you can get the same results with something like...

```just
in-ci := env_var_or_default('CI', "0")
ci-suffix := if in-ci == "1" { '_ci_env' } else { '' }

@_default:
	just --list

# Recipe that calls hidden recipes
@recipe_name:
	echo "Recipe router"
	echo "Router in-ci: {{in-ci}}"
	echo 'Router ci-suffix: "{{ci-suffix}}"'
	just _recipe_name{{ci-suffix}}

@_recipe_name:
	echo "Base code"

@_recipe_name_ci_env: _recipe_name
	echo "CI code"
```

```sh
$ just recipe_name
Recipe router
Router in-ci: 0
Router ci-suffix: ""
Base code
```

```sh
$ CI=1 just recipe_name
Recipe router
Router in-ci: 1
Router ci-suffix: "_ci_env"
Base code
CI code
```

The last block demonstrates adding a environment variable  to a command run which is something common to UNIX and UNIX-like systems.
