### ISSUE TITLE
Using variables in recipe parameters

### ISSUE THREAD

**Issue by papertigers** [casey/just#1310]
I noticed it's not currently possible to do something like:
```
first_path := "foo"
second_path := "bar"

copy file:
    cp {{file}} /tmp

setup: (copy {{first_path}})
    some_cmd

setup-dev: (copy {{second_path}})
    other_cmd
```

Is this by design or just something that no one has added support yet? In my real life example I have two top level commands that currently take string values for file names.  I would like to define those file names as a variable that I can reuse.

**Comment by casey** [comment]
Outside of recipes, you don't need `{{…}}` to do interpolation:

```
first_path := "foo"
second_path := "bar"

copy file:
    cp {{file}} /tmp

setup: (copy first_path)
    some_cmd

setup-dev: (copy second_path)
    other_cmd
```

Let me know if that works for you!

**Comment by papertigers** [comment]
That works! Thanks, I should have realized that was the case. 

Is the namespace global?  For example if one defines the `foo` variable at the top of a justfile and then makes a recipe like `do_stuff foo:`.  Will that overwrite the variable set or is it scoped to just that recipe? Thanks again.

**Comment by papertigers** [comment]
PS added a short example for this in #1311 if you find it useful.

**Comment by casey** [comment]
> Is the namespace global? For example if one defines the foo variable at the top of a justfile and then makes a recipe like do_stuff foo:. Will that overwrite the variable set or is it scoped to just that recipe? Thanks again.

You bet! The namespace is global, but if you try to redefine a variable with a function parameter, it actually complains:

```
error: Parameter `foo` shadows variable of the same name
  |
3 | j foo:
  |   ^^^
```
