### ISSUE TITLE
`cargo install just` fails to compile just v1.4.0

### ISSUE THREAD

**Issue by mrcnski** [casey/just#1312]
## Error

```
error: unknown `--json` option `future-incompat`

error: could not compile `target`
warning: build failed, waiting for other jobs to finish...
error: failed to compile `just v1.4.0`, intermediate artifacts can be found at `/var/folders/gw/053czpm957z2rq6k8xqvnxx00000gn/T/cargo-installckbwiW`
```

## Rustc version

```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

## Cargo version

```
cargo 1.62.0 (a748cf5a3 2022-06-08)
```

**Comment by casey** [comment]
Thanks for the report! It seems to be working for me. I notice that your rustc and cargo are different versions. Here's what I get:

```
: rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)
: cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)
```

Could that be the source of the problem?

**Comment by mrcnski** [comment]
Ah, of course. My `rustup` installation was corrupted -- had to uninstall and reinstall everything, and also manually remove the bad `cargo` binary. Thanks for the quick reply!

**Comment by casey** [comment]
You bet! We're actually super lucky it happened to show up as mismatched version strings. If it were corrupted in some other way, it might have been super hard to figure out.
