### ISSUE TITLE
`just --clean` (fix whitespace in justfile)

### ISSUE THREAD

**Issue by Mjboothaus** [casey/just#1313]
Hi - awesome tool!  😃 

Would be great to be able to have a `--clean` option or similar to clean up the whitespace in the just file. So that I don't get looks of these errors:

error: Recipe line has inconsistent leading whitespace. Recipe started with `␉` but found line with `␠␠`

Keep up the great work.

**Comment by casey** [comment]
Thank you!

I'm not actually sure if this is possible, in the general case, just doesn't know how much indentation to put at the beginning of recipe lines, or how many tabs equals how many spaces. Also, if you mix tabs and spaces, just doesn't know if it should use all tabs or all spaces.

**Comment by fabienheureux** [comment]
For what it's worth, if anyone find this issue, ChatGPT can be quite effective to this task. 
Ask to "Fix this makefile", git it your justfile, and voilà.

For this kind of simple task, it should not hallucinate and alter it but it is always better to double check that it did not alter the content of your commands
