### ISSUE TITLE
Suggestion: subcommands by chaining justfiles

### ISSUE THREAD

**Issue by indigoviolet** [casey/just#1317]
Have you considered more explicit support for sub-commands? Specifically: having a recipe that could "chain" into a different justfile. So if I have 
```
#.justfile
sub = subcommand("/path/to/sub.justfile")
```

```
#sub.justfile
foo_recipe:
    ....
```

I could execute `just sub foo_recipe`.

This supports modularization in some ways, and it could help organize multiple justfiles in a neat way. 

It's pretty easy to simulate today:

```
sub subcmd *args:
     just -f /path/to/sub.justfile {{ subcmd }} {{ args }}
``` 

But you could imagine adding niceties on top: shell completion & help for the subcommand recipes, passing down variables etc.

**Comment by casey** [comment]
Definitely! I want to do this via a module system, see #383 and #929.
