### ISSUE TITLE
Thank you for creating and maintaining just - a utility that enables your creativity and clean workflows 

### ISSUE THREAD

**Issue by epogrebnyak** [casey/just#1322]
I have been a casual user of just for a while and at each of the steps I was able to get support and clarification from @casey here at issues. 

I'm usng `just` at a new project that involves building and exporting documantation at various formats and `just` proved itself as truely an enabler for the workflow, not just a utiltiy that helps to fix something to repeat, but a tool that allows exporation and learning.

A few details:

- I'm not a bash or command line guru, but just allows to save quickly things that work and reuse and review them
- by trying several versions of commands I was able to discover better and cleaner workflows that did not emerge at first attempt
- a lot of this work is back and forth, try this and that, but then you tend to crystalise better solutions and reuse them
- justfiles are discoverable on github and I'm planning to share mine - could be useful for user of jupyterbook.

Few things I was able to achieve is the following:

- use `pyproject.toml` version for Github releases and tags
- send `pyproject.toml` version to sphinx  documentaiton
- make a Github release with all artefacts, or roll back a release too
- combine poetry environment manager to run jupyter-book commands

All of the above is achieved through composing commands in a best of linux philosophy and picking commands that work best, for example there are several npm utilities that I used in a primary Python-based project, sometimes a JS utility instead of a corrsponding Python utility (for example, `mustache`). 

Also my observation is that just also makes setup and learning within a team more manageable. 

The alternatives for `just `I think are made to allow shipping finished software (eg MAKE, invoke), not exactly exploring, learnign and iterating fast, as `just` does.

Thanks again for the useful utility and all the support @casey!

**Comment by casey** [comment]
Thank you so much Evgeny for the kind words! It's so nice to be able to enable other people to be more productive, and make their workflows easier and more fun. I like this issue so even though there's no bug or feature request, I'll leave it open for a bit 😄

**Comment by epogrebnyak** [comment]
Here is a project `justfile`, in case anyone interested:

```
# List available commands.
list: 
 - just --list

# Prettify markdown files.
lint:
  - npx prettier . --write

# Clean _build folder.
clean folder:
 - rm -rf {{folder}}/_build/

# Build jupiter-book outputs of various types.
_build builder folder:
 - poetry run jb build {{folder}} --config ./_config.yml --path-output {{folder}} --builder {{builder}}

# Build HTML and see website.
html folder:
 - just _build html {{folder}}
 - start {{folder}}/_build/html/index.html

# Build, purge and save single page HTML to /assets/page folder.
page folder:
 - just _build singlehtml {{folder}} 
 - pandoc -f html -t html {{folder}}/_build/singlehtml/README.html > assets/page/{{folder}}.html 

# Build PDF via headless browser and save to /assets/pdf folder.
pdf folder:
 - just _build pdfhtml {{folder}}
 - cp {{folder}}/_build/pdf/book.pdf assets/pdf/{{folder}}.pdf
 
# Build LaTeX.
latex folder:
  - just _build latex {{folder}} 

# Build DOCX and save to /assets/docx folder.
docx folder:
  - just latex {{folder}}
  - pandoc -f latex -t docx {{folder}}/_build/latex/book.tex -o assets/docx/{{folder}}.docx

# Build single-page HTML, PDF and DOCX and save to /assets folder.
assets folder:
  - just page {{folder}}
  - just pdf {{folder}}
  - just docs {{folder}}

# Build all PDFs.
pdf-all:
  - just pdf Flyer
  - just pdf Overview
  - just pdf Day2
  - just pdf Glossary

# Check spelling.
spell folder:
  - yaspeller {{folder}}

# Project version from pyproject.html prefixed by v (eg v0.3.1)
version:
  - poetry version -s | tr -d '\r' | xargs -I % echo v%

# Uptick patch version.
uptick:
  - poetry version patch
  - just make-config

# Make a Github release.
release title:
  - just version | xargs -I % git commit -am"% {{title}}"
  - git push 
  - just version | xargs -I % gh release create % 'assets/pdf/Flyer.pdf#Флайер' 'assets/pdf/Overview.pdf#Обзор курса' 'assets/pdf/Day2.pdf#Проведение испытания' 'assets/pdf/Glossary.pdf#Глоссарий' -F release.md -t "{{title}}"

# Delete latest Github release.
release-rollback:
   - just version | xargs gh release delete 

# Delete remote tag.
untag tagname:
  - git push --delete origin {{tagname}}

# Create _config.yml from _config_template.yml file.
make-config:
  - poetry run python scripts/from_toml.py . | mustache - _config_templatе.yml > _config.yml
```

**Comment by casey** [comment]
> Here is a project `justfile`, in case anyone interested:

Nice! I see the `  -` prefix for most recipes. Is this to suppress errors?

**Comment by epogrebnyak** [comment]
> Nice! I see the ` -` prefix for most recipes. Is this to suppress errors?

I think I worked too much in markdown and I was inserting `-` just as a notation for list of commands. Everything supposed to work without `-` prefix, thanks for pointing out!

**Comment by casey** [comment]
Ah, okay. That will work, but it will have an unexpected side-effect! The `-` prefix makes `just` keep going if a command fails. Normally, if you do:

```
foo:
  command-that-fails
  echo bar
```

`echo bar` will never run, because `just` stops after `command-that-fails` fails.

If you do:

```
foo:
  -command-that-fails
  echo bar
```

Then `echo bar` will still run. This is useful if you want a recipe to keep going after something fails, but usually what you want is for a recipe to stop after a command fails.

**Comment by epogrebnyak** [comment]
Thank you for explaining, @casey!
