### ISSUE TITLE
Justfile in this repository contains an invalid shebang

### ISSUE THREAD

**Issue by hwittenborn** [casey/just#1329]
Looking at the [justfile in this repository](https://github.com/casey/just/blob/master/justfile), it appears to be using an invalid shebang. Using it on my Ubuntu 22.04 system shows the following error from the `env` command:

```
/usr/bin/env: ‘just --justfile’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

Following the `-S` suggestion makes calling `./justfile` work correctly:

```
#!/usr/bin/env -S just --justfile
```

**Comment by casey** [comment]
Nice, thanks for reporting this! I develop on a Mac, and I know that BSD-derived unices parse shebang lines differently. Fortunately it looks like `-S` is supported everywhere, and adding it doesn't break MacOS, so adding it in #1330.
