### ISSUE TITLE
just variable to be exported as environment variables (array)

### ISSUE THREAD

**Issue by tomikais** [casey/just#1332]
Hi casey,

is it possible to export a just variable as an array? Something like this?

```just
set export := true
ips        := '(
192.168.0.1
192.168.0.2
)'
```

My plan is to define this array and use it in the recipes.

Kind regards, Thomas

**Comment by casey** [comment]
Currently not, and I'm not sure it's possible. `just` exports variables to the shell as environment variables, and I believe that it's only possible to export variables as strings, and not as lists, which are only supported by certain shells.

**Comment by runeimp** [comment]
Most modern shells (including most versions of `bash`, `csh`, `ksh`, `tcsh`, and `zsh`) support arrays or lists. But the Just default shell `sh` (Bourne Shell) does not. In most systems `sh` is actually an alias to `ash`, `bash`, or `dash`. These shells usually run in POSIX mode when accessed as `/bin/sh` and the POSIX shell definition doesn't support arrays or lists so even when the native shell supports arrays it's not usually available as `sh`. So supporting arrays/lists by default would be problematic at best. Though maybe it could be allowed via a settings such as `set allow-array-vars` when changing the default shell?

**Comment by casey** [comment]
@runeimp It's true that many shells support arrays. However, `just` is invoking the shell as a subprocess, so there would need to be some way to pass arrays through environment variables to the shell. Is that possible? I thought environment variables could only be strings.

**Comment by runeimp** [comment]
Most shells have an option to specify a dot file to load with the shell invocation.

All shell variables are environment variables if they are exported, no? Originally they were always strings back in the AT&T UNIX days. Arrays were a feature added to later shells. Original UNIX shells didn't have arrays. Which, of course, is why the PATH variable uses semicolons as a separator character on Windows and colons everywhere else. Sort of the original CSV of the time. 

I did some testing and Bash (my primary shell) had no problem with loading arrays from it's dot files. Unfortunately my environment is a bit screwy at the moment though and I could not get my other shells to successfully read new variables from their respective dot files. But I would be surprised if the majority had any problems with arrays.

The bigger issue to me is simply that the default is Bourne / POSIX Shell and many semi-popular shells don't support arrays or lists. So it's definitely tricky either way.

**Comment by tomikais** [comment]
This works for me! I write my array to the dot env file and use it in my just scripts :-)

**Comment by ross-spencer** [comment]
Apologies for dragging this one up from the past, but is there any further guidance on this?

.env:

```sh
export PROVIDER=(1, 2, 3)
``

justfile:

```just
set shell := ["bash", "-uc"]
set dotenv-filename := 'provider.env'
```

But it fails with the error:

```sh
error: Failed to load environment file: Error parsing line: '("1" "2" "3")', error at line index: 5
```

Just is at 1.35.0. 

Is it expected to work, or am I reading the issue incorrectly?

**Comment by casey** [comment]
I guess that `export PROVIDER=(1, 2, 3)` isn't valid syntax for a `.env` file. But more importantly, even if it was, shells that support array variables only support them for local variables, and can't import and export them.

**Comment by runeimp** [comment]
@ross-spencer If you do `export PROVIDER='1;2;3';` (Windows) or `export PROVIDER='1:2:3';` (non-Windows) some shells will interpret PROVIDER as an array automatically. You seem to be using Bash which may work depending on the version. I think Bash 4 was the first version with arrays. But I could be wrong.
