### ISSUE TITLE
Supress the "error: Recipe `...` failed on line ... with exit code ..." without suppressing the exit code

### ISSUE THREAD

**Issue by aldanor** [casey/just#1334]
If you're wrapping some binary CLI with `just`, e.g.

```sh
$ just some-command --some --flags
```

It will often return a non-zero exit code (e.g. 2) while you trying to browse through some arguments (especially if there's incomplete subcommands that have further nested subcommands etc). It's pretty annoying to have the `error: Recipe `...` failed on line ... with exit code ...` message pop up every time, making it feel somewhat alien.

Suppressing the error is not the right solution though, because it should remain to be a non-zero exit code! (especially if called from some scripts)

Is there a way to make `just` even more transparent and a bit more quiet? I.e., don't suppress exit codes but don't print anything extra to the output, at all (unless there's some fatal errors in the justfile itself).

// Apologies in advance if I'm missing something obvious here but I couldn't find anything except `@` and `-`.

**Comment by casey** [comment]
How about using the `--quiet` flag? You could do this:

```
just -q some-command --some --flags
```

**Comment by aldanor** [comment]
> How about using the `--quiet` flag? You could do this:
> 
> ```
> just -q some-command --some --flags
> ```

@casey But then all output is suppressed :) You run `just my-cli --help` and you get a blank screen.

**Comment by casey** [comment]
Ah, okay. I think the behavior of `--quiet` is ill considered. It seems to me like one `--quiet` should only suppress output from `just` and not from subcommands. But it's probably too late to change that, since there are probably people relying on the current behavior of `--quiet`.

I'd be open to a PR which added a flag, name TBD, like `--reticent`, which suppressed all additional output from `just` but left subcommand output alone.

**Comment by runeimp** [comment]
@casey where are you with the editions concept. Seems like updating `--quiet` behavior would be a great change to lock behind an edition. 😃

**Comment by casey** [comment]
@runeimp Ahh, yeah, good point. Instead of a flag, it could be a setting, and then in a later version we could default the setting to on.

**Comment by gokhanettin** [comment]
@casey Can you please have a look at #1354. I think a flag like `--reticent` is enough to suppress the extra exit code messages from `just` without affecting `--quiet` behavior. Making this a setting rather than a flag could require more work as we have no access to the settings within the `run` main entry point where these messages are printed to `stderr`. On the other hand, we could easily make `reticent` just another verbosity level.

What do you think?

**Comment by casey** [comment]
I'm fine with a flag too. @aldanor, would that work for your use-case? I'm also debating if the flag should also suppress recipe line echoing. The idea being that it suppresses all output from `just`, but not from the commands it runs. What do you think?

**Comment by aldanor** [comment]
I think line echoing is a completely different thing and a very useful one and should probably not be mixed up with this? (plus, there's the whole '@' thing)

While `--reticent` indeed seems to block extra exit code messages... because it's *not* a default, how does one integrate it into the justfile itself? I.e., if you don't ever want to see those exit codes in a certain justfile, how do you set that mode as a default? (In a certain recipe, or even better yet, all recipes at once). Saying you have to pass `--reticent` everytime you call just is not really cool, especially if you're sharing a justfile beyond your own use.

Wouldn't it make more sense to set reticent mode by default and have the next level of verbosity to output those exit error code messages? (e.g. non-reticent, or whatever that would be called)

**Comment by casey** [comment]
> I think line echoing is a completely different thing and a very useful one and should probably not be mixed up with this? (plus, there's the whole '@' thing)

I was thinking of the setting as "suppress extra output from just" as opposed to "suppress exit code messages from just".

> Wouldn't it make more sense to set reticent mode by default and have the next level of verbosity to output those exit error code messages? (e.g. non-reticent, or whatever that would be called)

`just` has a pretty large userbase that's used to, and might depend on, the current behavior, so I wouldn't want to change the default behavior. Also, I personally like the error messages.

Regarding setting vs flag, it sounds like @aldanor would like it to be a setting, but @gokhanettin implemented it as a flag.

I'm not personally sure if a setting makes sense. It seems like whether or not exit messages are printed is a personal preference, and I'm not sure it makes sense to encode it in the justfile itself.

**Comment by runeimp** [comment]
Setting via Environment Variable / `.env` maybe?

**Comment by aldanor** [comment]
While this can be implemented in many ways, leaving it to the user/flag/env to enable, I think it would be really great if it was doable within a justfile itself. It's kind of similar to suppressing command echoing within justfile itself: there are some cases where non-zero exit codes are not to be treated as recipe errors that need any extra treatment other than passing the return code itself back to the shell (eg., wrapping a CLI where even a help command may return an exit code of 2). In cases like this, we'd just want that disabled within the justfile for a particular recipe and *not* globally.

> I was thinking of the setting as "suppress extra output from just" as opposed to "suppress exit code messages from just".

Oh - so that `@` would suppress not only echoing commands to stdout, but also the exit code messages? (which would be great ofc and would partially solve the issue)

> It seems like whether or not exit messages are printed is a personal preference

I personally find it quite helpful and useful, except for some particular cases like outlined above. It's sort of the same as enabling/disabling echoing the command itself via `@`, why would it be a global setting if it usefulness (or annoyingness) depends primarily on which recipe you're currently running?

**Comment by runeimp** [comment]
Also, if we must stick with flags (fine by me), what I do when I need flags, etc. for a specific recipe is to put an underscore in front of that recipe, making it hidden/invisible, and recreate the recipe call including the flags to call the hidden recipe that does all the work.

```make
coolrecipe *args:
	just _coolrecipe {{args}} --long-flag-name-i-can-never-remember --nic-nacks

_coolrecipe *args:
	# Do the thing
```

**Comment by aldanor** [comment]
@runeimp I don't think your example is applicable in this particular case (which is exactly kind of the point here; and please correct me if I'm wrong), because as soon as your _coolrecipe returns a non-zero exit code (without printing anything if you used `--reticent` or the like, we'll grant it that), the parent coolrecipe will then also exit with that same exit code and hence you'll see the verbose exit code message right before the topmost just process terminates.

**Comment by gokhanettin** [comment]
It seems everybody has some use-cases with strong arguments. Instead of picking one, maybe we could implement all of them. For example,

- `--reticent` as an alternative to `--quiet`. It should suppress everything just itself produces, and thus output only messages from commands.
- Recipe and/or command level exit code message suppression. We already have `@` to suppress echoing and `-` to ignore non-zero exit codes and continue. Can we have one more character here to suppress exit code messages from just?Alternatively, a setting like `set suppress_both_echo_and_exit_code_messages`. When this is set,  `@` also suppresses exit code messages when the command fails.

**Comment by casey** [comment]
> --reticent as an alternative to --quiet. It should suppress everything just itself produces, and thus output only messages from commands.

Is this something you would use? I'm definitely open to adding it, I just want to make sure it meets a real need.

> Recipe and/or command level exit code message suppression. We already have @ to suppress echoing and - to ignore non-zero exit codes and continue. Can we have one more character here to suppress exit code messages from just?Alternatively, a setting like set suppress_both_echo_and_exit_code_messages. When this is set, @ also suppresses exit code messages when the command fails.

I'm a bit hesitant to add an additional symbol here. `@` and `-` are already a bit cryptic, but they have a precedent in `make`, and another symbol would be rather confusing.

It sounds like maybe a recipe annotation would be best for @aldanor's use-case, e.g.:

```
[reticent]
foo *args:
  foo {{args}}
```

or

```
[no-exit-message]
foo *args:
  foo {{args}}
```

**Comment by aldanor** [comment]
@casey `[no-exit-message]` would solve it, I think, at least partially.

Command annotation would probably be even nicer (although cryptic, but there's already `@`, `-` and `!`, so...) - because you can then do things like this (assume the prefix is `~`)

```make
~foo:
    abc

bar:
    abc
    ~xyz
```

-- whereas I'm guessing an attribute `[no-exit-message]` would always be recipe-wide?

> > --reticent as an alternative to --quiet. It should suppress everything just itself produces, and thus output only messages from commands.
> Is this something you would use? I'm definitely open to adding it, I just want to make sure it meets a real need.

I would probably use it quite often, but only if it was a command annotation, like a more powerful version of `@` (i.e. "please don't print ANYTHING extra but keep the exit codes intact"), or if that was how `@` itself behaved. Don't think I'd ever use it as a `just --reticent` though, because for some recipes printing exit codes makes sense whereas for some it doesn't.

So, just to sum up my personal subjective opinion re: exit code printing,

- CLI flag is not of much use (but it can still be added as long as it's also controllable within justfile itself via attributes or annotations).
- Recipe attribute is more useful.
- Command/recipe annotation like `@-!` gives the most flexibility.
- Could silencing error codes be integrated in `@`, perhaps? (I would guess not because it would be not backwards-compatible, but hypothetically it could be viewed as more consistent than the current behaviour)

**Comment by runeimp** [comment]
@aldanor it was just an example of handling a potentially large number of flags used often in a concise format.  😁

**Comment by casey** [comment]
I think the version that we should start with is the `[no-exit-message]` recipe annotation. It's a downside that it's recipe wide, but I don't know if there are any good options for a recipe line prefix. `~foo/bar` could be the `bar` script in the user `foo`'s home directory, so `~` is out.

This would be pretty easy to implement, if someone feels like taking a crack at it. Just got to parse an annotation, and set an option on the `Recipe` object its attached to.

**Comment by gokhanettin** [comment]
I can update my PR.

**Comment by gokhanettin** [comment]
I have some problems with annotations and doc comments. Consider the following cases:

```mk
[no-exit-message]
#This is a doc comment
recipe:
    @exit 1
```

```mk
[no-exit-message]
#Does above annotation still apply to the recipe
#if we have some more comment lines or possible empty lines?
 
#This is a doc comment
recipe:
    @exit 1
```

```mk
#Should this be a doc comment?
[no-exit-message]
recipe:
    @exit 1
```

```mk
#If previous case is yes, How about this?
[no-exit-message]

recipe:
    @exit 1
```

**Comment by aldanor** [comment]
> I think the version that we should start with is the `[no-exit-message]` recipe annotation. It's a downside that it's recipe wide, but I don't know if there are any good options for a recipe line prefix. `~foo/bar` could be the `bar` script in the user `foo`'s home directory, so `~` is out.
> 
> This would be pretty easy to implement, if someone feels like taking a crack at it. Just got to parse an annotation, and set an option on the `Recipe` object its attached to.

Would `^` be a valid one? :) (just wondering)

**Comment by aldanor** [comment]
@gokhanettin In the 3rd example, I'd say yes; in the fourth - no (because there's a separating newline). Basically, if you replace `[no-exit-message]\n` with an empty string, all existing rules should still hold?

**Comment by gokhanettin** [comment]
The first example works fine in my last commit in #1354. Still have problems with the second and the third if they are valid.

**Comment by casey** [comment]
@gokhanettin For now, we should make it as restrictive as possible: Loosening restrictions is backwards compatible, but tightening restrictions is not.

For now, I'd say we should only accept this form:

```
#Should this be a doc comment?
[no-exit-message]
recipe:
    @exit 1
```

If we want to accept more we can do so in a future PR.

**Comment by runeimp** [comment]
> Would ^ be a valid one? :) (just wondering)

@aldanor that could be problematic on Windows as `^` is the escape character for CMD, Command Prompt, etc. The escape character for PowerShell is `` ` ``. So depending on your OS/shell any single character can be problematic. But maybe something like `{{ no-exit-message() }}` could work as Just parses the double curly-braces before launching the shell. What do you think @casey?

**Comment by gokhanettin** [comment]
I have implemented

```mk
# Some doc comment
[no-exit-message]
some_recipe:
    exit 2
```

in the PR as suggested by @casey. It produces unknown annotation or unattached annotation errors if the annotation is invalid. Still need to update json tests as we have an additional field within the recipe struct.

I am open to implement every possible solution. Flag, annotation and what is next? :)

**Comment by casey** [comment]
The recipe-annotation version of this has been added in #1354, thanks to @gokhanettin! Try it out and let us know what you think.
