### ISSUE TITLE
Default recipe with arguments that take a URL give the wrong error

### ISSUE THREAD

**Issue by nk9** [casey/just#1351]
Create a Justfile with this as the first recipe:

```
fetch URL PATH="/tmp":
    curl --output-dir "{{PATH}}" -O {{URL}}
```

Then run this on the command line:

```
just https://apple.com/
```

This is a default recipe with an argument, so it errors:

```
error: I/O error reading directory /Users/nick/Projects/fetcher/https:/apple.com/: No such file or directory (os error 2)
```

Instead, @casey says we should get a different (and more helpful) error:

```
Recipe `fetch` cannot be used as default recipe since it requires at least 1 argument.
```

**Comment by casey** [comment]
Ah, okay, I was super confused in Discord but figured this out. When an argument contains a `/` or `.`, `just` will treat it as a directory that it should start the search for a `justfile` from. `https://apple.com/` contains a `/`, so `just` tries to find a justfile starting at `https://apple.com/`, but that isn't a directory, so there's an I/O error.

**Comment by casey** [comment]
This is confusing, but working as intended.

**Comment by runeimp** [comment]
That seems like odd behavior given that the default recipe has a required argument not satisfied by the call.

Also, couldn't Just be updated to recognize URIs. That could be useful in the future and would fix this issue unless the URI is something like `file:///path/to/resource` of course, which could still look for the path but might be better to just leave as a string argument so path arguments could be sent to recipes and not change the Just context.  😃
