### ISSUE TITLE
Jinja templating support

### ISSUE THREAD

**Issue by mihaigalos** [casey/just#1355]
## Overview

`just` currently has support for templating. Please make `just` support templating Jinja `.j2` files so that I don't need Jinja anymore. 

## Description

Unfortunately, every time I have a Jinja `.j2` file, I need the Jinja templating engine (`j2` package installed via `pip`) and pass it a key-value pair to generate the templated end-file. ([`example`](https://github.com/mihaigalos/config/blob/0550962f92aaebcc3227265ec55eeb2e75a2833b/services/wireguard/Justfile#L7-L15))

Ideally, since I am already using Just and it already has an internal templating engine, it would be awesome to use it and not rely on Jinja anymore.

What do you think?

**Comment by casey** [comment]
Just's template functionality is very wrapped up in the parser and lexer, so it would be a lot of work to extract it from `just`. It would be interesting if you could tell `just` that a recipe was to be treated as a template, and instead of executing it, it should just print the text to stdout. It would need some kind of annotation:

```
[template]
foo bar:
  This is a {{ bar }}!
```

```
$ just foo thing
This is a thing!
```

**Comment by mihaigalos** [comment]
Hi @casey,

It's a nice start. It would also need support for:
* exact 1:1 Jinja syntax.
* for loops: `{% for item in navigation %}`.
* if conditionals: `{% if item is True %}`.

Would you consider a separate crate for the templating engine perhaps?

**Comment by casey** [comment]
I think that would probably be too much work. Jinja has a ton of features, and it would probably be easier to just use Jinja itself if perfect syntax compatibility is a requirement.

**Comment by mihaigalos** [comment]
Ok, thanks for the clarification. I'm closing this now.
