### ISSUE TITLE
Absolute paths can't be constructed with leading `/`

### ISSUE THREAD

**Issue by nk9** [casey/just#1359]
[The documentation says this](https://just.systems/man/en/chapter_27.html?highlight=foo#variables-and-substitution):

> Absolute paths can also be constructed:
> 
> ```
> foo := / "b"
> ```
>
> ```
> $ just --evaluate foo
> /b
> ```

However, when I try this, I get an error:

```
$ just --evaluate foo
error: Expected backtick, identifier, '(', or string, but found '/'
   |
10 | foo     := / "b"
   |            ^
```

just 1.3.0

**Comment by casey** [comment]
Sorry for the confusion! This was added in 1.5.0. I just opened #1361, to note this in the readme.

**Comment by nk9** [comment]
D'oh! Should have checked I was on the latest version first. Thanks.

**Comment by casey** [comment]
No worries! This happens a lot. I should definitely start mentioning the versions in which features were introduced in the readme.
