### ISSUE TITLE
Bash script recipes cannot access positional parameters

### ISSUE THREAD

**Issue by DevinLeamy** [casey/just#1366]
I have a justfile recipe written in bash, similar to the following:
```justfile
myscript +args:
   if [ x = "option1" ]; then ...
   elif [ x = "option2" ]; then ...
```
I'd like to be able to pass in arguments to the script (flags, subcommands, etc.). 
```bash
just myscript option1
just myscript option2 --flag
```
Unfortunately, command line arguments are not passed as positional arguments into bash script recipes. 
```justfile
# does not work
myscript +args:
   echo $1
```

This problem can be avoided by manually converting the arguments into positional arguments as in:
```
# this works
myscript +args:
   set -- {{args}}
   echo "$1 $2"
```
```bash
# prints: option1 --flag
just myscript option1 --flag
```
However, I feel like this should be the default behavior.

I haven't investigated this issue when writing recipes in other languages, but I suspect this is faced in other places as well.

**Comment by runeimp** [comment]
Try `set positional-arguments := true` in your Justfile

**Comment by runeimp** [comment]
Also if you want the body of the recipe to be treated as a single script file you need to add a shebang at the top of the recipe body to trigger that behavior. Otherwise it's just line-by-line shell execution.

**Comment by DevinLeamy** [comment]
> Try `set positional-arguments := true` in your Justfile

Exactly what I'm looking for. Thanks
