### ISSUE TITLE
Add case-conversion functions

### ISSUE THREAD

**Issue by casey** [casey/just#1376]
Apropos of #1375, case-conversion functions might be useful. [heck](https://github.com/withoutboats/heck) is an extremely popular Rust library that implements case-conversions.

I'd be on-board with adding all the conversions it supports:

- UpperCamelCase
- lowerCamelCase
- snake_case
- kebab-case
- SHOUTY_SNAKE_CASE
- Title Case
- SHOUTY-KEBAB-CASE

Each should have a test and be added to the readme. The readme docs should have `<sup>master</sup>` next to each entry, to indicate that the function is on master and not in a released version of just yet. I'll change it to the version it winds up being released in.

**Comment by gVirtu** [comment]
Can I help with this one? :)

Also, speaking of cases, I'm assuming these functions will follow the same naming convention as `lowercase(s)` and `uppercase(s)`, is that right? (without underscores)
So `snakecase(s)`, `titlecase(s)`, `shoutykebabcase(s)`...

Thanks!

**Comment by casey** [comment]
Yup, absolutely! I haven't thought about it much, but I suppose they should be all one word, since `lowercase` and `uppercase` are all one word, and `lower_case` and `upper_case` feel pretty awkward.

**Comment by casey** [comment]
Closed by #1383!
