### ISSUE TITLE
Allow using variables in later variables that use command evaluation

### ISSUE THREAD

**Issue by ianpittwood** [casey/just#1388]
Hi, all! I have a use case where I want to reuse a variable defined earlier in my justfile inside of a later variable's backtick command evaluation like this:
```just
VERSION := "2022.10.28+523.25"
SAFE_VERSION := `echo {{VERSION}} | sed 's/+.*//g'`
```
Right now in this example, `SAFE_VERSION` sets to `{{VERSION}}` instead of `2022.10.28` as I would like it to. I'm on Ubuntu 22.04 just 1.1.2.

**Comment by casey** [comment]
Closing as a duplicate of #11. Check out #11! As you can see by the issue number, it's a longstanding request.

**Comment by ianpittwood** [comment]
Thanks @casey! I was trying to search for something like that, but I think I was too focused on the specific usage in command evaluation and not the broader picture.

**Comment by casey** [comment]
No worries! The issues are a bit messy to say the least!
