### ISSUE TITLE
error: No justfile found

### ISSUE THREAD

**Issue by PassLass** [casey/just#1392]
error: No justfile found

**Comment by casey** [comment]
It isn't possible to give advice or help given an error message with no context. What do you want do to? How are you trying to do that? Is there any other context that would be helpful?

**Comment by PassLass** [comment]
I try to: just setup, and console give me: no justfile found. When I try complete all command, console just give me: justfile not found

**Comment by PassLass** [comment]
![2022-10-29_08-28-53](https://user-images.githubusercontent.com/65995394/198815583-91b1fcce-5087-4941-aa37-6d4b3cc00f89.png)

**Comment by runeimp** [comment]
I believe you'll need to add that to your shell config file and restart your terminal for the shell to pickup those changes. `PATH` is often handled differently that other variables depending on the shell you're using.

**Comment by PassLass** [comment]
The thing is, **PATH** doesn't even help.

**Comment by PassLass** [comment]
I am working in WSL (Windows), and after restarting the PATH is reset, and the system simply does not see Just and its path

**Comment by runeimp** [comment]
It likely won't until to update the shell config and restart your terminal. Also did you create a `justfile`? The `just` command expects to find a justfile within the current directory or one of it's parent directories.

**Comment by PassLass** [comment]
How to create justfile?

**Comment by PassLass** [comment]
I've just never worked with Just

**Comment by PassLass** [comment]
I will be grateful for your help

**Comment by PassLass** [comment]
I think, i found a justfile.

**Comment by PassLass** [comment]
![2022-10-29_08-28-53](https://user-images.githubusercontent.com/65995394/198815945-19422e00-4ada-4bcd-af5b-aab964d4899a.png)
Now i have new problem:

**Comment by PassLass** [comment]
Now i have a new problem:
![2022-10-29_08-42-50](https://user-images.githubusercontent.com/65995394/198815962-f994d309-8e5f-476e-aab6-77608ff02896.png)

**Comment by PassLass** [comment]
The program swears that the username is something special?

**Comment by runeimp** [comment]
Here is a really short example. Create a file named `Justfile` or `justfile`

```just

@_default:
	just --list

# Hello, world!
hello arg='world':
	echo "Hello, {{arg}}!"

# Run an echo
run:
	echo "Running!"

```
Then execute just in the same directory that file is in.

**Comment by PassLass** [comment]
See my error, please

**Comment by runeimp** [comment]
I have no idea what that error is about. Unfortunately, I'm not the developer of `just` and also not a Rust developer. I recommend:

1. Create a new directory with no spaces in the name
2. Create the example justfile I noted about in that new directory
3. `cd` into that directory and run `just` all by itself

If that works then nothing is wrong with `just`. If you get crazy errors from that then post them so others who have more specific knowledge can help.  :-)

**Comment by PassLass** [comment]
Okay :)

**Comment by PassLass** [comment]
I'll try and give some answer

**Comment by PassLass** [comment]
Сейчас я попробовал запустить код. В итоге всё-таки же ошибка, которую я показывал выше:
![2022-10-29_08-42-50](https://user-images.githubusercontent.com/65995394/198817402-03765ca4-9cfc-4c9a-82e4-4de30f7e7fd0.png)

**Comment by PassLass** [comment]
@casey, help me please.

**Comment by casey** [comment]
Are you trying to use just, or are you trying to run the tests?

If you're trying to use just, run `just init` to create a justfile.

If you're trying to run the tests, I think you might have a variable NAME defined that's interfering with the tests. Try undefining NAME with.

**Comment by PassLass** [comment]
I simply can't use Just

**Comment by PassLass** [comment]
I can't use Just, let alone create files and program them.

**Comment by casey** [comment]
What are you trying to use just to? What are you trying to accomplish?

**Comment by PassLass** [comment]
Open Readme.md in this [page](https://github.com/Nukesor/ultimate-poll-bot), and see Installation and Starting. I am following all the points that are listed in Installation and Starting. Just doesnt work in this project.

**Comment by casey** [comment]
What does it print when you run `just --version`?

**Comment by PassLass** [comment]
just 1.7.0

**Comment by casey** [comment]
Okay, good. So have just installed and working.

What happens when you clone https://github.com/Nukesor/ultimate-poll-bot.git, cd into the directory, and run `just --list`?

```
git clone https://github.com/Nukesor/ultimate-poll-bot.git
cd ultimate-poll-bot
just --list
```

**Comment by PassLass** [comment]
anton@ubuntu:~/just$ just --list
Available recipes:
    build
    build-book
    check
    c                         # alias for `check`
    ci
    clippy                    # everyone's favorite animate paper clip
    done BRANCH=`git rev-parse --abbrev-ref HEAD` # clean up feature branch BRANCH
    filter PATTERN            # only run tests matching PATTERN
    fmt
    forbid
    fuzz
    generate-completions
    install                   # install just from crates.io
    install-dev-deps          # install development dependencies
    install-dev-deps-homebrew # install system development dependencies with homebrew
    man
    polyglot                  # run all polyglot recipes
    pr
    publish                   # publish current GitHub master branch
    push
    pwd                       # Print working directory, for demonstration purposes!
    quine                     # make a quine, compile it, and verify it
    render-readme
    replace FROM TO
    run
    sloc                      # count non-empty lines of code
    test
    t                         # alias for `test`
    test-completions
    test-quine
    update-changelog          # add git log messages to changelog
    update-contributors
    view-man
    watch +COMMAND='test'
    watch-readme

**Comment by PassLass** [comment]
Give a second

**Comment by PassLass** [comment]
anton@ubuntu:~/ultimate-poll-bot$ just --list
Available recipes:
    default
    format
    initdb *args
    lint
    migrate
    run
    setup
    test
    watch *args  # E.g. `just watch lint` or `just watch test`

**Comment by casey** [comment]
Great, looks like it's working.

The names it prints are the Just recipes in `justfile`.

So `just run`, `just format`, `just lint`, `just, test`, etc are all commands you can run to do some project specific task.

**Comment by casey** [comment]
For `just` to work, you have to `cd` into the directory that contains the `justfile`.

**Comment by PassLass** [comment]
Okay. I will check and write you

**Comment by PassLass** [comment]
![2022-10-29_12-00-17](https://user-images.githubusercontent.com/65995394/198823098-f59455ba-92b7-4dd7-a32c-dc5829d24efe.png)
I don't understand what the program requires of me. I reinstalled: Python 3.8, 3.9, 3.10, and there is no result.

**Comment by PassLass** [comment]
Guys, i restart system, and have this: 
![2022-10-29_12-03-54](https://user-images.githubusercontent.com/65995394/198823237-5a2a5ffb-a42e-40e3-a911-1fdffa45f5e6.png)
What the heck?

**Comment by PassLass** [comment]
It not good...

**Comment by casey** [comment]
I think your problems are either with your computer, or with ultimate-poll-bot. If you're having trouble running just recipes in ultimate poll bot, they're the ones that can help you.

**Comment by PassLass** [comment]
Okay, thanks! I check it and write you.

**Comment by PassLass** [comment]
Hello everyone again! Today I began to torment the question: how to replace Python from version 3.8 to version 3.10? The program requires a Python version of at least 3.10.

**Comment by PassLass** [comment]
I already have 3.8 and 3.10 installed together, but I need the system to use only 3.10.

**Comment by casey** [comment]
Sorry, but generic Python support is off-topic for this project.
