### ISSUE TITLE
Plans for a "proper" vscode extension?

### ISSUE THREAD

**Issue by macintacos** [casey/just#1395]
Hello! I would like to adopt `just` for some personal (and some work) projects, so I was taking a look at the recommended `just` VSCode extension linked in the README and realized the [the repository is read-only now](https://github.com/skellock/vscode-just), with the last commit being 5 years ago.

Any plans on adding a proper extension for VSCode?

**Comment by macintacos** [comment]
https://marketplace.visualstudio.com/items?itemName=sclu1034.justfile&ssr=false#overview this extension says that it is no longer under active development, but it seems like it has slightly more advanced TextMate grammars (not sure if "advanced" translates to "better" though):

- https://github.com/skellock/vscode-just/blob/master/syntaxes/just.tmLanguage.json
- vs. https://github.com/sclu1034/vscode-just/blob/master/syntaxes/just.tmLanguage.json

Since I really only care about accurate syntax highlighting, I'm going to try the other one and see if it's any better.

**Comment by macintacos** [comment]
I already kinda like the newer one, as it switches to proper completions/syntax for scripts that are embedded in recipes (as long as it matches a shebang). So I can get Python completions and such if I just add `#!/usr/bin/env python3`, which is kinda neat. I don't think the skellock one has that.

**Comment by casey** [comment]
The VS Code extensions aren't written and maintained by me, so it's not my call! Thanks for updating me on skellock/vscode-just's status. I changed the readme to also link to sclu1034/vscode-just.
