### ISSUE TITLE
Guidance for using an argument value in bash script substitution

### ISSUE THREAD

**Issue by macintacos** [casey/just#1397]
I'm having a little trouble escaping curly braces properly - it's a bit of an esoteric example (and I should probably just make it a script that I call from `just` directly), but for the sake of demonstration purposes, I would like to figure this out.

I have a recipe that takes a single argument, `type`, and I want to check to see if the argument passed in is in a bash array of strings and do something different depending on what is given. I think it would help to first show what the bash script would look like (that works fine):

```bash
#!/usr/bin/env bash
echo 'Checking to make sure release request is valid...'
valid_types=("patch" "minor" "major")
[[ ${valid_types[*]} =~ ${1:?} ]] &&
    echo "Release type accepted!" || echo "no!"
```

Running the script works as expected:

```
$ ./script.sh patch
Checking to make sure release request is valid...
Release type accepted!

$ ./script.sh lol
Checking to make sure release request is valid...
no!
```

I want to put this into a `just` recipe. So I'm trying the following, and I can't quite seem to get it to work:

```just
# Cut a release! Valid arguments: 'patch'/'minor'/'major'
release type:
    #!/usr/bin/env bash
    echo 'Checking to make sure release request is valid...'
    valid_types=("patch" "minor" "major")
    [[ ${valid_types[*]} =~ ${{{{{type}}:?} ]] &&
        echo "Release type accepted!" || echo "no!"
```

Running the recipe gives me an error:

```
$ just release blah
Checking to make sure release request is valid...
/var/folders/6w/3nlpd0_d6wv82xwsbg0jxpww0000gp/T/just0ftGRC/release: line 13: ${{{type}}:?}: bad substitution
error: Recipe `release` failed with exit code 1
```

I _think_ I'm escaping the initial `{` properly (by putting two `{{` before it), but it doesn't seem like that's working quite right. The README gives guidance on how to escape _two_ curly braces, but it doesn't give guidance for doing it for just one. Any guidance someone could provide me here?

**Comment by runeimp** [comment]
Oh, trying to stuff just references within Bash variables with a post-colon modifier?! You may not want to do that. Or at least my brain doesn't wan't to figure that out right now. There are a few options to consider before trying to escape the Bash variable name from the `just` variable recipe argument. Yes, it could work but "there lies madness" and I still need breakfast.  👼 

### Position Arguments Setting

```just
# Allows positional arguments to be accessed "normally" and supports $@ access as well
set positional-arguments := true

# Cut a release! Valid arguments: 'patch'/'minor'/'major'
release type:
    #!/usr/bin/env bash
    echo 'Checking to make sure release request is valid...'
    valid_types=("patch" "minor" "major")
    [[ ${valid_types[*]} =~ ${1:?} ]] &&
        echo "Release type accepted!" || echo "no!"
```

-or-

### Pass to Shell Variable

```just
# Cut a release! Valid arguments: 'patch'/'minor'/'major'
release type:
    #!/usr/bin/env bash
    echo 'Checking to make sure release request is valid...'
    input_type={{type}}
    valid_types=("patch" "minor" "major")
    [[ ${valid_types[*]} =~ ${input_type:?} ]] &&
        echo "Release type accepted!" || echo "no!"
```

There may be a few more options I'm not thinking of currently. But these are how I generally handle such situations. It's easy to read and grok even after the code has been entirely forgotten a week or two later.

**Comment by macintacos** [comment]
Jeez, didn't even thing about just using it like a normal positional argument to a script. That makes tons of sense. Thanks - I'll close this out in that case, I think it's a perfectly valid alternative to what craziness I was trying to do!
