### ISSUE TITLE
`just --list` does not evaluate default parameter expressions

### ISSUE THREAD

**Issue by epbuennig** [casey/just#1405]
I have a recipe for a project where I usually pass a some args and file to a recipe, and if I don't pass anything, I use `xplr` to choose a file.

It works as expected (using `just 1.8.0`) with this:
```
FILES := "path_to_files"

# the echo inside the file expression is where I had xplr
recipe +args=('$(xplr ' + FILES + ')'):
    echo {{args}}
```

However, I expected `just --list` to substitute the variable, but it doesn't.
Current behavior, no substitution nor evaluation of the expression:
```
$ just --list
Available recipes:
    recipe +args=('$(xplr ' + FILES + ')'):
```
Expected behavior, variable is substituted and expression is shown evaluated:
```
$ just --list
Available recipes:
    recipe +args='$(xplr path_to_files)':
```

I think expressions as parameter defaults should be evaluated when showing the recipes as it shows a better picture of what the default argument means.

EDIT:
On a similar note I'd also expect `just --show` to evaluate expressions, which it currently doesn't. Maybe it `--evaluate` could be used in conjunction with `--list` and `--show` to evaluate all expressions?

**Comment by casey** [comment]
Thank you for the issue! I definitely agree that it would be good from a documentation perspective. However, we would have to evaluate things like backticks and assignments, which might not be desirable when not executing recipes. I'm open to feedback on this but overall I'm leaning towards not doing this.

**Comment by epbuennig** [comment]
I think it would be fine if it is opt in? Like I suggested `--evaluate --list`/`--evaluate --show`, which currently can't be used together, could be used here. Do you have any concerns with that approach?

**Comment by casey** [comment]
Oh, sorry, I missed that! Yes, definitely, I think that's a great approach.

**Comment by epbuennig** [comment]
I'd love to tackle that, seems fairly straight forward and like a good first issue, I'd tackle the problem this weekend.

**Comment by epbuennig** [comment]
### I've done some reading and testing and have a few questions:

How much should we actually evaluate?
My initial guess was, as much as we can, but that seems like a bad idea.

Consider this example:
```
key := 'value'
recipe PARAM=key:
    echo {{ if PARAM == key { 'default: ' } else { 'arg: ' } }} {{ PARAM }}
```
How far can we evaluate `just --evaluate --show recipe`, I'd expect this as a user:
```
recipe PARAM='value':
    echo {{ if PARAM == 'value' { 'default: ' } else { 'arg: ' } }} {{ PARAM }}
```
Only `key` is known at this point, but what if we allow passing the recipes arguments? If yes, do we require them if they are required for the recipe?
Should `just --evaluate --show recipe arg` output this:
```
recipe PARAM='value':
    echo {{ if 'arg' == 'value' { 'default: ' } else { 'arg: ' } }} arg
```
or this:
```
recipe PARAM='value':
    echo 'arg: ' arg
```
Including arguments runs the risk of complicating both evaluation and the CLI.

So do we simply evaluate only values known at load time, i.e., no parameters?
Should `--dump` be considered for this change as well?

### Some issues I ran into while testing:

How do we pass an evaluator which needs to be mutable to the formatting functions currently used for displaying a recipe body?
Having to use a wrapper struct with a `RefCell` doesn't sound like a nice solution, but passing `Option<&mut Evaluator>` to these functions seems like breaking the abstraction of `ColorDisplay`.

When testing the evaluation, I used the former.

The evaluations seem to be nicely constrained to `run_recipe`, `Justfile::run` and friends, I wouldn't want to do the same thing they do in `Subcommand::{show,list}`, should everything that can be evaluated be a method on `Justfile` similar to `run`?

Because `evaluate` was previously a subcommand moving it from the subcommand arg group to be just an arg with a special meaning changes the usage message generated by clap, which is unfortunate.

I'll make a Draft PR tomorrow to show a few changes, and you can review it and tell me if I'm going in the right direction.

**Comment by casey** [comment]
I think it's best to just start with `just --list --evaluate`, and leave `just --show --evaluate` for a follow-up PR. `just --show --evaluate` seems much more complicated. For the other questions, can you open a draft PR that I can take a look at? It'll be easier to answer the other questions if I can take a look at the code. It doesn't need to work, or even compile.
