### ISSUE TITLE
How to use the methods?

### ISSUE THREAD

**Issue by PassLass** [casey/just#1406]
I have a file and to get the URL I have to execute function/method. How to use them and where?

![Screenshot from 2022-11-04 22-29-55](https://user-images.githubusercontent.com/65995394/200104171-11140066-61d8-411c-989e-9a57332d4977.png)

**Comment by PassLass** [comment]
@casey

**Comment by casey** [comment]
Sorry, but this question is not related to `just`. Please ask for help in an appropriate venue.
