### ISSUE TITLE
CC0 Issues

### ISSUE THREAD

**Issue by casey** [casey/just#1408]
The Fedora project has recently changed the classification of the CC0 license to `allowed-content` only, and will not accept CC0-licensed software going forward:

https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/

This is due to paragraph 4(a) of the CC0:

> No trademark or patent rights held by Affirmer are waived, abandoned,
> surrendered, licensed or otherwise affected by this document.

Such a clause may strengthen the case of a party that releases software under the CC0 that infringes a software patent that they hold, and attempts to sue those who use the software they release for patent infringement.

Software patents are deeply harmful to free and open-source software, and such a clause makes the CC0 less suitable for use with software.

I like the CC0 for the following reasons:

- Preamble which indicates the desire to do away with copyright for this work and contribute to a commons
- Thorough revocation of as many rights as possible
- Allows changing the license going forward without needing prior contributor approval

Because of this, I would like to release Just under a license which:

- Preserves the above qualities of the CC0
- Does not potentially create a vulnerability to patent lawsuits
- Is not problematic for inclusion in distros like Fedora

I created a [repo](https://github.com/casey/pd0) with a proposed license that is simply the CC0, but renamed to PD0, and without paragraph 4(a).

I am sensitive to the issue of license proliferation and the use of non-standard licenses, so this is not a proposal to use the PD0 at this time. I am creating this issue to document the situation and get feedback,

My ideal outcome is for Creative Commons to adopt and release PD0 as a Creative Commons license, after consulting with Fedora, and other members of the FOSS, to ensure that such a license alleviates their concerns around patents.

**Comment by casey** [comment]
@richardfontana Sorry for the unsolicited ping! I wonder what you think of the above summary, and what your advice is going forward. I'd like to make sure that Just remains easily available for use by Fedora users, and that I can continue using an instrument like the CC0.

**Comment by richardfontana** [comment]
@casey I looked at the [PD0](https://github.com/casey/pd0/blob/master/PD0.txt) quickly -- seems ok to me. Creative Commons mentioned possibly looking into a revision of CC0 later this year but ... now it is later this year and I haven't heard anything further about this.

**Comment by casey** [comment]
I haven't heard anything from Fedora, so I'm just going to ignore this until it becomes a problem, since maybe it never will be.
