### ISSUE TITLE
Feature Request: Unlisted aliases without a `_` prefix

### ISSUE THREAD

**Issue by JesseTG** [casey/just#1421]
I've been using `just` a lot lately. I have several commands that will let me deploy a game I'm working on to development hardware. So I have a recipe named `launch-sdk`.

But sometimes I don't remember if the recipe's name is `launch-sdk` or `sdk-launch`. There might be other synonyms I could've used as well; am I certain that I didn't name the recipe `run-sdk`, for instance?

And when I want to kill the process running on the SDK, I could use `kill-sdk`. Or maybe it was `sdk-kill`? `sdk-terminate`? `stop-sdk`?

That's what aliases are for, sure. But I have a *lot* of aliases, enough that they distract from actual recipes.

My proposed solution: The ability to specify that an alias should be unlisted without giving it an explicit `_` prefix.

**Comment by casey** [comment]
This seems reasonable to me.

We have recipe attributes, and it's always been planned that there would be a recipe attribute that would hide recipes without needing to change the name. This could also apply to aliases.

Something like this:

```
[private]
alias foo = bar

[private]
bar:
```

**Comment by casey** [comment]
I added the private attribute for recipes in #1422. Aliases are a slightly larger larger change, since the parser doesn't accept attributes on aliases yet.

**Comment by JesseTG** [comment]
Thanks, I'll be sure to give it a whirl! I'm fine with using private recipes instead of aliases for a little while.

Great work on `just` by the way, it's already made my life easier.

**Comment by neunenak** [comment]
https://github.com/casey/just/pull/1434 should make that `private` attribute applicable to aliases as well @casey @JesseTG

**Comment by rummik** [comment]
Seems like this issue is resolved?

**Comment by casey** [comment]
Yup, resolved. Thanks for commenting!
