### ISSUE TITLE
Child justfile does not inherit set windows-shell from parent just-file

### ISSUE THREAD

**Issue by hapatch** [casey/just#1424]
We have started using just for one of our new projects, and are loving it! 

For our setup:
We have a root folder with a just file,
Some sub folders contain their own just files to localise scripts to that folder/project
the root just file simply looks for just files in subdirectories, and executes just in those folders if the recipe exists
purely set up for the compartmentalisation of implementation and ownership

We would like to globalise the option for: 
set windows-shell := ["cmd.exe", "/C"]

Since we have developers on different OS's we currently need to have this option configured in every justfile, but we would love a nice way of configuring it globally

Currently doing this results with the sub-folder justfile throwing this error: 
`error: Recipe `generate` could not be run because just could not find the shell: program not found`

But if we include the configuration in all just files it eliminates the error

Being able to set the windows-shell option from an env variable so that it is globally accessible to justfiles would work!

Or similarly some type of global config could be set like git config?

**Comment by casey** [comment]
Would something like #1407 work? Would have any shared settings and recipes in a root justfile, and then you could do `include ../global.just` in your justfiles.

**Comment by hapatch** [comment]
Yeah that would be work well for our setup, 
I will close this issue and subscribe to the other one
