### ISSUE TITLE
New replace_regex function doesn't seem to work as expected

### ISSUE THREAD

**Issue by ngirard** [casey/just#1429]
Using latest precompiled binary on Ubuntu 22.04.

Invoking Just against 
```make
foo:
    echo {{ replace_regex('123bar123bar123bar', '\\d+bar', 'foo') }}
    echo {{ replace_regex('123bar123bar123bar', '(\\d+)bar', '$1:ok') }}
```

produces
```
echo 123bar123bar123bar  
123bar123bar123bar  
echo 123bar123bar123bar  
123bar123bar123bar
```

Also, neither the unit tests from the PR nor the documentation states whether capture groups are supported, without which the function would lose much of its interest to me.

In doubt, I tested in the 2nd line of the above recipe the conventional syntax (`$1..$n`) used by Ripgrep, Rargs and Sd, without success.

**Comment by casey** [comment]
I think you have an extra backslash, which isn't needed in single-quoted strings:

```
foo:
    echo {{ replace_regex('123bar123bar123bar', '\d+bar', 'foo') }}
    echo {{ replace_regex('123bar123bar123bar', '(\d+)bar', '$1:ok') }}
```

```
$ just foo
echo foofoofoo
foofoofoo
echo 123:ok123:ok123:ok
123:ok123:ok123:ok
```

**Comment by ngirard** [comment]
Ooh nice, thanks for your feedback and sorry for the noise !

Could you please consider mentioning that capture groups are supported in the README and providing an example ?

Cheers

**Comment by casey** [comment]
You bet, and no worries! I opened PR #1454 to link to the regex crate docs in the readme.
