### ISSUE TITLE
Proposal: provide a {{just}} macro for easier recursive invocations

### ISSUE THREAD

**Issue by ngirard** [casey/just#1430]
In practice, many of my justfile files evolve into a shell script, gaining a name of their own and a shebang line, such as

my_script:
```
#!/usr/bin/env bash

...
```

In order for recursive invocations to work both inside a `justfile` and inside a script as described above, the rules must include
```
just --justfile {{justfile()}}
```
which is why, for the sake of brevity, my files always contain
```
just:='just --justfile "'+justfile()+'"'
```
allowing me to express my recipes as
```
{{just}} <some_recipe> ...
```

I propose that this idiom be available all the time in the form of a `{{just}}` macro, which would be equivalent to `just_executable() --justfile "'+justfile()+'"`.

As an example, this code
```make
#!/usr/bin/env bash

do_a:
    echo "a"
    {{just}} do_b

do_b:
    echo "b"
```
would work equally well within a justfile invoked via `just`, or within a shell script.

This would also resolve my older proposal #1098.

**Comment by ngirard** [comment]
I created this issue at the end of my working day yesterday, I just updated it, I hope it is clearer now ;-)

**Comment by casey** [comment]
Not sure if it helps your use-case, but the example you gave could actually be rewritten using subsequent dependencies:

```
#!/usr/bin/env bash

do_a: && do_b
    echo "a"

do_b:
    echo "b"
```

I'm open to this, but my feeling is that there will be a long tail of gotchas, for example, passing the `--unstable` flag, and other flags that change behavior that you want in sub-invocations, so I'd rather find a way to support this without needing to invoke just recursively.
