### ISSUE TITLE
what is the formatting style for Justfile ?

### ISSUE THREAD

**Issue by pythops** [casey/just#1433]
Is there any defined formatting style for Justfile ? if yes is there any formatter to integrate with vim/neovim editor ?
Thanks

**Comment by casey** [comment]
There isn't currently any kind of style guide for just.

I tend to use two-space tabs, but any number of spaces can be used, or hard tabs, as long as they're consistent within a recipe.

No auto-formatting yet!

**Comment by alloc33** [comment]
I would create a grammar
