### ISSUE TITLE
How to get colored output when just is called by cargo-watch?

### ISSUE THREAD

**Issue by Boscop** [casey/just#1437]
I have this recipe:
```sh
set dotenv-load

watch:
	cargo watch -x build \
		-s "cp ../target/debug/foo.dll '$DATA_DIR/libs/'" \
		-s "just another-recipe"
```
But the output of `another-recipe` contains verbatim color codes which make the output unreadable in the terminal (Windows 10).
I added `--color=never` to the `just` invocation for now, but it would be preferable to get colored output, is it possible somehow?

**Comment by casey** [comment]
I'm not sure how the windows terminal works.
