### ISSUE TITLE
Correct way to escape quotes, to pass args that contain spaces to other commands

### ISSUE THREAD

**Issue by Boscop** [casey/just#1439]
I have this justfle:
```sh
set dotenv-load

INSTALL_PATH := "$DATA_DIR/foo bar.ext"

watch:
	cargo watch -x build -s "install.bat \"{{INSTALL_PATH}}\""
```
Note that `INSTALL_PATH` contains a space!
When I run it, I get this error:
```bat
> just
cargo watch -x build -s "build.bat \"$DATA_DIR/foo bar.ext\""
[Running 'cargo build && build.bat "C:\Users\me\AppData\Roaming\FooBar/foo bar.ext"']
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
bar.ext\"" was unexpected at this time.
```
How can I make it work? :)
I tried a bunch of different escapings, nothing seems to work..

**Comment by casey** [comment]
I'm not sure about this one. There are multiple levels of escaping, just, sh, and cargo watch, and you need evaluate the DATA_DIR variable, which makes it especially tricky.
