### ISSUE TITLE
Bash string manipulation

### ISSUE THREAD

**Issue by mabdelaal86** [casey/just#1441]
I wanted to do some string manipulation with bash in a recipe.

The following bash script is working with no issues in terminal:
```
LL="ABCDEFGH"; echo ${LL:3}
```
it prints "DEFGH"

When I tried it inside a just recipe as the following:
```
remove-3:
    LL="ABCDEFGH"; echo ${LL:3}
```

The command `just remove-3` failed the following outputs:

> **LL="ABCDEFGH"; echo ${LL:3}**
> sh: 1: Bad substitution
> **error**: Recipe `remove-3` failed on line 2 with exit code 2

**Comment by shamil** [comment]
The default shell is `sh`, try setting `bash` as default shell

```justfile
set shell := ["bash", "-uc"]

remove-3:
    LL="ABCDEFGH"; echo ${LL:3}
```

if you'd like to avoid changing default shell, then call `bash` directly in the recipe, like:

```justfile
remove-3:
    bash -uc 'LL="ABCDEFGH"; echo ${LL:3}'
```

**Comment by mabdelaal86** [comment]
Thanks a lot @shamil. That solves the problem.
