### ISSUE TITLE
Support for memory limited execution

### ISSUE THREAD

**Issue by kulkarniniraj** [casey/just#1483]
Hi,

Is it possible to a feature that would allow limiting maximum memory allowed for each recipe? It would allow usage as background pipeline monitoring tool.

**Comment by casey** [comment]
I think this would be tricky. Monitoring memory usage of processes is probably not easy to do in a cross platform way. I would suggest looking into [control groups](https://unix.stackexchange.com/questions/44985/limit-memory-usage-for-a-single-linux-process), which are the usual way to do this, at least on Linux.
