### ISSUE TITLE
Include prior/subsequent info on dependencies in JSON dump

### ISSUE THREAD

**Issue by nk9** [casey/just#1485]
Right now dependencies are listed in order, but there's no indication of which are [prior dependencies and which are subsequent](https://just.systems/man/en/chapter_38.html?highlight=dependency#running-recipes-at-the-end-of-a-recipe)

```just
b: a && d
  echo 'B start!'
```

becomes:

```js
{
  // …
  "dependencies": [
    {
      "arguments": [
      ],
      "recipe": "a"
    },
    {
      "arguments": [
      ],
      "recipe": "d"
    }
  ]
}
```

It seems like this should be as easy as adding a `subsequent` boolean to the dependency dictionary.

**Comment by casey** [comment]
I think this is actually already indicated, check out `recipe.priors`, which gives the number of prior dependencies. Any dependencies after that are subsequent, so you can do: 

```rust
let (prior, subsequent) = recipe.dependencies.split_at(recipe.priors);
```

**Comment by nk9** [comment]
Oh, indeed! Apologies, I missed that.
