### ISSUE TITLE
Only error on environment variables not being set when using a recipe that requires them

### ISSUE THREAD

**Issue by macintacos** [casey/just#1486]
Essentially what it says on the tin - I have some environment variables that need to be set for some specific instances, and I use the `env_var()` function to get them. However, `just` error's on them even when I'm calling a recipe that does not require that they be set. This isn't the worst thing in the world, but would be a decent quality of life improvement.

**Comment by casey** [comment]
I think this is covered by #953. This would make assignment evaluation lazy, so missing variables would only be a problem if you use them.
