### ISSUE TITLE
Cannot run 'just --init' on Termux (Android CLI)

### ISSUE THREAD

**Issue by lyderic** [casey/just#1492]
I installed Termux on my Android phone. I tried to initialise a _justfile_ by running 'just --init' on it. It doesn't work.

Log of my actions:

```
$ curl --proto '=https' --tlsv1.3 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
install: Repository:  https://github.com/casey/just
install: Crate:       just
install: Tag:         1.11.0
install: Target:      aarch64-unknown-linux-musl
install: Destination: /data/data/com.termux/files/home/bin
install: Archive:     https://github.com/casey/just/releases/download/1.11.0/just-1.11.0-aarch64-unknown-linux-musl.tar.gz
install: error: just already exists in /data/data/com.termux/files/home/bin

$ just -V
just 1.11.0

$ pwd
/data/data/com.termux/files/home
$ just --init
error: I/O error reading directory `/data/data`: Permission denied (os error 13)

$ ls -l /data/data
ls: cannot open directory '/data/data': Permission denied
```

Notes:

- The directory I run _just_ from (/data/data/com.termux/files/home) is definitely r/w'able
- Compiling _just_ myself with 'cargo install just' yields the same result.
- If I **manually** create a _justfile_ in /data/data/com.termux/files/home, then it works:

```
$ cat > justfile << EOF
> foo:
>   @echo foo
> EOF
$ just
foo
```

I don't understand why _just_ tries to read this _/data/data_ directory when initialising a new _justfile_...

Has anyone been able to successfully run _just --init_ on Termux?

Thanks,
L.

**Comment by casey** [comment]
I believe the issue is that `just --init` tries to look for an existing justfile, and refuses to create a new one if one already exists. If `/data/data` isn't readable, then that initial search will fail. It partially defeats the purpose, but you could do `just --init --justfile justfile`

Alternatively, a simple justfile is very simple, so you could also just do `echo default: > justfile`

**Comment by lyderic** [comment]
Thanks for the workaround. It's working well.

**Comment by casey** [comment]
Nice!

**Comment by casey** [comment]
vv happy that `just` is running on an android phone somewhere ^_^

Seems like it might be a pretty good use case, since you want to minimize the amount of typing you have to do.

**Comment by lyderic** [comment]
Definitely! I find myself typing things like 'j o' or 'j r' now :-) _just_ is a fantastic tool!

**Comment by TomJo2000** [comment]
Hi I'm currently reviewing the pull request just above (termux/termux-packages#19712).
Just wanted to pop in to ask if we should bother to patch `just --init` to stop at Termux's "effective root directory" (`/data/data/com.termux/files/usr`).

**Comment by casey** [comment]
@TomJo2000 If there's a simple and non-hacky way to detect whether we're running in Termux, and stop the search for a justfile when we hit the effective root directory, I wouldn't be opposed to it. It shouldn't just stop when it hits an error. Feel free to open an issue!

**Comment by TomJo2000** [comment]
> If there's a simple and non-hacky way to detect whether we're running in Termux, and stop the search for a justfile when we hit the effective root directory, I wouldn't be opposed to it. It shouldn't just stop when it hits an error. Feel free to open an issue!

We have a variable called `$PREFIX`, although that name is subject to change in the future, since we've run into collisions with it before and it's generally too generic, I think generally detecting Android, and limiting the search to the bounds of the App based on the app directory would be a more generic way to handle it.

So for example our `PREFIX` variable is `/data/data/com.termux/files/usr`, but it's probably fine to search up to `/data/data/{{application.name}}/`, that way it isn't specific to `com.termux`, or our specific directory layout.

I'll need to think about this some more as I'm not exactly sure how to best handle this.

**Comment by casey** [comment]
`PREFIX` is a bit too generic, but if it were `TERMUX_PREFIX`, then it would be totally reasonable to stop searching when just hits `TERMUX_PREFIX`.

**Comment by TomJo2000** [comment]
> `PREFIX` is a bit too generic, but if it were `TERMUX_PREFIX`, then it would be totally reasonable to stop searching when just hits `TERMUX_PREFIX`.

I think the current replacement candidate is `TERMUX__PREFIX`, but there isn't a timeline on that being changed.
So I think a generic "we're running on Android, let's stop at the app directory" approach might be better in this situation.

**Comment by casey** [comment]
Is there an easy way to get the app directory on android? Is `/data/data` always the location of the app directory? Are `/data` and `/` accessible, i.e., does `just` finish searching for a justfile successfully in those locations? Another option is to treat permission errors on `/data/data` on android as a special case.

**Comment by TomJo2000** [comment]
As far as I know everything outside of `/data/data/{{app.name}}` is read-only so can be ignored for our purposes here.
But I work on the packaging end of things, not app development, so I'm not 100% sure on that.
There definitely wouldn't be any just files expected outside of the app's directory though.

**Comment by Manamama** [comment]
Just quick FYI that runs out of the box almost in Termux now, see: https://github.com/Piebald-AI/gemini-desktop/discussions/22

**Comment by onedr0p** [comment]
@casey sorry for the ping but I can confirm `TERMUX__PREFIX` works for me on the latest version of Termux, maybe this can be used now?

```
❯ echo $TERMUX__PREFIX
/data/data/com.termux/files/usr
```

```
❯ which just
/data/data/com.termux/files/usr/bin/just
```

```
❯ echo $HOME
/data/data/com.termux/files/home
```

**Comment by casey** [comment]
@onedr0p It looks like `TERMUX__PREFIX` shows where Termux files are installed, but what just actually needs is the prefix which it should stop at when looking for a justfile.


Is that just `$TERMUX__PREFIX/../..`? i.e. `/data/data/com.termux`? Or is it `/data/data`?

**Comment by onedr0p** [comment]
I would say `/data/data/com.termux/files` so just `$TERMUX__PREFIX/..`

**Comment by casey** [comment]
I'm a little be hesitant to add a special case on `$TERMUX__PREFIX`. As a possible solution, I opened #2870, which adds a `--ceiling` flag which allows you to pass a directory above which just shouldn't ascend when looking for a justfile to run, or when looking for a project root in which to initialize a justfile. You can also pass it as an environment variable, `JUST_CEILING`, so you can set it in a config file.

Does that work? On termux, you could set it to `/data/data/com.termux/files`, or whatever is appropriate.

**Comment by onedr0p** [comment]
I'd be happy with `JUST_CEILING`, that makes perfect sense!

**Comment by casey** [comment]
Merged in #2870!

**Comment by onedr0p** [comment]
Looking forward to using it, thanks 🤩

**Comment by TomJo2000** [comment]
Hi I just saw that this thread had picked up again when checking my notifications, thanks for adding an option for this, that should help us out a lot over on Termux.

Is there a way for us to easily compile in a default "ceiling"?

**Comment by casey** [comment]
@TomJo2000 It isn't currently possible to compile in a default ceiling. Is it possible to set the `JUST_CEILING` environment variable when `just` is installed?

**Comment by TomJo2000** [comment]
> @TomJo2000 It isn't currently possible to compile in a default ceiling. Is it possible to set the `JUST_CEILING` environment variable when `just` is installed?

We could throw the `just` binary into `libexec` and make the `just` executable in `bin` a wrapper script.
Would definitely work, but it's a bit of a hacky solution.

**Comment by TomJo2000** [comment]
> You can also pass it as an environment variable, `JUST_CEILING`, so you can set it in a config file.

I just noticed this comment.
I'm not sure how exactly that would work.
Does `just` have a global config file or did you mean adding to `just`'s environment via the `~/.bashrc` or similar means.

> Does that work? On termux, you could set it to `/data/data/com.termux/files`, or whatever is appropriate.

The appropriate pattern to look for would be `/data/data/{{app name}}/` as the ceiling I believe.
I'd suggest avoiding any hardcoded reference to Termux or `com.termux` as the app name since that would need to be modified by Termux forks or unrelated versions of Just for Android.

**Comment by casey** [comment]
Sometimes an OS will provide system-wide environment variables in `/etc/bash.bashrc`, so something like that. Although that's certainly not ideal. `just` does not have a global config file, although there is an issue for it in #395. I wouldn't want to change the behavior based on the name of the current directory, i.e., whether it starts with `/data/data`, I find those sorts of implicit behavior changes to be somewhat confusing.

**Comment by TomJo2000** [comment]
We'll just ship a wrapper script then.
Thanks for the help.
