### ISSUE TITLE
Pass `--check` output to `stdout`

### ISSUE THREAD

**Issue by nk9** [casey/just#1494]
If you want to see what `--fmt` would do to your justfile, you can run `--fmt --check` on it. If `--fmt` would make changes, the return code is set to `1` and `just` prints a unified diff of the file. But the diff output is sent to `stderr`. This doesn't make a lot of sense, since this content is not an error. Instead, the diff output should go to `stdout`. The trailing `error:` line can still go to `stderr`, though.

**Comment by casey** [comment]
Done in #1506!
