### ISSUE TITLE
Need way to suppress "Trying ../justfile" output when fallback occurs

### ISSUE THREAD

**Issue by jeffrey-aguilera** [casey/just#1509]
Ideally, this output would be suppressed unless the --verbose flag is given, as it is only useful for debugging.

**Comment by casey** [comment]
I think that's reasonable. Now that it requires a setting, the user probably doesn't need to be notified that fallback is occurring.

**Comment by casey** [comment]
Fixed in #1510!

**Comment by jeffrey-aguilera** [comment]
Wow! You're fast. Thanks for the fix.
