### ISSUE TITLE
When piped using `|` `just --list` should output targets in a list omiting the `Available recipes:` text

### ISSUE THREAD

**Issue by axkirillov** [casey/just#1514]
To make parsing and piping simpler, just should detect wether it is printing to standard output or being piped.

**Comment by casey** [comment]
Can you use the output of `just --summary` instead? `just --summary` prints out a space-separated list of recipe names, which should be more amenable to piping.

**Comment by jeffrey-aguilera** [comment]
You could also use `--list-heading ''`.

**Comment by axkirillov** [comment]
Thank you for the prompt reply and for the awesome tool. I tried the --summary option and it requires the same amount of  manipulation to make the output usable, since I gotta replace space with "\n"
`just --summary | tr " " "\n"`
However I am not implying that you should tailor to my use case. Perhaps a space separated list is generic enough 🙂

**Comment by casey** [comment]
I'm a little hesitant to do things based on whether or not we're connected to a pipe or not, just because it can be a bit confusing and hard to discover. You could do `--list-heading ''` as @jeffrey-aguilera suggested, which suppresses the list heading.

**Comment by casey** [comment]
> Thank you for the prompt reply and for the awesome tool.

And you bet!
