### ISSUE TITLE
Calling another recipe from an initial recipe for Python

### ISSUE THREAD

**Issue by mihaigalos** [casey/just#1515]
[This](https://github.com/casey/just#running-recipes-in-the-middle-of-a-recipe) suggests one can `just run` something from another recipe.
That is however tightly coupled to the shell interpreter. How would one go about in the following scenario?

```just
set shell := ["python3", "-c"]

foo:
  print("Hello")
  just bar

bar:
  print("World!")
```
Output:
```bash
$ just foo
print("Hello")
Hello
just bar
  File "<string>", line 1
    just bar
    ^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
error: Recipe `foo` failed on line 5 with exit code 1
```

**Comment by mihaigalos** [comment]
A potential implementation could be:

Variant 1:
```just
set shell := ["python3", "-c"]

foo:
  #!/usr/bin/python3
  import subprocess
  print("Hello")
  exit(subprocess.run("just bar", shell=True).returncode)

@bar:
  print("World")
```

Variant 2:
```just
set shell := ["python3", "-c"]

call_start := "import subprocess; exit(subprocess.run('"
call_end := "', shell=True).returncode)"

@foo: 
  print("Hello")
  {{call_start}} just bar {{call_end}}

@bar:
  print("World")

```

Any better way to do this without explicit `exit()`,`subprocess()` calls and without the python3 shebang?

**Comment by casey** [comment]
I think variant 1 is about as good as it gets. Python is just inherently more verbose than shell.
