### ISSUE TITLE
just could not find the shell: program not found

### ISSUE THREAD

**Issue by 2-5** [casey/just#1517]
`just-1.11.0` stopped working on my Windows 10 machine, but nothing in my just/shell/terminal config changed as far as I'm aware.

```makefile
hello:
  echo 'This is a recipe!'
```

Running `just` fails:

```shell
Microsoft Windows [Version 10.0.19045.2486]
(c) Microsoft Corporation. All rights reserved.

H:\Work\issue\just>just --dump
hello:
    echo 'This is a recipe!'

H:\Work\issue\just>just hello
echo 'This is a recipe!'
error: Recipe `hello` could not be run because just could not find the shell: program not found

H:\Work\issue\just>
```

**Comment by 2-5** [comment]
It was because of the emergency git update from yesterday.

**Comment by TreehouseFalcon** [comment]
Ran into this issue and solved it by adding the `bin` folder containing `sh.exe` from Git to my system's path.
`C:\Program Files\Git\bin`

**Comment by LY1806620741** [comment]
I encountered the same problem in my `windows 11 professional`. And I think this solution is too unfriendly...

**Comment by LY1806620741** [comment]
I think `just` can use `where.exe git` get git bin path like `C:\Program Files\Git\cmd\git.exe`,then search `sh` in `C:\Program Files\Git\bin`. Any one support It? Can I add the feature to source code?

**Comment by LY1806620741** [comment]
You can also add `set windows-shell := ["C:\\Program Files\\Git\\bin\\sh.exe","-c"]` to your `justfile`

**Comment by nozwock** [comment]
It wasn't obvious to me that it's complaining that it couldn't find `sh`, because for some reason I was thinking pwsh (on windows) is the default and that it doesn't make sense that it couldn't find it.

Please mention which program wasn't found instead of just `program not found.`

**Comment by casey** [comment]
I just added the name of the shell to the error message in #3208.
