### ISSUE TITLE
Github release for 1.12.0

### ISSUE THREAD

**Issue by wydengyre** [casey/just#1518]
It would be really nice to have a corresponding GitHub release for this git tag, making the corresponding binaries available for download.

**Comment by casey** [comment]
Thanks for catching this! The GitHub actions release job failed, so a release was never created and binaries were never uploaded. Just restarted the jobs, so binaries should be up soon.

**Comment by casey** [comment]
Binaries are up! https://github.com/casey/just/releases/tag/1.12.0
