### ISSUE TITLE
cannot pass . as an argument from one justfile to another

### ISSUE THREAD

**Issue by jeffrey-aguilera** [casey/just#1519]
Create a justfile:
```
say ARG:
	echo {{ARG}}
```
In child/ directory, create another justfile:
```
say ARG:
	just ../say {{ARG}}
```
If you execute `just say .` from the parent directory, everything is OK; but from the child directory, you get:
```
$ just say .
just ../say .
error: Recipe `say` got 0 arguments but takes 1
usage:
    just say ARG
error: Recipe `say` failed on line 2 with exit code 1
```

**Comment by casey** [comment]
Fixed and added a test so it doesn't break in the future. Thank you for reporting!
