### ISSUE TITLE
ubuntu install fails

### ISSUE THREAD

**Issue by dcsan** [casey/just#1521]
tried both methods listed but doesn't work:
https://github.com/casey/just#packages

```
$ makedeb -si
Command 'makedeb' not found, did you mean:
  command 'makedb' from deb libnss-db (2.2.3pre1-6ubuntu3)
Try: apt install <deb name>

$ sudo apt install makedeb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package makedeb
```

pls don't close without comment like https://github.com/casey/just/issues/1391
as ubuntu and debian are pretty popular. 
if we can't install just on the server, then I don't want to make local recipes on a mac.

**Comment by dcsan** [comment]
```
curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
sudo apt update
```
THEN

`sudo apt install just`

seems to work

**Comment by casey** [comment]
The documentation seems pretty clear:

> You must have the [Prebuilt-MPR set up](https://docs.makedeb.org/prebuilt-mpr/getting-started/#setting-up-the-repository) on your system in order to run this command

Let me know if it can be improved.

**Comment by Bryce-Colton** [comment]
I had the same issue, and thankfully, this topic pointed me in the right direction. 

What's unclear, though, is that for Debian/Ubuntu and derivatives, there are two ways to proceed. 
I think the procedure for the 'pre-built MBR' deserves a dedicated paragraph for versions where the apt command alone isn't sufficient. 

It might sound a bit crazy, but I believe a good number of developers aren’t familiar with Linux ecosystems (myself included).
