### ISSUE TITLE
just --list should display first line of multi-line comment

### ISSUE THREAD

**Issue by jeffrey-aguilera** [casey/just#1526]
```
#!/usr/bin/env just --justfile

# example of a multiline comment where just --list picks the last line.

# Brief description.
#
# More detailed description.
# Possibly spanning multiple lines
@example:
  just --list
```
Expect: `just example` prints `Brief description`

Actual: `just example` prints `Possibly spanning multiple lines`

**Comment by casey** [comment]
Dupe of #1337. Definitely an annoying limitation, and hard to fix without breaking existing justfiles, although it can be fixed in an edition.
