### ISSUE TITLE
Add to macports

### ISSUE THREAD

**Issue by casey** [casey/just#153]
Macports is easy, since I'm already the maintainer of the just package. I'm not sure if just meets the notability clause to be accepted to homebrew.

Edit: @Ezku added just to homebrew

**Comment by casey** [comment]
If anyone wants to help with the homebrew port, I would be most grateful!

**Comment by Ezku** [comment]
Hey @casey, here's my attempt: https://github.com/Homebrew/homebrew-core/pull/19320 I have no familiarity with either brew formulas, rust or cargo so far, so if something seems wrong any and all pointers are appreciated.

**Comment by casey** [comment]
So awesome!

A good test might be to create a simple justfile in a tempfile, and then make sure it does the right thing. For example:

```
default:
  touch it-worked
```

And then assert that the file `it-worked` exists. For an example of creating a temp file, check out the ripgrep formula:

https://github.com/Homebrew/homebrew-core/blob/ed324bc0e2edb502cc6bff074cff440057a44eae/Formula/ripgrep.rb

**Comment by casey** [comment]
I just published 0.3.3 to crates.io, but nothing functional changed, so it probably isn't worth updating the homebrew diff.

I just added a short readme that will be displayed at https://crates.io/crates/just, so no code changes whatsover.

**Comment by Ezku** [comment]
Thanks for the pointer on testing, that's now in the PR.

**Comment by Ezku** [comment]
The PR was merged, so `brew install just` should now work :)

**Comment by casey** [comment]
Great news! Thank you so much for getting it included! I'll update the readme with instructions for how to get it from homebrew.
