### ISSUE TITLE
Dependency in other directory

### ISSUE THREAD

**Issue by leviska** [casey/just#1535]
Imagine we have two justfiles:
```
foo
├── justfile # contains foo recipe
├── bar
│   ├── justfile # contains bar recipe
```
Right now we can do `just foo &&  just bar/bar`
But I couldn't find a way to make a recipe inside `foo` justfile, which will depend on `bar`, i.e.
```
# foo/justfile
foo:
  echo "foo"

foobar: foo bar/bar

# foo/bar/justfile
bar:
  echo "bar"
```
I think it's something that could be supported

**Comment by leviska** [comment]
Although it can be done just by manually calling just from the target
```
foobar:
  just foo
  just bar/bar
```

**Comment by neunenak** [comment]
The relatively-new [include directives](https://just.systems/man/en/chapter_52.html) feature will let you include the contents of one justfile within another one. So in this case you could have:

```
#foo/justfile 

!include bar/justfile

foo: bar
    echo "foo"

```

and

```
# foo/bar/justfile

bar:
    echo "bar"

```

And invoke `just --unstable foo` on the top-level justfile to get the behavior you want.
