### ISSUE TITLE
Running Firestore Emulator From Just Prevents Control C

### ISSUE THREAD

**Issue by LLBlumire** [casey/just#1558]
I have the following in a Justfile.

```
start:
    gcloud emulators firestore start
```

If I run the command on it's own, I am able to CTRL+C to stop the emulator. If I run the command through just with `just start`, CTRL+C does nothing.

---

For a reproducible example of this here's a `shell.nix` which will set up an environment that demonstrates this.

```
{ pkgs ? import <nixpkgs> {} }:
let
    gcloud = pkgs.google-cloud-sdk.withExtraComponents([
        pkgs.google-cloud-sdk.components.cloud-firestore-emulator
    ]);
    shell = pkgs.mkShell {
        buildInputs = [
            pkgs.just
            pkgs.jdk11
            gcloud
        ];
    };
in
shell
```

If you run

```
nix-shell --pure
gcloud emulators firestore start
<C-c>
just start
<C-c>
```

You'll see the first control C does stop the program, but the second one does nothing (and the only way to exit is to start a new terminal and kill the java process).

Hopefully the nix environment is enough to reproduce the error (that's the whole point of nix after all)!

**Comment by LLBlumire** [comment]
On further experimentation, I believe this may be connected to the fact that just doesn't forward SIGTERM into it's child processes. I'm uncertain however

**Comment by runeimp** [comment]
Checkout issue #302

**Comment by LLBlumire** [comment]
Is there any configuration required to enable that feature? As it does not appear the signal is being forwarded?

**Comment by runeimp** [comment]
To my knowledge that feature was never added. Sorry, I thought that was obvious from the other discussion. Maybe not as cut-and-dry as I thought though.

**Comment by LLBlumire** [comment]
The issue was closed as completed and it looked to me as https://github.com/casey/just/pull/345 provided this functionality somehow? I may have misunderstood! So there is no way to have signals be forwarded to the program Just is running? and there's no scope planned for this to be implemented?

**Comment by runeimp** [comment]
Ah, you're right. Looks like that was my mistake. Not sure how to activate it or anything. @casey ?

**Comment by casey** [comment]
Closing in favor of #2473, where I've tried to collect everything related to signal handling in one place. Take a look and see if I've missed anything! A reproduction of this which doesn't depend on `gcloud` would be much appreciated.
