### ISSUE TITLE
Request: snap package for arm64

### ISSUE THREAD

**Issue by heygarrett** [casey/just#1569]
When I run `snap install --edge --classic just` on Ubuntu 22.04.2 I get:

> error: snap "just" is not available on edge for this architecture (arm64) but
       exists on other architectures (amd64).

**Comment by casey** [comment]
`just` is now packaged for Ubuntu, and the `snap` package is quite out of date, so I think the preferred method for installing `just` should be with `apt`, which should work for any architecture.
