### ISSUE TITLE
How can we disambiguate recipe names from recipe arguments on the commandline?

### ISSUE THREAD

**Issue by KevinMGranger** [casey/just#1572]
Consider the following justfile:

```just
rule-with-arg arg="default":
    @echo "argument is {{arg}}"

arg:
    @echo "this is the arg target"
```

and the following invocations:

```console
$ just arg rule-with-arg
this is the arg target
argument is default
$ just rule-with-arg arg
argument is arg
```

Is there any way to disambiguate in the latter case? I would think something like `arg=arg_value` could work, but that's already reserved for setting variables.

**Comment by KevinMGranger** [comment]
This is still an issue as of 1.15. The issue isn't passing arguments to targets within the justfile itself, it's disambiguating on the cli.

**Comment by laniakea64** [comment]
related to https://github.com/casey/just/issues/1556 ?

**Comment by casey** [comment]
Sorry, I should have commented when closing, this is a dupe of #1556.
