### ISSUE TITLE
The `just-install` package regularly fails in CI

### ISSUE THREAD

**Issue by TimDiekmann** [casey/just#1573]
Hi and first of all thanks for `just`, it's an amazing tool!

We currently have an issue in our CI as we have added `just-install` as dev-dependency, so not everyone needs to deal with installing `just` locally by hand. However, `just-install` just uses `install.sh` without specifying `--tag`, so GitHub most probably rate-limiting the request so it results in a `403` error when attempting to run `yarn install`. Is there a way to handle this? Or any suggestion how to avoid this at all?

One option could be to check if the `CI` variable is set and `just` is already installed (as it was installed manually). If so the install action could just exit.

Related:
- https://github.com/casey/just/issues/1488
- https://github.com/casey/just/pull/1499

**Comment by casey** [comment]
Glad you like just!

`just-install` is actually maintained by someone else, although I forget who at the moment 😅
