### ISSUE TITLE
specify shell on the fly doesn't work.

### ISSUE THREAD

**Issue by thisismygitrepo** [casey/just#1579]
as per README, I'm specifying the shell on the fly, but I'm getting this error:

```
error: Justfile does not contain recipes `--shell`, `pwsh.exe`, `--shell-arg`, or `-c`.
```

my cmd: `just bapi --shell pwsh.exe --shell-arg -c`

**Comment by thisismygitrepo** [comment]
it worked, I just had to push recipe to come after the optional arguments. But still, it should work either way.

**Comment by runeimp** [comment]
It would be next to impossible to allow both ways. What if a recipe that is called can accept options that have meaning to Just? If you allowed both how would you specify that the option that was written after a recipe was actually for Just and not the recipe?

**Comment by thisismygitrepo** [comment]
You're right, that would be confusing. I think it customarily handled with `--` to indicate that whatever comes next is arguments for the command called.

**Comment by runeimp** [comment]
Yes, but many (most ?) people forget about `--`. It is also a UNIX standard to put all options for a command after the command and before all other arguments. Depending on the command there is no possible consequence to putting options anywhere on the command line. But that is only true for a relatively small subset of all common commands on a system. Allowing this but requiring `--` to avoid issues is error prone and can fail without explanation depending on the contents of the target recipe or possibly sup recipe calls. Where as it stands currently it just fails immediately and is easy to recognize and recover from.
