### ISSUE TITLE
Support a leading dash like GNU Make

### ISSUE THREAD

**Issue by casey** [casey/just#159]
Currently, if any line in recipe returns a nonzero exit code, the recipe fails. GNU Make allows a leading `-` to signify that the line may fail, like so:

```make
foo:
  -rm bar
```

This would be nice to support.

**Comment by casey** [comment]
Also should make sure nothing wierd happens when there are multiple dashes and different orderings of `@` and `-`

**Comment by nathanielknight** [comment]
I'm not sure this is a good change. I remember finding Make's use of arbitrary symbols very confusing when I was learning it, and this kind of syntax is really hard to search for.

I would expect that a lot of use cases for this feature could be served by modifying the command (e.g. changing `rm bar` to `rm -f bar`). I think that's easier to figure out?

**Comment by casey** [comment]
I think that's a good point. Some commands can't be modified, but you can always do `foo || true`, which will cause the recipe to return the exit code from `true` if `foo` fails.

**Comment by casey** [comment]
I think I'm going to close this. The 👍s don't lie!
