### ISSUE TITLE
bug: Variadic recipe parameters remove all passed quotes

### ISSUE THREAD

**Issue by nachtjasmin** [casey/just#1601]
## Description

Consider the following `justfile`:

```justfile
# copies files.
deploy_target := "<some target folder>"
deploy *OPTIONS:
    rsync {{ OPTIONS }} --delete --delete-after --progress --archive public/ {{ deploy_target }}
```

If we want to pass custom arguments to rsync, we can do something like:

```shell
$ just deploy --backup
```

## Problem
However, if we pass arguments with quotes, like this:

```shell
$ just deploy -e "ssh -o StrictHostKeyChecking=accept-new -i .ssh/id_rsa"
```

Then the quotes gets removed, resulting in the following execution:

```
$ rsync -e ssh -o StrictHostKeyChecking=accept-new -i .ssh/id_rsa --delete --delete-after --progress --archive public/ {{ deploy_target }}
```

**This is not the expected behaviour.** And I haven't found a way to pass the correct arguments. 

1. Quoting the whole `OPTIONS` would be wrong as well.
2. Using single quotes doesn't change the behaviour.

## Expected behaviour

```
$ rsync -e "ssh -o StrictHostKeyChecking=accept-new -i .ssh/id_rsa" --delete --delete-after --progress --archive public/ {{ deploy_target }}
```

## Possible solution

Since we could pass every argument quoted (`rsync --version` is equal to `rsync "--version"`), there should be an option to enable this behaviour. 

```shell
$ just deploy -e "ssh -o StrictHostKeyChecking=accept-new -i .ssh/id_rsa"
```

Would then result in:

```shell
rsync "-e" "ssh -o StrictHostKeyChecking=accept-new -i .ssh/id_rsa" --delete --delete-after --progress --archive public/ {{ deploy_target }}
```

`quoted-variadic-arguments` is just a suggestion for this option, but this is how a `justfile` could look like:

```justfile
set quoted-variadic-arguments

deploy_target := "<some target folder>"
deploy *OPTIONS:
    rsync {{ OPTIONS }} --delete --delete-after --progress --archive public/ {{ deploy_target }}
```

**Comment by runeimp** [comment]
This is a long standing issue. But there is a way to fix it. Check out [Avoiding Argument Splitting - Just Programmer's Manual](https://just.systems/man/en/chapter_57.html)

**Comment by nachtjasmin** [comment]
As I already said:

> 1. Quoting the whole `OPTIONS` would be wrong as well.

It's not a suitable option for variadic parameters, if some of them should be quoted and some not. Right now, it's an all-or-nothing solution. Positional arguments would not help here, because we don't know beforehand which arguments are quoted and which are not.

But if I understand the manual, there's no way of detecting whether an argument was passed with quotes or not. But because we could pass every single argument as quoted (instead of all arguments in one single string), an option to quote every variadic parameter would be a nice workaround. Updated the issue with it.

**Comment by runeimp** [comment]
Oh, the page I linked to should have included... In all POSIX and most POSIX-like shells (Bash, Korn, Z shell, etc.) `"$@"` will expand to individually quoted arguments similar to how you would manually use the numbered references with quotes (`"$1"`, `"$2"`, etc.). This does not work for the built-in Windows shells thought.

Are you working on a POSIX type system (BSD, Linux, macOS, etc.), Windows, or other?

**Comment by nachtjasmin** [comment]
> "$@" will expand to individually quoted arguments

oh. TIL. Well then, the following justfile works as expected:

```justfile
set positional-arguments

deploy_target := "<some target folder>"
deploy *OPTIONS:
    rsync "$@" --delete --delete-after --progress --archive public/ {{ deploy_target }}
```

Closing this issue, thanks again for your help!

**Comment by mickdekkers** [comment]
In my case, I needed to pass the variadic arguments to a CLI app run through [`cargo watch`](https://github.com/watchexec/cargo-watch). If you want to pass additional arguments to the `cargo run` command when using `cargo watch`, you need to _quote the entire `-x` argument_ like so:
```sh
cargo watch -x "run --bin some-binary"
# equivalent to
cargo run --bin some-binary
```

The same applies if you want `cargo run` to pass additional arguments to the binary itself:
```sh
cargo watch -x "run -- foo bar"
# equivalent to
cargo run -- foo bar
```

This is problematic with Just's variadic arguments, because just inserting `$@` in the `-x` string strips the quotes from the arguments.

## Solution

After some trial and error, the solution that ended up working for me was using a bash script to loop over the individual arguments and using `printf "%q"` to escape any problematic characters:

```just
set positional-arguments

watch *args:
    #!/usr/bin/env bash
    set -euo pipefail
    escaped_args=()
    for arg in "$@"
    do
        escaped_args+=("$(printf "%q" "$arg")")
    done
    cargo watch -x "run -- ${escaped_args[*]}"
```

When you then run:

```sh
just watch "string with spaces" foo bar
```

What ends up being executed by `cargo watch` is:

```sh
cargo run -- string\ with\ spaces foo bar
```

Hope this is useful to someone else! 😄
