### ISSUE TITLE
dotenv-load should fallback to environment variables when .env (or key inside it) is not found.

### ISSUE THREAD

**Issue by mrpandey** [casey/just#1602]
I have something like this in my justfile.

```
set dotenv-load

DB_URI := "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB"

DB_URI_PARAMS := "?sslmode=disable"

some-cmd:
	some-cmd --db "{{DB_URI}}{{DB_URI_PARAMS}}"
```

And my `.env` looks like

```
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=somedb
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
```

This works when `.env` is present. But in some situations, .env will not be present and there I want to fallback to environment variables.

Currently, it does not seem to work.

**Comment by runeimp** [comment]
Checkout [Getting and Setting Environment Variables - Just Programmer's Manual](https://just.systems/man/en/chapter_36.html) on how to access system environment variables with Just. 😃

**Comment by mrpandey** [comment]
My bad. I was running this in a docker container and compose was not passing the env correctly. Closing this.

The script in original issue actually looks at both places - first at actual environment variables, then at .env file.
