### ISSUE TITLE
Paths backslashes are not escaped on Windows

### ISSUE THREAD

**Issue by johhnry** [casey/just#1608]
Hi,

This is a simple justfile where I want to use the `absolute_path` function on Windows:

```
default:
    @just --list

echo-path:
    ls {{absolute_path(".")}}
```

What I get is this:

```shell
$ just echo-path
ls C:\Users\jhenry\project
ls: cannot access 'C:Usersjhenryproject': No such file or directory
error: Recipe `echo-path` failed on line 5 with exit code 2
```

What is wrong here?

Thanks!

- Just `1.13.0`

**Comment by casey** [comment]
Can't believe I let this sit for so long!

WIndows paths contain backslashes so they need to be quoted:

```just
echo-path:
    ls '{{absolute_path(".")}}'
```
