### ISSUE TITLE
Proposal: include with namespace

### ISSUE THREAD

**Issue by presidento** [casey/just#1614]
I have standalone submodules, I can work with each of them independently, also they are grouped into one project.
I have justfiles in the submodules, and also one in a project top-level folder. It would be good to be able to include a justfile with namespace.

# Example

## justfile

```just
!include foo/justfile as foo
!include bar/justfile as bar

bootstrap: foo.bootstrap bar.bootstrap
```

## foo/justfile

```just
bootstrap:
    # Bootstrapping foo

runserver:
    # Running foo server
```

## bar/justfile

```just
bootstrap:
    # Bootstrapping bar

runserver:
    # Running bar server
```

# Expected output

`just --list` could be something like

```
bootstrap
foo.bootstrap
foo.runserver
bar.bootstrap
bar.runserver
```

# Workaround

I can manually map every task into the project justfile.

## justfile

```just
bootstrap: foo_bootstrap bar_bootstrap

just_foo := "just -f foo/justfile"
just_bar := "just -f bar/justfile"

foo_bootstrap:
    {{ just_foo }} bootstrap
foo_runserver:
    {{ just_foo }} runserver

bar_bootstrap:
    {{ just_bar }} bootstrap
bar_runserver:
    {{ just_bar }} runserver
```

Or I can write a script which parses all of justfiles of the dependant projects and creates the mapping justfile which can be included in the project global justfile.

**Comment by expelledboy** [comment]
I would prefer using a namespace "tag", eg

```justfile
not_in_group:
    echo

[group: foo]

!include foo/justfile

task_in_group:
    echo yes

[group: bar]

!include bar/justfile

[group]

# Outside group again
bootstrap: not_in_group foo.bootstrap bar.bootstrap foo.task_in_group
```

**Comment by marcbria** [comment]
@expelledboy this is your proposal but it's not working yet in just, isn't it?

**Comment by laniakea64** [comment]
Seems this was implemented as [Modules](https://just.systems/man/en/chapter_54.html)?

**Comment by casey** [comment]
Yes indeed, this has been done! Thanks @laniakea64 for the ping!
