### ISSUE TITLE
Better support for paths and filenames

### ISSUE THREAD

**Issue by casey** [casey/just#162]
String variables whose values are files and paths are common in justfiles.

It might be nice to provide better support for this. Some ideas:

- `path(string)` constructor for building paths. Should maybe call out that this will perform the conversion according to the environment, like `path_from_windows()`, `path_from_unix()`, and `path_from_local()`
- A `/` operator for joining path components. Don't need to worry if one part already has a `/`
- Abstract over `/` and `\` separated paths so it works on both windows and unix
- Provide some useful functions that operate on paths, such as converting to an absolute path, popping off a path component, and the like
- A `.` variable which is the directory that contains the justfile
- A `justfile` variable which is the path to the justfile
- Perhaps also a `file(string)` function which throws an error if there is a path component

**Comment by casey** [comment]
Moving this to the wiki and closing:

https://github.com/casey/just/wiki/Feature-Ideas

**Comment by InAnYan** [comment]
I upvote this.

IMHO, `/` operator looks cringey. Looking at the docs (<https://just.systems/man/en/expressions-and-substitutions.html#joining-paths>), what is the purpose of this operator if it's equal to string concatenation?
