### ISSUE TITLE
Multi-level just files

### ISSUE THREAD

**Issue by psyciknz** [casey/just#1621]
Hi just started using this program.  More for reference info on comands etc.   I'm trying to figure out best approch re: set fallback, or  inlcudes.

I'd like to get a list of commands depending how deep I am back to a main level.
Eg:
docker
  default
      restic

Each of these dirs have a just file with specific commands relating to each.
So docker justfile would have something like a docker stop and rm a container.
The default just file might have something like restarting my telegraf container (which is in a stack here)
The restic justfile would have a bunch of command relating to restic (restore etc).

If I was in restic, I'd like to be able to list:
the restic commands
default commands
and docker dir commands.

How might I achieve this?  I can through just --list and just list ..  get two levels working.  But not that 3rd level.

Cheers

**Comment by dezyh** [comment]
I'm doing something similar like this but it won't be ideal if you have deep nesting or lots of sub-directories.

```
.
├── justfile
├── client
│   ├── justfile
│   └── ...
├── server
│   ├── justfile
│   └── ...
└── ...
```


```
# justfile

project := justfile_directory()
client := project + "/client"
server := project + "/server"

# run a server command
@server *cmd:
    cd {{server}} && just {{cmd}}

# run a client command
@client *cmd:
    cd {{client}} && just {{cmd}}
```

```
# client/justfile

client := justfile_directory()
project := client + "/.."

# run a client command
@client *cmd:
    cd {{project}} && just client {{cmd}}

# run a server command
@server *cmd:
    cd {{project}} && just server {{cmd}}
```

```
# server/justfile

server := justfile_directory()
project := server + "/.."

# run a client command
@client *cmd:
    cd {{project}} && just client {{cmd}}

# run a server command
@server *cmd:
    cd {{project}} && just server {{cmd}}
```

It lets you run commands in `client/justfile` and `server/justfile` through `just client {{cmd}}` and `just server {{cmd}}` respectively regardless of which directory you're in.

**Comment by SonicZentropy** [comment]
That is fantastic and should be added to the readme!

**Comment by ccxuy** [comment]
Upvote, we need this feature!

**Comment by casey** [comment]
Good news! Since this issue was opened, we've added the ability to import justfiles, as well as an unstable modules feature.

Check out the readme:

https://github.com/casey/just/?tab=readme-ov-file#imports
https://github.com/casey/just/?tab=readme-ov-file#modules1190

Note that modules are unstable, so to use it, you'll need to pass `--unstable` or do `export JUST_UNSTABLE=1`.

I think the use-cases here are covered by modules, but feel free to ping this issue if not.

**Comment by ccxuy** [comment]
> Good news! Since this issue was opened, we've added the ability to import justfiles, as well as an unstable modules feature.
> 
> Check out the readme:
> 
> https://github.com/casey/just/?tab=readme-ov-file#imports https://github.com/casey/just/?tab=readme-ov-file#modules1190
> 
> Note that modules are unstable, so to use it, you'll need to pass `--unstable` or do `export JUST_UNSTABLE=1`.
> 
> I think the use-cases here are covered by modules, but feel free to ping this issue if not.

it still doesn't solve the problem of invoking just like "just A B option1 option2", whcih A and B could be first and second level of command.
it's helpful when using something similar to docker compose -f yml pull, docker compose up

**Comment by ccxuy** [comment]
```
> cat .justfile

@task *cmd:
  cd tasks && just --justfile .just {{cmd}}
```
```
> cat tasks/.just
list:
  ls -1

build *cmd:
  echo just {{cmd}}
```
It could be done like this, but is there a more native way to do this?

@casey

**Comment by ccxuy** [comment]
BTW, I want to pass some flags to commands.
something like `just cmd -l`

**Comment by ccxuy** [comment]
modules could solve most of the problem, is this syntex already stable?
