### ISSUE TITLE
dlang recipe fails to run

### ISSUE THREAD

**Issue by Dialga** [casey/just#1623]
Following the polyglot example, I tried using dlang and it fails with an error.
```
$ cat justfile
d:
  #!/bin/env rdmd
  void main() {
    import std.stdio;
    "hello from d!".writeln;
  }
$ just
Error: cannot find input file `/tmp/justONmxPi/d.d`
import path[0] = /tmp/justONmxPi
import path[1] = /usr/include/dlang/dmd
Failed: ["/usr/bin/dmd", "-v", "-o-", "/tmp/justONmxPi/d.d", "-I/tmp/justONmxPi"]
error: Recipe `d` failed with exit code 1
```
The embedded dlang code works in an executable script by itself.

**Comment by Taywee** [comment]
Looks like rdmd doesn't like a script that doesn't end in the `.d` extension.  You can see this if you name your script without it:

```nushell
> ./test
Error: cannot find input file `./test.d`
import path[0] = .
import path[1] = /usr/include/dmd/phobos
import path[2] = /usr/include/dmd/druntime/import
Failed: ["/usr/bin/dmd", "-v", "-o-", "./test.d", "-I."]
```

[At least one rdmd manual](https://digitalmars.com/d/1.0/rdmd.html) says:

> rdmd will only compile and execute files with a '.d' file extension

[The current manual doesn't say this](https://dlang.org/rdmd.html), but it does show an example of rdmd automatically assuming the file extension.

[Looking at the source code, it is indeed impossible to run a file with the wrong file extension](https://github.com/dlang/tools/blob/3e1d86e6fb3528314673c0bccdb61c1388a353db/rdmd.d#L230-L234).

Maybe `just` should allow customizing the temporary file template, but this seems to me to be a really silly restriction of a tool like rdmd, which should allow you to let the user call your script as a script without having to worry about the implementation language.

**Comment by Taywee** [comment]
I did a little bit of digging around, and [it looks like `dub` allows you to get around this](https://github.com/Abscissa/scriptlike/blob/master/USAGE.md#a-basic-script-in-d):

```nushell
> cat justfile
d:
  #!/usr/bin/env dub
  /+ dub.sdl: +/

  void main() {
    import std.stdio;
    "hello from d!".writeln;
  }

> just d
hello from d!
```

`dub` will allow you to even specify dependencies and the like.  Using the example right out of that link:

```nushell
> cat justfile
d:
  #!/usr/bin/env dub
  /+ dub.sdl:
    name "myscript"
    dependency "scriptlike" version="~>0.10.2"
  +/
  import scriptlike;

  void main(string[] args) {
    string name;
    if(args.length > 1)
      name = args[1];
    else
      name = userInput!string("What's your name?");

    writeln("Hello, ", name, "!");
  }

> just d
/home/work/.dub/packages/scriptlike/0.10.3/scriptlike/src/scriptlike/core.d(425,2): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
/home/work/.dub/packages/scriptlike/0.10.3/scriptlike/src/scriptlike/core.d(456,2): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
/home/work/.dub/packages/scriptlike/0.10.3/scriptlike/src/scriptlike/core.d(425,2): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
/home/work/.dub/packages/scriptlike/0.10.3/scriptlike/src/scriptlike/core.d(456,2): Deprecation: usage of the `body` keyword is deprecated. Use `do` instead.
What's your name?
> Taylor
Hello, Taylor!

> 
```

**Comment by Dialga** [comment]
Excellent find there! though it should be more obvious on the dlang side.

**Comment by casey** [comment]
I think this is working as expected on the Just side.
