### ISSUE TITLE
vlang recipe fails to run

### ISSUE THREAD

**Issue by Dialga** [casey/just#1624]
Following the polyglot example, I tried using a [vlang](https://github.com/vlang/v/) script which didn't work.
```
$ cat justfile
v:
  #!/bin/env v
  println("hi from v!")
$ just
usage: `v file.v` or `v directory`
unknown file extension ``
error: Recipe `v` failed with exit code 1
```
Here V expects the extracted script to have a .vsh extension in order to run as a script.

**Comment by Taywee** [comment]
[Looks like vlang has a way to work around that](https://github.com/vlang/v/blob/master/doc/docs.md#vsh-scripts-with-no-extension).

Looks to me that the way of doing that is setting the shebang to `#!/usr/bin/env -S v -raw-vsh-tmp-prefix tmp run` to make sure you don't keep redundant files around.
