### ISSUE TITLE
cd cannot switch directories, it is still the current directory

### ISSUE THREAD

**Issue by 107295472** [casey/just#1625]
![image](https://github.com/casey/just/assets/6436116/d33b46a2-41a2-40bc-bc71-e351d5e018ee)

**Comment by maccoda** [comment]
Have a look [at this chapter in the manual](https://just.systems/man/en/chapter_45.html). Each recipe line is executed in a new shell so you will need to make it either a 1 line command (`cd rust && ls`) or a shebang recipe.
```
lint:
  #!/usr/bin/env bash
  set -euxo pipefail
  cd rust
  ls
```
