### ISSUE TITLE
The argument "-n" of command echo be treated as content to output

### ISSUE THREAD

**Issue by shuizhongyueming** [casey/just#1630]
I have defined a recipe like below to output content without the trailing newline

```just
e:
  echo -n "Hello World"
```

What I expect when executing command `just e` is output `Hello World` without newline. But it output `-n Hello World`

<img width="209" alt="image" src="https://github.com/casey/just/assets/2059860/9cba3e51-de2b-4b30-b8dc-206fd0eca439">

Additional Information:
+ Operating System: macOS 13.4
+ Shell: zsh
+ Terminal: Warp, system default terminal
+ just version: 1.14.0

**Comment by casey** [comment]
I think this is probably just the behavior of echo in bash, which just uses. Try printf for better control of formatting.

**Comment by shuizhongyueming** [comment]
@casey thanks for intro the command `printf`.

I have tested the `echo` command in bash, it can accept the `-n` as option but not parameter that can remove the trailing newline.

<img width="525" alt="image" src="https://github.com/casey/just/assets/2059860/876202d0-6985-49e9-8148-f399b38490b2">

But in just, `-n` is still treated as parameter to output

<img width="198" alt="image" src="https://github.com/casey/just/assets/2059860/3a9fc89c-3927-48a1-a45f-4f71b5a8382f">

**Comment by casey** [comment]
Ah, my mistake, just uses sh, not bash. What does sh do with echo -n? (On my phone, otherwise I would check myself.)
