### ISSUE TITLE
JSON dump stablity

### ISSUE THREAD

**Issue by xavdid** [casey/just#1632]
Is there a plan / timeline to remove the `--unstable` flag from the JSON format of `--dump`? I have some functionality I want to build on top of it, but want to wait until it's stabilized.

It's totally cool if there's no plan yet, either. I figure folks can subscribe to this issue and (eventually) get notified of its closing (which is part of why I filed it).

Thank you!

**Comment by casey** [comment]
The JSON dump format was introduced 19 months ago, and there haven't been any major changes or issues, so we might as well stabilize it.

**Comment by casey** [comment]
Stabilied in #1633!

**Comment by xavdid** [comment]
Amazing, thank you!
