### ISSUE TITLE
Add ansi colors as baked in variables 

### ISSUE THREAD

**Issue by dionjwa** [casey/just#1645]
I add this to *all* my justfiles, so perhaps something that could be baked in:

```sh
bold                               := '\033[1m'
normal                             := '\033[0m'
green                              := "\\e[32m"
yellow                             := "\\e[33m"
blue                               := "\\e[34m"
magenta                            := "\\e[35m"
grey                               := "\\e[90m"
```

So I can

```sh
echo -e "{{green}} something here! {{normal}}"
   
```

in different places. It's a lot of repeated preamble in the justfile.

Maybe there is a better way to do this?

**Comment by casey** [comment]
Maybe a function or functions would be better, since just doesn't have a concept of global, default variables. If there's one function, it could be `color("green")` and `color("none")`.
