### ISSUE TITLE
Support for global justfiles

### ISSUE THREAD

**Issue by spartas** [casey/just#1648]
I'm a recovering [Task][1] / [Taskfile][2] refugee, who's recently got into `just`. One of the features of Task that I use extensively is the `-g` ([global][3]) option, which will only search the user's `$HOME` directory (and no subdirectories) for a Taskfile.

This is very handy for running global tasks or recipes that do not need the current directory context, but it is also useful for running tasks that are somewhat generic, but do need the current directory as context (e.g. `docker compose` commands that use the services from the current working directory). Obviously this can be replicated in just with something like `just $HOME/`, but when used with flags and parameters, this quickly becomes unwieldy.

[1]: https://github.com/go-task/task
[2]: https://taskfile.dev
[3]: https://taskfile.dev/usage/#running-a-global-taskfile

**Comment by fordneild** [comment]
if you try a command that isnt in your justfile, iirc just will searching up the file tree looking for one. I have a "global" justfile with general commands at ~/justfile and then project specific commands i put in a justfile at the root of the repository.

**Comment by casey** [comment]
This seems reasonable to me, and pretty easy to implement. If you pass `--global` or `-g`, it looks for a justfile in `~/.justfile` (or maybe `~/justfile` or `~/.config/just/justfile`)

**Comment by spartas** [comment]
> fordneild:
> if you try a command that isnt in your justfile, iirc just will searching up the file tree looking for one. I have a "global" justfile with general commands at ~/justfile and then project specific commands i put in a justfile at the root of the repository.

I didn't consider that `just` would continue searching up the tree until it found a match. There are a few things that I do that wouldn't work though.

In my Docker projects, I typically have a `default` recipe (it's the first recipe in my `justfile`) that runs `docker compose ps`. It doesn't make sense to put this (context-specific recipe) in a global `justfile`, so I also have a `default` recipe in the global file that runs `docker compose ls` to list running compose projects across the whole system.

Secondly, I'm often working under mounted filesystems or subtrees that aren't descendants of `$HOME`.

> casey:
> This seems reasonable to me, and pretty easy to implement. If you pass `--global` or `-g`, it looks for a justfile in `~/.justfile` (or maybe `~/justfile` or `~/.config/just/justfile`)

I don't have a strong opinion about the location for global justfiles (I'd probably use `~/justfile` or `~/.config/just/justfile`). If you support multiple locations for global justfiles, please document the order of precedence that `just` will use when searching for these justfiles (it helps when deciding how to override global justfiles on a per-case basis).

Additionally, if you do support `~/.config/just/justfile`, please support the [`$XDG_CONFIG_HOME`][1] env var from the XDG Base Directory spec. I don't use these vars myself, but I'm sure that someone will.

[1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by dionjwa** [comment]
I have two workarounds for a similar need (although they are not exactly what you are asking for):

This in my `~/.aliases`:

```sh
alias j='just '
alias .j='just --justfile ~/.justfile --working-directory .'
```

so `j` shorthand for normal `just` and `.j` for "global" `just`


And a `justfile` (in my case renamed `backup` for its role) but in my `$PATH`, given executable permissions with the following at the top so that it executes as a command:

```
#!/usr/bin/env just --justfile
```

**Comment by fordneild** [comment]
Fails over to global justfile, its magical.

justg.sh
```sh
#!/bin/bash

# Create a temporary file to capture output.
tmpfile=$(mktemp)

# Tee writes unfiltered output to tmpfile, then we filter the stream with sed before displaying.
just "$@" 2>&1 | tee "$tmpfile" | sed '/error: Justfile does not contain recipe/d'

# Capture the exit code from the just command.
exit_code=${PIPESTATUS[0]}

# If the local just fails and the error indicates "does not contain recipe", retry with the global justfile.
if [ $exit_code -ne 0 ] && grep -q "does not contain recipe" "$tmpfile"; then
  just -f ~/justfile "$@"
fi

# Clean up the temporary file.
rm -f "$tmpfile"
```
.aliasrc (or whereever u put them)
```sh
alias j='sh ~/justg.sh'
```
