### ISSUE TITLE
Proposal positional arguments support  in `just` for shell like nushell etc.

### ISSUE THREAD

**Issue by vincent-herlemont** [casey/just#1651]
Related issues:
 - https://github.com/casey/just/issues/1559
 - https://github.com/casey/just/issues/1554
 - https://github.com/casey/just/issues/1592

I am currently integrating `just` with `nushell`, and I'm experiencing a roadblock with the handling of positional arguments. As of now, it appears that `nushell` lacks support for this functionality.

Here is a snippet of my current Justfile:

```yaml
set shell := ["nu", "-c"]

test_command *args='':
    echo $1
```

Regrettably, this format isn't compatible with `nushell`. I am proposing a feature where we could retrieve positional arguments similar to how it's done in bash or other traditional shells. The idea is to use a syntax ([Variables and Substitution](https://github.com/casey/just#variables-and-substitution)) like `{{1}}`, `{{2}}`, etc. to represent positional arguments equivalent to `$1`, `$2`, etc.

A proposed usage might look like:

```yaml
set shell := ["nu", "-c"]

test_command *args='':
    echo {{1}}
```

This implementation would greatly aid those of us utilizing `just` in conjunction with `nushell` and maybe others. Tell me your opinion on this proposal? Maybe I could try my hand at an MR.

**Comment by casey** [comment]
This should work if you add `set positional-arguments`, which causes positional arguments to be passed to each command

```just
set positional-arguments
set shell := ["nu", "-c"]

foo *args='':
    echo $1
```

Please feel free to reopen if that doesn't work!
