### ISSUE TITLE
[Feature] Support for executing multiple Just commands with a prefix or wildcard notation.

### ISSUE THREAD

**Issue by uasd7** [casey/just#1652]
Hello,
I would like to propose a feature request: it would be cool to be able to execute multiple commands with common prefix via wildcards. 

```
# Justfile
[...]

lint-php: [...]
lint-style: [...]
lint-helm: [...]

[...]

test-unit: [...]
test-component: [...]
test-integration: [...]

[...]

### without wildcards we have to list every command and keep it up to date
pre-commit: lint-php lint-style lint-helm test-unit test-component test-integration

### with wildcards we don't have to worry about additions (f.e. new test stages or linting commands)
pre-commit: lint-* test-*
[...]
```

The primary advantage of adding this feature is the enhanced flexibility it would offer to developers. By supporting the execution of multiple Just commands using a prefix or wildcard notation, users would gain the ability to add new tasks dynamically without modifying the command invocation itself.

With the proposed feature, developers can easily create and integrate new tasks into their workflows without the need to update the command line every time. As projects evolve, and new tasks become necessary, this flexibility becomes invaluable. Furthermore, it fosters a more seamless and maintainable development process, as users can adapt the Just tool to suit their evolving needs without facing cumbersome modifications.

Practical Use Cases:
Custom Task Groups: For projects with various modules or components, developers could create custom task groups using a common prefix. For instance, running just build-* could execute all build-related tasks, irrespective of the specific module, streamlining the build process.

Automated Testing: Users could easily run specific test suites by employing a wildcard expression. For example, executing just test-* could trigger all tests at once.

Code Quality Management: With the ability to use wildcards, developers can effortlessly lint or format subsets of the codebase with a single command, making it easier to enforce consistent code quality standards.

**Comment by bhollis** [comment]
Came here to request the same feature - this would be a huge boon to us in combination with imports, since we have a lot of conventionally-named tasks (`lint-go`, `lint-ruby`, etc.)

**Comment by casey** [comment]
To me personally, this doesn't feel like a huge win, since it doesn't seem that hard to add new recipes to a top-level recipies dependencies:

```
lint-php:
lint-style:
lint-helm:

lint: lint-php lint-style lint-helm
```

And wildcards might lead to executing unexpected recipes, and make the justfile itself somewhat harder to read.

**Comment by casey** [comment]
And, I should also say, I think the implementation would be quite messy.

**Comment by bhollis** [comment]
Fair enough. I've gotten used to using this sort of thing from Yarn and PNPM, for example to run a bunch of different "lint" tools that are each declared as a separate task:

https://pnpm.io/cli/run#running-multiple-scripts

**Comment by uasd7** [comment]
> To me personally, this doesn't feel like a huge win, since it doesn't seem that hard to add new recipes to a top-level recipies dependencies:
> 
> ```
> lint-php:
> lint-style:
> lint-helm:
> 
> lint: lint-php lint-style lint-helm
> ```
> 
> And wildcards might lead to executing unexpected recipes, and make the justfile itself somewhat harder to read.

This may be the case if you only have a few linting commands and only one linking command. Our just files are a bit longer and we have this case for different types of commands (lint, test, start commands, ci, ...), which are summarised in different linking commands, sometimes in several. It would therefore be nice to be able to simply prefix similar commands (we already have this anyway) so that the new commands do not have to be explicitly listed in the various linking commands each time. Especially when different linking commands are involved, it is easy to forget one. In addition, our code is split into micro services, which increases the potential for errors. 

But basically, there now seems to be a similar feature via groupings, so the use case is covered. It is certainly a more verbose approach (more lines in the just file), but achieves the same goal.
