### ISSUE TITLE
string interpolation issue

### ISSUE THREAD

**Issue by Yakiyo** [casey/just#1653]
Hi, i have a go project where im using just as a task runner. My just file is as follows: ([source](https://github.com/Yakiyo/scoob/blob/main/Justfile))
```make
set positional-arguments

flags := "-X github.com/Yakiyo/scoob/consts.BuiltAt=$(date -u)"

default:
  @just --list

@run *arg:
    go run main.go $@

test:
	go test ./...

build:
	go build {{ flags }} .

update:
	go get -u
	go mod tidy

fmt:
	go fmt ./...

tidy:
	go mod tidy
```
Im facing two issues. First i cannot append to `flags` and two, i could not find any way to have `date -u` executed and attaching the output to the string. In a makefile it would be like
```make
ldflags := -X 'github.com/Yakiyo/scoob/consts.BuiltAt=$(shell date -u)'
ldflags += -X 'github.com/Yakiyo/scoob/consts.Revision=$(shell git rev-parse --short HEAD)'
ldflags += -s
ldflags += -w
```
An example makefile from a different repo: [here](https://github.com/metafates/mangal/blob/main/Makefile)
i need to pass all those flags in the build command. but i couldnt find anything in the docs about appending variables. ive tried reassigning the variable again like `ldflags := {{ ldflags }} more string` but that failed too. Is there any way i can do this without needing to write one long as string, and how would i go about executing the commands like `date`  and `git`.

**Comment by laniakea64** [comment]
Executing commands in that context is done with [backticks](https://just.systems/man/en/chapter_33.html).

Does this do what you're looking for? -
```
flags := ("-X github.com/Yakiyo/scoob/consts.BuiltAt=" + quote(`date -u`)
          + " -X github.com/Yakiyo/scoob/consts.Revision=" + `git rev-parse --short HEAD`
          + " -s -w")
```
(added [`quote()`](https://just.systems/man/en/chapter_31.html#string-manipulation) in case the `date -u` output contains characters that are special characters to the shell)

**Comment by Yakiyo** [comment]
> Executing commands in that context is done with [backticks](https://just.systems/man/en/chapter_33.html).
> 
> Does this do what you're looking for? -
> 
> ```
> flags := ("-X github.com/Yakiyo/scoob/consts.BuiltAt=" + quote(`date -u`)
>           + " -X github.com/Yakiyo/scoob/consts.Revision=" + `git rev-parse --short HEAD`
>           + " -s -w")
> ```
> 
> (added [`quote()`](https://just.systems/man/en/chapter_31.html#string-manipulation) in case the `date -u` output contains characters that are special characters to the shell)

That actually does solve it. Thanks for the soln
