### ISSUE TITLE
Can `just` load .env from sub-directory?

### ISSUE THREAD

**Issue by azone** [casey/just#1654]
Here is my directory structure:
```
root
├── Justfile
├── project1
│  └── .env
└── project2
```

I execute the recipe in the project1 directory with `.env` file variables, but `just` do not load the `.env` file in project 1. Is there any way to load it?

**Comment by casey** [comment]
This currently isn't possible. I think this is tracked by something like #945, which would allow specifying a custom `.env` path, e.g. `project/.env`.
