### ISSUE TITLE
Conditional dependencies?

### ISSUE THREAD

**Issue by Swandog** [casey/just#1655]
Is there any way to specify conditional dependencies?

For example, I have a Justfile with a recipe `test`. `test` requires a `docker-compose` of the project to be running in the background, so `test` is dependent on a recipe called`up`, which calls `docker-compose up`. `up` is dependent on the containers being built, so `up` is dependent on the recipe `build`, which builds the containers.

All of that works great! But sometimes, I want to run the `test` recipe twice in a row, and I don't need to rebuild the containers and/or redeploy the `docker-compose`. So it would be nice if I could somehow in my Justfile specify to only run dependencies if needed (i.e., if `docker-compose` is already up, don't run the dependency)

I figure I could probably get a similar effect by putting conditional code in the `up` and `build` recipes, but I'm wondering if there's a way to keep those clean and put the logic in the recipe that is calling them.

**Comment by casey** [comment]
Currently there isn't a way to do this. I think your best bet is to add conditional code in the `up`, e.g. check if the docker container is running, and only run `docker-compose up` if it isn't.
