### ISSUE TITLE
`trim_end_match` doesn't work as expected

### ISSUE THREAD

**Issue by avi-cenna** [casey/just#1658]
I'm not sure if I'm misunderstanding the documentation, but I would expect the following lines to print the same result.

```bash
test:
    echo {{ replace_regex('ping-pong', '-.*$', '') }}
    echo {{ trim_end_match('ping-pong', '-.*$') }}
```

In fact, the first line prints `ping` as expected, but the second line prints `ping-pong`. Isn't `trim_end_match` supposed to take a regular expression?

**Comment by casey** [comment]
Actually this is as-intended. Only `_regex` takes a regular expression, the other `_match` functions take a string literal which is matched verbatim.
