### ISSUE TITLE
Consider renaming `recipe` to `task`

### ISSUE THREAD

**Issue by casey** [casey/just#166]
The word "recipe" comes from make's terminology. However, since `just` is not a build system that is intended to produce artifacts, the term is a bit lacking. The best alternative to is probably `task`.

I'm waffling over whether or not this change is a good idea, so 👍 if you prefer the name `task`, and 👎 if would rather that we keep the existing `recipe` terminology.

**Comment by kbknapp** [comment]
`action`?

**Comment by casey** [comment]
Action is okay, although I haven't seen it used in that sense before. I like that they would be "just actions" though. It has kind of a poetic ring to it.

**Comment by Ezku** [comment]
Since the first comment had multiple suggestions, can I 👍  "just tasks"? :)

**Comment by TeddyDD** [comment]
I like term "recipe". It sounds... tasty 🍰

**Comment by runeimp** [comment]
I like `task`, `action`, and `chore` better than `recipe`, myself. And in that order.

**Comment by dionjwa** [comment]
I would go with `command`. Here are some extremely subjective and personal reasons (add "for me" to every statememt :-)):

 - `task` has other connotations, e.g. compute workflows (with tasks), CI systems with build tasks, and the like
 - `command` puts the emphasis on the user of `just`. I see `just` as a way of nicely packaging and specifying commands, that I as a user am invoking. `task` implies some automated procedures
 - I use `just` as a kind of "command-ops", as an extension of "git-ops". "task-ops" doesn't capture the power and end user ease and UX enjoyment compared to "command-ops". 
 - `command` sounds cooler (I am very scientific)
 - replace "task" with "action" and my above preferences stand

I can't believe I have such strong preferences but `just` is changing the way I organize complex mono-repos, and I have manually changed the default to "Commands:" myself. Thanks for changing my life @casey !

**Comment by casey** [comment]
I think the ship has sailed on this one.
