### ISSUE TITLE
How to enable awk support?

### ISSUE THREAD

**Issue by linux-china** [casey/just#1661]
I want to integrate AWK with just, and awk script as following:

```
demo:
  #!/usr/bin/awk -f
  { print $1, $2, $3 }
```

Is it possible to run AWK script with just?  just alike `just demo log.txt`.

**Comment by casey** [comment]
I'm not super familiar with how awk works. Does the example you gave above not work?

**Comment by linux-china** [comment]
Create a demo.awk file with following code:

```awk
#!/usr/bin/awk -f
{ print $1, $2, $3 }
```

Then execute `./demo.awk demo.log` .

**Comment by laniakea64** [comment]
Try something like this? -
```
demo log:
  #!/usr/bin/awk -f
  BEGIN { ARGC = ARGC + 1;ARGV[ARGC - 1] = "{{log}}" }
  { print $1, $2, $3 }
```
