### ISSUE TITLE
unbound variable check makes it impossible to optionally take into account an environment variable

### ISSUE THREAD

**Issue by schlichtanders** [casey/just#1666]
Hi,
I today tried to migrate some adhoc scripts to a justfile and arrived at a bug/crucially missing feature/some misunderstanding:

```justfile
test:
   #!/usr/bin/env bash
   set -euo pipefail
   if [[ -z "$MYVARIABLE" ]]; then
      DEFAULT="somedefault"
   else
      DEFAULT="$MYVARIABLE"
   fi
```

This raises the unbound variable error if MYVARIABLE does not exist as a environment variable
I would also be happy to know about a workaround (setting the environment variable manually before to empty is NOT a workaround for me - I want the final just call to be convenient)

**Comment by laniakea64** [comment]
From `man bash` -

> `-u`      Treat unset variables and parameters other than the special parameters "@" and "*" as  an  error  when
>         performing  parameter  expansion.   If  expansion  is attempted on an unset variable or parameter, the
>        shell prints an error message, and, if not interactive, exits with a non-zero status.

So try removing `u` from the `set` line?

**Comment by casey** [comment]
You can also leave -u and use ` -z "${VAR:-}"`. `${VAR:-}` will be empty if `VAR` is unset or empty, but won't trigger the unset variable check.

**Comment by schlichtanders** [comment]
thank you so much for your help! that is it indeed!
