### ISSUE TITLE
Passing options to default recipe

### ISSUE THREAD

**Issue by jacg** [casey/just#1668]
It is easy to write recipes which accept flags:
```bash
just my-recipe --some-flag
```
but if this recipe is the default and you try to use it as such, the flag is passed on to `just` itself:
```bash
just --some-flag
error: Found argument '--some-flag' which wasn't expected, or isn't valid in this context
```
Many commands use `--` in these sorts of cases, but it looks like `just` does not:
```bash
just -- some-flag
error: Justfile does not contain recipe `--some-flag`.
```
I have come up with the hack of naming the default recipe `_`, which works, but ... meh.

Does `just` cater for passing flags to the default recipe?

If not, might `--` be added for these sorts of use cases?

**Comment by casey** [comment]
It isn't possible to pass arguments, flags or otherwise, to the default recipe without naming it. I can see the argument for using `--` for this, but I'm not sure that's much better than just naming the default recipe, e.g., `just default --some-arg`.
