### ISSUE TITLE
Handy snippet for "Shell alias" section of the manual

### ISSUE THREAD

**Issue by Andrew15-5** [casey/just#1671]
IIRC, there was a snippet with `alias $command="just $command"` in the manual, but not it is gone. Anyway, I don't think it was as cool as this one:

```sh
for command in $({
  just --summary;
  just -l | grep "# alias for " | awk "{print \$1}";
} | tr " " "\\n" | sed "/^default\$/d" | xargs); do
  alias $command="just $command"
done
```

Then in the shell config:

```sh
alias j='just'
alias just.shell='for command in $({
  just --summary;
  just -l | grep "# alias for " | awk "{print \$1}";
} | tr " " "\\n" | sed "/^default$/d" | xargs); do
  alias $command="just $command"
done'
alias js='just.shell'
```

This will not only add commands from justfile, but also all aliases. `default` command is excluded since it can be accessed via `j`.

I think this snippet should be added to the manual, don't you think so?

P.S. Yeah, there should be a built-in option to only list aliases or list them via `-l, --list`.

**Comment by casey** [comment]
I think this is the section called `Recipe Aliases`. Feel free to open a PR if you have an idea for an improvement!

**Comment by Andrew15-5** [comment]
Oh yeah, found it: [1.8.6. User justfiles](https://just.systems/man/en/chapter_67.html#recipe-aliases).
