### ISSUE TITLE
variable assignment not same as expected

### ISSUE THREAD

**Issue by rmGFW** [casey/just#1674]
```justfile
var1:= "var1"
var2:= var1/ "var2"

target1 var1= "t1":
  echo {{var2}}

target2 :
  echo {{var2}}
```
❯ j target1
echo var1/var2
var1/var2
❯ j target2
echo var1/var2
var1/var2
---
what i want is ,
just target1 output t1/var2

**Comment by casey** [comment]
The `var1` outer variable and the `var1` argument are distinct variables, and the outer `var1/"var2"` uses the outer one.

I'm not sure it works for your use-case, but you can always try:

```just
target1 var1= "t1":
  echo {{var1/"var2"}}

target2 :
  echo {{var1/"var2"}}
```

**Comment by rmGFW** [comment]
> The `var1` outer variable and the `var1` argument are distinct variables, and the outer `var1/"var2"` uses the outer one.
> 
> I'm not sure it works for your use-case, but you can always try:
> 
> ```just
> target1 var1= "t1":
>   echo {{var1/"var2"}}
> 
> target2 :
>   echo {{var1/"var2"}}
> ```

this works, but , i dont want write `{{var1/"var2"}}` again and again , it will be better define a variable for it
