### ISSUE TITLE
Global Quiet?

### ISSUE THREAD

**Issue by dharrigan** [casey/just#1698]
Hi,

Would you consider adding a global setting so that all recipes can be made quiet, then opted-out either having the prefix '@' (inversion) or `[no-quiet]`? Perhaps something like `set quiet`?

My use case is that for the majority of my recipes, I don't want to see the commands that are being run (I'm more interested in the output of the commands). If I do want to see what the recipe is, I can always just edit/cat the Justfile (or just --dump) to remind myself of the command (this happens infrequently, as normally when the recipe is added, it's already been tested that the commands do what I want them to do). Thus, I'm not interested in seeing all the commands being echoed out across all my recipes, so having a way to switch quiet on at a global level would be super handy :-)

Thank you.

-=david=-

**Comment by casey** [comment]
Sure, that sounds reasonable. This would also make a great first PR, for anyone interested!

**Comment by dharrigan** [comment]
Thank you for the consideration.

I don't mind doing the PR - already on it :-)

-=david=-

**Comment by dharrigan** [comment]
This has now been implemented. Thanks @casey for the assist in getting it in :-)

-=david=-
