### ISSUE TITLE
test FAILED thread 'fmt::write_error' panicked

### ISSUE THREAD

**Issue by gpsagency** [casey/just#1706]
~$> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

---

~$> mkdir -p ~/SOFT/RUST/
~$> cd ~/SOFT/RUST/
~$> git clone https://github.com/casey/just
~$> cd ./just
~$> cargo build
~$> cargo install -f just
~$> just

failures:
---- fmt::write_error stdout ----
thread 'fmt::write_error' panicked at tests/test.rs:243:9:
Stderr regex mismatch:
"Wrote justfile to `/tmp/temptreeGttTHo/justfile`\n"
!~=
/Regex("^error: Failed to write justfile to `.*`: Permission denied \\(os error 13\\)\\n$")/
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    fmt::write_error

test result: FAILED. 566 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out; finished in 1.66s

error: test failed, to rerun pass `--test integration`
error: Recipe `test` failed on line 14 with exit code 101

**Comment by casey** [comment]
Interesting! I'm not able to reproduce this locally on my Mac. If anyone can reproduce this, let me know. If it's just this one test failing, then it's unlikely that anything is actually wrong.

**Comment by tgross35** [comment]
FWIW, looks like this is failing in Debian's upstream repos too since they patched it out https://salsa.debian.org/rust-team/debcargo-conf/-/blob/6d8c1b4feddb0be1ae339e7cf1186b20c6b623ac/src/just/debian/patches/skip_failing_tests.patch (I am sure it is a nonissue in real life, but interesting)

**Comment by casey** [comment]
I reproduced this on a debian system where I was running as root. I think the issue is that this test expects an error writing to a file with perms `400`, since it tests an error message, but root can write to the file anyways. I think we should just check if we're root, and not run that test if we are.

**Comment by casey** [comment]
Fixed this to not run if we're root.
