### ISSUE TITLE
Feature request – confirmation option

### ISSUE THREAD

**Issue by lud-wj** [casey/just#1711]
It would be nice if we could flag a command to ask for confirmation. 

For instance we use a lot of commands like `reset-db-test` and `reset-db-dev`, but the latter would mean losing all data manually entered by the developer on the project. We can do the confirmation manually but it could be a nice feature.

What do you think?

**Comment by casey** [comment]
You can use `--dry-run` to preview the commands that would be executed, without actually running them, and then run just again without the `--dry-run` flag to actually run them. Does that work?

**Comment by lud-wj** [comment]
Not really because I know what the command does. It's just that I run the wrong one by mistake. But I dont want to dry-run all the time.

For now I have this recipe:

```just
_confirm:
  #!/usr/bin/env bash
  read -p "Are you sure? " -n 1 -r
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
      echo # newline
      [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
  else
      echo # newline
  fi
  ```
  
  And for instance I use it on the "reset dev" but not on "reset-test":
  
```just
# Rollbacks and re run all migrations for the test database
reset-db-test:
  MIX_ENV=test mix ecto.drop
  MIX_ENV=test mix ecto.create --quiet
  MIX_ENV=test mix ecto.migrate --log-migrations-sql

# Rollbacks and re run all migrations for the development database
reset-db-dev: _confirm
  mix ecto.drop
  mix ecto.create --quiet
  mix ecto.migrate --log-migrations-sql
  ```
  
It works, but it could be nice if the recipe was built-in, with nicer propmpt, and the guarantee that answering "no" will terminate everything (I don't know bash, I am not sure those `return` and `exit` will work 100% of the time).

But that's just a suggestion, for now what I have works!

**Comment by casey** [comment]
Gotcha! I'd be okay with this, especially if the implementation is simple.

**Comment by Hwatwasthat** [comment]
I've had a look at this, I wondered about adding an attribute that would require confirmation for just the annotated recipe. I've got a running example but I don't know if it's handled in a way you'd want in the project (it reads from stdio right now, which I can't see being used directly elsewhere in the project). I can make a pull request and we could go from there?

**Comment by casey** [comment]
I wouldn't be opposed to an attribute which required confirmation. I think this covers @lud-wj's original feature request, @lud-wj, what do you think?

**Comment by lud-wj** [comment]
Sure! I did not know about attributes, but that's great :)

If it's something baked in in the system and not a pseudo-recipe, then it could be nice to have support for a `--force` or `--no-confirm` flag as well. Hmmm but if the recipe calls another that also requires confirmation, then the flag may be `--confirm <recipe-name>` so you can target and keep the mechanism for any other recipe.

Anyway, reading from stdio allows to use `yes | just do-stuff` I guess.

**Comment by Hwatwasthat** [comment]
This can be closed now that #1723 has been merged.

**Comment by casey** [comment]
Nice, closing.

**Comment by lud-wj** [comment]
Excellent, thank you!
