### ISSUE TITLE
Please also release armv6 version

### ISSUE THREAD

**Issue by ragazenta** [casey/just#1714]
Hi,

We have older Raspberry Pi Zero, plan to use justfile in our application. But I see no armv6 version in the release page.
I could create a pull request to add target in release.yaml, but I'm not sure which target to choose:

- arm-unknown-linux-gnueabihf, or
- arm-unknown-linux-musleabihf

Thanks

**Comment by casey** [comment]
I'm not familiar with arm targets, but the release targets use musl, so `arm-unknown-linux-musleabihf` is probably the best bet. Let me know if you run into any issues!

**Comment by casey** [comment]
Fixed in #1715.
