### ISSUE TITLE
Emerging (compiling) just in Gentoo yields an error

### ISSUE THREAD

**Issue by manuvazquez** [casey/just#1718]
I'm trying to emerge `just` in Gentoo from the *guru* overlay and I get the following error
```
rustc: /var/tmp/portage/dev-lang/rust-1.71.1/work/rustc-1.71.1-src/src/llvm-project/llvm/lib/Analysis/I
nstructionPrecedenceTracking.cpp:97: void llvm::InstructionPrecedenceTracking::validate(const llvm::BasicBlock*) const: Assertion `It->second == nullptr && "Block is marked as having special instructions but in fact it  has " "none!"' failed.                                                                   
error: could not compile `just` (bin "just")
```
I've been using (hence, compiling) `just` for a while without a glitch, and I just hit this issue a few weeks ago.

**Comment by casey** [comment]
Look at the error, I'm pretty sure this isn't an issue with just, more likely an issue in rustc using llvm incorrectly, or hitting a bug in llvm, just based on the code that's triggering the error.

**Comment by manuvazquez** [comment]
You are probably right. Anyway, I was able to compile/emerge *just* using `rust-bin`. Thanks!!

**Comment by casey** [comment]
Nice, glad you found a fix!
