### ISSUE TITLE
Specifying dependency by alias causes error

### ISSUE THREAD

**Issue by laniakea64** [casey/just#1725]
Using `just` 1.16.0 Linux x86_64 build downloaded from https://github.com/casey/just/releases/tag/1.16.0

Minimal test justfile:
```
foo: a
	echo 'Foo'

actual-recipe:
	echo 'this recipe has an alias'
alias a := actual-recipe
```

Running `just` just errors with -
```
$ just
error: Recipe `foo` has unknown dependency `a`
  |
1 | foo: a
  |      ^
```

Same error still occurs when putting the aliased recipe and/or its alias before the recipe that depends on it.

Workaround: instead of using an alias, define it as another recipe:
```
foo: a
	echo 'Foo'

actual-recipe:
	echo 'this recipe has an alias'
a: actual-recipe
```

Is it possible to make this work with alias?

**Comment by casey** [comment]
This currently isn't possible. I'm not sure this is super desirable, since you can always use non-aliased recipe name in the dependency. And using an alias is less readable, since you have to look for the alias to see which recipe it is. Is there a reason you can't do this?

**Comment by laniakea64** [comment]
The "workaround" is fine when recipe doesn't take parameters, but recipes with parameters would run into this problem - https://github.com/casey/just/discussions/1302#discussioncomment-6802368

> I'm not sure this is super desirable, 

Before filing this issue, I checked [documentation on aliases](https://just.systems/man/en/chapter_25.html) to make sure this wasn't a misuse of `alias`.  That page says only "Aliases allow recipes to be invoked with alternative names", which implies aliases can be used anywhere in lieu of the main recipe name.

So aliases only apply in the command line, not anywhere in a justfile?  If so, and if that is the desirable behavior, it should be documented.  Would it be helpful if I made a pull request to clarify the documentation?

**Comment by casey** [comment]
> The "workaround" is fine when recipe doesn't take parameters, but recipes with parameters would run into this problem - [#1302 (reply in thread)](https://github.com/casey/just/discussions/1302#discussioncomment-6802368)

I checked out that discussion, and can't figure out how it relates to this issue. Can you give an example justfile which demonstrates the problem?

> So aliases only apply in the command line, not anywhere in a justfile? If so, and if that is the desirable behavior, it should be documented. Would it be helpful if I made a pull request to clarify the documentation?

I think some documentation would be great!

**Comment by laniakea64** [comment]
> I checked out that discussion, and can't figure out how it relates to this issue. Can you give an example justfile which demonstrates the problem?

Sure -
```
set positional-arguments

main-recipe *FLAGS:
	#!/bin/bash
	for i in "$@";do
	  echo "'${i}'"
	done

r *FLAGS: (main-recipe FLAGS)

alias a := main-recipe

test1: (main-recipe '123' '456')
test2: (r '123' '456')
```

The recipes `test1` and `test2` produce different outputs.  If `test2` could use the alias instead of the shim recipe, its output would match the `test1` recipe.

> I think some documentation would be great!

:+1: Opened https://github.com/casey/just/pull/1726 .  Thanks for clarifying the scope of `alias`.

**Comment by casey** [comment]
In this case, why not modify `test2` to call `main-recipe` directly, e.g, `(main-recipe '123' '456')`?

**Comment by laniakea64** [comment]
The case that prompted this issue was a justfile where almost all the recipes depend on one particular recipe, so was seeking to reduce typing by using a one-letter alias when specifying that dependency.

Thinking again, maybe would be best to make the short name the actual recipe name, and make the full spelled-out name an alias for command line usage? :thinking:

**Comment by casey** [comment]
Ah, I see. Yah, in that case maybe that would be the best solution.
