### ISSUE TITLE
[Question] Is there a timeline on making include directives a stable feature?

### ISSUE THREAD

**Issue by nefrob** [casey/just#1729]
Any information on the timeline or outstanding blockers for include directives being added as a stable feature to `just` would be great. This seems highly useful but I do not want to bake a feature into my workflow that will change or be removed.

**Comment by casey** [comment]
Fair question!

Not really, unfortunately. The `#!include` feature as it is a bit sub-optimal. It does literal text inclusion, i.e., it just copies the contents of a file into the justfile that's including it, so error messages have the wrong line number and don't tell you which file the error is coming from. I'm not sure I want to stabilize it before we can make sure that line numbers are decent, and point to the right file.
