### ISSUE TITLE
[Feature Request] pass parameters to to recipe with naming

### ISSUE THREAD

**Issue by oliverdding** [casey/just#1749]
As far as I know, just support **naming variables** and **position parameters**.

But it's also important that user would want to pass the third parameter to the recipe while other parameters are left with the default value, which is called **naming variables**.

Take this justfile as example:

```justfile
test str="foo":
    echo "{{str}}"
```

It's a nice to have feature:

```bash
> just test str="bar"
echo "bar"
bar
```

I know I can use variables instead, but these arguments may be only used in one recipe, which I don't want to leak.

**Comment by casey** [comment]
I agree that this would be useful, although this syntax:

```
just test str=bar
```

Wouldn't work, since `str=bar` is a valid argument for `str`, so it wouldn't be backwards compatible.

I'm working on adding options to recipes: #476 #1746

This would allow declaring test as:

```
test --str str="foo"
```

Which would let you do:

```
just test --str bar
```

To set the value of `str`.

Does that seem like a reasonable solution?

**Comment by oliverdding** [comment]
Hi @casey , I think the declaration of recipe is a bit strange, since I have declare parameter's name as `str`, but I have to set another `--str` just for options.

I have read #476 , I prefer:

```justfile
test --param1="default value here" param2="default value here":
   ...
```

If parameters name is starts with `--`, `just` should register naming for it when calling this recipe, which would not break the backwards compatible, and is much more clean and comfortable.

---

But there is another question, how to call the recipe with both naming parameter and position parameter?

I think `just` should only support naming parameter instead of position parameter, but this would break the compatible...

**Comment by oliverdding** [comment]
Sorry, I accidentally closed it...

**Comment by casey** [comment]
People often use uppercase identifiers, but probably don't want uppercase flags, so there has to be a way to specify the variable name separate from the flag name.

I think there's probably enough overlap to use flags. If a user everything to be given by flag, they can use flags exclusively, and not have any positional arguments.

**Comment by informeti** [comment]
@casey Thank you for clarifying (and for this amazing project!).

I'm not quite certain I understand what the closure of this issue means though: Are named parameters supported now, or can the use case be achieved differently somehow?

I have the use case where tasks have _multiple_ parameters, each with default values. And I have the need to specify _one_ of these parameters. AFAIK, this isn't possible yet, right?
```justfile
uninstall cluster="my-cluster" namespace="my-namespace":
	echo "Uninstalling from cluster: {{cluster}}, namespace: {{namespace}}"
```
In the above example, I'd like to override the value for `namespace`, but leave `cluster` to the default value.

**Comment by Piotr1215** [comment]
Likewise @casey thank you for this amazing project, I'm using it in almost every repo. 

I've just stumbled upon the same usecase. I have this recipe (simplified):

```just
testme registry_name=(temp_registry_name) registry_location=(tilt_registry_location):
  @echo {{registry_name}} and {{registry_location}}
```

I would like to pass the registry_location leaving the default value of registry_name.

**Comment by juanitocalero** [comment]
Hi! 
Having the same problem. I think the syntax @oliverdding proposed is cleaner. Regarding this:

> I agree that this would be useful, although this syntax:
> 
>     just test str=bar
>     
> Wouldn't work, since `str=bar` is a valid argument for `str`, so it wouldn't be backwards compatible.

What about setting a global flag (`set allow-named-parameters`. ) to avoid breaking backwards compatibility?
The implementation will also be easier than a full-blown flags feature, I suspect.
