### ISSUE TITLE
Add a way to set the shell per recipe

### ISSUE THREAD

**Issue by wiiznokes** [casey/just#1767]
I would like to use the same justfile for windows and linux, without having to add argument at each call. It would be nice if for example, `just `take the shell it has been launch with, or we could define a shell per recipe.

**Comment by laniakea64** [comment]
This is done by [shebang recipes](https://just.systems/man/en/chapter_41.html).

If you're seeking to use different shell for the same recipe depending whether it is run on Windows or Linux, see the example in `kitchen-sink.just` -

https://github.com/casey/just/blob/3dbbb2ed70aa7c1b0ae261fda30ff46d3b9e4ef9/examples/kitchen-sink.just#L131-L147

**Comment by wiiznokes** [comment]
Thanks. Also, after settings: `set windows-powershell := true` on the top of my file, it seems to works just fine on bash on Ubuntu and powershell on Windows
