### ISSUE TITLE
feat: Include directive with prefixing

### ISSUE THREAD

**Issue by gabyx** [casey/just#1768]
It would be nice to have a prefixing mechanism for `include` statements, such that when importing another file
```
!include-with-prefix "sub-" a/b/c
```
such that the task `one` in `a/b/c` will be imported with `sub-one`.

**Comment by casey** [comment]
The way I'd like to solve this in the long term is with modules, see #929.

**Comment by gabyx** [comment]
Sounds awesome! Good project! 
Monorepos are The use case … the thing is if just does not reinvent the wheel, e.g. bazel… (gives me 🥶 only looking at their doc … 😂)
