### ISSUE TITLE
Unknown attribute `confirm` 

### ISSUE THREAD

**Issue by JaydenElliott** [casey/just#1773]
## Repeatability steps
1. `pacman -S just`

2. Create `justfile`
```
[confirm]
delete:
  rm file.txt
```
3. run `just delete`

## Error
```
error: Unknown attribute `confirm`
  |
1 | [confirm]
  |  ^^^^^^^
```

**Comment by laniakea64** [comment]
This requires `just` 1.17.0 or later.  Try installing it with `pacman -Syu just` and make sure the Arch Linux packages mirror you're using is up to date?
