### ISSUE TITLE
Bug: Import statement fails

### ISSUE THREAD

**Issue by nefrob** [casey/just#1777]
Following the example from the [docs](https://just.systems/man/en/chapter_53.html) fails:

<img width="528" alt="Screenshot 2023-12-24 at 9 23 19 AM" src="https://github.com/casey/just/assets/25070989/1e15095f-2e67-4127-9cde-88a489705850">

**Comment by casey** [comment]
This wast just added, and I didn't add a note to the readme that it was only available on master. I just released 1.18.0 which includes import statements.
