### ISSUE TITLE
wishlist: A way to know the recipes target

### ISSUE THREAD

**Issue by diegotolentino** [casey/just#1783]
Casey your tool is really cool, I'm playing with this for 1 week and am planning to replace all my Makefiles :dancers: 

A nice feature would be to have an var/function to get the target recipes (in the context of #435) or maybe the full list of params like the $@ for bash scripts. That will allow us to have commands like this:

`ifeq ($(MAKECMDGOALS),docker-respin)
	recreatedb := $(shell dialog --keep-tite --defaultno --yesno 'Recreate Postgres and import DB?' 0 0 --stdout && echo 'recreatedb')
endif`

Or a more just way:

`
recreatedb := if (TARGET =~ 'recreate') {
  `dialog --keep-tite --defaultno --yesno 'Recreate Postgres and import DB?' 0 0 --stdout && echo 'yes'`
} else {
''
}
`

**Comment by laniakea64** [comment]
Can you make that command part of the `recreate` recipe, or have your `recreate` recipe depend on a recipe that runs that command?

**Comment by diegotolentino** [comment]
@laniakea64 In make the "only" (at least in my current knowledge) is adding that before the recipe, so the steps are:

1. if the command I'm running is `recreate`
1.1 ask for the user input and store it on the `recreatedb` var
2. in the recreate use that var

My goal is to replicate this on just, but I couldn't.

**Comment by laniakea64** [comment]
One way would be to make `recreate` a shebang recipe and use a shell variable:
```
recreate:
	#!/bin/bash
	recreatedb="$(dialog --keep-tite --defaultno --yesno 'Recreate Postgres and import DB?' 0 0 --stdout && echo 'yes')"
	echo "The user said $recreatedb"
```

-----------------

Another possibility might be to make the `recreatedb` variable a recipe parameter:
```
recreate recreatedb=`dialog --keep-tite --defaultno --yesno 'Recreate Postgres and import DB?' 0 0 --stdout && echo 'yes' || echo`:
	echo 'The user said {{recreatedb}}.'
```
Note that with this method the prompt is only default - user could bypass the prompt by entering their response directly on the command line, e.g. `just recreate yes`.

**Comment by diegotolentino** [comment]
@laniakea64 It works just fine, thanks for your help

```
docker-respin:
  #!/usr/bin/env bash
  recreatedb=`dialog --keep-tite --defaultno --yesno 'Recreate Postgres and import DB?' 0 0 --stdout && echo 'yes' || echo`
  if [ "$recreatedb" = "yes" ]; then
    docker compose down --remove-orphans --volumes;
  else
    docker compose down --remove-orphans;
  fi
```
