### ISSUE TITLE
import and recipes order

### ISSUE THREAD

**Issue by stessaris** [casey/just#1787]
The interaction between the import statement and the overriding of recipes doesn't seems intuitive to me, because imported recipes take the precedence over the ones in the importing file. I'd expect the other way around, in order to be able to override "defaults".

The following example  shows the problem. With the two files:

```
# justfile

set allow-duplicate-recipes

import 'lib.just'

_default: hello
```
```
# lib.just

_default:
    @just --list

hello:
    echo "hello world"
```

I get the following:

``` sh
$ just --version
just 1.19.0
$ just
error: Justfile contains no default recipe.
$ just _default
Available recipes:
    hello
```

While I'd expect that the default recipe exists, and should be the `_default` defined in `./justfile`. If I move `set allow-duplicate-recipes` in `./lib.just`, or move the `_default` definition before the import, I get the same results.

**Comment by casey** [comment]
Nice catch! I agree, recipes in parent modules should override recipes in imports. Fixed in #1790.
