### ISSUE TITLE
Optional modules

### ISSUE THREAD

**Issue by casey** [casey/just#1796]
From a [comment](https://github.com/casey/just/issues/929#issuecomment-1871710779) by @laniakea64:

> But in testing out replacing this recipe with mod foo 'some_repo/foo/justfile', came across a couple points that block this usage:

> The main place I have such recipe is in a justfile that manages temporary clones of a couple repos. So the repo that contains the justfile I would use as module does not always exist. Currently this state causes error: Failed to read justfile that prevents running any recipes. Could there please be a way for "module only if specified file exists", i.e. if the module file is not found at the specified path, the justfile doesn't error out but the module/subcommands simply doesn't work?

How about the following syntax?

```just
# without a path:
mod foo?

# with a path:
mod foo? 'bar.just'
```

A module with a `?` wouldn't provoke a warning or error when not found.

It could also be:

```just
# without a path:
mod? foo
mod? foo 'bar.just'

mod foo?
mod foo 'bar.just'?
```

Which could be used with import statements, which lack a module name:

```
import? 'foo.just'
import 'foo.just'?
```

**Comment by crdx** [comment]
I was about to raise an issue suggesting the exact same thing re `import`.

I have some public repositories where I would like some non-public recipes in a gitignored justfile. I can only use `import` for this if it's possible to optionally import.

The syntax that feels most natural to me is `import? 'foo.just'`. The `?` at the end of the line reminds me of rust where it has a different meaning.

**Comment by laniakea64** [comment]
> The syntax that feels most natural to me is `import? 'foo.just'`.

+1 for the `mod? foo 'bar.just'` / `import? 'foo.just'` form

**Comment by casey** [comment]
Done in #1797!

With the `mod?` and `import?` syntax:

```just
mod? foo
import? "foo.just"
```

**Comment by crdx** [comment]
Love how quickly you get stuff done.
