### ISSUE TITLE
Include completion files in GitHub release artifacts

### ISSUE THREAD

**Issue by agateau** [casey/just#1814]
I maintain a [Clyde](https://github.com/agateau/clyde) package for Just, and I would love to ship shell completion files. Can you integrate them to the GitHub release artifacts?

**Comment by casey** [comment]
Definitely! One thing you can do in the mean time is get them from just itself. `just --completions SHELL` will print the completion script for that shell to stdout, for example `just --completions zsh` will print the zsh completion script.

**Comment by casey** [comment]
Fixed in #1837!

**Comment by agateau** [comment]
Great, thanks!
