### ISSUE TITLE
"error: Variable `project_name` has multiple definitions" when importing justfiles

### ISSUE THREAD

**Issue by sylvorg** [casey/just#1827]
Hello!

I am getting the error in the title when trying to import a `justfile` with the same variable as in the parent file; is there any setting, perhaps similar to `allow-duplicate-recipes`, that works for variables as well, such as `allow-duplicate-variables`, maybe?

Thank you kindly for the help!

**Comment by casey** [comment]
I'm not sure I understand, can you copy and paste your justfiles so I can take a look?

**Comment by sylvorg** [comment]
Not at my computer right now, _but,_ it's something like this:

`p/a/justfile:`
```make
x := `basename {{justfile_directory()}}`
```
Where `x` results in `a`, and:

`p/b/justfile:`
```make
import "../a/justfile"
x := `basename {{justfile_directory()}}`
```
Where `x` is _supposed_ to result in `b`, but `just` errors out with what's in the title of the issue.

**Comment by casey** [comment]
Gotcha. I think that `set allow-duplicate-variables` would be reasonable to add, and not too much work.

**Comment by casey** [comment]
I marked this as good first issue, in case anyone wants to take a crack at it.

**Comment by sylvorg** [comment]
Wish I could help, but I know nothing of rust, though I've been wanting to learn it for a while! 😅

**Comment by bukowa** [comment]
Can this be closed as completed?

**Comment by sylvorg** [comment]
I have not tested the changes yet, as I'm working on something else at the moment, unfortunately! 😅 We could possibly reopen it if necessary?

**Comment by bukowa** [comment]
> I have not tested the changes yet, as I'm working on something else at the moment, unfortunately! 😅 We could possibly reopen it if necessary?

`set allow-duplicate-variables := true`

I am just using it ^^ I landed here trying to find out why it didn't work before

**Comment by sylvorg** [comment]
Then we should be good to go, I think! My thanks to everyone involved here! 😸

**Comment by teto** [comment]
is there a way to check if the variable is already set and dont override it instead ?
