### ISSUE TITLE
Error function not working as intended

### ISSUE THREAD

**Issue by pportxyz** [casey/just#1830]
Hi Casey! First of all, amazing work : )

I'm starting with just and I want to evaluate some arguments. For example, the test recipe in my justfile has an argument which it needs to have a corresponding file (host_vars file for an ansible project) with the same name. If the evaluation fails, it shouldn't run. I can shell-exit, but it would be amazing to use a built-in function.

From the documentation, I've read there is a `error()` function to abort recipe execution but I cannot make it work. Here is my minimun example:

```
test TEST:
	if test ! -f ansible/host_vars/{{ TEST }}.yaml; then {{ error("host_var file doesnt exist") }}; fi


test-2 TEST:
	if test ! -f ansible/host_vars/{{ TEST }}.yaml; then echo "host_var file doesn't exist"; exit 1; fi

```

And here is the output:

```
pport@laude:~/projects/just-test
> just test hola
error: Call to function `error` failed: host_var file doesnt exist
 ——▶ justfile:2:58
  │
2 │     if test ! -f ansible/host_vars/{{ TEST }}.yaml; then {{ error("host_var file doesnt exist") }}; fi
  │                                                             ^^^^^

pport@laude:~/projects/just-test
> just test-2 hola
if test ! -f ansible/host_vars/hola.yaml; then echo "host_var file doesn't exist"; exit 1; fi
host_var file doesn't exist
error: Recipe `test-2` failed on line 6 with exit code 1

pport@laude:~/projects/just-test
> just --version
just 1.22.1

```

I only could find one instance of the `error()` function in use in the examples directory and there's no other issue like this (at least of what I've seen so far).

Thank u in advance!

**Comment by pportxyz** [comment]
Ok, I've just seen [this part of the documentation](https://just.systems/man/en/chapter_35.html) and it seems the defined behaviour.

If find it quite strange because "Call to function \`error\` failed" somewhat implies that calling the `error()` function itself was the error, not that the intention was to throw it because of "message".

Do you agree? I may be not looking at this with the right pair of glasses...

**Comment by casey** [comment]
The issue here is that just interpolations are evaluated *before* recipes are run, so `error` runs and fails, which prevents the recipe from running.

Can you use the shell `exit` command, like so:

```
test TEST:
	if test ! -f ansible/host_vars/{{ TEST }}.yaml; then echo host_var file doesnt exist; exit 1; fi
```

**Comment by pportxyz** [comment]
Hey! Thank u for your rapid response!

I'm not aware of the internals of your project so please take this with a gigantic grain of salt.

If `error()` is a function to manage bad behaviours, like an exception, should it fail? I think a better flow will be for the error function to stop the execution in a controlled manner rather than letting it fail and become an error on itself. I found it misleading; but then again, I'm not experienced with your project and its internals, even less with rust.

Using the built-in shell `exit` command is actually a solution, but then I see no point to have an `error()` function in the first place.

If you don't agree and think the current behaviour is correct, feel free to close this ticket.

Another time: thank u for your attention and keep going with this fantastic project : ).

**Comment by casey** [comment]
For sure!

I agree it's a bit confusing. I think the primary use of the error function is to serve as the else branch of an if statement:

```just
foo := if bar != "" {
  bar + "hello"
} else {
  error("bar isn't set")
}
```

In this case, you want to error if `bar` is the empty string, because there's no default value for `foo`. It's not super useful inside of recipes.
