### ISSUE TITLE
Strange - old version of just appearing

### ISSUE THREAD

**Issue by epogrebnyak** [casey/just#1832]
Probably something mixed up on path, but I try to build newest version of just, but get an old one. Maybe someone can help spot a problem, many thnaks in advance. ) 

```
@epogrebnyak ➜ /workspaces/abacus (main) $ cargo install just --version 1.22.1 
     Ignored package `just v1.22.1` is already installed, use --force to override
@epogrebnyak ➜ /workspaces/abacus (main) $ just --version
just 1.14.0
@epogrebnyak ➜ /workspaces/abacus (main) $ which just
/home/codespace/.cargo/bin/just
```

**Comment by laniakea64** [comment]
Maybe the following commands will help troubleshoot? -
```
which -a just
echo "CARGO_HOME=$CARGO_HOME"
cat "${CARGO_HOME:-$HOME/.cargo}/.crates2.json" | jq
```

If your shell is `bash`, also check `hash -t just`

**Comment by epogrebnyak** [comment]
Many thanks for the clues, found a real latest version on my machine.
