### ISSUE TITLE
`absolute_path()` returns backslashes on windows in git bash

### ISSUE THREAD

**Issue by dgudim** [casey/just#1838]
I am trying to get an absolute path to a folder on windows, i am running just in git bash. `absolute_path()` returns `C:\something\folder\folder2` which then gets turned into `C:somethingfolderfolder2` when I use the variable via `{{variable}}`. Is there a setting to change the `absolute_path()` behaviour?

**Comment by casey** [comment]
You could wrap `{{variable}}` in single quotes: `{{variable}}`. Really we should make all path functions return forward-slash separated paths, since windows handles them, but that would be a larger change.

Something like `set windows-forward-slash-paths`.
