### ISSUE TITLE
Add support for importing all justfiles in a directory

### ISSUE THREAD

**Issue by noahdotpy** [casey/just#1841]
some syntax like `import '~/justfiles/*'` would be great to import all justfiles in ~/justfiles/

**Comment by casey** [comment]
That seems pretty reasonable. Technically this would be backwards incompatible, but having paths with `*` in them is so rare that I think adding this is reasonable. I think `glob` and `globset` are both good options.

**Comment by pprkut** [comment]
This looks like a duplicate of #1641

**Comment by casey** [comment]
Oh, nice, you're right. Closing in favor of #1641.
