### ISSUE TITLE
realpath in addition to clean

### ISSUE THREAD

**Issue by JonathanDoughty** [casey/just#1858]
I'm struggling with a use case where `justfile_directory()` isn't sufficient. I'd like to keep two independent directories _partially_ in sync. That includes the Justfile. I'd like a way so that, in the controlling directory, the Justfile could use realpath to determine that it was the controller while in the dependent directory the Justfile could recognize "this shouldn't be run here"

Back ticks' limitations are preventing me from, e.g., using the / operator or environment variables or the external realpath (which has its own platform differences) to construct paths. Environment variables not being shared between recipes precludes that approach. None of the other path manipulation functions appear to deal with resolving symbolic links.  (Too bad `clean()` does not seem to.)

[function to get Justfile location path](https://github.com/casey/just/issues/387) seems like the most relevant past issue that was solved by adding `justfile_directory()` With a copied Justfile that won't suffice.

[SIGSEGV in release build](https://github.com/casey/just/issues/508) is the only other issue I find that refers to realpath but illustrates a use case where someone is having to embed native realpath invocations in a recipe where a rust-based one might make for better platform dependence, e.g., macOS had [no native realpath prior to Ventura](https://apple.stackexchange.com/questions/450035/is-the-unix-realpath-command-distributed-with-macos-ventura) and realpath(1) implementations support different flags.

**Comment by casey** [comment]
`clean()` does lexical path cleaning, so it only looks at the path it gets passed, not the filesystem to resolve symlinks. Would adding a `canonicalize()` function help? `canonicalize()` would be like `clean()`, except it would look at and resolve symlinks to produce a canonical path. `canonicalize()` would be easy enough to add, since rust provides `std::fs::canonicalize`, and the function could just call that.

**Comment by JonathanDoughty** [comment]
Yes, that looks like it would provide the desired symlink resolution, with Windows support for those that need it. Thanks!

**Comment by casey** [comment]
Just added a `canonicalize` function, which calls `std::fs::canonicalize`.

**Comment by ghost** [comment]
> Just added a `canonicalize` function, which calls `std::fs::canonicalize`.

I just fell for it, because it's already merged in `master` and thus part of the online documentation, but has not yet been released. 😅 I guess, it will be contained in 1.24.0+. Can you say, when it will be released?

**Comment by casey** [comment]
I'm supposed to put a note in the readme when something is available on master but not a release, but I always forget 😅 Just released [1.24.0](https://github.com/casey/just/releases/tag/1.24.0) which includes canonicalize!
