### ISSUE TITLE
Feature Request: attributes turn off recipe command printing

### ISSUE THREAD

**Issue by serle** [casey/just#1862]
I'd like to be able to only print out the output after executing a just command as many of the scripts are lengthly and distract from seeing the output. 

Examle
  [output-only]
  hello:
     cat .hello.txt | echo
-------
Executing:

should look like this:

$ just hello
$ this is the hello file content

should no longer look like this:

$ just hello
$ cat .hello.txt | echo
$ this is the hello file content

**Comment by laniakea64** [comment]
https://just.systems/man/en/chapter_50.html#quiet-recipes
