### ISSUE TITLE
Error message incorrect when running a non-existent recipe in a module

### ISSUE THREAD

**Issue by crdx** [casey/just#1866]
```bash
$ just foo
error: Justfile does not contain recipe `foo`.

$ just foo::bar
error: Justfile does not contain recipes `foo` or `bar`.
```

**Comment by casey** [comment]
Yah, that is not great 😅 Both space and `::`-separated recipe paths are supported, and just splits `::`-separated paths before processing, which leads to this unhelpful error.

**Comment by casey** [comment]
This was surprisingly hard to fix! When the argument parser was extended to handle submodules, it was hacked in in a pretty unprincipled way. Fixing it required completely refactoring it, but the end result should be simpler and more maintainable. I also found some other bugs, like if you had a recipe `foo` that took an argument, calling `just foo::bar` would call `foo` with the argument `bar`.

**Comment by crdx** [comment]
Back when I reported the issue I tried to fix it myself. I found the relevant part of the code but it was clear that it was going to take a refactor beyond what I could do with my limited knowledge of the codebase.
