### ISSUE TITLE
Use recipe parameter to construct default value for another parameter

### ISSUE THREAD

**Issue by 0phoff** [casey/just#1876]
I wanted to setup a recipe where I specify an input and optionally an output.
If no output is given, I automatically construct an output by changing the extension of the input.

Here is the recipe I tried:
```justfile
recipe input output=(without_extension(input) + '.svg'):
  @echo "{{input}} - {{output}}"
```
However, this gave me the error: **"Variable 'input' not defined"**.
Did I miss something in the documentation or is this indeed not possible ?
My interim solution was to enter a empty string as default output and handle the default value in bash, but I would prefer to use the `without_extension` function provided by _just_.

---

It seems that we can only use variables in the default parameter values, but this means the command is not as clean to use and requires me to enter a default variable value for input.
The usage scenario I would like to obtain is the following:

```bash
# Requested behavior
> just file.png
file.png - file.svg

> just file.png other.svg
file.png - other.svg
```

**Comment by laniakea64** [comment]
Does something like this work for your case? -
```
recipe input output='':
  @echo "{{input}} - {{if output == '' { without_extension(input) + '.svg' } else { output } }}"
```

**Comment by casey** [comment]
Yah, this is unfortunately not possible. Recipe parameters are evaluated in the outer scope, so they don't have access to other parameters.
