### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by marcbria** [casey/just#1886]
Trying to reproduce the import example as follows:

```
$ cat justfile
include "foo/bar.just"
a: b
    @echo A

$ cat foo/bar.just
b:
  @echo B
```

Then , when I run just:

```
$ just -l
error: Expected '*', ':', '$', identifier, or '+', but found string
 ——▶ justfile:1:9
  │
1 │ include "foo/bar.just"
  │        
```

Fails in ubuntu 22.04 (LTS) with the Prebuilt-MPR just version 1.14 and also with the cargo just 1.23.0

**Comment by laniakea64** [comment]
This requires `just` 1.18.0 or later, and `!include` was removed in that version.  It should work if you change `include` to `import`.

**Comment by marcbria** [comment]
Tested with just 1.23 too (installed with cargo) and also fails.
```
$ just --version
just 1.23.0

```

Running on zfs. Could it be related?
Nope. Tried with bash with same result.

**Comment by marcbria** [comment]
Nope. With bash the result is the same.

**Comment by casey** [comment]
Replace `include` with `import`, and it should work:

```
$ cat justfile
import "foo/bar.just"

a: b
    @echo A
$ cat foo/bar.just
b:
  @echo B
```

**Comment by marcbria** [comment]
Frack. I'm stupid. ;-)

Thanks a lot for your help and for this wonderful project!

**Comment by casey** [comment]
You bet, and thank you for using it!
