### ISSUE TITLE
[Feature Request] Usage of variables and functions in defining global variables

### ISSUE THREAD

**Issue by FeryET** [casey/just#1890]
Hi.

Right now if I want define a variable that can be declared easily via interpolation with other variables, I have to use '`executable line`'  format like this:

```just
ABS_BASE_DIR := `echo "$(pwd)/some_dir"`
```

While IMO this could be way more readable and consistent:
```just
ABS_BASE_DIR := '{{ justfile_directory() }}/some_dir'
```

We currently cannot interpolate global variables using other variables or pre-built functions in the recipe.

**Comment by casey** [comment]
Does this work? You can use the `/` operator like so:

```just
foo := justfile_directory() / 'some_dir'
```

```shell
$ just --evaluate foo
foo := "/Users/bar/some_dir"
```

**Comment by FeryET** [comment]
> Does this work? You can use the `/` operator like so:
> 
> ```just
> foo := justfile_directory() / 'some_dir'
> ```
> 
> ```shell
> $ just --evaluate foo
> foo := "/Users/bar/some_dir"
> ```

Yes, it works and it's awesome! Needs to be explicitly documented, tho.

Still in some cases variable interpolation is far easier to read and understand as it reminds people of go template engine or jinja. e.g.:

```just

registry_url := 'example.registry.local'

image_name := 'python'

image_tag  := '3.8-slim'

full_image_id := '{{ registry_url }}/{{  image_name }}:{{  image_tag }}'

@build:
         docker build . -t {{ full_image_id }}

@push:
         docker push {{ full_image_id }}


```

**Comment by casey** [comment]
This is [documented here](https://github.com/casey/just/?tab=readme-ov-file#joining-paths). Interpolation is definitely wanted, see #11.
