### ISSUE TITLE
just --list  --exclude alias

### ISSUE THREAD

**Issue by woutervh** [casey/just#1891]
I 'm defining lots of aliases for multiple commands

but this pollutes my default list-output,
filtering the output in windows looses the colored output

I would be nice to have an option to exclude aliases:
```
# list available recipes
default:
    @ just --list --justfile justfile --unsorted --no-alias
```

**Comment by laniakea64** [comment]
Does this not work? -
```
# list available recipes
default:
    @just --color always --list | grep -Pv {{ quote('#.\[[0-9;]+m\s+.\[[0-9;]+malias for `') }}
```

**Comment by casey** [comment]
A flag seems fine too, if someone wants to open a PR.
