### ISSUE TITLE
issue with build using `env_logger = "0.11.0"` 

### ISSUE THREAD

**Issue by jhheider** [casey/just#1898]
changed in https://github.com/casey/just/commit/a2ff42e6c37ba5c429d444f3a18d3633e59f9a34

building with rust 1.76/cargo 0.65 (or 0.66) give the following:
```
cargo install --path=. --root=/opt/just.systems/v1.24.0+brewing
  Installing just v1.24.0 (/__w/pantry/pantry/builds/just.systems-1.24.0)
    Updating crates.io index
error: failed to compile `just v1.24.0 (/__w/pantry/pantry/builds/just.systems-1.24.0)`, intermediate artifacts can be found at `/__w/pantry/pantry/builds/just.systems-1.24.0/target`

Caused by:
  failed to select a version for `env_logger`.
      ... required by package `just v1.24.0 (/__w/pantry/pantry/builds/just.systems-1.24.0)`
  versions that meet the requirements `^0.11.0` are: 0.11.1, 0.11.0

  the package `just` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
   It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


  failed to select a version for `env_logger` which could resolve this conflict
```

reverting the version of `env_logger` to `"0.10.0"` fixes the build.

failed build: https://github.com/pkgxdev/pantry/actions/runs/7864327681/job/21455948535
successful build: https://github.com/pkgxdev/pantry/actions/runs/7864885532

**Comment by casey** [comment]
I tried to reproduce this with `cargo install --path .`, and it seems to have worked. Is there something else which might be contributing to the issue?

**Comment by jhheider** [comment]
it's certainly always possible. this was rust 1.76 and cargo 0.66 and 0.65. i can't tell which rust/cargo versions are running in your CD without breaking out `rustup`, but what versions are you running locally that work?

it almost has to be cargo, since it's failing during package resolution.

**Comment by jhheider** [comment]
oh, wait. no, cargo is up to 0.77. i bet it's cargo version. let me test a few more.

**Comment by jhheider** [comment]
yup, old cargo versions. apologies for the noise!

**Comment by casey** [comment]
Awesome, no worries, glad it works!
