### ISSUE TITLE
Feature request: print warnings during --dry-run

### ISSUE THREAD

**Issue by nmay231** [casey/just#1899]
This is just a side-thought from #867.

It might be helpful to print warnings during a `--dry-run` for mistakes like using `sha256("file/path.txt")` instead of `sha256_file("file/path.txt")`. Don't know how common or reasonable this is, but it's a thought. \*shrug\*

**Comment by casey** [comment]
I think it's not possible to detect an error like `sha256("file/path.txt")`, since you might actually want the hash of that string. Anything that is detectable should get a warning, and that should definitely printed during `--dry-run`.
