### ISSUE TITLE
Use command-color for shebang recipes

### ISSUE THREAD

**Issue by avi-cenna** [casey/just#1903]
The recent `command-color` flag works nicely for regular just recipes, but it's not used for shebang recipes (e.g. those which start with `#!`).

So if I do `just --command-color purple foo`, it will echo recipe lines in purple if `foo` is a regular recipe, but will still use white if `foo` is a shebang recipe.

Unless anyone thinks this is the desired behavior, I can probably work on a fix for this.

**Comment by casey** [comment]
Using the `--command-color` for shebang recipes seems reasonable to me!
