### ISSUE TITLE
Consider embeding deno_task_shell

### ISSUE THREAD

**Issue by double-daruma** [casey/just#1907]
https://github.com/denoland/deno_task_shell is the rust library used by deno for its tasks system. It's an implementation of a simple shell scripting language that is mostly like `sh`. Embedding this would allow users to write cross platform justfiles without requiring that `sh` is installed on windows systems.

For the supported syntax see https://docs.deno.com/runtime/manual/tools/task_runner#syntax

**Comment by casey** [comment]
Thanks for the suggestion! I think I'm hoping to find something that's a fully-featured sh compatible shell, which ideally comes with a userland as well.
