### ISSUE TITLE
Setting codegen-units=1 for release reduces binary by 230kB

### ISSUE THREAD

**Issue by amarao** [casey/just#1919]
I played with build options, and found, that if 

```
[profile.release]
lto = true
codegen-units = 1
```

than resulting binary is about 200k smaller (without stripping and other manipulations). May be it worth considering for release? Downside is slightly longer compilation time.

Without option: 6737560 bytes.
With option: 6506000 bytes.

**Comment by casey** [comment]
That seems worth it to me. Release options are compiled infrequently, so the smaller binary size is welcome, even if it increases compile times.

**Comment by amarao** [comment]
Fixed in #1920
