### ISSUE TITLE
Interpolation for scripts in targets

### ISSUE THREAD

**Issue by gl-yziquel** [casey/just#1926]
Hi.

As of today, it is not possible to interpolate parameters into scripts. More precisely, this does not work:

```console
do SOMETHING:
    #!/bin/sh
    {{SOMETHING}}
```

This is rather unfortunate.

My use case is the following: I need to run `mystmd` which is a framework that allows to renders pdfs and websites for scientific documents written in an extended form of markdown. To use it, I need to `nvm use lts/iron` to get the right version of node on which `mystmd` runs. However, `nvm use` is a shell builtin, and not an executable. It is therefore not quite possible for me to use something else than a shebang in order to achieve this. (Or, if I'm mistaken, I'd **really** like to know how to bypass that limitation.) And, in order to feed an argument to mystmd, I'd like to pass it via an argument via just.

The lack of interpolation highlighted above precludes this approach.

Which is unfortunate.

**Comment by gl-yziquel** [comment]
My bad. It works. I had some escape nonsense with backslashes going on. Closing.

**Comment by casey** [comment]
No worries, glad you fixed it!
