### ISSUE TITLE
Syntax error with error command

### ISSUE THREAD

**Issue by Munchotaur** [casey/just#1929]
In the manual, the an example error statement is shown as:

`error("123")`

But if I try that in a simple recipe, the error command generates a syntax error (!):

```
# fail horribly
fall_over:
    error("2")
```

```
$ just fall_over
error("2")
sh: 1: Syntax error: word unexpected (expecting ")")
error: Recipe `fall_over` failed on line 50 with exit code 2
```
The second error (`error: Recipe...`) was expected, the first was not.

This is from bash on MX Linux 23.

**Comment by laniakea64** [comment]
`error()` is a `just` function, so to use it in a recipe body, it needs to be in an interpolation:
```
# fail horribly
fall_over:
    {{error("2")}}
```

**Comment by casey** [comment]
And if you'd like to return an error from the shell, you can do:

```
foo:
  exit 2
```

**Comment by Munchotaur** [comment]
> {{error("2")}}

Thanks! Unfortunately there's a new error now:
```
error: Call to function `error` failed: 2
  ——▶ justfile:50:7
  │
50 │     {{error("2")}}
  │       ^^^^^
```

**Comment by casey** [comment]
I think that's the correct error. It's not a great error message, but it's what happens when the error function is called.
