### ISSUE TITLE
Can a recipe know if it has been invoked directly or as a depedency of another?

### ISSUE THREAD

**Issue by nogweii** [casey/just#1930]
Per the question, if not, I think it would be a useful function to add.

For what I'm thinking, I'd like to do the following:

```just
run: install
  ./start_server.py

install:
  poetry install {{ if is_dep() { '--quiet' } else { '--verbose' } }}
```

That is, if someone were to run `just install` manually, they'd get the full output from `poetry install`. If a user runs `just run` instead, poetry would have reduced output.

**Comment by casey** [comment]
This isn't currently possible, but seems pretty reasonable to me. I think the implementation would be pretty simple, in case anyone wants to take a crack at it.

**Comment by laniakea64** [comment]
In the mean time, here's a possible workaround? -
```
run: (install '--quiet')
  ./start_server.py

install flag='--verbose':
  poetry install {{ flag }}
```

**Comment by neunenak** [comment]
With https://github.com/casey/just/pull/2139 this issue can be closed
