### ISSUE TITLE
Consider listable optional named recipe arguments 

### ISSUE THREAD

**Issue by alshdavid** [casey/just#1932]
### Problem

I'd like to be able to use optional named recipie arguments along with variadic arguments so they can be listed with `just -l` and ignored if omitted.

```
just run hello-world
> cargo run --profile dev -- hello-world

just run profile=release hello-world
> cargo run --profile release -- hello-world

just -l
> Available recipes:
>    build profile="dev"
>    run profile="dev" *ARGS
```

### Alternative

I can partially achieve this with environment variables:

```make
profile := env_var_or_default("profile", "dev")

build:
  cargo build --profile {{profile}}

run *ARGS:
  cargo run --profile {{profile}} -- {{ARGS}}
```

```
just run 
> cargo run --

profile=release just run
> cargo run --profile release
```
but I'd like to be able to list them as part of `just -l` so they are discoverable and autocompletion could work - however env vars are not listed
```
just -l
> Available recipes:
>    build
>    run *ARGS
```

### Suggestion

Would the just team consider adding named arguments? 

This isn't valid just config but like this:
```make
build #profile="dev":
  cargo build --profile {{profile}}

run #profile="dev" *args:
  cargo run --profile {{profile}} -- {{ARGS}}
```

Where I could invoke it with 

```
just run hello-world
> cargo run --profile dev -- hello-world

just run profile=release hello-world
> cargo run --profile release -- hello-world

just -l
> Available recipes:
>    build #profile="dev"
>    run #profile="dev" *ARGS
```

Alternatively, given environment variables are explicitly opt-in, could we list out the used environment variables in `just -l`? That wouldn't help with auto-complete but it would help with discoverability.

```
just -l
> Available environment variables:
>    profile="dev"
> Available recipes:
>    build
>    run *ARGS
```

**Comment by casey** [comment]
I think this is covered by #476.
