### ISSUE TITLE
Read a `JUST_VERBOSE` environment variable to always enable the `--verbose` flag

### ISSUE THREAD

**Issue by tgross35** [casey/just#1934]
For CI, I run `just --verbose` for everything. Would be great if I could just set the environment to `JUST_VERBOSE=1` :)

**Comment by casey** [comment]
This seems totally reasonable to me. Would be a great first issue if anyone wants to take a stab at a PR.

**Comment by CramBL** [comment]
Close this? 🤓

**Comment by tgross35** [comment]
Ah yeah this is fixed, but not documented in the main README. Probably should update that with a list of the changes in https://github.com/casey/just/pull/2044/files#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecd before closing

**Comment by casey** [comment]
This is sort-of documented [here](https://github.com/casey/just?tab=readme-ov-file#command-line-options). We could add a list of environment variables to the readme, but that might wind up getting out of date, so I just mention to check the output of `--help`.
