### ISSUE TITLE
show variables in "list help"

### ISSUE THREAD

**Issue by woutervh** [casey/just#1958]
Example justfile

```
docs_dir := "var/docs"

# generate html in {{docs_dir}}/html
docs-html: create-dirs
    sphinx-build doc {{docs_dir}}/html -b html 
    @ echo -e "HTML-build finished in $(realpath {{docs_dir}}/html)."

```

This substitutes the variable in the commands as expected. 
But in "just list" it is not substituted
```
docs-html                     # generate html in {{docs_dir}}/html
```

It would be nice to have substitute the variable in the comment-strings.
OR maybe better the add a section at the top with the list of available variables

```
Available variables
    docs_dir          var/docs

Available recipes:
    docs-html       # generate html in  {{docs_dir}}/html
```

**Comment by laniakea64** [comment]
Related to https://github.com/casey/just/issues/1955 ?

**Comment by woutervh** [comment]
@laniakea64  yes,  #1955 was my initial idea, 
 but that would hide the fact that you can use a variable.

listing the variables, and not substituting in the comment might be a better idea.

**Comment by casey** [comment]
See my [comment here](https://github.com/casey/just/issues/1955#issuecomment-2111443877). I think the right way to fix this is with a `[doc(…)]` attribute which allows using an arbitrary expression as the doc comment.
