### ISSUE TITLE
Is it possible to persist some variables for next just commands?

### ISSUE THREAD

**Issue by ccxuy** [casey/just#1960]
I want to do something like this:

```
a=1
b=2
just a=1 b=2 modA funcB
```
(I thinks` just modA funcB a=1 b=2 `is better)

what I could do now is
```
export a=1
export b=2
just modA funcB
```
(which call `funcB $a $b`, but this would pass variables over all receipts)

maybe some other better way to do this is
```
just save config1 a=1 b=2
just load config1 modA funcB
```
if we can determin scope and namespace of variable is better

**Comment by Mijago** [comment]
You can do this using `--set` - [Setting Variables from the Command Line](https://just.systems/man/en/chapter_36.html#setting-variables-from-the-command-line). While not being my favorite syntax, it certainly does the job!

justfile:
```
a := "x"
b := "y"
```


```shell
> just --evaluate
a := "x"
b := "y"

> just --evaluate --set a b
a := "b"
b := "y"

> just --evaluate --set a 1234 --set b 4567
a := "1234"
b := "4567"
```

**Comment by casey** [comment]
I think maybe a .env file would work for you:

```
$ cat justfile
set dotenv-load

foo:
  echo $A
$ cat .env
A=2
$ just
echo $A
2
```

**Comment by ccxuy** [comment]
How to auto save dotenv? Besides some gramma seems not fully compatible, but `source .env` in every recipes work.
```
just --unstable show_basic
error: Failed to load environment file: Error parsing line: '([0]="2" [1]="11")', error at line index: 9
Failed at 35: just --unstable show_basic
```
@casey

**Comment by ccxuy** [comment]
Is it possible to add a doenv-auto-save option? @casey
