### ISSUE TITLE
bug: just fails to evaluate .env vars

### ISSUE THREAD

**Issue by Nasfame** [casey/just#1967]
just file

```
set dotenv-filename := ".env"

```
.env
```
PORT=9080
IP=0.0.0.0
SERVER_URL="http://$IP:$PORT"
```

Run: `just`
```
error: Failed to load environment file: Error parsing line: '"http://$IP:$PORT"', error at line index: 17

```

**Comment by Mijago** [comment]
The syntax for interpolation is `${IP}` instead of `$IP`.

The following `.env` file works:
```
PORT=9080
IP=0.0.0.0
SERVER_URL="http://${IP}:${PORT}"
```


Tested with this `justfile`:
```
set dotenv-filename := ".env"

default:
  #!/bin/bash
  echo $PORT
  echo $IP
  echo $SERVER_URL
```

Resulting in:
```bash
$ just
9080
0.0.0.0
http://0.0.0.0:9080
```

**Comment by Nasfame** [comment]
Thanks @Mijago ,  i expected it to work cuz my application uses https://github.com/joho/godotenv and it supports it. And yes the interpolations are working when used in curly brackets .

**Comment by Nasfame** [comment]
I would ask for feature for the $ substituted env vars as `source .env`  supports it
