### ISSUE TITLE
file listening

### ISSUE THREAD

**Issue by summer-boythink** [casey/just#1969]
I want `just` to provide a file listening function so I can re-run a `recipe` when some of my files change

**Comment by casey** [comment]
I think this is best done by an external tool, for example, `watchexec`. I updated the readme in #2036 to document how to do this. Check out [the readme](https://github.com/casey/just?tab=readme-ov-file#re-running-recipes-when-files-change).

**Comment by summer-boythink** [comment]
> I think this is best done by an external tool, for example, `watchexec`. I updated the readme in #2036 to document how to do this. Check out [the readme](https://github.com/casey/just?tab=readme-ov-file#re-running-recipes-when-files-change).

thanks you🙂
