### ISSUE TITLE
Add url encoding functions

### ISSUE THREAD

**Issue by nyurik** [casey/just#1982]
I was trying to use `curl` from just:

```just
upload credentials file:
   curl '-u{{credentials}}' -T {{quote(file)}} 'https://example.com/foo/bar/{{file_name(file)}}'
```

and this worked fine until the filename had a `#` character - which broke the above because i was not URL-encoding it.  I think just could use a url encoding function to handle such cases

**Comment by casey** [comment]
Seems reasonable to me! Maybe `url_encode(STRING)`. This would make a great first PR for anyone who wants to take a crack at it.

**Comment by laniakea64** [comment]
"URL encoding" can have several different meanings, e.g.
- percent-encoding some characters, like [Javascript `encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)
- percent-encoding most characters, notably including characters that have meaning in a URL, like [Javascript `encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)
- the encoding that replaces some whitespace characters with `+` and does percent-encoding in some other cases, like seen in search engine search URLs
- base64
- ...

Guessing from the example case, you're seeking `encodeURIComponent`-like encoding?

**Comment by nyurik** [comment]
agree, url encoding has a number of different usecases, so it might be useful to provide more than one function.   For my usecase, `encodeURIComponent` is enough. I do not know how common are other usecases - I haven't encountered them (yet)

**Comment by laniakea64** [comment]
Now that https://github.com/casey/just/pull/2052 has been merged and is available in latest `just` release, should this issue be closed?

**Comment by casey** [comment]
Yup, thanks for noticing!
