### ISSUE TITLE
Support for secure random sequence generation, with a customizable alphabet

### ISSUE THREAD

**Issue by t3hmrman** [casey/just#1991]
Thanks (as always) for the awesome tool!

One thing I'd like to have is secure random sequence generation in `just`. Right now we have `uuid()` which is OK for generating random phrases and stuff, but it would be nice to have a utility that generates a secure random (i.e. from the appropriate OS-provided entropy source) value, of a customizable length, with a customizable alphabet.

This is quite a big feature, but it *would* help remove a bunch of hacks around this that I think many people are doing. Maybe I'm the only one piping `openssl` output through various tools like `tr` trying to get reasonable random values, but it would be nice if this was handled by `just` natively.

**Comment by casey** [comment]
Seems reasonable to me! I think it would be a nice function to add. To keep things simple, I think the first version should just be a function `rand()` which returns a 64-character random hex string. This corresponds to 256 bits of entropy, which is reasonable for almost all cases, and would be a good default. Later, the amount of entropy and alphabet can be customized, perhaps by adding an optional argument, like `rand('01')` if you want a binary string, and `rand('01', 64)` if you want 64 bits of entropy. Syntax TBD.

**Comment by laniakea64** [comment]
Hi, I was curious to see if I could do this and think I might have got somewhere.

[`rand::thread_rng()`](https://docs.rs/rand/latest/rand/fn.thread_rng.html) return value [implements CryptoRng](https://docs.rs/rand/latest/rand/rngs/struct.ThreadRng.html#impl-CryptoRng), which is ["A marker trait used to indicate that an RngCore or BlockRngCore implementation is supposed to be cryptographically secure."](https://docs.rs/rand/latest/rand/trait.CryptoRng.html)  So it seemed reasonable to use that here.

I found it simplest to implement the function as:

`rand(len)` -> return string of `len` random hex digit characters
`rand(len, alphabet)` -> return string of `len` random characters chosen from the characters in `alphabet`

I know this is not quite what casey proposed, so to check:
 - @t3hmrman , would this serve your case?
 - @casey , would this version of `rand()` function be wanted as a PR?

**Comment by casey** [comment]
One thought is that if people are trying to generate entropy, then the amount of entropy provided depends both on `len` and `alphabet`. For example, `rand(5, '10')` provides 2**5 bits of entropy, whereas `rand(5, '0123456789')` provides 5**10 bits of entropy. What the user should care about is how many bits of entropy is provided, and not the length of the resulting string, since the size of the alphabet determines how much entropy is in a string with a given length.

I think calling the function `entropy` and making the first argument the number of bits of entropy to return is probably the safest bet.

**Comment by casey** [comment]
It should be easy to calculate, for a alphabet of size N, one random symbol from that alphabet provides `log2(N)` bits of entropy.

**Comment by laniakea64** [comment]
Hit a roadblock trying to implement that calculation -
```
error: current MSRV (Minimum Supported Rust Version) is `1.63.0` but this item is stable since `1.67.0`
   --> src/function.rs:182:35
    |
182 |     Ok(b) => match alphabet.len().checked_ilog2() {
    |                                   ^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
note: the lint level is defined here
   --> src/lib.rs:1:9
    |
1   | #![deny(clippy::all, clippy::pedantic)]
    |         ^^^^^^^^^^^
    = note: `#[deny(clippy::incompatible_msrv)]` implied by `#[deny(clippy::all)]`

error: could not compile `just` (lib) due to 1 previous error
```
But https://just.systems/man/en/chapter_73.html says MSRV is latest stable Rust, i.e. 1.78.0 today, which is what I'm using? :confused:  What do you suggest?

**Comment by casey** [comment]
You can do the calculations using floating point values, and then in the last step convert to an integer.

**Comment by casey** [comment]
The function should also check that all symbols in the provided alphabet string are unique, and throw an error if they aren't.

**Comment by t3hmrman** [comment]
A bit late here but thanks for giving this a try @laniakea64!

Your initial suggestion would definitely work for me -- I'm really trying to do things like generate IDs/unique suffixes, etc.

I wonder if also pseudo random is worth including, could enable re-running generation deterministically, but it's definitely not important for a v1!

**Comment by casey** [comment]
If they aren't being used as a source of entropy, then a length-based approach is fine, but the name should reflect that, something like `pick(10, 'abcd')`.

**Comment by t3hmrman** [comment]
Yeah, I was less thinking as a source of entropy but I think both the secure and insecure cases are probably reasonable to cover -- `pick` sounds a bit more general, are you wanting an API that's a bit more general to start? 

I doubt that `pick` does enough to suggest that it' a *random* pick.

**Comment by laniakea64** [comment]
> The function should also check that all symbols in the provided alphabet string are unique, and throw an error if they aren't.

The way I currently have it, I think repeats would allow weighted randomness with no extra implementation on `just` side.  Is this something we specifically want to prevent?

**Comment by casey** [comment]
> The way I currently have it, I think repeats would allow weighted randomness with no extra implementation on `just` side. Is this something we specifically want to prevent?

Oh interesting, is that useful? If we make it an error, it would be backwards compatible to allow it later, whereas the opposite isn't true.

**Comment by laniakea64** [comment]
> Oh interesting, is that useful?

It has been useful for me in a few scripts.

> If we make it an error, it would be backwards compatible to allow it later, whereas the opposite isn't true.

Fair enough, I'll make it an error before creating a PR.

**Comment by casey** [comment]
> It has been useful for me in a few scripts.

Can you give an example use-case? I'm not at all opposed to allowing it, I just can't think of a case in which it would be useful myself.

**Comment by laniakea64** [comment]
> Can you give an example use-case? I'm not at all opposed to allowing it, I just can't think of a case in which it would be useful myself.

I don't remember all the cases, but one was generating pronounceable random hostnames for temporary VMs, where the random name is more likely to be pronounceable if some letters are favored more than others.

**Comment by casey** [comment]
Done in #2049! If someone needs an `entropy` function with len specified in bits, please feel free to open a PR or create an issue.
