### ISSUE TITLE
Request: release for Windows arm64

### ISSUE THREAD

**Issue by alshdavid** [casey/just#1992]
Hi, can you please add a release binary for Windows arm64 🙏

**Comment by casey** [comment]
If anyone wants to tackle this, it will require adding an additional target to the [release workflow](https://github.com/casey/just/blob/master/.github/workflows/release.yaml). Unfortunately I have no idea how cross-compiling works on WIndows, so I can't be much help 😅

**Comment by alshdavid** [comment]
Not sure how to test it but I think this might do it :laughing: 

https://github.com/casey/just/pull/2100

**Comment by alshdavid** [comment]
Merged
