### ISSUE TITLE
Cargo.toml dependencies need cleanup?

### ISSUE THREAD

**Issue by laniakea64** [casey/just#1995]
During recent research for `vim-just` I ran across this - https://deps.rs/crate/just

Where couple things jumped out:

1) `just`'s dependency on `regex` [states version 1.5.4](https://github.com/casey/just/blob/c237c0097b50f669f5607a15feafcf1fd6ce40c1/Cargo.toml#L37), which the deps.rs link flags as a security vulnerability.  However, `just` is actually using `regex` version 1.10.3 -
https://github.com/casey/just/blob/c237c0097b50f669f5607a15feafcf1fd6ce40c1/Cargo.lock#L715-L718
Should this be updated in `Cargo.toml` to prevent false positives?

2) `just` [declares a development dependency on `yaml-rust`](https://github.com/casey/just/blob/c237c0097b50f669f5607a15feafcf1fd6ce40c1/Cargo.toml#L57), which [is unmaintained](https://rustsec.org/advisories/RUSTSEC-2024-0320).  AFAICT this dependency is completely unused in today's `just` code, seems its use was removed in https://github.com/casey/just/commit/bb5b962c3dbcf0dc8258e50844602f1f5080f00c ?

**Comment by casey** [comment]
I think this was fixed in #1999.
