### ISSUE TITLE
Allow variable replacement on confirm's prompt

### ISSUE THREAD

**Issue by marcbria** [casey/just#1996]
New [confirm(prompt)] feature is great but is not able to replace the variables of the recipes.

If you try something like this:

```
[confirm("Are you sure you like to create [{{ site }}]?")]
create site:
    echo Site: {{ site }}
```

You will notice that `site` variable won't be replaced in prompt and text will be shown "as is".

Not sure if this is a bug or a feature request. ;-)

Anyway, thanks A LOT for the this wonderful piece of software.

Cheers,
m.

**Comment by casey** [comment]
Closing in favor of #2521, since that fixes this for all attributes.
