### ISSUE TITLE
Remove version number from release assets to make auto-install scripts a little easier?

### ISSUE THREAD

**Issue by alshdavid** [casey/just#2003]
Currently to grab the latest `just` binary you have to query the GitHub releases API for the just repo, lookup the binary name associated with your platform before downloading it.

Would you consider changing the release asset names to omit the version number so the API lookup could be avoided?

This would allow auto-download scripts to use:
```
wget https://github.com/casey/just/releases/download/latest/just-aarch64-apple-darwin.tar.gz
```

Rather than
```
wget https://github.com/casey/just/releases/download/1.25.2/just-1.25.2-aarch64-apple-darwin.tar.gz
```

**Comment by casey** [comment]
I'd definitely consider it. Is it common practice? I personally like having the version number in the release archive name, so you can, for example, download multiple to the same directory.

And there's always the install script:

```
curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s
```

**Comment by VladimirMarkelov** [comment]
I do not think it is common practice. I checked a few very popular apps (e.g, nu/bat/delta). They all add version to the archive name.

Besides loosing the mentioned feature - download a few different version into the same directory, removing version URL may break existing scripts of other people. As I mentioned in another thread, e.g, Windows package managers like `scoop` can be hurt by this change.

If you mark the last release "latest", it is accessible with the link `https://github.com/casey/just/releases/latest` - it automatically redirects the release marked "latest". I am not sure how to download this way in script. Maybe, get redirect URL and extract version number in script?

Edit: checked that URL `https://github.com/nushell/nushell/releases/latest` works fine at this moment.

**Comment by alshdavid** [comment]
That's okay, appreciate the consideration.

Given the filename includes the version you still need to query the contents of the URL to determine the package name to download (even with the `latest` tag in the URL). 

This means that rather than an install being a simple one line `curl | tar -C $HOME/.local/just`, the install script would depend on `jq`, which adds a hurdle for Windows scripts that have to be a bit more spartan.

**Comment by hustcer** [comment]
#1956

**Comment by woutervh** [comment]
https://github.com/casey/just/issues/2006 would fix the same problem in a different way.

**Comment by alshdavid** [comment]
That would help with updating an existing install, but not with fresh installs - right?

**Comment by casey** [comment]
I think I'd rather keep the version number. I prefer to have it there personally, and without the number, after you downloaded an archive, you wouldn't know which version it was.
