### ISSUE TITLE
Expose parser as a crate / AST output as JSON

### ISSUE THREAD

**Issue by gwennlbh** [casey/just#2007]
Hi! First of all thanks a lot for this projects, the DX is 100x better than Makefiles'.

I looked at the Rust crate on docs.rs and saw basically nothing, so I guess there's just the CLI entrypoint that's exposed?

I built a small silly script that takes a Justfile and spits out markdown of the recipes to include in a README: https://gist.github.com/ewen-lbh/d8eb815ad36e4f9d4652c6def0c1a9cd [[Usage example]](https://github.com/ewen-lbh/portfolio)

The parsing is pretty rudimentary and I wondered if exposing the parse output is some way (either by exposing some methods of the rust crate, or by adding a subcommand that dumps a JSON-encoded repr of the AST) would be easy to do, so that people can build things on top of Just

**Comment by casey** [comment]
There's actually already a way to export a justfile to JSON: `just --dump-format json --dump`. Let me know if that works for you and feel free to reopen if not!
