### ISSUE TITLE
make just-functions accept just-variables

### ISSUE THREAD

**Issue by woutervh** [casey/just#2008]
just  has a set of functions you can use in recipes:

- absolute_path(path)
- ...

see https://just.systems/man/en/chapter_31.html

but what if path itself is a variable?

For example
```
BIN_DIR := env_var_or_default("BIN_DIR", "${HOME/bin")
BIN_ABS_DIR := absolute_path({{BIN_DIR }})  # breaks syntax
```

It seems you can currently not pass such variable to a function.

**Comment by laniakea64** [comment]
Does this do what you're looking for? -
```
BIN_DIR := env_var_or_default("BIN_DIR", env_var("HOME") / "bin")
BIN_ABS_DIR := absolute_path(BIN_DIR)
```
