### ISSUE TITLE
Official Debian package

### ISSUE THREAD

**Issue by mgoral** [casey/just#2011]
Hello,

I noticed that just is available in official repositories for Debian Sid (unstable) and Trixie (current testing). It might be worth updating a readme about it:

- https://packages.debian.org/trixie/just
- https://packages.debian.org/sid/just

**Comment by laniakea64** [comment]
That badge is from [Repology](https://repology.org/project/just/badges), which seems to be listing the Debian packages as [a separate project](https://repology.org/project/rust:just/versions)? :confused:

**Comment by casey** [comment]
Sweet! Finally `just` in Debian :)

Hmm, interesting. It looks like rust packages get a `rust:PACKAGE` project on Repology. I added the `rust:just` package table to the readme in #2032.

Eventually the install instructions should be updated to include Debian, but I'd like to wait un that until they're available in stable.
