### ISSUE TITLE
Update snap version of just from 1.2.0

### ISSUE THREAD

**Issue by wiktor-k** [casey/just#2013]
Hi,

I've noticed that https://github.com/casey/just/issues/429 is fixed and that's great but in the meantime, until it's propagated more widely would it be possible to update just in the snap store?

The version there https://snapcraft.io/just is 1.2.0 from 21 June 2022 and I think it has been uploaded by the same person that's maintaining this project.

Context: I'm using [this snippet of YAML](https://github.com/casey/just/pull/1867/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R326) to install packaged version of just for major OSes (so the installation is fast) and it's an old version only on Ubuntu which prevents me from using [Recipe Attributes](https://just.systems/man/en/chapter_32.html) such as `[linux]`.

Thank you for your time and work on this great tool!

**Comment by casey** [comment]
The snap has been kindly adopted by @lucabello, and is now up to date!
