### ISSUE TITLE
Zed editor plugin

### ISSUE THREAD

**Issue by Congyuwang** [casey/just#2015]
It would be really nice to support Zed editor as a plugin for:

- syntax highlighting (should be easy to implement since Zed uses tree-sitter).
- adding just commands in justfile as Zed tasks.

**Comment by syphar** [comment]
For syntax there is already an extension: https://github.com/jackTabsCode/zed-just/tree/6de8206b72f64065013bdf0feab732d428d40ffe 

Commands / justfile would depend on zed exposing a plugin interface for this, for which you should create an issue on their repo

**Comment by Congyuwang** [comment]
Oh. Didn't notice that. Let me close this issue.
