### ISSUE TITLE
justfile_directory() on GitBash returns no separators

### ISSUE THREAD

**Issue by logandavies181** [casey/just#2017]
Running the following justfile on GitBash:

```justfile
@default:
    echo {{justfile_directory()}}
```
Returns the windows-style path with no separators, e.g.:
```
C:UsersUsername
```

<details>
  <summary>Versions</summary>

Windows 10

Just Installed via WinGet:
```
$ just --version
just 1.25.2
```

```
$ bash --version
GNU bash, version 5.2.21(1)-release (x86_64-pc-msys)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

</details>

I've worked around the issue using `invocation_directory()`, which interestingly returns the posix-style path in this case.

Love the project btw 🚀

**Comment by casey** [comment]
This is because the windows-style path contains backslashes, which GitBash interprets as escapes. Does quoting the value work?

```just
@default:
    echo '{{justfile_directory()}}'
```

**Comment by logandavies181** [comment]
Ah, it does. Thank you!

**Comment by casey** [comment]
Nice!
