### ISSUE TITLE
Subshell notation during globals' initialization

### ISSUE THREAD

**Issue by mihaigalos** [casey/just#2025]
Dear maintainers,

just has excellent support for backticks when defining global variables.

I would like to just -pun intendend- use simple subshell syntax like `$(foo)` during globals' initialization.

Backticks are akin to subshell commands anyway, why not the explicit subshell notation support?

This would:
* allow nesting
* clearly delimit subshells

**Comment by casey** [comment]
I'm fine with allowing `$(…)` as a synonym for backticks. Although I'd like to wait for a bit to get some more positive feedback, since it would be a bit confusing to have two ways of doing the same thing.

**Comment by laniakea64** [comment]
> it would be a bit confusing to have two ways of doing the same thing.

The confusion is worse than that.  People coming from `make` will be used to seeing `$(foo)` mean referencing a variable.  People coming from `bash`/`sh` will be used to needing to quote this notation like `"$(...)"`, which in `just` you'd have to **not** do.

And the proposed syntax has nothing to do with the stated benefits.  Nested `$(...)` command evaluation already works in backticks, and backticks already clearly delimit commands.

**Comment by casey** [comment]
Ah yeah, right, if you want nested backticks, you can of course use `$(…)` which is also the recommended syntax for bash. In that case, I don't think this is worth it.
