### ISSUE TITLE
OS-independent Justfile - Suggestion

### ISSUE THREAD

**Issue by chasealanbrown** [casey/just#2042]
In efforts to 'better solidify' the attempts at making an elegant Justfile that is OS-independent, I was wondering what thoughts were towards simplifying the whole system by adding in a 'Universal Package Manager' to `just`, such that a very simple base Justfile for installation of nearly any package could be standardized.

There are options for such a 'universal package manager', such as [upt](https://github.com/sigoden/upt) (the likely choice to add in, as it's Rust?), [app](https://github.com/hkdb/app), or [sysget](https://github.com/emilengler/sysget), and likely many others.

The proposed Justfile could look something like this (with the great efforts and solutions provided by the team! 😄 ):

```Justfile
# Unsure of how to define an array (not currently possible)... :/
#pkgs := ('zathura', 'zathura-pdf-mupdf', 'typst')
# Perhaps load _somehow_ from toml?
pkgs = load("deps.toml")

default: install test run

run:
  python run.py # or anything

test:
  # do tests

# General installation of all packages needed, in any OS / any package manager
install:
  # The 'std' (standard) part of toml for consistent named pkgs for all OS
  upt install $pkgs.std

# (Advanced): specific considerations if needed for a single OS pkgs
[macos]
install:
  upt install $pkgs.std
  # do something macOS specific for each package in $pkgs.mac (each pkg has specific commands)
  for pkg_ in {{pkgs.mac}}; do
    upt install $pkg_ && $pkg_.cmds
  done
```

Of course for packages it's always good practice to use the package management tool for the language; however, for some projects there are just a few executables or programs that are needed.

Justfiles are one of the few real possibilities that I see (other than containers) to finally fix this problem, and `upt` seems rather small, so perhaps this is a useful addition.

**Comment by casey** [comment]
I think the idea of using a dependency manifest along with a universal package manager is a great idea! Though I don't think just really needs to do anything special to support it. You could do:

```just
deps:
  brew bundle install --no-lock --file Brewfile

foo:
  # use binaries installed by deps recipe
```

**Comment by chasealanbrown** [comment]
The idea is more to have it available (in just) such that it isn't required for the person to install just, then something else (upt), then ...

The hope is to only have to install one thing (like docker, but for native / non-containerized solutions).
