### ISSUE TITLE
multiple targets with varadic arguments

### ISSUE THREAD

**Issue by eridal** [casey/just#2043]
The multiple targets execution is a nice feature, however we can't execute anything after a target that has varadic arguments.

```
none:
  echo none

single ARG:
  echo single: {{ARG}}

variadic *ARGS:
  echo variadic: {{ARGS}}
```

We can run most combinations of these, like for instance..

- `just none single 1`
- `just none single 1 single 2 none`

..plus variadic will also work..

- `just none variadic 1 2 3`
- `just single 1 variadic 1 2 3`

..however we can't run anything before variadic targets, like for example `just variadic 1 2 3 none` will pass `none` as parameter

Could we use a separator to instruct just to stop processing variadic arguments
and interpret the next argument as a target name?

Personally I think that using `\;` make sense as some tools are already using it for similar purposes (ie. find -exec); 
also I'd avoid `--` and `-` as these are usefull when composing commands (ie. `just grep -- file.txt`, or `just print -`)

---

>
> Foot Note: just will not escape `;`, which will be interpreted as a separator and the shell system will execute the rest. Is this expected?
>
> `just variadic 1 2 3 \; echo 1`
> `just variadic 1 2 3 ';' echo 1`
>

**Comment by casey** [comment]
Check out #1556. The syntax that's proposed there is `just [ foo 1 2 3 ] [ bar a b c ]` where `foo` receives arguments 1 2 3 and bar receives arguments a b c. This prevents needing quoting, and is backwards compatible, since `[` isn't a valid recipe name.

**Comment by eridal** [comment]
Oh I see casey, thanks for the quick reply. Is this available or just planned?

**Comment by casey** [comment]
Just planned, someone would need to take a crack at it!
