### ISSUE TITLE
PROPOSAL: Do not change current working directory when just finds a target in the parent

### ISSUE THREAD

**Issue by gabyx** [casey/just#2051]
When`just gaga ./myfile`is executed in a subfolder `/a/b/c` of a `/justfile` it will change the working directory to this justfile's directory e.g. `/` and then execute the 
target. Arguments given to the command might be relative file paths and these will then not work as intended, when suddenly the cwd is changed (there is also no documentation for this behavior AFAIK).

It would be nice to disable this behavior (ok its braking change I guess, or introduce a setting `set cwd-to-current-justfile = false`.

**Comment by laniakea64** [comment]
Can you use [`[no-cd]` attribute](https://just.systems/man/en/chapter_32.html#disabling-changing-directory190) on the recipes where you want this behavior disabled?

**Comment by casey** [comment]
Good noticing that there wasn't any documentation of this. I opened #2053 to rectify this.

This is a pretty fundamental behavior of `just`, and I think there are more pros for it than cons, although I see how this case is annoying.

You can use `[no-cd]` on a recipe, like @laniakea64 says, to change this behavior.

A potential feature that could be added is marking an argument as a path somehow, which would cause it to be joined with the invocation directory, making it an absolute path, and thus insensitive to the current directory:

```just
@foo bar~path:
  echo {{bar}}
```

```sh
$ cd subdir
$ just foo hello/baz
/subdir/hello/baz
```

**Comment by gabyx** [comment]
Ah nice there is already a solution, cool.
Maybe yes, the path thing on an argument  would be nice.
