### ISSUE TITLE
I've created just runner plugin for neovim

### ISSUE THREAD

**Issue by nxuv** [casey/just#2057]
You might be interested

https://github.com/al1-ce/just.nvim

Creates a number of commands to use just as a build tool, namely:
- JustDefault - Builds current file/project using default task.
- JustBuild - Builds current file/project using build task.
- JustRun - Builds current file/project using run task.
- JustTest - Builds current file/project using test task.
- JustSelect - Gives you selection of all tasks in justdfile.
- JustStop - Stops currently executed task
- JustCreateTemplate - Creates template justdfile with included "cheatsheet".

And has some special [keywords](https://github.com/al1-ce/just.nvim/blob/master/primer.md#argument-keywords-macros) like passing file path/file name to just and is able to ask user for input for arguments

**Comment by casey** [comment]
Looks very cool! I like the keyword system! If it gets some traction I'll definitely add it to the readme.
