### ISSUE TITLE
Documentation on just.systems not updated?

### ISSUE THREAD

**Issue by laniakea64** [casey/just#2068]
Recent updates to README.md are not being reflected on https://just.systems/man/en/ .  Looks like the last README.md change to make it there was https://github.com/casey/just/commit/eb8227744eaf574a36a90d89e429ee6a488978b1 , so if this is caused by a change in this repo, the regression range maybe https://github.com/casey/just/compare/eb8227744eaf574a36a90d89e429ee6a488978b1...daf4520a2b8259ea26db15c1c55972170dfb9dc2 ?

**Comment by casey** [comment]
Good catch! I fixed it, but I still have no idea what went wrong. It does look like it happened around the time of those changes to the workflow files, although I fixed it, I think, by just turning on and off GitHub pages, and didn't have to change any workflow files. Hopefully it stays fixed!
