### ISSUE TITLE
import?? as more optional than import? w/r shadowing of recipes. Or [conspicuous] directive ?

### ISSUE THREAD

**Issue by gl-yziquel** [casey/just#2075]
Hi.

I like the `import?` feature, and am making heavy use of it to keep some Justfile recipes out of version control. I find it mighty useful. So: keep it.

However, whereas the ? imposes that the compilation phase of the Justfile does not fail if the optional file is not present, it is not quite fully transparent to the end user.

For instance, if a recipe is declared in both the main justfile and the optional justfile, the compilation phase fails. In my opinion, in that setting, it should not fail unless it is specified behaviour. Indeed: if A is a host justfile that compiles fine, and B a justfile that is designed to work generically for multiple hosts A0, A1, ..., An, the expected behaviour would be that it be deployable just fine in all cases as that is more transparent.

I suggest import?? to implement that unobtrusive behaviour.

However, what I would think smarter would be the following behaviour:

1. By default, if two recipes conflict with an import? (and not an import without ?: I'd expect a failure in that case), the host recipe should IMO shadow the imported recipe. (Although that is debatable, and, ideally, configurable).

2. A [conspicuous] (as opposed to [inconspicuous] / [shadowable]) directive could instruct the imported recipe to override that of the host.

The use case is here simple. I wish to deploy `todo` recipes in optionally imported justfiles to provide bug tracking functionality (with taskwarrior) in my repos, local to my repos. Importing an optional justfile that is ignored from git is perfect in that context. However, if I already have a "todo" recipe that I have not yet migrated in my host file, I'd expect behaviour that is already specified to not change.

Thoughts ?

I use this feature in places such as this one:

https://github.com/gl-yziquel/ogma/blob/master/Justfile#L10

**Comment by casey** [comment]
Does `set allow-duplicate-recipes` do what you want? If `allow-duplicate-recipes` is set, duplicate recipes are permitted, and the last defined recipe with a given name overrides previously defined recipes with the same name.

**Comment by gl-yziquel** [comment]
Ah. Yes. I just found it out.

Checking...

**Comment by gl-yziquel** [comment]
... and closed.

I just love just.

**Comment by casey** [comment]
Nice, glad that works!

**Comment by gl-yziquel** [comment]
Nice just just works...

Thank you endlessly for this most magnificent tool.
