### ISSUE TITLE
Add timestamps to each command printed

### ISSUE THREAD

**Issue by nogweii** [casey/just#2078]
Using `just` in CI, it would be pretty handy to have a bunch of timestamps on each printed line of the recipe to see how long each step takes. Possibly by opting into it with a new `--timestamps` flag?

**Comment by casey** [comment]
That seems reasonable to me!

**Comment by starthal** [comment]
Closed by #2084 ?

**Comment by casey** [comment]
Whoops, yup! Thanks for noticing!
