### ISSUE TITLE
`dotenv-path` causes error if the specified envfile does not exist

### ISSUE THREAD

**Issue by FelixZY** [casey/just#2093]
**Steps to reproduce:**
1. Create this `justfile` in an empty directory:
    ```just
    set dotenv-load := true
    set dotenv-path := ".env"

    sayhi:
        @echo "Hello world"
    ```
2. execute `just sayhi`

**Expected**

> Hello World

**Actual**

```
error: Failed to load environment file: No such file or directory (os error 2)
```

**Additional context**
* just version 1.27.0 (cargo)
* setting `dotenv-load` to `false` still reproduces the issue
* [Documentation for `dotenv-path`](https://github.com/casey/just#table-of-settings) states (my emphasis):
  > Load a .env file from a custom path, **if present**."

**Comment by casey** [comment]
I just tested this, and it looks like `dotenv-path` has always failed if the environment file isn't present. Whether or not this is the best behavior is up for debate. On the one hand, if you have a truly optional `.env` file, then it would be nice to run if it isn't found. On the other hand, if the `.env` file is required for recipes to run correctly, you would want an error.

For now I'm going to update the docs, and leave this issue open to collect feedback.

**Comment by FelixZY** [comment]
In my case, the env file is required for most actions. However, I have some additional requirements (specifically, docker compose secrets) which makes setting up the env file manually a bit of a pain. For this reason, I have a special task to help the user generate their env file, which is placed in a special location. 

If `dotenv-path` did not care about the presence of the env file, as originally documented, my users could start using `just` from a fresh clone. Now though, there is a manual step required first in creating an empty env file. 

Perhaps you're right that `dotenv-path` and `dotenv-filename` should not define the behaviour for the case of a missing env file. However, I really think there should be an option to support cases where `just` itself is used to generate the envfile (using `just` to interact with [`vercel env`](https://vercel.com/docs/cli/env) is yet another example of this)! Perhaps something like `dotenv-optional` or `dotenv-fallback: ignore/fail`

**Comment by FelixZY** [comment]
Also, forcing the presence of an env file seems a bit weird in general. The env file is supposed to offer one *alternative* way of defining environment variables. It does not necessarily have to be *the* way.

Consider a CI environment such as GitHub actions where environment variables are pre-defined. If `just` throws an error simply because the env file does not exist, I'm now forced to add an extra step of setting up an env file, despite my environment having been correctly configured from the start.

**Comment by casey** [comment]
I think maybe the best option is to add a new setting, `set dotenv-required`, or something like that, which, when set, makes not finding a `.env` file an error, and at the same time time, making `set dotenv-path` not cause an error if an environment file is not found. This would make `set dotenv-path` and `set dotenv-file` work the same way, with respect to a dotenv file not being found, and allow users to opt-in to getting an error if a `.env` is not found.

**Comment by FelixZY** [comment]
I like this, especially as it is not a breaking change like #2099 was (even if it never did work without the env file before).

+1 for `dotenv-required`

**Comment by casey** [comment]
It is done! I added a new setting, `set dotenv-required`, which makes it an error if an environment file is not found. Not finding an environment file with `set dotenv-path` is now no longer an error .
