### ISSUE TITLE
1.27.0 broke completion when using alias

### ISSUE THREAD

**Issue by lyderic** [casey/just#2094]
Hi,

I am used to alias `just` to a single letter (`k` in my case).

To have recipe completion, I have added these lines to my ~/.bashrc:

```bash
source <(just --completions bash)
complete -F _just -o bashdefault -o default k
```

So `k <tab>` would give the same result as `just <tab>`.

However, since the update to 1.27.0, `k <tab>` displays a list of files in the current dir, not a list of available recipes as was previously the case.

I can't figure out where this difference comes from, because it seems that the only change has been the addition of the `--groups` option in `just.bash`.

Am I missing something?

Please note the issue doesn't seem to be related to installation procedure, as I have tried both `pacman -S just` and `curl --proto...`

Many thanks,
L.

**Comment by neunenak** [comment]
One of the changes in 1.27 (see https://github.com/casey/just/releases/tag/1.27.0) was updating `clap`, the rust library just uses for handling command-line arguments, from version 2 to version 4. This library is used to handle `just --completions <shell>`, so probably something about the upgrade affected the bash shell completion output.

Here's the diff on my system between the 1.26 `--completions bash` output and the version on latest master:

```
$ diff 1.26-output 1.27-output
<     local i cur prev words cword opts cmds
---
>     local i cur prev words cword opts cmd
22,23c22,23
<         case "${i}" in
<             "$1")
---
>         case "${cmd},${i}" in
>             ",$1")
26d25
<             
33,34c32,33
<         just)
<             opts=" -n -q -u -v -e -l -h -V -f -d -c -s -E  --check --yes --dry-run --highlight --no-aliases --no-deps --no-dotenv --no-highlight --quiet --shell-command --clear-shell-args --unsorted --unstable --verbose --changelog --choose --dump --edit --evaluate --fmt --init --list --summary --variables --help --version --chooser --color --command-color --dump-format --list-heading --list-prefix --justfile --set --shell --shell-arg --working-directory --command --completions --show --dotenv-filename --dotenv-path  <ARGUMENTS>... "
---
>         "$1")
>             opts="-n -f -q -u -v -d -c -e -l -s -E -g -h -V --check --chooser --color --command-color --yes --dry-run --dump-format --highlight --list-heading --list-prefix --no-aliases --no-deps --no-dotenv --no-highlight --justfile --quiet --set --shell --shell-arg --shell-command --clear-shell-args --unsorted --unstable --verbose --working-directory --changelog --choose --command --completions --dump --edit --evaluate --fmt --init --list --groups --man --show --summary --variables --dotenv-filename --dotenv-path --global-justfile --help --version [ARGUMENTS]..."
56d54
<                 
85c83
<                     -f)
---
>                 -f)
105c103
<                     -d)
---
>                 -d)
113c111
<                     -c)
---
>                 -c)
118c116
<                     COMPREPLY=($(compgen -W "zsh bash fish powershell elvish" -- "${cur}"))
---
>                     COMPREPLY=($(compgen -W "bash elvish fish powershell zsh" -- "${cur}"))
125c123
<                     -s)
---
>                 -s)
137c135
<                     -E)
---
>                 -E)
148d145
<         
152c149,153
< complete -F _just -o bashdefault -o default just
---
> if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
>     complete -F _just -o nosort -o bashdefault -o default just
> else
>     complete -F _just -o bashdefault -o default just
> fi
```

It looks like the 1.27 version changed the literal string `"just"` to `"$1"`, which might be affecting your snippet. I'm unfortunately not familiar with how bash shell completion works, but hopefully that gives you something to go on with.

**Comment by lyderic** [comment]
Thanks. I guess that fixing the problem is not simply a matter of reverting from `"$1"` to `"just"` :-(

When I have some time, I will try anyway and I will use the opportunity to learn how to build `just` and rust project in general.

Cheers,
L.

**Comment by laniakea64** [comment]
> It looks like the 1.27 version changed the literal string `"just"` to `"$1"`, which might be affecting your snippet. 

It is exactly that change.  Can confirm this works around the issue -
```bash
source <(just --completions bash | sed -r -e 's/^(\s+")\$1"\)$/\1just")/')
```

**Comment by casey** [comment]
Since we already patch the completion script, we could change `$1` to `just`, assuming it doesn't break anything else.

I notice that in `completions::BASH_COMPLETION_REPLACEMENTS`, we replace `        just)` with `        "$1")`. I have no idea why though.

**Comment by laniakea64** [comment]
> I have no idea why though.

Ironically, looks like https://github.com/casey/just/pull/1035 which was _adding_ support for this case.  Seems the instance of `            just)` it was replacing at the time doesn't exist anymore?

**Comment by casey** [comment]
The completion subcommand will actually throw an error if a replacement isn't found, so it still exists.

**Comment by laniakea64** [comment]
> The completion subcommand will actually throw an error if a replacement isn't found, so it still exists.

Sorry I wasn't clear.  Yes, that string is still present, but it's not the specific instance of that string that was originally intended to replace.

Back then, it was line 12 in this code -
https://github.com/casey/just/commit/f70b6711a227aa2b12322f8004f464f95c695ca2#diff-45d316426f902c2d07925d33b4c3d3c51b9e6d1e861425b03fd7859f06ba8637L12-R12
https://github.com/casey/just/blob/f70b6711a227aa2b12322f8004f464f95c695ca2/completions/just.bash#L9-L22

In current `just`, the equivalent code is -
https://github.com/casey/just/blob/8678565b045fd48fe950a0a3cbbae9226b4a5909/completions/just.bash#L20-L32

The equivalent line is 23 which is no longer a match and already uses `$1`.

The question is, is the line 32 in the current version being modified in a way that breaks completing shell aliases?  or would it anyway be `"$1")` and not `just)`?

**Comment by lyderic** [comment]
> > It looks like the 1.27 version changed the literal string `"just"` to `"$1"`, which might be affecting your snippet.
> 
> It is exactly that change. Can confirm this works around the issue -
> 
> ```shell
> source <(just --completions bash | sed -r -e 's/^(\s+")\$1"\)$/\1just")/')
> ```

Many thanks for the workaround.

To recap, these are the relevant lines in my ~/.bashrc now:

```bash
alias k=just
source <(just --completions bash | sed -r -e 's/^(\s+")\$1"\)$/\1just")/')
complete -F _just -o bashdefault -o default k
```

Obviously, this doesn't work if only sourcing the completion script provided by the package manager: in my case, the script is `/usr/share/bash-completion/completions/just` and is provided by `pacman`.

However, the workaround works for me and the above lines overwrite any other possible previous sourcing. My versions are:

```bash
$ pacman -Q just bash
just 1.27.0-1
bash 5.2.026-2
```

L.

**Comment by laniakea64** [comment]
Have confirmed that https://github.com/casey/just/issues/2094#issuecomment-2132531351 is correct and that the bug is indeed caused by the replacement applying where it wasn't intended.  Will try to make a PR.

**Comment by casey** [comment]
@laniakea64 Awesome, thanks for digging into this!
