### ISSUE TITLE
Get just to show up in cargo/crates.io search

### ISSUE THREAD

**Issue by casey** [casey/just#210]
See rust-lang/crates.io/issues/321 for details.

Crates.io is hosted on heroku, using the postgres add-on as the database. It seems unlikely that it'll be possible to change the default stop list. However, it might be possible to change the to_tsvector configuration to not use stop words entirely. I'll have to spin up a crates.io backend and test it myself.

**Comment by jonas-schievink** [comment]
FWIW, Cargo is now showing just as an "Exact Match": https://crates.io/search?q=just

**Comment by casey** [comment]
Excellent!
