### ISSUE TITLE
module_file() ?

### ISSUE THREAD

**Issue by gl-yziquel** [casey/just#2101]
Hi.

There is `justfile()` and `source_file()`.

Executing `just --list --unsorted --justfile` on the Justfile does not allow to list the recipes of the current module, but only does so for the whole Justfile. Using that on the source_file(), when it is the main file of a module, does list the module recipes. But I'd like to make that listing uniform across all my modules, and would like to import a common file for this help recipe that each module should have. In that context, source_file() refers only to the imported file, and not to the main module file.

So, as of today, unless I'm mistaken, there is justfile() and source_file() but no module_file().

I'd like a module_file() to be able to refer to the module that is importing my help.just snippet.

Doable ?

**Comment by casey** [comment]
Manes sense! Information about which module we're in isn't present in the information available to functions, but it could be wired through.

**Comment by gl-yziquel** [comment]
@casey As I'm multitasking between tasks, I'd appreciate having some information on how that could be performed. If, on the top of your head, you could give quick hints as to how module_file() could be wired in, I may eventually find the time to look at it.

**Comment by casey** [comment]
I wound up starting to work on this #2105. I still need to add tests, but that shouldn't be too hard.

**Comment by casey** [comment]
This was surprisingly tricky! There are multiple contexts in which expressions are evaluated, outer assignments, parameters, and within recipe interpolations, and they all had to be handled differently.

**Comment by gl-yziquel** [comment]
Thanks. Will try to test it when my use case pops up again.

**Comment by gl-yziquel** [comment]
Yep. Very cool. Works like a charm. Thank you @casey

**Comment by casey** [comment]
Dope, glad to hear it!
