### ISSUE TITLE
Windows shebang recipe

### ISSUE THREAD

**Issue by fabiomoratti** [casey/just#2143]
I ran into a strange behavior running a shebang recipe on windows.

I currently don't have `cygpath` installed so I don't have "/" in the interpreter path as per documentation ("_If the interpreter path does not contain a / it will be executed without being translated._ ") [here](https://just.systems/man/en/chapter_44.html).

The following just script:

```
default:
    #!bash
    echo "Greetings from Just"
```
throws this error:
```
/bin/bash: C:UsersfabioAppDataLocalTempjust-9dsFivdefault: No such file or directory
error: Recipe `default` failed with exit code 127
```

While this modified scripts works just fine:

```
export DUMMY_VARIABLE := "DUMMY_VALUE"

default:
    #!bash
    echo "Greetings from Just"
```

My intuition is that the `export` command sorts of "bootstraps" the bash execution environment, but I was wondering if I'm missing something or what is the explanation for this behavior.

Thanks,

Fabio

**Comment by casey** [comment]
Thanks for the report! I opened #2144 with a test for this, and is passes on windows CI. Are you able to run `bash` in the terminal by itself?

**Comment by fabiomoratti** [comment]
Yes but, I don't know if it's relevant, I've changed the default path in the dos terminal from where I run just to execute the bash shipped with git instead of the one in "C:\Windows\System32\" which I suppose is the WLS one.

Maybe I messed up my environment is some other way...

No big deal, as the workaround is trivial, I was just curious to understand what happens under the hood.

Thanks - Fabio

**Comment by casey** [comment]
Interesting, I'm thinking it must be some kind of configuration issue. Let me know if you run into problems again!
