### ISSUE TITLE
How to set variables depending on current recipe name or group

### ISSUE THREAD

**Issue by mathieuruellan** [casey/just#2149]
Hello,

I'm migrating a Makefile into Justfile;

In the Makefile I'm using $(MAKECMDGOALS) to analyse and set parameters depending on target.
The goal is to factor many settings for several recipes.

Example:
```
ifeq ($(findstring myprefix-,$(MAKECMDGOALS)),)
else
  setting1 := xxxxx
  setting2 := yyyy
endif
```

Is there a good practice to do that?

**Comment by casey** [comment]
Thanks for the issue! This currently isn't possible, `just` is more or less statically typed, and it would make the type system more complicated if variables were sometimes set and sometimes not, depending on dynamic information. I think #1144 covers this. Figuring out how to make this work is really about coming up with an implementation that does what you want without having too weird of an implementation.

**Comment by mathieuruellan** [comment]
Ok, I need to change the way i think. It is not a rule engine.
Actualy I spent the day to get something acceptable by using recipe parameters.
It is less powerful than Makefile, but more accessible for my team and it answers to our needs.
