### ISSUE TITLE
If-else multi-line syntax error

### ISSUE THREAD

**Issue by sim4life** [casey/just#2150]
I'm trying to write a recipe with simple multi-line if-else to check and/or create the needed directories.

```
srchout_dir := 'srch_out'
srchout_path := join(invocation_directory(), srchout_dir)

create-setup-dirs: && verify-setup
  if !path_exists({{srchout_path}}); then \
    mkdir -p {{srchout2_dir}}; \
    echo "Just created path: {{srchout_path}}"; \
  fi

verify-setup:
  if !path_exists({{srchout_path}}); then \
    error("Does NOT exist: {{srchout_path}}"); \ 
  else \
    echo "All is well!"; \
  fi
  ```
Running the following justfile recipe:
`$ just create-setup-dirs`
  
reports this syntax error:
```
if path_exists(/home/myuser/myproj/srch_out); then mkdir -p srch_out; echo "Just created path: /home/myuser/myproj/srch_out"; fi
sh: 1: Syntax error: word unexpected (expecting ")")
error: Recipe `create-setup-dirs` failed on line 24 with exit code 2
```

Is such a thing possible in multi-line syntax? If NO, then what's the syntax to produce expected behaviour in single-line if-else?

**Comment by laniakea64** [comment]
The problem is that justfile is trying to feed `just` syntax to the shell.  Putting all `just` syntax inside interpolation should work -
```
create-setup-dirs: && verify-setup
  {{if path_exists(srchout_path) != "true" { \
    "mkdir -p " + srchout_dir + ";" + \
    'echo "Just created path:" ' + quote(srchout_path) \
    } else { "" } \
  }}

verify-setup:
  {{if path_exists(srchout_path) == "true" { \
      'echo "All is well"' \
    } else { \
      error("Does NOT exist: " + srchout_path) \
    } \
  }}
```

**Comment by casey** [comment]
This is correct. Just syntax is only allowed outside of recipes. The inside of recipes is `sh` syntax (or whatever other shell you use). It's probably easiest to just use normal shell conditionals inside your recipes.
