### ISSUE TITLE
It should be possible to have groups appear in justfile order

### ISSUE THREAD

**Issue by FelixZY** [casey/just#2157]
`just` supports outputting individual commands in the order they are defined in the justfile:

> `just --list --unsorted` prints recipes in their justfile order within each group:
>
> https://github.com/casey/just?tab=readme-ov-file#recipe-groups

However, the `--unsorted` flag does not appear to apply to the groups themselves, neither can I see an option to have the groups printed in justfile order.

**Comment by casey** [comment]
Seems reasonable to me! Implemented in #2160.

**Comment by FelixZY** [comment]
Awesome! @casey you really have some good turnaround time on issues - thank you _very_ much! 

Question after looking at the new tests: how does #2160 interact with `just --list --unsorted`? I'd really like the groups to be unsorted in this instance as well.

**Comment by casey** [comment]
Gotcha, that makes sense! Implemented in #2164.

**Comment by casey** [comment]
> Awesome! @casey you really have some good turnaround time on issues - thank you _very_ much!

You're most welcome! That's what you get when I'm sitting around bored at home ;)
