### ISSUE TITLE
Stop parsing flags after the first positional argument

### ISSUE THREAD

**Issue by casey** [casey/just#216]
`just` currently parses flags even if they could be parsed as recipe arguments:

```make
commit flag:
  git commit {{flag}}
```

```sh
$ just commit --all
error: Found argument --all which wasn't expected...
```

Can't decide if this is a bug or working as intended. If this bugs you, make sure to comment!

**Comment by bb010g** [comment]
I think treating any flags after a recipe name literally makes the most sense. It allows for adjusting `just` pretty normally while keeping scenarios like that smooth (as opposed to the more verbose `just commit -- --all`).

**Comment by casey** [comment]
I think I agree. I'm *slightly* worried because it's a breaking change, so some things will do something different now. For example, it breaks a bunch of tests which relied on the old behavior. I can fix those though, and I guess I can just bump the version to 0.3.0 :P
