### ISSUE TITLE
Recipe-specific defaults (and setting vars in general)

### ISSUE THREAD

**Issue by samhaaf** [casey/just#2165]
I can't, for the life of me, figure out how to set values, and in this case, recipe-specific default values for global vars.

I want to pass in my environment vars with the syntax:

```bash
just PORT=345 HOST=12.0.0.1 serve
```

Where PORT and HOST are optional.

```justfile
PORT=""
HOST=""

install:
    npm install

build:
    npm run build

serve:
    SERVE_PORT="{{PORT}}"
    SERVE_HOST="{{PORT}}"
    : ${SERVE_PORT:-"80"}
    : ${SERVE_HOST:-"0.0.0.0"}
    PORT=$SERVE_PORT HOST=$SERVE_HOST npm run serve

watch PORT="8080" HOST="127.0.0.1":
    WATCH_PORT="{{PORT}}"
    WATCH_HOST="{{PORT}}"
    : ${WATCH_PORT:-"8080"}
    : ${WATCH_HOST:-"127.0.0.1"}
    PORT=$WATCH_PORT HOST=$WATCH_HOST npm run watch
```

I don't want to use positional args with default values. My args aren't inherently positional. Sometimes I just want to change the host, sometimes I just want to change the port. I've used Justfiles in a lot of projects and I just have to figure this out - the problem is too generally applicable.

Much appreciation for the project.

Btw chatgpt loves Justfiles but is god awful at writing them. It's a shame.

**Comment by casey** [comment]
You could do something like this:

```just
PORT := ""

SERVE_PORT := if PORT == "" { "80" } else { PORT }
WATCH_PORT := if PORT == "" { "8080" } else { PORT }
```

Note that by default, each line of a recipe is executed in its own shell, so variable assignments will not carry over to later lines.

You can use a shebang recipe to make just execute the whole thing as a script:

```just
PORT := ""
HOST := ""

serve:
    #!/usr/bin/env bash
    SERVE_PORT='{{PORT}}'
    SERVE_HOST='{{HOST}}'
    : ${SERVE_PORT:=80}
    : ${SERVE_HOST:=0.0.0.0}
    PORT=$SERVE_PORT HOST=$SERVE_HOST echo $SERVE_PORT $SERVE_HOST
```

Note a few changes:

- Assignments use `:=`
- `: ${VAR:=VAL}` will assign to the variable, whereas `: ${VAR:-VAL}` will just expand the value

> Btw chatgpt loves Justfiles but is god awful at writing them. It's a shame.

😂

AI researchers suspect that strong AI will be required to write correct justfiles.

**Comment by samhaaf** [comment]
That's what I was looking for! Thanks :)

> AI researchers suspect that strong AI will be required to write correct justfiles.

😂

**Comment by casey** [comment]
Nice!
