### ISSUE TITLE
Consider `[module]` recipe attribute

### ISSUE THREAD

**Issue by FelixZY** [casey/just#2168]
Something I really like about the [support for modules](https://github.com/casey/just?tab=readme-ov-file#modules-1190) is that I can get "subcommands". I.e., rather than writing `just db_migrate` I can do `just db migrate`.

Currently I'm using a combination of prefixes (`db_`) and the `[group]` recipe attribute to get something similar when using a single `justfile` but I find myself disliking this pattern and unconsciously avoiding adding prefixes to commands which causes inconsistencies. I also am unable to fold help sections which can cause long help outputs.

As a solution, I would like to suggest a `[module]` recipe attribute (I also considered `[subcommand]` but think `[module]` would fit better with existing functionality). This attribute would cause the annotated command to behave as if it was located in a module. I.e. these should be equivalent:

#### `justfile`
```
mod db ".db.justfile"

[private]
default: help

help:
    @just --list --justfile {{ justfile() }}
```

#### `.db.justfile`
```
[private]
default: help

help:
    @just --list db --justfile {{ justfile() }}

# Commits the current migration into the `committed/` folder
commit:
    @npx graphile-migrate commit
```

#### `justfile`
```
[private]
default: help

help:
    @just --list --justfile {{ justfile() }}

[module("db")]
help:
    @just --list db --justfile {{ justfile() }}

# Commits the current migration into the `committed/` folder
[module("db")]
commit:
    @npx graphile-migrate commit
```

**Comment by laniakea64** [comment]
> (I also considered `[subcommand]`

Actually, this way is more intuitive and more flexible.  Modules have their own scope of variables, and recipe attributes can't be applied to variables, so "inline modules" defined with the proposed syntax would have no way to use any variables.  Separate `[subcommand]` functionality could be its own thing without such limitation.

How would this interact with `[group]`?

**Comment by FelixZY** [comment]
Makes sense.

> How would this interact with `[group]`?

For now I would expect it not to, given that it would be breaking for `[group]` to interact with this functionality in any way. `[group]` and `[module`/`subcommand]` would be distinct (perhaps even incompatible?).

For v2.x it would be nice to settle on only one of these.

**Comment by casey** [comment]
I hesitate to add multiple ways to define recipes in modules.

Is the only issue here that you would prefer to avoid creating a separate file? Or there something else that prevents using submodules?

**Comment by FelixZY** [comment]
I have two issues: 
1. I would like to group commands based on a common subcommand.
2. I would like to avoid polluting my project with multiple justfiles just to get this behavior. Multiple justfiles make sense in a monorepo but not in a single-project repo.

The reason I suggested `[module]` is that I thought it might be easier to jack in to existing functionality. I also thought that changing the behaviour of `[group]` would be breaking enough to warrant a major version bump - though it may be more suitable.

---

An additional alternative would be support for syntax similar to

```
db::commit:
    @npx graphile-migrate commit
```

**Comment by casey** [comment]
Just is committed to backwards compatibility and stability, and part of that is guaranteeing that existing justfiles never break, so there will never be a major version bump.

I have been thinking of supporting an inline module syntax:

```
foo::
  bar:

  baz:
```

Where, in this case, `bar` and `baz` are inside module `foo`, which would allow you to put all recipes inside a single file. How does that strike you?

**Comment by FelixZY** [comment]
Inline modules is definitely an interesting concept - and it would address the issues raised by @laniakea64 as well. I have two main concerns with your proposal:
1. Readability (I think a more prominent prefix would be more readable than the `::` postfix)
2. I'm a bit concerned that inline modules may become complex, especially to maintain

However, the proposal gave me an idea!

### YAML

YAML supports multiple "documents" in a single file using the `---` separator:

```yaml
document:
  title: This is the first document
---
document:
  title: This is the second document
```

I think this would be nice since you can simply parse every document as a separate justfile. The only extra logic needed is to split a single file into multiple documents. After this step you wouldn't care if the documents originated from the same or different files.

### Markdown

Markdown uses `#` to denote headlines. `# = headline 1`, `## = headline 2`, `### = headline 3` and so on. We could reuse this to allow for nested submodules:

```
foo:
    @echo "foo"

# say

hi:
    @echo "hi"

## the

time:
    @date
```

Given that `#` is used for comments in just, I would suggest a different character.

### Proposal

* We introduce a *module delimiter character*. This character is used to indicate the end of the current document and the start of a new.
  * I suggest `=`.
* The *module delimiter character* must be followed by a space followed by a module identifier
  * Example: `= db`
* Multiple *module delimiter characters* can be used to indicate a submodule
  * Example:
    ```
    = just
    == is
    === awesome
    ```
* Submodules are automatically imported into its direct parent module (this includes the first module which is automatically imported into the primary document)
* It is possible to use fewer *module delimiter characters* to put multiple modules under a previous parent
  * Example:
    ```
    = just
    == is
    === awesome
    == be
    === cool
    = foo
    == bar
    ```
* It is a syntax error to use more than one additional *module delimiter character* than its parent
  * Example
    ```
    = do
    == this
    = not
    === this
    ```
* It is not  allowed to import only a submodule from a file. Not only is this complicated, I think it goes against the intent of the author to extract individual submodules from a given justfile and could have unforeseen consequences.
  * Example:
    ```
    # Not allowed!
    mod sub ".other.justfile#sub"
    ```

Example:

```
# We still support external modules but these must be explicitly imported.
mod db "db/.db.justfile"

start:
    @npm start

# just env <>
= env

# Note: this would apply as if the module defined by "env" was a standalone file!
# It does _not_ affect the parent scope, nor any of the submodule scopes.
export := true

a := "hello"

foo:
    @echo $a

# just env pull <>
== pull

vercel:
    @npx vercel env pull

# just env add <>
== add

vercel:
    @npx vercel env add

# just debug <>
= debug

dev:
  @npm run dev
```

Also note that I would expect the modules defined in the above file to work even if the file was imported by another file:

```
mod app ".app.justfile"

# We now have e.g. `just app debug dev <>` instead of `just debug dev <>`.
```

**Comment by FelixZY** [comment]
Sidenote, maybe there should be some sort of way to define the minimum `just` version required for a given justfile. I think it would be better for just to fail with a shorter "please upgrade just" message than throw some sort of (syntax)error when features such as this are introduced.

**Comment by casey** [comment]
I think that the `=` syntax is pretty weird on first impression, but I think that's just because I've been thinking of intent-based inline module syntax. It's definitely an interesting idea.

I'm not very worried about the maintainability of the inline module notation. It basically just boils down to handling indentation correctly, which is annoying, but shouldn't pose long-term maintainability issues. With indent-based inline module syntax, I'm actually most worried about ease of writing. Remembering and using the correct indentation inside of a file depending on how deep you are into a construct can be annoying.

> Sidenote, maybe there should be some sort of way to define the minimum just version required for a given justfile. I think it would be better for just to fail with a shorter "please upgrade just" message than throw some sort of (syntax)error when features such as this are introduced.

This is also an interesting idea. Although, I don't think it would work in general. Just would need to parse the justfile in order to extract the value of a hypothetical `set just-version := 1.99` setting. Since new versions of just introduce new syntax, which old versions of `just` can't parse, an older version of `just` wouldn't be able to parse a `justfile` with the new syntax.

I can't rule out a `[module]` attribute, but I think having two ways to put recipes into a module probably isn't a good idea. I'm going to close this for now, but I will try to keep it in mind while thinking about inline modules, and will definitely keep the `=` syntax in mind.
