### ISSUE TITLE
Ignore interpolation for comments

### ISSUE THREAD

**Issue by gl-yziquel** [casey/just#2179]
Hi.

I've just been shuffling around some build instructions encapsulated in my justfiles. And commented out one such build instruction (since the build system of jax has been in flux).

```just
#cd jax-{{TAG}} && bazelisk run --verbose-failure=true //jaxlib/tools:build_wheel -- --output_path=dist --cpu=x86_64
```

just then told me the following:

```console
error: Variable `TAG` not defined
```

So, basically, it tried to interpolate the TAG value in the comment. I believe this is a situation where you should opt out of interpolation.

Of course, this depends whether or not the comment is a comment for the shell, or a comment for just. It seems to be a comment for the shell, in which case, well, I would understand just not being aware of what is a comment for the shell.

Nonetheless, the ergonomics of it seems suboptimal: I'd like to wildly refactor my build instructions without having just complaining about failing to interpolate my comments...

EDIT: It can be fixed by putting the # as the first element of the line and not putting it after the tab. But, still, it feels wrong.

**Comment by laniakea64** [comment]
By default it's still an arbitrary line for the shell, so interpolation would be expected.  But shouldn't it become a `just` comment if the justfile does `set ignore-comments`?  Surprisingly, `set ignore-comments` doesn't eliminate this error? :eyes:

**Comment by gl-yziquel** [comment]
I'll give it a shot with `set ignore-comments`. I learn about just every day...

P.S.: feel free to close.

**Comment by laniakea64** [comment]
> I'll give it a shot with `set ignore-comments`. ...
> 
> P.S.: feel free to close.

:confused: To be clear, I _expected_ `set ignore-comments` to be the solution to the error, but it doesn't work for me with latest `just` master:
```
set ignore-comments

foo:
	echo recipe
	#echo {{not_an_interpolation}}
	echo recipe
```

```
error: Variable `not_an_interpolation` not defined
 ——▶ justfile:5:10
  │
5 │     #echo {{not_an_interpolation}}
  │             ^^^^^^^^^^^^^^^^^^^^
```

So I would wonder if this is a bug?

**Comment by casey** [comment]
It's not quite a bug, I think originally the point of `ignore-comments` was just to not print and execute comment lines, but they would still be parsed and analyzed.

I thought it would be hard also skip analysis (when unknown variable errors are raised) but it turned out to be pretty straightforward. As of #2180, comments are now parsed but not analyzed when `ignore-comments` is set. Since they're parsed, they need to be valid *syntax*, but you won't get unknown variable errors anymore.
