### ISSUE TITLE
feat: Add command-line option for unsorting groups

### ISSUE THREAD

**Issue by RachaelAva1024** [casey/just#2181]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

- ---

Let's suppose you have a justfile where the following 3 recipes are declared in this order from top to bottom:

* build
* run
* clean

If you run `just --list`, you get a list like this:

```
Available recipes:
    build
    clean
    run
```

The resulting output is sorted alphabetically, and in my opinion, it looks silly to have 'clean' in between 'build' and 'run'.

If you instead run `just --list --unsorted`, you get a list like this:

```
Available recipes:
    build
    run
    clean
```

That looks much better to me. Now let's suppose you have a justfile where you have multiple build, run and clean recipes for different things. Logically, you would group them together into 3 distinct groups. In this instance, this new justfile would have the following 8 recipes with their assigned groups declared in this order:

### build

* build-debug
* build-release
* build-all

### run

* run-debug
* run-release

### clean

* clean-debug
* clean-release
* clean-all

Now if we run `just --list --unsorted`, the recipes themselves are unsorted, but the groups aren't. You now get a list that looks like this:

```
Available recipes:

    [build]
    build-debug
    build-release
    build-all

    [clean]
    clean-debug
    clean-release
    clean-all

    [run]
    run-debug
    run-release

```

A command-line option like `--unsorted-groups` would be a nice feature to have to complement the existing `--unsorted` option. Additionally, the unsorted option uses the `-u` shorthand, so it would make sense the `-U` be the shorthand for the unsorted groups option.

The above examples may not be the best examples for this use case, but I believe that the option to unsort groups in addition to unsorting recipes (or even without unsorting recipes) would be useful to have, especially when making justfiles that use the `default` recipe to display all available recipes to run.

- ---
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE8IaBC0J6MzIZHrar6LmBDkbPqa4FAmZ2HDsACgkQ6LmBDkbP
qa74+g//X6lWate9zuHK1ZjjY+rPRlvSVOYx5sskA1blUVxwBzF6mTJAvykDRRP2
7evuALY3K4qo1pt9Fvxteng6SGEEXDOQgkDWIVN5ycozh6gQFv+w8J9/7KEcZu/g
U5RKmFjZDpnFSAwopM/aLJ5CWvfJqJv1VueECECjE9HqsZTk7w/rjHWllamcHZHb
1T8kKxdoyQvJvVELlApV1jwFL0gX9nI5ns3feER7lM5bXUJnhYBuYw/B5a5BvoUn
GpjrVZTgYEhMVIrNRLYLu0yzhP2qKtiTKwHD84uHPKMti9thVAU7YlO5gS741Rx9
joiw1H/r+drl4UIOjDi3Ec66wDitb/H540vShFeM1xoqeTIT6aI7RUi5as0rLzb4
mQQ1C8PON3dHqR34KSLTjmDmwTGCKCkD9LPAW6EEkBp1dPjR1QPgTknDhynjpKmu
yiRXUNKOHuC3pCQA45GyWNeZkEBq4VqW++IwnOYkjFt/uN7UIhMfxTpP2U5059CQ
Var3rwAXWvizbnVDzzu8vIbwszKzl2Y6fx8xFqlIhgHTuEDJ+F+xtmiKrGIMulmH
9vmF0sN8CqnjwzGSkcVhNThznH97z1WSU+JUFQNcbP+6yqmeSAYNKWiAEsyRlH6/
6ZZU1u37IFgJkdeDOSmq3lZ+npc9WtvOAYLBU3pVJpUnDprYTOw=
=vs7Q
-----END PGP SIGNATURE-----

**Comment by laniakea64** [comment]
In latest `just` pre-release, `--unsorted` already works the way you're seeking.  With this justfile:
```
[group:"build"]
build-debug:
[group:"build"]
build-release:
[group:"build"]
build-all:

[group:"run"]
run-debug:
[group:"run"]
run-release:

[group:"clean"]
clean-debug:
[group:"clean"]
clean-release:
[group:"clean"]
clean-all:
```

I get:
```
$ just --list --unsorted
Available recipes:
    [build]
    build-debug
    build-release
    build-all

    [run]
    run-debug
    run-release

    [clean]
    clean-debug
    clean-release
    clean-all
```

**Comment by casey** [comment]
@laniakea64 is correct, this should work how you want in the next release.
