### ISSUE TITLE
Macro feature similar to make

### ISSUE THREAD

**Issue by happysalada** [casey/just#2182]
Hi, thank you for making this !

I was looking for a macro feature just like in make to be able to create tasks based on some arguments.

Maybe there is a different way to do that with just ?

For example say i have three environments dev qa and prod and two components frontend and backend
I would like to generate one task for each of the combinations so something like
Deploy_frontend_dev
Deploy_frontend_qa
Deploy_frontend_prod
...

I know you can do this with arguments, but i havent found a way to constrain the arguments to a certain set.
I want exactly those tasks to be available and i dont want any other wrong possible inputs to work.

Is this possible currently ? Maybe i just missed this in the docs ?

**Comment by casey** [comment]
I personally do this just by making recipes for each combination a recipe:

```just
deploy-frontend-dev: (deploy "frontend" "dev")
deploy-frontend-prod: (deploy "frontend" "prod")
deploy-frontend-qa: (deploy "frontend" "qa")
deploy-backend-dev: (deploy "backend" "dev")
deploy-backend-prod: (deploy "backend" "prod")
deploy-backend-qa: (deploy "backend" "qa")

deploy component env:
```

Or:

```just
deploy-frontend-dev: (deploy-frontend "dev")
deploy-frontend-prod: (deploy-frontend "prod")
deploy-frontend-qa: (deploy-frontend "qa")
deploy-backend-dev: (deploy-backend "dev")
deploy-backend-prod: (deploy-backend "prod")
deploy-backend-qa: (deploy-backend "qa")

deploy-frontend env:
deploy-backend env:
```

You could also make the `deploy` recipes private, so users don't accidentally use them directly:

```just
# with attribute
[private]
deploy component env:

# with underscore
_deploy component env:
```

Not the most satisfying answer!

There are a couple issues covering this, one for enums #857 and another one which I can't find about validating arguments up front. They're tricky though, so who knows if they'll get done!
