### ISSUE TITLE
manual: modules are introduced before declared

### ISSUE THREAD

**Issue by bukowa** [casey/just#2186]
Hey!

While reading manual: [chapter 24](https://just.systems/man/en/chapter_24.html) it states:
```
Recipes in submodules can be listed with just --list PATH, where PATH is a space- or ::-separated module path:
```

But modules are introduced in chapter [chapter 56](https://just.systems/man/en/chapter_56.html) and manual states:
```
...you’ll need to use the --unstable flag, or set the JUST_UNSTABLE environment variable to use them.
```

So it's a bit inconsistent and makes me wonder what `modules` are for 32 chapters! 😃

**Comment by casey** [comment]
Seems reasonable to me! I added a link to the modules chapter in chapter 24.
