### ISSUE TITLE
windows: `just` slower with default target

### ISSUE THREAD

**Issue by bukowa** [casey/just#2189]
### Discussed in https://github.com/casey/just/discussions/2187

<div type='discussions-op-text'>

<sup>Originally posted by **bukowa** June 25, 2024</sup>
Hey I wonder why is one slower than the other?
This is with this short `justfile` - the more recipes I have the slower it is.

```justfile
# default target
_:
    @just --list
```

```bash
$ time just
Available recipes:

real    0m0.044s
user    0m0.000s
sys     0m0.000s

````
```bash
$ time just --list
Available recipes:

real    0m0.017s
user    0m0.000s
sys     0m0.000s

````
</div>

Some interesting segmentation faults:
https://gist.github.com/bukowa/2c0b035c23f1c4c66ec2524962a7e81c

This leads to https://github.com/casey/just/issues/2188
And it's probably because of this difference ( `mingw64` provided with `git` for `windows`; no idea what happens here)

**Comment by casey** [comment]
This:

```
_:
    @just --list
```

Causes just to invoke itself as a subprocess, whereas `just --list` doesn't need to invoke a subprocess, so the slowdown is expected.

**Comment by bukowa** [comment]
> This:
> 
> ```
> _:
>     @just --list
> ```
> 
> Causes just to invoke itself as a subprocess, whereas `just --list` doesn't need to invoke a subprocess, so the slowdown is expected.

Is that process exception somehow related to this ?
I checked on 2 PC's

**Comment by casey** [comment]
> Is that process exception somehow related to this ? I checked on 2 PC's

I'm not  sure. Did `just` fail? We aren't doing much weird, so I'm not sure if that's an issue with `just`, or just something weird with Windows.

**Comment by bukowa** [comment]
> > Is that process exception somehow related to this ? I checked on 2 PC's
> 
> I'm not sure. Did `just` fail? We aren't doing much weird, so I'm not sure if that's an issue with `just`, or just something weird with Windows.

Ok - I understand - it's just hard to get any interest in `Windows` related issues 😆 
Ill check this out in my free time. Thanks

**Comment by casey** [comment]
I definitely want to support Windows as best as possible, unfortunately I don't have access to a Windows development machine, and Windows VMs are super annoying to run. With the exceptions you're seeing, I'm wondering if they're actually an issue, since they don't seem to cause any user facing problems, or if they're just an artifact of strace reporting, like they just happen when a thread is stopped, or something like that. For example, what does the trace look like of a Rust hello world binary?

**Comment by bukowa** [comment]
> I definitely want to support Windows as best as possible, unfortunately I don't have access to a Windows development

```bash
$ strace ./target/release/untitled.exe 
--- Process 20424 created
--- Process 20424 loaded C:\Windows\System32\ntdll.dll at 00007ffcd6f30000
--- Process 20424 loaded C:\Windows\System32\kernel32.dll at 00007ffcd5d50000
--- Process 20424 loaded C:\Windows\System32\KernelBase.dll at 00007ffcd45f0000
--- Process 20424 loaded C:\Windows\System32\apphelp.dll at 00007ffcd1570000
--- Process 20424 thread 50012 created
--- Process 20424 loaded C:\Windows\System32\ucrtbase.dll at 00007ffcd4d40000
--- Process 20424 thread 39040 created
--- Process 20424 loaded C:\Windows\System32\vcruntime140.dll at 00007ffcce950000
--- Process 20424 thread 26060 created
Hello, world!
--- Process 20424 loaded C:\Windows\System32\kernel.appcore.dll at 00007ffcd2450000
--- Process 20424 loaded C:\Windows\System32\msvcrt.dll at 00007ffcd6600000
--- Process 20424 loaded C:\Windows\System32\rpcrt4.dll at 00007ffcd5430000
--- Process 20424 thread 39040 exited with status 0x0
--- Process 20424 thread 26060 exited with status 0x0
--- Process 20424 thread 50012 exited with status 0x0
--- Process 20424 exited with status 0x0
```

Heres full gist to the just once again: https://gist.github.com/bukowa/2c0b035c23f1c4c66ec2524962a7e81c

**Comment by bukowa** [comment]
This hello world is much better, it's causing the same error:
https://gist.github.com/bukowa/a9997b770b9fbc6167b6f908949193ff

```bash
fn main() {
    std::process::Command::new("sh")
        .spawn()
        .expect("failed to execute process");
}
```
This code is what's triggering the segmentation fault.

When I run `strace sh.exe`, I encounter the same error.

I understand your point now. I apologize for the confusion; it seems the issue is not directly related to what I were suggesting.

**Comment by casey** [comment]
No worries at all!
