### ISSUE TITLE
Comments not allowed in module usage.

### ISSUE THREAD

**Issue by Spatenheinz** [casey/just#2200]
This fails parsing

```
mod foo #breaking comment
```

I dont see anything that should be problematic with this approach?
Specifically I can see that modules are only matched when:

```
          Some(Keyword::Mod)
            if self.next_are(&[Identifier, Identifier, StringToken])
              || self.next_are(&[Identifier, Identifier, Identifier, StringToken])
              || self.next_are(&[Identifier, Identifier, Eof])
              || self.next_are(&[Identifier, Identifier, Eol])
              || self.next_are(&[Identifier, QuestionMark]) =>
```

Is there a reason to explicitly match on `Eof` and `Eol`?
Also what does the triple indentifier, StringToken match?

**Comment by casey** [comment]
Good catch! Fixed in #2201.

`Identifier, Identifier, Identifier, StringToken` catches this case, which uses a shell-expanded string:

```just
mod foo x"$HELLO/bar.just"
```
