### ISSUE TITLE
Neovim syntax highlighting not working when adding Documentation Comment

### ISSUE THREAD

**Issue by vincentvdk** [casey/just#2224]
When adding a Documentation Comment in neovim, the syntax highlighting breaks for everything below.

Example

![image](https://github.com/casey/just/assets/676958/53c92d82-1961-4b76-8046-118ae86470a2)

**Comment by casey** [comment]
Which syntax highlighting plugin are you using?

**Comment by laniakea64** [comment]
This looks similar to https://github.com/NoahTheDuke/vim-just/issues/97 where the culprit turned out to be `nvim-treesitter` / `tree-sitter-just`.  But https://github.com/IndianBoy42/tree-sitter-just/issues/164 was closed via PR, so try updating to the latest version?

**Comment by vincentvdk** [comment]
Updating both `Treesitter` and `tree-sitter-just` fixed it. Thanks!
