### ISSUE TITLE
[feature request] user-defined functions

### ISSUE THREAD

**Issue by gyreas** [casey/just#2233]
The title says it all, really. 

Anyway, I'm not aware of a way to combine Just functions in complex ways, and make them reusable without copy-pastas. A user-defined function is a combination of Just functions (and/or other user-defined functions) bound to a name and reusable anywhere regular functions are allowed.

Since modules are supported now, one can build a library of functions that can re-exported etc.

One syntax for this could be:
```
just

newfunc/arity = function({{1}}) / function ({{2}}, {{1}}

recipe-name:
  echo {{ newfunc(arg1,arg2,...) }}

```
Since variables use `variable-name := value` , functions can use `function-name/arity = body`.

`arity` is the number of arguments, and `newfunc` is the function name

Is this a good idea?

**Comment by casey** [comment]
This is definitely a good idea! There's actually an open issue for this, although the title wasn't clear, so I changed it: #1059.

I started working on this, but only the very beginnings of it, and it's pretty tricky.

**Comment by casey** [comment]
The syntax I'm thinking uses named arguments:

foo(bar, baz) := bar / baz
