### ISSUE TITLE
Cannot get Shell-expanded strings working but falls short for me by design anyway

### ISSUE THREAD

**Issue by hammer2j2** [casey/just#2240]
Like many have requested, I am looking for a tool that is configurable globally per environment.    
  
I have just v1.30 on Mac OS arm M1  
  
As in [this discussion](https://github.com/casey/just/discussions/1972#discussioncomment-9310718) this justfile fails:

```
ENV := "dev"
set dotenv-required
set dotenv-filename := "{{ENV}}.env"
```

`error: Dotenv file not found`

I see that implementation wasn't taken, now, still opting for `x${VAR}` - but the ask was for just vars and there is an important distinction.

One issue I am attempting to solve with `just` is to get away from explicitly handling environment variables.  
Having them in a include file is fine, but I absolutely do not want to have to define them in my shell, before executing `just` nor do I want to do funny things with them at all like `MYENV=dev just test`

What I want to do with a command line is this:  
  
`just test dev`

or at least

`just test -e dev`  
 

Inside the just file I don't mind environment variables - I just don't want to pollute my shell, and then accidentally burn down prod one day b/c of an env var left about.

There is a real economy in the expressive form I am looking for which `just` is ever so close to supporting, but `just` doesn't.  
 

Thanks.

**Comment by casey** [comment]
Can you use `unexport` to avoid polluting sub-shell environments?

```just
unexport ENV
```

**Comment by hammer2j2** [comment]
Thanks for your response. Well, any interaction manually managing shell vars is what I am avoiding for the same reason: it means humans making mistakes from settings which are out of sight in a terminal session on their machine. 

We can assume we already have indicated what env we intend with [afeldkamp's](https://github.com/afeldkamp) example `current_project := gcloud config get project` which is quite deliberately delegating the decision - this avoids duplicate and potentially contradictory paths.  

I understand the `just` utility hasn't been designed with "basically" global variables in mind so it's not a simple ask. This is why I mentioned supporting user defined flags as another way to avoid requiring shell variable handling outside of the `justfile` such as `just test -e dev`. Perhaps something as simple as only adding `-e <envString>` support would satisfy my requirements nicely - although it doesn't satisfy the case of delegation - that's of secondary importance from my POV. Thanks.

**Comment by casey** [comment]
Oh, one other thing, you can override just variables on the command line by putting the overrides after `just` but before any arguments:

```just
just ENV=dev test
```

In the above command, `ENV` is a `just` variable and not an environment variable. Does that work?

**Comment by hammer2j2** [comment]
Thanks for your reply.  I don't see how I can load an environment file globally using that: `x'$ENV'.sh` \<-- `error: Shell expansion failed: error looking key 'ENV' up: environment variable not found` 

[This](https://github.com/casey/just/discussions/1972#discussioncomment-9310718) example by afeldkamp is an example of what I am looking for.  It feels like to me that `just variables` are not first class citizens and this leads to reliance on env variables.  And yet, I can't turn this ENV variable into something useful because  `set dotenv-filename` won't work with just vars as in the below

```
set dotenv-filename := "{{ENV}}.env".  # error
```

_Maybe_ I could call another recipe in the dependency of _every_ recipe to set up variables for global env settings... IDK if that would work.  Overall, variable scope limitations are coming up against `just var` vs `env var` quirkyness, meets up against variable file loading limitation, meets command line argument passing limitations, and something basic like this IMHO shouldn't be that hard in what seems otherwise a very useful tool.    
\- What about support for sub-recipies to allow variable sharing?  
\- What about supporting a getopts style of variable passing on the command line?  (with an option to allow them to be environment vars OR just vars via setting).  
Thanks.

**Comment by casey** [comment]
Ah, sorry, you're right. Yah, just environment variables won't work there.

Can you do `just -E dev.env test` to load the dev environment? This avoids needing to set an environment variable, and is very close to `just test -e dev` which you suggested above.

**Comment by hammer2j2** [comment]
Thanks for help with a good option; I will try it.   
I'm content to close this issue, but, overall would like to point out the following.  
\- Due to the name of this utility, there is an implied lean in to natural language - can that be denied? However, due to the limitations of handling command line options, positional parameters and env vars vs justvars etc.. (all things mentioned above and by others), command line constructs that look and feel natural and memorable are few and far between in reality.  Your latest suggestion is a case in point,  `just -E dev.env test` is not at all natural, and really can't compare to `just test -e dev.` So, I may have missed the point, but, the expectation that I wouldn't need to write fancy shell wrappers to avoid awkward command lines seeped into my head when I wanted to evaluate this tool.  
Thanks for your time.
