### ISSUE TITLE
[Feature Request] `just global init-rust`; an ability to define global `Justfile` that will run commands anywhere on your machine.

### ISSUE THREAD

**Issue by jymchng** [casey/just#2258]
As described in title, imagine you want to be able to run arbitrary commands in your terminal to e.g. generate a new Rust repository from a template, etc, a command like `just global init-rust` with the script defined in the 'global' `Justfile`, perhaps located at the `~/` or `${HOME}` directory.

**Comment by laniakea64** [comment]
Like this? - https://just.systems/man/en/chapter_73.html#global-justfile

**Comment by casey** [comment]
I think this is covered by global justfiles, see the above link. In short: `just -g init-rust`.
