### ISSUE TITLE
Document an argument starting with `-` can be supplied using the `--` separator

### ISSUE THREAD

**Issue by naufraghi** [casey/just#227]
Not a new thing, but can be useful to note as an example that a recipe like:

```
fix zipfile extra:
   unzip {{extra}} "{{zipfile}}"
```

Can be used as `just fix some.zip -- -FF`

**Comment by casey** [comment]
Whoops, this works as of #219, but I never published it to crates.io. Just published the latest version to crates.io, so it should work without `--`. Please re-open if it doesn't!
