### ISSUE TITLE
Set default working dir for the whole justfile

### ISSUE THREAD

**Issue by nyurik** [casey/just#2273]
Frequently I need to place justfile in a different location from where the default working dir should be. Would it be possible to have some global `set` command to modify the working directory, either for the current justfile, or possibly for all of the included ones as well (unless they override it?). The multiple justfiles could in theory be solved with modules, so this is a lower priority.

**Comment by casey** [comment]
I think this would be pretty useful, and not super complicated. Currently, settings are not shared between modules, so adding some kind of setting sharing would be something for another PR. `set working-directory := …` would be pretty easy to add. Marking as good first issue in case someone wants to take a crack at it.

**Comment by nyurik** [comment]
I hacked together an implementation  in #2283, but it is still missing the actual workdir setting. May need some guidance here.

**Comment by casey** [comment]
Implemented in #2283.
