### ISSUE TITLE
Command line flag to exit without error if recipe not found

### ISSUE THREAD

**Issue by sergei-dyshel** [casey/just#2275]
In some cases it's helpful to run `just` so that it silently exists with code 0 if requested recipe is not found.  Possible usecase: running same recipe in multiple directories (e.g. with GNU parallel) when in some of them the recipe is not defined, in which case we just want to skip the dir.

It is currently possible to do with NPM scripts, for example `npm run --ws --if-present <script>` will run *script* in every workspace where script is defined.

**Comment by casey** [comment]
This seems perfectly reasonable to me! Marking as good first issue in case anyone wants to take a crack at it.

**Comment by walla** [comment]
i want to try
