### ISSUE TITLE
Add missing or (if it's there) improve module information in documentation

### ISSUE THREAD

**Issue by Thermatix** [casey/just#2277]
I'm trying to figure things out and I'm struggling to find the following information

 * How to refer to module tasks from other modules  (for task dependencies)
 * How to refer to tasks in the parent file (I.e. super::task_name) 
 * sub-module settings
 * Variables defined in other files or in parent (or via import statements)
There was a few other's but I can't recall now.

Some of the things are mentioned in Modules stabilization tracking issue #929, some of them are mentioned at the top but with no actual "This is how you do this" under each item (nor I can't find it within the thread itself).

Also for the top two I did find this: [Dependency from a parent/child justfile](https://github.com/casey/just/issues/1550)

P.s.

I get syntax errors when I try something like `task: super::task`

**Comment by casey** [comment]
Modules are definitely incomplete at the moment. See #2252, and feel free to comment there or open individual issues if something is missing.
