### ISSUE TITLE
Hide recipe from the `--list` and `--summary` commands

### ISSUE THREAD

**Issue by cledoux** [casey/just#228]
Is it possible to mark certain recipes as private, such that `just --list` and `just --summary` does not display them?

I often use "helper" recipes that would simply clutter the output of list and summary.

**Comment by TeddyDD** [comment]
@casey  I like your idea. Alternatively I propose to hide recipes that starts with dot `.private:`

**Comment by casey** [comment]
@TeddyDD: I think I find dots more aesthetically pleasing. However, dots are not currently allowed in names, and I have vague thoughts about using them in the future for things like property access, or maybe special kinds of recipes.

Underscores are a little less attractive, but they're already used for private names in python and javascript, so we would be taking advantage of an existing convention. We would be breaking existing justfiles that use names that start with an underscore, but I think they're probably rare, so it's not a serious breakage.

@cledoux Are the recipes that you make private ever called from outside, or only within the justfile?

**Comment by cledoux** [comment]
@casey  Here's the basic structure of a Justfile I was writing today that used helper recipes. An analysis system we've built has four steps to testing it: setup the environment, run the analysis on test data, verify the output, clean up the test environment.

```
test: test-clean
    just test-setup
    just test-analyze
    just test-verify
    just test-clean

test-clean:
    rm -rf test-directory

test-setup:
    mkdir -p test-directory
    # Some custom setup code

test-analyze:
    # Run system on test data

test-verify:
    # Verify that the output of the analysis was as expected.
```

I sometimes call the `test-cleanup` recipe manually, but other than that the recipes are only called from within the justfile. I could, if needed, define my test-cleanup as a public recipe and the other helpers as private.  

In general, I think of my helper recipes as private functions in python.  I don't intend for anyone to use them directly, but if you know what you are doing and really want to use them, I'm not going to try and stop you.

It's probably worth mentioning that the Justfiles I write are used by our entire dev team.  Part of the reason I want to hide the helper recipes is because I want to make it clear that these recipes are not meant to be run directly. A naming convention is a decent enough workaround, but it does clutter the output of the help commands.

As per the naming convention, we are a python shop, so underscores make perfect sense for us. :smile:
