### ISSUE TITLE
`set working-directory` should create that dir if missing

### ISSUE THREAD

**Issue by nyurik** [casey/just#2293]
Consider a "wrapping" scenario: some big git repo does not want to introduce `justfile`, but some developers really want to have it.  So they create a small repo that only contains `justfile`, and in there they set the working dir and init it (real life [example](https://github.com/nyurik/just-maplibre-native))

```just
# does not work -- repodir does not yet exist
set working-directory := 'repodir'

init:
  # does not work because by now, repodir would somehow exist, and git clone would fail
  git clone ...
```

The issue with the above is that if `repodir` does not yet exist, it will fail because `shell` won't be able to start in a missing directory.  If `repodir` does exist, `git clone` should be skipped.

The first problem could have been fixed if the `set` command was a regular sequence operation, and because it requires a string:

```just
# does not work because `set` is executed first
_ := `mkdir -p repodir`
set working-directory := 'repodir'

# does not work because `set` takes a literal string
set working-directory := `mkdir -p repodir && echo "repodir"`

# in theory this COULD work if we have a `mkdir` function?  Possibly `mkdir` could even return that same string?
set working-directory := mkdir('repodir') and 'repodir'
```

The `git clone` could be solved with some check to see if the dir is empty, and then run a `rm repodir && git clone ...`

**Comment by laniakea64** [comment]
The proposed ideas won't help with the stated problem and trying to use them that way would be a mess.  Also, they would break backwards compatibility.

A smoother solution that quick test indicates would already work in current `just` would be something like
```
set working-directory := 'repodir'

[no-cd]
init:
    cd {{quote(justfile_directory())}} && if test ! -d repodir;then git clone ...;fi
```

**Comment by nyurik** [comment]
@laniakea64 brilliant idea, thanks!   Totally solves my problem.

Now the only problem left is the un-readable error message.  I think just should check if working directory already exists before running the recipe (unless it has `[no-cd]`) -- this way users will get much better error than this one:

```
error: Recipe ... could not be run because just could not find the shell: No such file or directory (os error 2)
```

**Comment by casey** [comment]
Another problem with creating the working directory is that it would mask typos, i.e., the working directory does exist, but you misspelled it in the justfile, `just` would create it and continue instead of erroring. I do think improving the error message is a good idea though, feel free to create a separate issue!
