### ISSUE TITLE
Incorrect Circular dependency

### ISSUE THREAD

**Issue by Spatenheinz** [casey/just#2301]
Consider:

```
#Justfile
mod a
mod b

# a.just
import 'lib.just'

a: _precompile
  @echo "a"
  
# b.just
import 'lib.just'

b: _precompile
  @echo "b"

# lib.just

_precompile:
    @echo "Preparing"
```

In this example we have the following tree of dependencies:

                Justfile
             /             \
          a.just        b.just
         /                    \
      lib.just             lib.just
      
This is however incorrectly tagged as a circular dependency:

```
$ just --unstable a::a
error: Import `<path>/lib.just` in `<path>/a.just` is circular
```

**Comment by casey** [comment]
I wasn't able to reproduce this, and I think this was fixed in #2065. Can you try updating `just` to version 1.27 or later?
