### ISSUE TITLE
failed to select a version for `env_logger` which could resolve this conflict

### ISSUE THREAD

**Issue by lantianlaoli** [casey/just#2303]
```
cxp@CXPfromR9000P:~/solana_learn/openbook-v2$ cargo install just --force
    Updating crates.io index
  Installing just v1.34.0
    Updating crates.io index
error: failed to compile `just v1.34.0`, intermediate artifacts can be found at `/tmp/cargo-installhep2UA`

Caused by:
  failed to select a version for `env_logger`.
      ... required by package `just v1.34.0`
  versions that meet the requirements `^0.11.0` are: 0.11.5, 0.11.4, 0.11.3, 0.11.2, 0.11.1, 0.11.0

  the package `just` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
   It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


  failed to select a version for `env_logger` which could resolve this conflict
```

**Comment by casey** [comment]
I'm not able to reproduce this. What version of Rust are you using?

**Comment by lantianlaoli** [comment]
It's fail on `cargo 1.70.0 (ec8a8a0ca 2023-04-25)`, but success on `cargo 1.80.0 (376290515 2024-07-16)`

**Comment by laniakea64** [comment]
This has happened before -
https://github.com/casey/just/issues/1898
https://github.com/casey/just/issues/1980

In the case of this issue, `just` does declare it's supposed to work with Rust/Cargo 1.70 -
https://github.com/casey/just/blob/f9c2479af8f8e676f3caa20c8c8c6ef408dfda48/Cargo.toml#L15
But `just` [uses Cargo.toml `[lints]`](https://github.com/casey/just/blob/f9c2479af8f8e676f3caa20c8c8c6ef408dfda48/Cargo.toml#L63), which [requires Rust/Cargo 1.74](https://releases.rs/docs/1.74.0/#cargo), and https://just.systems/man/en/chapter_84.html says MSRV is actually current stable Rust, i.e. currently 1.80.0.

I can reproduce this issue with Rust 1.70.0, but not with Rust 1.74.1.  Should the MSRV declared in Cargo.toml be updated?

Although, does `just` need to depend on `env_logger` and `log`?  AFAICT it's only used in two places:
https://github.com/casey/just/blob/f9c2479af8f8e676f3caa20c8c8c6ef408dfda48/src/config.rs#L754
https://github.com/casey/just/blob/f9c2479af8f8e676f3caa20c8c8c6ef408dfda48/src/run.rs#L19

**Comment by casey** [comment]
> Although, does just need to depend on env_logger and log? AFAICT it's only used in two places:

Good point! I removed logging in #2305.

I also bumped the MSRV to 1.74 in #2306, and confirmed that it builds with 1.74, so I think this can be closed.
