### ISSUE TITLE
Run in existing shell OR create interactive child shell

### ISSUE THREAD

**Issue by fastfedora** [casey/just#2304]
It would be useful to run a command within the existing shell and/or to create an interactive child shell. 

Specifically, I'm trying to create the following recipe for Python, which switches my environment into a specific virtual environment:

```
activate:
  source venv/bin/activate
```

However, because Just is running commands in their own shell instance, this executes the activation in that shell instance, then exists that shell.

If there were a way to tell Just to execute the command in the existing shell, this would operate the same as a normal alias, which is the ideal. If that is not possible, it would be nice if the new shell instance used to run the command could be made into an interactive child shell instance, which would achieve nearly the same effect.

**Comment by laniakea64** [comment]
> If there were a way to tell Just to execute the command in the existing shell, this would operate the same as a normal alias, which is the ideal. 

This is not possible, the closest you can get would be something like https://github.com/casey/just/issues/1957#issuecomment-1992000723

> If that is not possible, it would be nice if the new shell instance used to run the command could be made into an interactive child shell instance, which would achieve nearly the same effect.

Do any of the ideas in https://unix.stackexchange.com/questions/123103/how-to-keep-bash-running-after-command-execution work for your case?

**Comment by fastfedora** [comment]
It looks like the follow works:

```
activate:
  bash -i <<< 'source venv/bin/activate; exec </dev/tty'
```

However, I can only get it to work for `bash`, not `zsh`. If there's ever a way to build the functionality in, that would be ideal. But for now this is a good enough workaround.

**Comment by casey** [comment]
This is a longstanding request, and unfortunately, I don't think there's a good way to support this, since doing so would probably require different commands for each shell, and `just` tries to be shell-agnostic.

**Comment by marvinestreet** [comment]
> It looks like the follow works:
> 
> ```
> activate:
>   bash -i <<< 'source venv/bin/activate; exec </dev/tty'
> ```
> 
> However, I can only get it to work for `bash`, not `zsh`. If there's ever a way to build the functionality in, that would be ideal. But for now this is a good enough workaround.

@fastfedora thanks for this, found a way to get this to work in zsh:
```
activate-venv:
  zsh -is <<< 'source .venv/bin/activate; exec </dev/tty'
```
I also found this oh-my-zsh plugin: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/python#virtual-environments

**Comment by fastfedora** [comment]
> @fastfedora thanks for this, found a way to get this to work in zsh:
> 
> ```
> activate-venv:
>   zsh -is <<< 'source .venv/bin/activate; exec </dev/tty'
> ```

Thanks so much. That works for me too.

> I also found this oh-my-zsh plugin: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/python#virtual-environments

I'll check this out. Thanks!
