### ISSUE TITLE
Trouble loading .env file from path

### ISSUE THREAD

**Issue by samhaaf** [casey/just#2307]
How do you load a dynamic env file?

This is what I'm trying to do:

```
set export

ENV := "dev"

set dotenv-path := "./envs/{{ENV}}.env"
set dotenv-load := true
set dotenv-required := true

ENV_VAR := env('ENV_VAR')

test:
    echo "ENV={{ENV}}"
    echo "ENV_VAR={{ENV_VAR}}"

```

Where my .env file contains:
```
ENV_VAR="Hello World"
```

And the error:
```
error: Dotenv file not found
```

**Comment by casey** [comment]
This is definitely an unfortunate limitation. It's an example of a general issue where arbitrary expressions cannot be used in settings. I opened #2309 to explore relaxing this..
