### ISSUE TITLE
Cannot have a dependencies when using module

### ISSUE THREAD

**Issue by davzucky** [casey/just#2316]
Thank you for Just. I really love it. As my Just file is growing, I would like to break it into modules; however, I'm not able to depend on recipes from other modules.

I'm trying to reuse modules from my main justfile and add them as dependencies. The idea is something like that

``` justfile
# module/foo.just
a:
    @echo  "a"
```

``` justfile
# justfile
mod foo "./module/foo.just"

b: foo::a
    @echo  "b"
```

I tried multiple solutions, like ``` foo::a``` or ```(foo a)```, but I always get an error like that. You can find multiple error outputs below.

```
error: Expected backtick, identifier, '(', ')', '/', or string, but found ':'
 ——▶ justfile:3:8
  │
3 │ c: (foo::a)

error: Expected '&&', comment, end of file, end of line, identifier, or '(', but found string
 ——▶ justfile:3:4
  │
3 │ c: "foo::a"
  │    ^^^^^^^^

error: Unknown start of token:
 ——▶ justfile:3:8
  │
3 │ c: (foo.a)
  │        ^
```

I looked at the test and couldn't see anything that matched it. Is it a known limitation of just today? The main idea is to be able to depend on parametrized module recipes.

**Comment by laniakea64** [comment]
> Is it a known limitation of just today?

Yes.  This is on the list in https://github.com/casey/just/issues/2252

**Comment by davzucky** [comment]
Thank you, @laniakea64, for pointing that out. I didn't find this issue. I will close that one and subscribe to the main one
