### ISSUE TITLE
Publish checksums of release binaries

### ISSUE THREAD

**Issue by twm** [casey/just#2322]
Would you be open to a PR that adds `.sha256sum` files for the GitHub release artifacts? These are useful for detecting a partial or corrupted transfer. For example:

- https://github.com/starship/starship/releases 
- https://github.com/neovim/neovim/releases

Without a checksum or signature the best I can do is check the size of the artifact [in the GitHub API](https://api.github.com/repos/casey/just/releases/168509026/assets), but that won't catch corruption in transit. The checksum is also useful for telling if an already-downloaded artifact is valid.

**Comment by casey** [comment]
Sure, that would be great!

**Comment by twm** [comment]
Fixed in #2323. Thank you @casey! :heart:
