### ISSUE TITLE
Do subsequents of a recipe run "immediately" after the recipe (by specification)?

### ISSUE THREAD

**Issue by donatello** [casey/just#2324]
Suppose I have the following Justfile:
```
a:
    echo "A"

b:
    echo "B"

# `a` runs before `c` and `b` runs after `c`
c: a && b
    echo "C"

d: c
    echo "D"
```

When running `just d`, I see the output sequence "A C B D", which looks good. However, could the output ever be "A C D B"?

According to the "Dependencies" documentation, `b` is only guaranteed to run after `c`, but it is not clear, if `b` could run after `d` and still be considered expected behavior. This may be worth documenting.

**Comment by casey** [comment]
> When running just d, I see the output sequence "A C B D", which looks good. However, could the output ever be "A C D B"?

Nope, for that justfile it will always be `A C D B`. I opened #2326 to clarify this in the readme.
