### ISSUE TITLE
set working-directory := justfile_directory()

### ISSUE THREAD

**Issue by anacrolix** [casey/just#2333]
I can't seem to set the working directory to remain unchanged.

Essentially I want `[no-cd]` to be the default everywhere.

Previously I've achieved this using a shebang with `#!/usr/bin/env -S just --working-directory . --justfile` but this doesn't work if I just invoke `just` in a directory, rather than execute the `justfile` directly.
```
> just -l
error: Expected keyword `x` but found identifier `justfile_directory`
 ——▶ justfile:2:26
  │
2 │ set working-directory := justfile_directory()
  │                          ^^^^^^^^^^^^^^^^^^
```

**Comment by nogweii** [comment]
See #2291 and #2082 for solving this.

**Comment by anacrolix** [comment]
Neither solves the case that you can't set the working directory programmatically for the whole file. You can already set it statically, so it seems odd.

**Comment by casey** [comment]
@anacrolix Yah, this is an unfortunate limitation of how evaluation works. Expressions can run commands, access files, and read environment variables, so how they execute depends on settings, so the value of settings can't be arbitrary expressions. The ultimate solution is probably to allow only expressions which don't depend on settings in setting values, see #2309, but that's a big change.

**Comment by anacrolix** [comment]
Thanks! And thanks for the effort on the great project.

**Comment by casey** [comment]
Of course! Thank you for the kind words ^_^
