### ISSUE TITLE
Color-code `just` groups

### ISSUE THREAD

**Issue by DeeGeeMan** [casey/just#2337]
It will be helpful to color-code the groups in the terminal.

**Comment by casey** [comment]
Thanks for the issue! I'm not sure what kind of color coding you mean. Can you elaborate?

**Comment by DeeGeeMan** [comment]
Adding color to the group title in the console when printing help.

**Comment by casey** [comment]
Seems reasonable to me! I changed group colors in `--list` output to yellow, so they stand out.
