### ISSUE TITLE
Unknown start of token for simple just

### ISSUE THREAD

**Issue by jtlimo** [casey/just#2338]
Hi, it's my first time using Just and I trying to create a simple justfile without success.

Here is my [justfile](https://gist.github.com/jtlimo/4026af50301e6d9d8b7b6a84387cdfcb) in gist to debug;

The error occurs when runs the command just:

```
error: Unknown start of token:
 ——▶ justfile:2:6
  │
2 │ just --list
  │      ^
```

**Comment by casey** [comment]
Hi!

Recipe bodies need to be indented:

```
default:
  just --list
  
hello:
  echo "hello world"

deploy:
  nixos-rebuild switch --flake . --use-remote-sudo

debug:
  nixos-rebuild switch --flake . --use-remote-sudo --show-trace --verbose

up:
  nix flake update
```
