### ISSUE TITLE
"ignore-comments" does not completely ignore commented lines

### ISSUE THREAD

**Issue by eddyg** [casey/just#2339]
Because both Docker and `just` use Go-style templates, it is necessary to escape any occurrences of `{{` to `{{{{` in various recipes that need to use Docker's `--format` option.

I put a comment in the recipe with the same command _without_ escaping the `{{`, with the intention of being able to easily copy the command from the `justfile` and paste it (in a "ready-to-go" state) in to an arbitrary shell for debugging, systems without `just`, etc.

For example:

```bash
set ignore-comments

ls-mounts:
    # docker inspect --format '{{range .Mounts}}{{if .Name}}{{.Name}}{{else}}{{.Source}}{{end}}{{"\n"}}{{end}}' $(docker ps --all --quiet) | grep -v '^$' | sort -u
    docker inspect --format '{{{{range .Mounts}}{{{{if .Name}}{{{{.Name}}{{{{else}}{{{{.Source}}{{{{end}}{{{{"\n"}}{{{{end}}' $(docker ps --all --quiet) | grep -v '^$' | sort -u
```

However, the `{{` in the _commented_ line causes `just` to fail — I have to escape them even though they are in the comment, which defeats my intended purpose.

Any suggestions?

P.S. Thanks for `just`!

**Comment by casey** [comment]
Thanks for the issue! This is definitely annoying, but it would be pretty hard to solve, and might not be worth the complexity. Whether or not `ignore-comments` is turned on can only be determined after parsing, so the `justfile` must be parsable, which includes comments, and unmatched `{{` and invalid syntax in `{{…}}` are both parse errors. So `ignore-comments` is only able to ignore errors that happen after parsing, like unknown variables.

I'll leave this open. A solution might be to defer parsing recipe bodies, but I honestly think the code for that might be so ugly that it won't be worth it.

**Comment by eddyg** [comment]
Thanks for the explanation! I totally understand why this happens now. 🙂 

Would it be possible to have an option to _print_ a recipe "as it it would be executed"? 

That might actually be better, because then it doesn't mean maintaining a _copy_ of the command in a comment.

For example, `just --print ls-mounts` could print the "unescaped" commands in the recipe (perhaps optionally along with any comments), ready for copy-and-pasting?

**Comment by laniakea64** [comment]
See also https://github.com/casey/just/issues/2179

> Would it be possible to have an option to _print_ a recipe "as it it would be executed"?
> 
> That might actually be better, 

`just --dry-run ls-mounts`

**Comment by casey** [comment]
Yah, i think `just --dry-run` might be what you want, give that a shot.

**Comment by eddyg** [comment]
Ah! I don't know how I missed `--dry-run`. 🤦‍♂️

I do indeed think that will be an OK work-around given the previously-explained difficulties of trying to _completely_ ignore comments.

Thanks for the super-quick responses! (I'll leave it up to you if you want to keep this issue open, but completely understand if you want to consider it a "won't fix".)

**Comment by casey** [comment]
Nice, glad that works! I think I'm going to close this. It would be nice to fix it, but the fix would be to delay parsing recipe bodies and store them in an unparsed form, and then parse them later on, which would be super gross.
