### ISSUE TITLE
Contributing guidelines are somewhat easy to miss

### ISSUE THREAD

**Issue by marcaddeo** [casey/just#2346]
I opened two PR's recently (#2342, #2344) before finding out there's actually a contributing guide at the bottom of the `README`.

This happened because I searched the issues for related things about inlining aliases next to recipes in `--list` and saw there were earlier discussions about this. So I decided I'd give it a go, and got it done. Then when opening a PR/Issue for the first time, you're presented with this popup from GitHub:

<img width="453" alt="image" src="https://github.com/user-attachments/assets/9c1dc71d-5418-4422-8e20-a9362df28ea7">

The [contributing guidelines](https://github.com/casey/just/blob/6e2b98938f11c4fc8ec829871da0a95f13b493ef/CONTRIBUTING.md) link there goes to the repositories [CONTRIBUTING.md](https://github.com/casey/just/blob/6e2b98938f11c4fc8ec829871da0a95f13b493ef/CONTRIBUTING.md) which only briefly talks about licensing. So I didn't realize there were actual guidelines for contributing until today when I was just looking through issues and saw a reference to it.

Anyway, with not knowing the guidelines existed I opened #2344 which may have been better suited to start as an issue for discussion.

Maybe it would make sense to update the `CONTRIBUTING.md` file to have a link to the `README` section that includes the guidelines, or have them in `CONTRIBUTING.md` and have the `README` link to it.

**Comment by casey** [comment]
Good idea! I just merged #2348 which links to the readme from `CONTRIBUTING.md`.
