### ISSUE TITLE
Possible bug when passing variadic parameter variables to recipe dependencies

### ISSUE THREAD

**Issue by marcaddeo** [casey/just#2354]
In #2342 there was discussion of an alternative use-case for aliases where aliases were being used as the "main" descriptive name for the recipe and the recipe name was meant for internal use. Looking through the reasoning in #1725 and the discussion in [#1302](https://github.com/casey/just/discussions/1302#discussioncomment-6802368), it seems to me this use-case appeared due to a possible bug?

```just
set positional-arguments

main-recipe *FLAGS:
  echo "$1"
  echo "$2"
  echo "$3"

r *FLAGS: (main-recipe FLAGS)

test1: (main-recipe '123' '456' '789')
test2: (r '123' '456' '789')
```

Given this Justfile, `test1` will give the expected results while `test2` will throw an error because `FLAGS` is parsed as a variable and evaluated to a single string `123 456 789` which cases only the `$1` positional argument to be set.

Is this a desirable/intended behavior? Or should dependency arguments that are variables for a variadic parameter get split back into individual strings before getting passed to the dependent recipe?

**Comment by laniakea64** [comment]
It's working as intended.  The current proposed solution for this use case is https://github.com/casey/just/issues/1988#issuecomment-2111522463

**Comment by casey** [comment]
Yah, unfortunately this is working badly as intended. Variadic arguments are immediately space-joined, which is why they exhibit this behavior.
