### ISSUE TITLE
Are there any youtube videos about just?

### ISSUE THREAD

**Issue by chicks-net** [casey/just#2357]
I've searched for youtube videos about `just` in a variety of ways, but I keep coming up empty handed.  My motivation is that I've been considering making a video about `just` and i wanted to see what has been done already.  I'm hoping the name of the tool is just foiling my searches and you've heard of something, but if not I'll try extra hard to make something worthy.  📹

**Comment by casey** [comment]
That would be dope! This is the only one I know of:

https://www.youtube.com/watch?v=hgNN2wOE7lc

`just` is definitely sub-optimal from an SEO perspective 😂

**Comment by chicks-net** [comment]
Perfect, that's exactly what I was looking for.

**Comment by chicks-net** [comment]
[Using just to speed development](https://youtu.be/m7ZCnGnYyvs?si=QNvUZJiGo20FVdnD) was what I came up with.

Thanks again for developing this excellent tool and answering my earlier question. 🙇

**Comment by casey** [comment]
Very nice! Just tweeted out the video: https://x.com/rodarmor/status/1840856340450943480

**Comment by casey** [comment]
The name of `just` used to be `j`, so searchability used to be even worse in the past 😂
