### ISSUE TITLE
Allow escaping arbitrary characters in double-quoted strings

### ISSUE THREAD

**Issue by laniakea64** [casey/just#2359]
Currently `just` strings delimited with `" "` or `""" """` only support escaping a limited set of characters - https://just.systems/man/en/chapter_30.html

Most other languages have a syntax for escaping arbitrary Unicode characters.  Having such syntax in `just` would make some justfiles easier to work with:
 - Not all valid Unicode characters are printable.  And even within the set of printable characters, some text editors don't always do a good job of displaying some printable Unicode characters.  Representing these characters as sequence of ASCII characters is not subject to such problems.
 - If you know the escape sequence of a character you want to use, having escape syntax means you can just type the character rather than needing to find the character in a character map and copy+paste.

Additionally, such syntax would be helpful if the recipe attribute suggested in https://github.com/casey/just/issues/647#issuecomment-2329480131 gets implemented.

Thinking about `just`'s backwards-compatibility guarantee, maybe the best syntax would be copying [Rust's `\u{...}`](https://doc.rust-lang.org/reference/tokens.html#character-escapes), since it allows a flexible and unambiguous number of hex digits?

**Comment by casey** [comment]
This would be great, and I agree that `\u{…}` is the ideal syntax. It'll require modifying `Parser::parse_string_literal`, which will be a bit of work to make it process multi-line escape sequences.
