### ISSUE TITLE
allow an .env file to be passed as an recipe parameter to change the dotenv-path setting

### ISSUE THREAD

**Issue by willie** [casey/just#2363]
In my projects, I have `.env` files for different contexts, like dev, prod, local, etc. I'd like to be able to specify which `.env` file to use based on a named parameter to the specific recipe.

I'm working around this now by embedding a shell script and calling out to `shdotenv` in the middle of it, but it's hacky.

```
some_recipe env="dev.env":
	#!/usr/bin/env sh
	set -euo pipefail
	export $(shdotenv -e {{env}} env)
	... do something with an environment variable loaded from env
```	

it would be neat if we could change the `dotenv-path` setting like passing an parameter. I don't know what the syntax would look like, maybe it would be...

```
some_recipe dotenv-path="dev.env":
	... do something with an environment variable loaded from env
```

I could always go, `shdotenv -e dev.env just recipe`, but that is awkward, too.

**Comment by laniakea64** [comment]
Why not using `just -E dev.env recipe`?

**Comment by willie** [comment]
> Why not using `just -E dev.env recipe`?

Wow. Thank you. I've looked at the documentation a ton (I've been writing justfiles for over a year) and I never saw that.

I think the documentation should mention that in the relevant place, https://just.systems/man/en/chapter_27.html#dotenv-settings. Maybe I'll write up a PR tomorrow.

**Comment by casey** [comment]
Nice, glad that works for you. There are way too many options for `.env` handling, so I'm sure the docs could use some work. PRs welcome!
