### ISSUE TITLE
Just behavior

### ISSUE THREAD

**Issue by cristianofmc** [casey/just#2369]
I want to know if this program is for me or not, after installation I tried to create a custom command and I came across a question, it asks me to create a file in the root of the project, but I was thinking more about a global tool, for example, "work on project a", then it opens, changes to the project directory and starts vscode, "start emulator" it will start the android emulator, or "work on project b" and it would change the context, you know, is this currently possible?

**Comment by laniakea64** [comment]
Would [Global justfile or User justfile](https://just.systems/man/en/global-and-user-justfiles.html) help?

**Comment by cristianofmc** [comment]
thank you I'll read it, for now I'm using the "alias"
