### ISSUE TITLE
Is there a way to fetch own recipe name as a variable?

### ISSUE THREAD

**Issue by dbranco-sdc** [casey/just#2373]
I would like to know if, is there a way to ask for the running recipe name?

That means for example

hello-myself:
   echo "Hello from {{RECIPE_NAME}}"

**Comment by casey** [comment]
Nope, there currently isn't. What is the use-case?

**Comment by dbranco-sdc** [comment]
> Nope, there currently isn't. What is the use-case?

We are currently working with just, and loving it. But, we are getting a lot of commands that they should be documented/show help better than just one line when executing "just --list"; the idea is to insert kind of piece of code that is capable to open a man page everytime you execute 

just foo help or just foo --help

That was the idea we were thinking about. And I was thinking to have a very generic code that pass the name of the recipe to pass it to the man command or whatever... Does it make sense?

**Comment by laniakea64** [comment]
Why not `just help foo`?

**Comment by MoaresOliveira** [comment]
So, you want a command that shows custom documentation for your justfile?

**Comment by dbranco-sdc** [comment]
> Why not `just help foo`?

Theres is nothing better than talking with people and having other point of view, thanks probably that would help



> So, you want a command that shows custom documentation for your justfile?

Yes, we are thinking in a README with pandoc, so the readme can be read in github but also from the just command. once again these are just ideas, thank you for your help!
