### ISSUE TITLE
just if/else if/else doesnt work with raw bools?

### ISSUE THREAD

**Issue by Distortedlogic** [casey/just#2380]
```
PACKAGE_MANAGER := if path_exists("/etc/fedora-release") { "dnf" } else { error("Dont use Fedora?") }
```

```
error: Expected '!=', '==', '=~', '+', or '/', but found '{'
```

**Comment by Distortedlogic** [comment]
also note I couldnt get `== true` to work either .. I tried the combos I could think of and get out of sonnet with docs in the context

**Comment by laniakea64** [comment]
Try this -
```
PACKAGE_MANAGER := if path_exists("/etc/fedora-release") == 'true' { "dnf" } else { error("Dont use Fedora?") }
```

`just` actually doesn't have booleans at all.  Every value in justfile is a string (this is a feature of `just`).  `path_exists()` returns string `"true"` or string `"false"`.

The condition in an if/else expression isn't a value and doesn't have a return value, it only directs which branch of the if/else to use.
