### ISSUE TITLE
readme uses sh codeblocks instead of console

### ISSUE THREAD

**Issue by lolbinarycat** [casey/just#2386]
`console` code blocks are meant for showing the output of commands

```console
$ just --list
Available recipes:
    build # build stuff
    test # test stuff
```

`sh` code blocks are meant for formatting shell scripts, and will incorrectly highlight any words that happen to be shell builtins:

```sh
$ just --list
Available recipes:
    build # build stuff
    test # test stuff
```

**Comment by casey** [comment]
Nice! I had no idea `console` was a thing. Fixed in #2388.
