### ISSUE TITLE
Can I use Just as an embedded command runner in my Rust CLI tool?

### ISSUE THREAD

**Issue by kajogo777** [casey/just#2396]
I'm building a client to improve developer experience by creating and sharing workflows, and I want to use Just as an embedded runner for dev team internal workflows.

Is this possible with the create available at the moment? where should I look for examples of how to programmatically fetch and execute Justfiles.

**Comment by casey** [comment]
There's a very simple `run` function [here](https://docs.rs/just/1.36.0/just/fn.run.html) which can be used to run `just` with some arguments. This doesn't provide any more control or functionality over calling `just` as an external command, but means that you don't have to have it installed locally, and can include it as a dependency. See #365 for discussion on actually providing a more complete library API.
