### ISSUE TITLE
Conditionals in recipe

### ISSUE THREAD

**Issue by gabrik** [casey/just#2407]
Hi, first thank you for this very usefull tool!

I'm trying to use conditionals as part of a recipe, but I keep getting syntax errors:
```
just zeros=true run cond
error: Recipe line has extra leading whitespace
  ——▶ justfile:40:5
   │
40 │         echo "true"
   │     ^^^^^^^^^^^^^^^

```

I've a very simple `justfile`

```
zeros := "false"
....
run cond:
    !#/usr/bin/env bash
    set -euxo pipefail
    if [[ "{{ zeros }}" == "true" ]]; then
        echo "true"
    else
        echo "false"
    fi
...
```

I've already had a look at other issues:
- https://github.com/casey/just/issues/1835
- https://github.com/casey/just/issues/2150

But the solutions provided there are not working.

Any suggestion?

**Comment by neunenak** [comment]
A unix shebang is `#!` not `!#` as you have it. So just isn't detecting that this is supposed to be a script-style recipe, tries to parse it as a linewise recipe, and ends up getting confused by the additional whitespace on the `echo "true"` line, which is perfectly good bash syntax but invalid just syntax.

I didn't notice the `#!` vs `!#` error immediately either, and I think it would be helpful if just could detect this character transposition and emit a warning that you probably meant to type `#!`.

**Comment by gabrik** [comment]
> A unix shebang is `#!` not `!#` as you have it. So just isn't detecting that this is supposed to be a script-style recipe, tries to parse it as a linewise recipe, and ends up getting confused by the additional whitespace on the `echo "true"` line, which is perfectly good bash syntax but invalid just syntax.
> 
> I didn't notice the `#!` vs `!#` error immediately either, and I think it would be helpful if just could detect this character transposition and emit a warning that you probably meant to type `#!`.

Oh man, shame on me :D

Thank you for spotting this!
Indeed maybe `just` could raise an error there, would have been more easy to catch the typo.
