### ISSUE TITLE
Unexport environment variables per recipe using attribute

### ISSUE THREAD

**Issue by W1M0R** [casey/just#2409]
Currently, environment variables can be unexported at the justfile level, using [unexport](https://just.systems/man/en/getting-and-setting-environment-variables.html?highlight=unexport#unexporting-environment-variables1290). This will unexport the environment variable for all recipes:

```justfile
unexport GIT_EXTERNAL_DIFF
unexport GIT_PAGER

# only this recipe should not have GIT_EXTERNAL_DIFF and GIT_PAGER exported
diff-delta:
  git diff | delta --line-numbers

# and this recipe should respect the parent shell's GIT_EXTERNAL_DIFF and GIT_PAGER, but won't due to the unexport statements
diff-default:
  git diff
```

In some cases it is helpful to unexport (in a cross-platform way) an environment variable (or a list of environment variables) for only a specific recipe. One workaround is to use submodules, e.g. `justfile-git-defaults.just` and `justfile-git-overrides.just`, but this feels cumbersome.

Ideally, it would be nice to be able to unexport using an attribute:

```justfile
[unexport("GIT_EXTERNAL_DIFF", "GIT_PAGER")]
diff-delta:
  git diff | delta --line-numbers

diff-default:
  git diff
```

Related:

1. https://github.com/casey/just/issues/2408

**Comment by neunenak** [comment]
Seems to me that this issue should be combined with https://github.com/casey/just/issues/2408 - the actual desired feature is a way to scope anything one can currently do with `just` variables to a single recipe (or maybe a group of recipes?)

**Comment by neunenak** [comment]
Seems to me that this issue should be combined with #2408 - the actual desired feature is a way to scope anything one can currently do with `just` variables to a single recipe (or maybe a group of recipes?), whether that's exporting, unexporting, etc.

**Comment by casey** [comment]
Yah, closing in favor of #2408, since whatever solution we come up with should handle both cases.
