### ISSUE TITLE
Rewrite Lexer

### ISSUE THREAD

**Issue by casey** [casey/just#241]
The lexer is by far the messiest code in `just`. Rewrite it using a character-at-a-time lexer, instead of regular expressions.

- [ ] parser invokes lexer
- [ ] new "Position" type, which stores an offset and a source file
- [ ] make eyes bleed less when reading it

**Comment by jonringer** [comment]
Would you be opposed to using a parser combinator library such as nom?
https://github.com/Geal/nom

**Comment by casey** [comment]
I'm actually pretty happy with the parser. It's a little gross, but it produces very good error messages and is easy to extend. Unless you mean replacing the lexer with nom?

The lexer, on the other hand, just matches a list of regular expressions one at a time, and is way messier. I'd like to replace it with something that doesn't use regular expression or a library like nom at all.

I read this [article](https://commandcenter.blogspot.com/2011/08/regular-expressions-in-lexing-and.html) by Rob Pike. I had always written lexers used regular expressions, so I was surprised that he seemed to think that they were overkill. I'm working on a shell, so I decided to try writing a lexer by hand, without regular expressions, and I was surprised how nice it was. It's more verbose than using regular expression, but it's far less cryptic and error prone.

This is a really low-priority issue though, since the lexer works, even if it is gross. Until there's a really good reason to replace it, I'll probably just be lazy and leave it as is.

**Comment by jonringer** [comment]
Yea sorry, I meant replace the lexer, in which it would parse the raw justfile and produce your token stream. You can still get really nice error statements, but I agree, it might not be worth the hassle right now.

**Comment by casey** [comment]
Added in #406. Feels good to rip out all that terrible code!
