### ISSUE TITLE
dotenv env expansion fails for envs names with underscores and no curly-braces

### ISSUE THREAD

**Issue by davidpeck-littlemonkey** [casey/just#2410]
```sh
# just --version
just 1.30.1
```

I have a dotenv file `.env`:
```
ENV1=myval1
ENV_2=myval2

MYENV1=$ENV1
MYENV_2=$ENV_2
MYENV3=${ENV1}
MYENV_4=${ENV_2}
```

and a `Justfile`:
```
set dotenv-required
set dotenv-path := '.env'

echo:
    echo $MYENV1
    echo $MYENV_2
    echo ${MYENV3}
    echo ${MYENV_4}
```

When I run `just echo`, I would expect the output:

```sh
# just echo
myval1
myval2
myval1
myval2
```
Instead I get:

```sh
# just echo
myval1
_2
myval1
myval2
```

**Comment by laniakea64** [comment]
This is by design of dotenv syntax - https://github.com/allan2/dotenvy/blob/db0d6aa8fc8d1b0ddbfe94b5c833372e463eb1c5/.env-substitution#L17

**Comment by casey** [comment]
Yah, looks like this is by design. Seems unfortunate, since shells, which `.env` syntax is supposed to mimic, don't require curly brackets around `$FOO_BAR`.

**Comment by casey** [comment]
If the `doenvy` was part of just, I would actually change this, since I think it's so unexpected that it's almost bug-like, even though it would technically be backwards incompatible. However, since it's not, unless upstream is interested in changing it, I think we've just gotta let it stand.
