### ISSUE TITLE
[Feature request] More list/dump options

### ISSUE THREAD

**Issue by nefrob** [casey/just#2413]
Integrating just into third party tools leverages just's `--list` or `--dump` options. Using `--dump` is potentially quite expensive since it includes the entire contents of the justfile rather than just the recipe definition. Using `--list` is not as powerful as it is difficult to correctly parse the recipe name, args and comment sections of a line.

Suggestions:
- Add a customizable delimiter between list outputs, ex. `recipe || args || doc comment`
- Allow selecting a subset of keys form the dumped justfile response (ex. `#recipes[#doc,name]`) without needing to rely on additional tools like `jq` that might not exist on the user's system

**Comment by laniakea64** [comment]
In the interest of avoiding a [XY-like problem](https://mywiki.wooledge.org/XyProblem), what specific integration are you seeking to implement with this feature?

**Comment by casey** [comment]
Also, I can't really think of an environment where you would have `just`, but where printing the contents of a justfile is expensive. You've already parsed the justfile, and the parsed file is in memory, printing it out as JSON shouldn't be a significant additional cost.

**Comment by nefrob** [comment]
@casey true, I'll stick with using the json then. Closing.
