### ISSUE TITLE
Conditional operator for NOT match regex?

### ISSUE THREAD

**Issue by laniakea64** [casey/just#2416]
I have run into a number of cases where a "not matching regex" condition would be useful, i.e. the opposite of `=~`.  Latest example is [here](https://github.com/NoahTheDuke/vim-just/pull/114/files#diff-dccf001585af8f37bb6b80fa80eb166ba6749533115939348bc40d59601e965fR20): without a "not matching regex" conditional operator, this check cannot use `assert()` which was specifically designed for cases like this.

Does `just` have such operator?  If not, could it please be added?

BTW I'm not finding the documentation of the `assert()` function-like expression in the README?

**Comment by Montana** [comment]
So @laniakea64, 

As of now, "just" does not natively support a "not matching regex" operator directly. However, you can usually achieve a similar effect using existing logical operations. Here’s a common workaround using negation `(!)` and `=~:`:

```regex
if !(some_string =~ r"some_regex") {
  # Code to execute if the string does NOT match the regex
}
```
Alternatively, the issue might be suggesting a feature request to add a specific `!~` or similar operator to make this more intuitive, but this does not seem to be implemented yet.

As for the `assert()` function, it’s likely being used to validate that certain conditions are true. If you’re not finding it in the documentation, it might be a less-documented feature or related to the specific environment or context the user is working with. Hopefully this helps you. 

Cheers, 
Montana.

**Comment by casey** [comment]
I think we should add `!~`. This seems common enough that it's useful, and you can't really work around with negation, since conditionals are a grammar-level hack.
