### ISSUE TITLE
Add to nixpkgs

### ISSUE THREAD

**Issue by casey** [casey/just#242]
An almost working derivation is here:

https://gist.github.com/casey/eabd1724ac2a5c5fbc2c75ba88205f49

**Comment by xrelkd** [comment]
Thanks for sharing this useful and powerful tool!

`just` is just added to [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs)!
The commit (https://github.com/NixOS/nixpkgs/pull/59306) has been merged into the master branch of  [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs).

**Comment by casey** [comment]
You're welcome, and thank you so much for packaging `just` for nix!

I'm adding instructions to the readme in #403.

I have a NixOS laptop at work, so I'll probably wind up making use of your package ^_^
