### ISSUE TITLE
winget for windows installation

### ISSUE THREAD

**Issue by gedw99** [casey/just#2421]
Hey

currently I see all these installers at https://github.com/casey/just?tab=readme-ov-file#cross-platform

https://github.com/microsoft/winget-cli

But no winget. For example:

```sh
winget install -e --id Rust.Just
```

it works very well and is pretty well supported by the MS team. It does not seem like a dead thing at all, despite what some say on Reddit etc.

I have been using it to Bootstrap Windows boxes for a few months now, and its been highly reliable.

**Comment by casey** [comment]
Thanks for the issue! Are you sure the package name is `Rust.Just`? I see it under [Casey.Just](https://winget.run/pkg/Casey/Just).

**Comment by casey** [comment]
Nice! Whoops, I actually forgot that it's already in the readme:

https://github.com/casey/just/?tab=readme-ov-file#windows

Under Windows Package Manager.
