### ISSUE TITLE
[Feature] Add support for a global `~/.justfile`

### ISSUE THREAD

**Issue by swils23** [casey/just#2422]
Looking for feedback! I've already implemented similar functionality in a Zsh plugin that wraps the `just` command [here](https://github.com/swils23/just_wrapper). However, it would be nice if this functionality were present in Just itself.
### Use Cases
- **Custom Commands**: Commands specific to your workflow, but don't belong in a project's Justfile
- **Overriding Commands**: Commands that overwrite ones defined in a project's Justfile to suit your needs
- **Shortcut Commands**: Commands that simplify or shorten existing commands (e.g. `just tp` for `just test_playwright`)
- **Roadblocks**: Commands that are used frequently, but project maintainers are hesitant to add to the Justfile

#### Warning: Potential for Lost Wisdom
There's a potential downside: **lost wisdom**. If team members add custom commands without sharing them, valuable improvements to a project's `just` commands might be missed. Encourage your team to share useful commands to ensure everyone benefits from collective knowledge.

**Comment by laniakea64** [comment]
https://just.systems/man/en/global-and-user-justfiles.html

**Comment by swils23** [comment]
I need to get my eyes checked. Thanks!
