### ISSUE TITLE
just 1.36.0 throws error when using CLI flag '-lu'

### ISSUE THREAD

**Issue by nem75** [casey/just#2425]
Hi,

my default recipe usually calls `just -lu` (short for `just -l -u`). Since updating to v1.36.0 this no longer works. Instead the error

```
error: Justfile does not contain submodule `u`
```

is thrown (exit code: 1).

`just -l -u` as well as `just -ul` work, so it seems to have something to do with the specific flag order and `-l` being first.

**Comment by laniakea64** [comment]
https://github.com/casey/just/discussions/2245

**Comment by casey** [comment]
Thanks for filing this issue! This was an oversight on my part. `-l` was changed to take a value, so in `-lu`, `u` is that value. `-l` should be used on its own, or last.
