### ISSUE TITLE
[Documentation] provide link to pre-commit hook

### ISSUE THREAD

**Issue by tomers** [casey/just#2443]
A [pre-commit](https://pre-commit.com/) hook for `just` is available here: https://github.com/instrumentl/pre-commit-just

I believe it should be reffered to in the main `README.md` file.

**Comment by casey** [comment]
This seems useful, but the `--fmt` command is currently unstable and has a lot of problems, so I'm not sure it's a good idea to link to or recommend a precommit hook which uses it.
