### ISSUE TITLE
Redirection ('>') when running a just command fails in bash

### ISSUE THREAD

**Issue by ross-spencer** [casey/just#2445]
When running a `just` command, e.g. `just do-something` if you try redirection `just` will report `error: Justfile does not contain recipe `2`.` 

Example:

```sh
just do-something 2&> output_errors.txt
```

It would be helpful to be able to use redirect with just so as to not have to unpack commands to get logging.

**Comment by casey** [comment]
I believe the command should be:

```
just do-something 2> output_errors.txt
```

Let me know if that doesn't work!
