### ISSUE TITLE
Support Conditional Assignments

### ISSUE THREAD

**Issue by Fleshgrinder** [casey/just#245]
Currently `just` allows us to assign values to variables, however, there is no way to conditionally assign like GNU Make has it. GNU Make uses the `?=` for a conditional assignment, this seems like a reasonable syntax to me.

Note that this feature is especially important for environment variables.

```make
export MY_ENV_VAR ?= foo

env:
    echo {{MY_ENV_VAR}}
```

```sh
$ MY_ENV_VAR=bar just env
echo bar
bar
```

**Comment by casey** [comment]
Thanks for opening this issue!

Hmm, interesting. You can currently override assignments at the command line, so this would specifically be for conditional assignment to environment variables if that environment variable isn't already set? For example, this works:

```
export MY_ENV_VAR = foo

env:
    echo {{MY_ENV_VAR}}
```

```
$ just MY_ENV_VAR=bar env
echo bar
bar
```

Is there a use case where this isn't good enough?

**Comment by Fleshgrinder** [comment]
We often use `make` to automate `docker` and `docker-compose` stuff. One recipe is starting the complete stack, incl. a server, database, etc. all of which expose ports on the host. This often leads to port collisions, hence, every host port is managed through an environment variable that developers may change at will.

```sh
# start the stack with defaults, e.g. MySQL on 3306
$ make
# customize the stack, because 3306 is used by something else
$ PROJ_MYSQL_PORT=3307 make
```

**Comment by casey** [comment]
You can do this currently, although you need to move the assignment after the command, so that it's processed by `just` and not the shell:

```sh
# start the stack with defaults, e.g. MySQL on 3306
$ just
# customize the stack, because 3306 is used by something else
$ just PROJ_MYSQL_PORT=3307
```

**Comment by Fleshgrinder** [comment]
This is possible with `make` too, but it also supports the standard POSIX way of doing it. Teaching every person that is verse in POSIX and shells that this particular program works differently, for whatever reason, is time-consuming, and usually not worth the effort. It would be better to have it implemented in the standard way of things.

That being said, the environment variable might come from a previous `export` in the shell, a `.bashrc` or similar. In that case, one is lost.

**Comment by bb010g** [comment]
It sounds like you more want a way to import environment variables and use them in just expressions.

**Comment by Fleshgrinder** [comment]
That’s basically part of the idea, yeah. I want to use the environment variable if it is already defined and otherwise define it. There are a couple of things with which this feature could be extended. Like support for `.env` files.

**Comment by casey** [comment]
It's a bit longer, but you can now use something like `export MY_ENV_VAR = env-default("MY_ENV_VAR", "foo")` to assign to an environment variable if it is not defined.
