### ISSUE TITLE
Make `working-directory` templateable

### ISSUE THREAD

**Issue by pavelzw** [casey/just#2452]
```
set working-directory := '{{env("ABC")}}'

default:
    echo 'Hello, world!'
```

the following doesn't work

```shell
❯ mkdir -p dir1
❯ ABC=dir1 just
echo 'Hello, world!'
error: Recipe `default` could not be run because just could not find the shell: No such file or directory (os error 2)
```

**Comment by laniakea64** [comment]
For your specific example, you can use [shell-expanded strings](https://just.systems/man/en/strings.html):
```
set working-directory := x'$ABC'

default:
  pwd
```

More generally: https://github.com/casey/just/issues/2309

**Comment by casey** [comment]
Yah, see shell expanded strings. I think this is a special case of #2309, so closing.
