### ISSUE TITLE
Possible to use : in recipe names?

### ISSUE THREAD

**Issue by itmecho** [casey/just#2457]
Thank you for creating a great tool :D 

I think it would be nice to be able to include `:` in recipe names to group them together nicely, i.e. `db:migrate`, `db:clean`, etc.

I've tried various things (`db:clean:`, `"db:clean"`, `'db:clean':`, `db\:clean:`) but I don't think it's currently supported.

**Comment by casey** [comment]
It is not, unfortunately. This is a commonly requested feature, however, any characters which are used in recipes names cannot be used elsewhere in `just`'s grammar. If `:` were used in recipe names, it could not be used for, for example, some future hypothetical type annotation or hint, or the like.

For now, if you want to group commands, consider using a module, which would let you do `just db clean`:

```
# justfile
mod db
```

```
# db.just
clean:
```
