### ISSUE TITLE
Be Quiet by Default

### ISSUE THREAD

**Issue by Fleshgrinder** [casey/just#246]
Typical Unix programs should be quiet by default and print only if there are failures. GNU Make is actually very, very, very bad at this because it is super verbose. It would be great if just would follow the Unix tradition here and only starts being talkative if `-v` or `--verbose` is passed to it.

**Comment by casey** [comment]
Thanks for opening this issue!

I personally like it the way it is, since it allows following along with what commands are being run. For something like just or make, I think this is reasonable, since many commands are being run, and when something fails we want to know what command failed.

If most users would prefer it to be quiet, I would be open to changing it.

**Comment by Fleshgrinder** [comment]
You are basically already stating what is of interest: _what failed?_ Having overly verbose output by default means that the user must scan the output manually. An absurdity we see with many _modern_ tools (I’m looking at you `npm`). Our QA staff is often misinterpreting build output because the programs print a ton of warnings, and the actual error is overlooked.

```make
# Justfile
build:
    cargo +nightly build --release
```

```sh
$ just build
error: recipe 'build' failed `cargo +nightly build --release` at /usr/opt/proj/Justfile:3
# stderr output
```

**Comment by Fleshgrinder** [comment]
I wrote `stderr` in the previous comment but actually, all output should be buffered and printed in case of error. I thought a little longer about this, and a possible way for this to work could be as follows:

- Default: no option was passed to just, nothing gets printed and output of the called programs is buffered. In case of error, the output buffer gets flushed and a banner is displayed.
- `-v` or `--verbose`: nothing gets printed and output of the called programs is buffered. In case of success, a banner is displayed with the name of the target(s) that succeeded. Error case is handled as it was previously. This mode would be the default if a `CI` environment variable is defined.
- `-vv`: executed target name(s) get printed and the output of the programs is piped through. Plus success and error banner. This mode would be the default if a `VERBOSE` environment variable is defined.
- `-vvv`: like `-vv` but incl. just informational stuff. This mode would be the default if a `DEBUG` environment variable is defined.
- `--debug`: like `-vvv` but incl. just debug stuff.

This allows users fine-grained control over the output that is being produced and follows plus enforces the [Unix rule of silence](http://www.linfo.org/rule_of_silence.html).

**Comment by casey** [comment]
Command stderr and stdout should still be printed by default. Since, for example, a compiler might produce warnings but still signal success, and just shouldn't hide those warnings from the programmer.

**Comment by Fleshgrinder** [comment]
You’re probably right here and a `--silent` mode to actually enable this buffering is more sensible.

**Comment by casey** [comment]
I think I'm going to close this. I'm actually highly sympathetic to the argument that programs should be quiet by default, but I personally find just's current behavior to be useful. I would definitely be open to some kind of argument that enabled buffering, and only showed buffered output if there was an error, if someone wanted to contribute a patch.
