### ISSUE TITLE
cargo install just version 1.37.0 

### ISSUE THREAD

**Issue by peternormann** [casey/just#2476]
First of all, thank you for making this tool. I have been using `Makefiles` for ages for non-compilation-y stuff and `just` is the perfect replacement that solves most, if not all, of the quirks of the previous tool (that really was intended for other things than my use cases).

Up until (and including) version `1.36.0` I have been able to install and update `just` by simply issuing

`cargo install just`

This no longer works, as I am getting a lot of error messages:

`error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg``

I have tried installing nightly and adding the` -Z unstable-options` flag, but that seems to open another can of worms.

Is this intentional (leading me to explore alternate installation options for `just`)?

Regardless, love your work <3

**Comment by laniakea64** [comment]
What version of `rustc` are you using?
What version of `cargo` are you using?

**Comment by peternormann** [comment]
@laniakea64 Thanks for your question.

I had initially issued a `rustup update` prior to attempting to upgrade `just`.

However, it turns out I had some stale versions of `cargo` and `rustc` that I guess has been installed using a package manager.

Removing said packages fixed everything.

**Comment by casey** [comment]
Phew! Glad it worked :)
