### ISSUE TITLE
Can I add to a justfile a string substitution/strip in a variable.

### ISSUE THREAD

**Issue by psyciknz** [casey/just#2477]
So I have a script I want to run in a docker container.  My just command is a docker exec <container> script <directory>

Now <directory> needs to be accessible to the container.  But as it's a variable for the just command I write it 
just mycommand /some/dir/host/some/common/dir

Where /some/common/dir will work in the container.
So all I really need to do is to strip off /some/dir/host before executing the script.

This is actually a just command to run a handbrake conversion script in a handbrake container.  The host has access to:
/mnt/media/tv
In the container that becomes
/media/tv

so I just need to strip off the /mnt (which I could do in my conversion script), but hey I'd like to see if just can do it.

**Comment by casey** [comment]
Try the `trim_start_match` function, I think it does what you want. See [string manipulation functions](https://github.com/casey/just?tab=readme-ov-file#string-manipulation) in the readme.
