### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by Spatenheinz** [casey/just#2485]
Would you be willing to support some sort of more in-depth comment view,
i.e. either allow to have multiple lines of comments show in list view (with a flag of course to not break backwards compatability)
Or a command something like 

`just --explain recipe` and then show the entire block of comments above a recipe?

**Comment by Spatenheinz** [comment]
Sorry if this is already something that is possible.

**Comment by laniakea64** [comment]
If your goal is to show a multi-line documentation for a recipe in `just --list` output, you can use [`[doc]` attribute](https://just.systems/man/en/documentation-comments.html) -
```
[doc("""
  This is a multi-line documentation comment.

  It explains a lot of detail about this recipe:
    - what it does,
    - what else it does,
    - etc.

  This text will be displayed in its full multi-line form when using `just --list`.
""")]
recipe:
  echo foo
```

**Comment by casey** [comment]
I think multi-line strings in doc comments are the way to go. See @laniakea64's comment.

**Comment by Spatenheinz** [comment]
Thank you!
