### ISSUE TITLE
Add function to check if a command is in path

### ISSUE THREAD

**Issue by bew** [casey/just#2489]
Here is my usecase:

Let's say just is installed at `/not/in/path/just`.

I want my receipes to call other receipe and not care whether just is in path or not, so I use:
```justfile
foo:
  {{ just_executable() }} bar

bar:
  echo foobar
```

I want to show the executed line in `foo` (so I don't prepend a `@` to `{{ ...`).
So calling `/not/in/path/just foo` would output something like:
```
/not/in/path/just bar
foobar
```

👉 BUT when `just` is in actually in $PATH I'd like instead to show:
```
just bar
foobar
```

I was thinking about making a just variable at the top that checks whether just in in $PATH and put `just` if it is, or `just_executable()` otherwise.

Hence why I'd like a way to check if just is in $PATH.

Or is there another way to do this?

**Comment by laniakea64** [comment]
The generic functionality you're requesting sounds covered by https://github.com/casey/just/issues/2109

For your specific case, would something like this work? -
```
just := if replace(env("PATH"), parent_directory(just_executable()) + ':', '') != env("PATH") {
  file_name(just_executable())
} else {
  just_executable()
}

foo:
  {{quote(just)}} bar

bar:
  echo foobar
```

**Comment by bew** [comment]
> The generic functionality you're requesting sounds covered by #2109

Ah yes good find, missed it when I searched 👍



> For your specific case, would something like this work?

For this example yes, but not for my usecase: I'm using Nix, so binary install path is symlinked a bunch of times to different places and one of those is actually in PATH (not the parent dir of just executable)

---
Thanks I'll close this and follow progress on #2109

**Comment by casey** [comment]
You can also do:

```just
just := if `which just || echo ''` == '' {
  just_executable()
} else {
  'just'
}
```

We have unstable `&&` and `||` syntax, with that you could do:

```just
just := `which just || true` && 'just' || just_executable()
```

Which is shorter and more inscrutable. But I do like inscrutable things.

**Comment by bew** [comment]
Thanks 👍
Used `which just 2>/dev/null` tho to avoid useless 'just not found' line ;)

**Comment by bew** [comment]
FWIW using `which` unstable (at time of writing) function, this looks like:
```just
set unstable # necessary for 'which' function

# Use full path to exe if just isn't in $PATH, or 'just' otherwise
just_exe := if which("just") == "" { just_executable() } else { "just" }
```
