### ISSUE TITLE
One test fails with non-english locales

### ISSUE THREAD

**Issue by vtamara** [casey/just#2494]
To reproduce, run the tests as explained in the README.md but with a non-english locale like:

```
LANG=es_CO.UTF-8 just ci
```

On OpenBSD/adJ 7.6beta and on Linux Ubuntu 24.04 it will produce:

```
---- constants::constants_are_not_exported stdout ----
thread 'constants::constants_are_not_exported' panicked at tests/constants.rs:60:6:
Stderr regex mismatch:
"echo $HEXUPPER\nbash: línea 1: HEXUPPER: variable sin asignar\nerror: Recipe `foo` failed on line 4 with exit code 127\n"
!~=
/Regex("^(?s).*HEXUPPER: unbound variable.*$")/
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    constants::constants_are_not_exported

test result: FAILED. 852 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out; finished in 0.59s

error: test failed, to rerun pass `-p just --test integration`
error: Recipe `test` failed on line 17 with exit code 101
```

**Comment by casey** [comment]
Thanks for creating this issue!

I think this is an instance of a more general problem. We rely on a lot of system binaries for testing, but those binaries often behave different in different environments, for example, different OSes, or, as you discovered, different locales.

I added a hidden `--request` subcommand to `just` #2498, which can be used in testing for, currently, getting and returning environment variable without relying on any particular system or shell behavior.

This can be expanded in the future, to add new things we currently rely on external binaries for. (Like `cat` and `touch`.)
