### ISSUE TITLE
The function `just_executable` on OpenBSD sometimes produces "error: Call to function `just_executable` failed: Error getting current executable: no current exe available (short)"

### ISSUE THREAD

**Issue by vtamara** [casey/just#2499]
Consider this `justfile`  (taken from a test):

```
a:                                                                                                                                                              
  @printf 'Executable path is: %s\n' '{{ just_executable() }}'
```

Running it on OpenBSD/adJ 7.6beta1 it could produce or not an error depending the way `just` is called:

```sh
% ~/.cargo/bin/just 
Executable path is: /home/vtamara/.cargo/bin/just
```

or

```
 % just
error: Call to function `just_executable` failed: Error getting current executable: no current exe available (short)
 ——▶ justfile:2:42
  │
2 │   @printf 'Executable path is: %s\n' '{{ just_executable() }}'
  │                                          ^^^^^^^^^^^^^^^
```

The difference is due to the implementation of `env::current_exe()` used by `just_executable`. As noted in <https://github.com/rust-lang/rust/issues/60560> in OpenBSD it produces an error when the binary is resolved with `$PATH`.

It could be possible to implement a workaround that produces better results in more situations as it was done at <https://github.com/bket/bupstash/commit/c6a8732db5457d42f06f6eb3ce1c4ebc7420188b>

However, in the moment of this writing, personally, I don't see that necessary because the users of OpenBSD/adJ know this behavior and we can start `just` with its full path in case that the `justfile` uses `just_executable`.

I opened this issue just as a reference.

**Comment by casey** [comment]
Thanks for the note! This is really interesting. I guess we could try to look in $PATH to find the executable in that case.

**Comment by vtamara** [comment]
Thanks, that could be another way of trying to deal, however  I found that:

1. It is a security feature of OpenBSD that OpenBSD users are (or should) be aware of (<https://github.com/ziglang/zig/issues/6718>)
2. Finding the path of the executable file used to start a process is not in POSIX according to <https://misc.openbsd.narkive.com/UpcchEvI/ld-so-behavior-with-origin>.
