### ISSUE TITLE
datetime format fails: Unknown start of token: %

### ISSUE THREAD

**Issue by AuroraLantean** [casey/just#2503]
The following just code do not work with the error message: `Unknown start of token`
```
time1 := datetime(%Y)
time2 := datetime(%Y_%m_%d__%H_%M_%S)
```
`%Y` is a valid format according to https://docs.rs/chrono/latest/chrono/format/strftime/index.html

**Comment by laniakea64** [comment]
The parameter of `datetime()` is a string:
```
time1 := datetime('%Y')
time2 := datetime("%Y_%m_%d__%H_%M_%S")
```
