### ISSUE TITLE
Feature request: single-line recipes

### ISSUE THREAD

**Issue by sociopart** [casey/just#2505]
Hello, and thank you for your effort!

Here's something Make (partially) supports, and it would be great if Just supported it too: single-line recipes. It feels logical when writing small commands related to a project. You can see everything you need in a table-like view, such as:

```
run: ; echo "cmd1"
con: ; echo "cmd2"
```
Make allows this, but you need to use some hacky stuff like `run: ; echo "cmd1"`. Could there be a way to support it properly in Just?

Thanks in advance!

**Comment by casey** [comment]
I can definitely see the use case, but I think this would just be really hard to support. The indentation-based recipe body parsing is already hideous, so I'm loathe to add a special case to it 😅
