### ISSUE TITLE
Crater for Just

### ISSUE THREAD

**Issue by casey** [casey/just#251]
There are a lot of justfiles on github, and it would be nice to leverage them to make sure that existing justfiles aren't broken by future changes to`just`.

I'm imagining a tool that would, for a new version of just:

- download all files on named `justfile` or `Justfile`
- check that all files are tokenized identically under the new and old versions
- check that all files are parsed identically under the new and old versions
- check that all files produce identical dry-runs under new and old versions

Caldera would be an appropriate name. It will probably need a blacklist for those files which are called `justfile` but which aren't actually justfiles.

**Comment by rollcat** [comment]
> It will probably need a blacklist for those files which are called `justfile` but which aren't actually justfiles.

On the lower layer, it should be sufficient to generate a report for given version of `just`, some `just-version`. If it fails to parse today, it shouldn't be a problem tomorrow.

A higher layer would have to track tuples of `(something-that-looks-like-justfile, just-version, report)`, and only raise red flags when there's a regression - something that worked with `just-version` is now broken in `just-version`+1.

Then there's no need for a hardcoded list - both whitelists and blacklists suck.

**Comment by casey** [comment]
It exists now!

https://github.com/casey/janus
