### ISSUE TITLE
Make uv friendly

### ISSUE THREAD

**Issue by linux-china** [casey/just#2519]
[uv](https://github.com/astral-sh/uv) is used for most Python developers now, and any idea to make just to work with uv friendly? 

Add setting `set uv-enabled` for uv, then 

-  adjust environment variables, such as VIRTUAL_ENV
-  unset PYTHONHOME
-  add `.venv/bin` to PATH by default. 
-  add pip3 alias: `alias pip3="uv pip"`

**Comment by casey** [comment]
Isn't uv supposed to work out of the box with no config? I.e., you do uv run, or equivalent, and don't need to set any env vars?

**Comment by linux-china** [comment]
According to  [Using uv run as a task runner](https://github.com/astral-sh/uv/issues/5903),  and lots of developers still want uv to have a task runner.  Just can make uv UX better without any configuration for task runner.   You can use uv in justfile, and you can use native tools too.   For examples:

- Run scripts: `uv run demo.py`, `python3 demo.py`,  both are ok
- Install package: `uv add xxx`, `pip3 install xxx`
- Run tools: `uv run fastapi dev`, `fastapi dev` are all good


Just copy commands/snippets from internet and paste them in justfile, and you can run these commands with uv support now.

**Comment by casey** [comment]
I'm definitely open to anything specific which would make `just` `uv` friendlier, but I think most of these can be accomplished with existing features, like exporting or unexporting environment variables.

**Comment by michielvermeir** [comment]
I should probably open another issue for this, but I ran into this uv-specific quirk when using shebang recipes. I got the idea from [Simon Willis](https://simonwillison.net/2024/Aug/21/usrbinenv-uv-run) to define a shebang recipe with `uv run`:

```
uv:
  #!/usr/bin/env -S uv run
  print(1 + 1)
```
But it just hangs whereas `env -S python` just works 🤔 
```
$ just -vv uv
===> Running recipe `uv`...
#!/usr/bin/env -S uv run




print(1 + 1)

^C⏎ 
```
