### ISSUE TITLE
Add env_var_with_value() function

### ISSUE THREAD

**Issue by begoon** [casey/just#2529]
Sometimes, an environment variable can be set, but it can be set to an empty value. Formally, the variable is preset in the environment, but the value is an empty string.

The `env_var_or_default()` function returns the default value only if the variable is not preset. If the variable is present, and it is set to an empty string, `env_var_or_default()` returns an empty string.

This behaviour may lead to the following confusing code:
```
# Take the PR parent branch as the default.

GITHUB_REF_NAME := env('GITHUB_REF_NAME', BRANCH_DEFAULT)

# Take the PR branch if GH is building a PR/feature branch.

GITHUB_HEAD_REF := env('GITHUB_HEAD_REF', '') || GITHUB_REF_NAME
```

To set `GITHUB_HEAD_REF`, we take `GITHUB_HEAD_REF` with the default of '', if it is missing, and then we use `|| GITHUB_REF_NAME` if its value is an empty string.

# Proposed solution

Add a new function, `env_var_with_value()`, which returns the default value, if:

1. if the variable is missing
2. if the variable is set, but its value is an empty string

# Example

Consider the following `Justfile`:
```makefile
VAR_OR_DEFAULT := env_var_or_default("VAR", "VAR_OR_DEFAULT-default")
VAR_WITH_VALUE := env_var_with_value("VAR", "VAR_WITH_VALUE-default")

TEST:
  @echo "VAR_OR_DEFAULT={{VAR_OR_DEFAULT}}"
  @echo "VAR_WITH_VALUE={{VAR_WITH_VALUE}}"
```

## invoke with VAR unset

`_VAR="1" just TEST`

```
VAR_OR_DEFAULT=VAR_OR_DEFAULT-default
VAR_WITH_VALUE=VAR_WITH_VALUE-default
```

Both functions return the default value.

## invoke with VAR set to "" (in fact, an empty value)

`VAR="" just TEST`

or 

`VAR= just TEST`

```
VAR_OR_DEFAULT=
VAR_WITH_VALUE=VAR_WITH_VALUE-default
```

`env_var_or_default()` returns an empty string, not default, because `VAR` is formally set.

`env_var_with_value()`, however, returns the default value because even `VAR` is set, but it is set to the empty string.

## invoke with VAR=1:

`VAR="1" just TEST`

```
VAR_OR_DEFAULT=1
VAR_WITH_VALUE=1
```

Both functions return the explicitly set value "1".

# Proposed PR

https://github.com/casey/just/pull/2528

**Comment by casey** [comment]
Thanks for writing this up, and for the PR!

This honestly seems like a pretty good workaround, so I'm a little hesitant to add a new function:

```
GITHUB_HEAD_REF := env('GITHUB_HEAD_REF', '') || GITHUB_REF_NAME
```

Or am I misunderstanding what the function does?

I think that in general, if the invoker of a process wants to remove an environment variable, they should unexport it, with `unset VAR`, instead of setting it to the empty string, and that `just` probably shouldn't compensate for callers not doing that.

**Comment by begoon** [comment]
Agreed, setting a variable to an empty value is strange in the first place. Why they just don’t set it at all, right?

We may say that it’s the invoker environment’s fault, and it is the invoker’s resposibility to fix the behaviour, unless the invoker is… GitHub actions :-). Asking them to fix would be likely no-go.

However, agreed, the workaround works. And the special function may be an overkill. Maybe the existing functions with defaults would work as my new function — treating a variable, which is set but empty, as missing, and return the default. But changing the existing functions behaviour is even worse.

Up to you :-). Maybe you would come up with another use case some day, or a better name for the function.

**Comment by begoon** [comment]
@casey To progress (or drop it with no actions) on this, would you consider the following options, not necessarily mutually exclusive:

1. Add the workaround snippet to the documentation to advise when a variable is set but empty, and that's it.

```makefile
GITHUB_HEAD_REF := env('GITHUB_HEAD_REF', '') || GITHUB_REF_NAME
```

2. Add a string helper function called, for example, `value_or_default(var_name, default_value)`, which returns the value if it is not an empty string. Otherwise - return the default value. This function may have different applications when you are only interested in non-empty string values without using `if`s.

I am happy to change the PR either way we go.

**Comment by casey** [comment]
I think the workaround with `||` is probably best, just because it's less obvious at a glance what`env_var_with_value` means, and probably hard to come up with a good name which explains it. `env_var_or_default_if_empty` is probably better, but that's so long.

We could also make the second argument of `env_var_or_default` optional, and it returns the empty string if it's not set:

```
GITHUB_HEAD_REF := env_var_or_default('GITHUB_HEAD_REF') || GITHUB_REF_NAME

# although honestly that's not much better than:
GITHUB_HEAD_REF := env('GITHUB_HEAD_REF', '') || GITHUB_REF_NAME
```

I think we should add a note to the docs about using `||` when you need to replace the empty string.

**Comment by begoon** [comment]
I agreed with just keeping the workaround in the docs.

Once you close the original PR, would you update the docs, or could I place another PR for the docs?

**Comment by casey** [comment]
Just added it in #2545.
