### ISSUE TITLE
Recommended way to check for non-blank required variables?

### ISSUE THREAD

**Issue by liquidaty** [casey/just#2537]
Hi, I'm just (no pun intended) trying to get started with just as a substitute for make, but, I'm having some difficulty finding a reasonably clean and platform-independent way to do the simple job of checking for required variables.

Compared with using a `Makefile`, I would expect the `Justfile` way to be at least as easy, equally effective, and cross-platform, but the only solutions I have found with a Justfile fail on all of those expectations.

Hopefully my attempts simply demonstrates my Justfile naivete. Is there a better way?

---

For background, imagine my Justfile requires the following variables to be set and non-empty:
```
REQUIRED_A
REQUIRED_B
```
A `Makefile` way to do this could be:
```make
ifeq ($(REQUIRED_A), )
      $(error Missing REQUIRED_A)
endif

# repeat for REQUIRED_B
```
This is pretty simple and easy-- does not require trailing semicolons or backslashes to retain newlines, allows indentation which is easier on the eyes, can be put at the top of the script, will always work for all targets, and is cross-platform.

Of course, I could use bash instead, either via `$(shell ...)` or in a target, in which case I need trailing backslashes or a one-liner such as:
```bash
[ "${REQUIRED_A}" != "" ] &&  [ "${REQUIRED_B}" != "" ]  || (echo "Missing required variable" >&2 && exit 1)
```

The only ways I've found to do this in a Justfile are a few, but all with serious drawbacks compared to the above:
- include the above `bash` in a recipe, either as multiline with a backslash at the end of each line or with `#!/usr/bin/env sh` as the first line. However, this approach is not cross-platform, and misplaces this logic, which should be at the top of the script and always executed, to be inside a recipe target which is not necessarily always executed, or duplicate it for every recipe
- include the above outside of a recipe in a form such as `dummy:=if "${REQUIRED_A}" == "" { error("Missing REQUIRED_A") } else { "" }`. This looks and feels like a hack because I have to assign a dummy variable and include a meaningless ` else ` clause. But at least it is cross-platform and lets me put the code where it should be (at the top, outside of a recipe target)

---

Am I missing something really obvious / easy / recommended?

**Comment by laniakea64** [comment]
If `REQUIRED_A` and `REQUIRED_B` are environment variables, you could do
```
_required_a := assert(env('REQUIRED_A', '') != '', 'Missing REQUIRED_A')
_required_b := assert(env('REQUIRED_B', '') != '', 'Missing REQUIRED_B')
```

Or if you want to avoid dummy variables, you could put the asserts in a recipe and make your recipes depend on it:
```
actual_work: check
  echo 'Doing the actual work'

check:
  {{assert(env('REQUIRED_A', '') != '', 'Missing REQUIRED_A')}}
  {{assert(env('REQUIRED_B', '') != '', 'Missing REQUIRED_B')}}
```

**Comment by liquidaty** [comment]
Ah, much better And I see I can also chain assertions.
```
_check := assert(env('REQUIRED_A', '') != '', 'Missing REQUIRED_A') + \
          assert(env('REQUIRED_B', '') != '', 'Missing REQUIRED_B')
```

Thank you!

**Comment by casey** [comment]
Since the value must be set, can you do:

```just
_check := assert(env('REQUIRED_A') != '', 'Missing REQUIRED_A') + \
          assert(env('REQUIRED_B') != '', 'Missing REQUIRED_B')
```

This uses the one-argument form of `env` which will fail if the environment variable isn't set.

This does work, but it kinda sucks T_T

I wonder if it would be worth making this less painful, for example with a way to evaluate an expression without needing to create a dummy assignment. No idea what the syntax would look like:

```just
> assert(env('REQUIRED_A') != '', 'Missing REQUIRED_A')
> assert(env('REQUIRED_B') != '', 'Missing REQUIRED_B')
```
