### ISSUE TITLE
Add a just scripts directory

### ISSUE THREAD

**Issue by DevilPepper** [casey/just#2539]
I imagine a _just.d/_ with scripts inside and the file names without extension would be the name of the task. i.e.:

```
just.d/
├── auth.sh
├── generate.sh
├── install.sh
├── serve-py.py
└── serve-ts.ts
```

`just --list` would look like this:

![image](https://github.com/user-attachments/assets/586fb33b-d324-429b-a2c6-eb4bf756fa71)

I think it would work similar to shebang recipes, but they're already files so you could skip the write to disk step.

### Some caveats:

1. Parameters wouldn't work the same. We could add a parameters attribute, but in the script we'd have to unpack, i.e. from `"$@"`, and that could be error prone. Maybe it's a small price to pay...
2. Task dependencies might also have to be listed in a new attribute. I thought about putting them in the first comment after the shebang, but that sounds bootleg. And we probably want the first non-attribute comment to be a doc comment.
3. You'd have to look for attributes in different comment formats.
4. In the example above, I'm not a fan of names serve-py.py and serve-ts.ts. Probably for those I'd want an attribute to rename the task... But in reality, they're probably both sh scripts...

### Contribution

I'd be happy to build this out if it's desirable... when I have bandwidth. And I'm interested in feedback before running with it.

**Comment by casey** [comment]
Can you describe the use-case for this? I think this would probably involve too many changes to be worth it, since it changes a whole lot about how recipes are loaded, how parameters are passed to recipes, how recipes call other recipes, etc.

**Comment by DevilPepper** [comment]
Oh. I'm not sure how large the change is yet. I was hoping it'd be as simple as adding another location to look for recipes, scan for comments with attributes, and pass that along to the recipe loader... I should probably come back after I've looked at the source :sweat_smile:

The primary use-case is on my team, we have a terrible `gulp serve` that runs a handful of large tasks, including `gulp serve::ts` and `gulp serve::py`. They're very large scripts that would bloat the justfile. But if `just` looked in _just.d/_ for them, that'd be nicer for maintenance.

An added benefit to making recipes standalone scripts is that you can use existing linters, etc on them.

`mise` does something like this: https://mise.jdx.dev/tasks/file-tasks.html

One thing I _could_ do is define recipes for each script like so:

```just
serve-ts:
  sh just.d/serve-ts.sh
serve-py:
  sh just.d/serve-py.sh
```
and call it recipes.just and import it in the main justfile.

**Comment by casey** [comment]
I think the workaround of creating recipes for each script is pretty decent, and if they're executable, you can just do:

```jsut
serve-ts:
  just.d/serve-ts.sh
```

I think that auto-generating recipes from the contents of a directory is too big a change in the compiler to be worth it, but you could imagine something like this:

```just
[source: '/bar/foo.sh']
foo:
```

Where the source for a recipe is taken from a file on disk. However, I don't know if this is actually worth it. The workaround is so simple, and all an attribute would buy you would be the ability to use interpolations in the script.

I think I'm going to close this, but thanks for the issue! Things like this are always worth thinking about.
