### ISSUE TITLE
does not substitute arguments

### ISSUE THREAD

**Issue by IvanKirpichnikov** [casey/just#2551]
justfile:
```just
command arg = "default":
    {{ if arg == "default" { "echo 'default arg {{ arg }}'" } else { "echo 'not default arg {{ arg }}'" } }}
```

enter in console: `just command`

expected output:
```sh
echo 'default arg default'
default arg default
```

real output:
```sh
echo 'default arg {{ arg }}'
default arg {{ arg }}
```

**Comment by casey** [comment]
`just` doesn't perform `{{…}}` interpolation inside strings. You can use `+`:

command arg = "default":
    {{ if arg == "default" { "echo 'default arg " + arg + "'" } else { "echo 'not default arg " + arg + "'" } }}

See #11 for the issue. Don't look at how old it is T_T

**Comment by IvanKirpichnikov** [comment]
personally, it seemed to me that formatting strings should get rid of this kind of code. Well okay. Thanks for the help
