### ISSUE TITLE
why can't submodules take the parent schell?

### ISSUE THREAD

**Issue by IvanKirpichnikov** [casey/just#2554]
justfile
```justfile
set windows-shell := ["powershell.exe", "-c"]
mod b
```
b.just
```just
command:
   echo 1
```
Why should I install shell in b.just? I expected it to be taken from justfile.

**Comment by casey** [comment]
This is a current limitation of modules. See #2252. It should be fixed, eventually T_T

**Comment by IvanKirpichnikov** [comment]
T_T
