### ISSUE TITLE
Conditional Logic

### ISSUE THREAD

**Issue by runeimp** [casey/just#262]
Is there any conditional logic in Just? I'd like to see `ifeq` type of support added if it or some similar does not already exist. I couldn't find any reference and local testing suggests it's not a thing yet.

**Comment by jonringer** [comment]
you can call out to a script interpreter.

https://github.com/casey/just#write-recipes-in-other-languages

then you have the full power of a generic programming language at your fingertips.

**Comment by runeimp** [comment]
While that can be very useful in certain instances, I'm hoping to **not** write even more scripts to do what Make can do today. I love everything about how `just` improves on `make` but some features are still missing. I have to install Git Bash on all the target Windows systems anyway so having that as a dependency for `just`, while not ideal, is fine. If needs be I can install Cygwin with `make`. But that is way more involved than I'm looking for beyond setting up and maintaining a `Justfile` or `Makefile`. I've been using computers for over 30 years and it seems to me that cross platform automation really shouldn't be that hard at this point. Just is my hope for making that a reality in an easy migration path from Make.

**Comment by casey** [comment]
@runeimp, can you provide an example of what you would use `ifeq` for? Would you use it inside of scripts or outside of scripts?

**Comment by runeimp** [comment]
It would be for use in the Justfile only. A big problem I face is supporting Windows. Because of the drive letters I can't use consistent paths across OSs. Cygwin and it's derivatives treats `/path/to/thing` different than `/c/path/to/thing`. I can use an `ifeq` to adjust root paths as necessary per OS. It would also allow me to normalize the values returned from `uname -sm` for other needs as well as discussed in #263. There are other ways around this but I'd rather use `just` only and not rely on `make` or external scripts.

**Comment by casey** [comment]
Were you thinking of something inside of recipes, like this:

```
foo:
  if {{windows}}
    cp a C:\\some\directory
  else
    cp a /some/directory
  done
```

Or at the top level, like this:

```
path = if windows { "/c/some/directory" } else { "/some/directory" }

foo:
  cp a {{path}}
```

**Comment by runeimp** [comment]
Top level would be ideal for my use case. I much prefer setting variables and then referencing them as needed over logic inside the recipes themselves. But inside recipes like with `make` would be fine if that's easier.

**Comment by casey** [comment]
I'd like to implement something usable at the top level eventually, but for now you can write a shell script to have the effect you want.

Recipes are executed line-by-line, so by default you'll need line escapes for multi-line statements:

```make
foo:
	if [ "$OS" = 'WINDOWS' ]; then \
		cp a /c/some/directory; \
	else \
		cp a /some/directory; \
	fi
```

You can also include a shebang line (`#!...`) to execute a recipe with a different interpreter, in this case the `sh`, which should be present, in which case you don't need line escapes:

```
bar:
	#!/usr/bin/env sh
	if [ "$OS" = 'WINDOWS' ]; then
		cp a /c/some/directory
	else
		cp a /some/directory
	fi
```

**Comment by runeimp** [comment]
Sorry for the late reply. Yes, that and the functions help make that work rather well and is how I'm using going forward.  👍

**Comment by casey** [comment]
A lot of people want this, so I think it would be a good idea to add it.

The only Just type is the string, so adding this will require letting conditions be strings, adding a dynamic type system (which I'm opposed to, since I believe a dynamic type system for just will be worse in the long run), or adding a static type system (which I would like to do, but which is very hard).

So, given all that, I propose adding an `if-empty` construct:

```
foo := if-empty CONDITION { IF } else { ELSE }
```

`CONDITION`, `IF`, and `ELSE` are all arbitrary expressions. If `CONDITION` is the empty string, then it will evaluate as `IF`, otherwise it will evaluate as `ELSE`.

This means that if Just later gets a proper static type system, we can add `if` without having to change the semantics of `if-else`.

**Comment by casey** [comment]
I think `if-empty` is a good way to go, so I created a tracking issue: #696.

**Comment by casey** [comment]
It is done! See [my comment in #696](https://github.com/casey/just/issues/696#issuecomment-716923105) for more details. Thanks to all for requesting and discussing this feature.

**Comment by mmstick** [comment]
It doesn't appear that this was actually implemented (`ifeq` support).

Take this makefile:

```make
package_source:
ifeq ($(CLEAN),1)
	make clean
endif
ifeq ($(VENDOR),1)
	ischroot || make vendor
endif
```

Currently, the only way to achieve similar is to use shell

```
package_source:
    test {{env_var_or_default('CLEAN', '0')}} -eq 1 && just clean || true
    test {{env_var_or_default('VENDOR', '0')}} -eq 1 && (ischroot || just vendor) || true
```

Or if variables are passed directly to just

```
package_source:
    test {{clean}} -eq 1 && just clean || true
    test {{vendor}} -eq 1 && (ischroot || just vendor) || true
```

**Comment by casey** [comment]
This issue is for the top-level, outside of recipes. For inside recipes, I think using a shebang recipe is probably the best solution at the moment:

```
package_source:
  #!/usr/bin/env bash
  if [[ $CLEAN == 1 ]]; then
    make clean
  fi
  if [[ $VENDOR == 1 ]]; then
    ischroot || make vendor
  fi
```

**Comment by tmpm697** [comment]
In my use case I use `ifeq/else ifeq/endif` for condition `recipe` in Makefile, currently condition with `just` does not go outside of assigment `:=`
