### ISSUE TITLE
Missing Shared Library api-ms-win-crt-heap-l1-1-0.dll

### ISSUE THREAD

**Issue by runeimp** [casey/just#266]
I was working on a Windows 10 Pro box and it was giving me issues so I refreshed the install and now just isn't working. So a fresh install and fresh install of Git Bash and I'm now getting the error:

`just.exe: error while loading shared libraries: api-ms-win-crt-heap-l1-1-0.dll: cannot open shared object file: No such file or directory`

There had prior been several Microsoft Visual C++ Redistributables on the system that are currently not installed. Is one required to use the prebuilt binary on Windows?

I also tried downloading the binary again. Still get the same error though.

**Comment by runeimp** [comment]
Did more searching regarding just the DLL itself. Looks like it's often part of MS Office. Office was not installed prior. Though MS OneDrive was installed twice. Don't ask me why. I didn't setup the system.

Searched the C drive and found it on the current system under OneDrive. Don't know why `just` can't find it. Can the Rust app be made independent of any external DLLs?

**Comment by runeimp** [comment]
The previous error was when run from within Git Bash. When I try to run the executable from the normal Command Prompt I get a dialog box with:

just.exe - System Error
The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.

Hope that may help shed some light on the problem.

**Comment by jonringer** [comment]
Looks like what cargo linked against when it first built was removed. If you reinstall just it should likely fix the issue
```
cargo install just -f
```

**Comment by runeimp** [comment]
Thanks @jonringer but I didn't build that executable. It's one of the binaries from the release page and I don't have or want to install Rust on this computer if I can avoid it. If I do need to rebuild it myself can I cross-compile from Mac? I haven't played much with Rust at all and that was over a year ago when I did.

**Comment by casey** [comment]
Hmmm, interesting. Just to confirm, the binary was working on Windows 10 Pro before? The windows release binaries are built on AppVeyor with the `x86_64-pc-windows-msvc` target. I'm guessing that this is a case of a missing redistributable/library.

I believe that you'll need something like "Visual C++ Redistributable Package for Visual Studio 2013 (x64)"

If you can hold off on fixing the problem, I'm going to try to build a new version of just with MinGW, which is a different compiler and toolchain, which might not have the same dependencies.

**Comment by casey** [comment]
@runeimp Also, random question, since you're a windows user: Would you be interested in being able to write recipes using the same syntax as `.bat` files? Currently on windows just uses `sh`, which is where the dependency on git bash comes from. But, if there was interest from windows users I could allow recipes to be run using cmd.exe

**Comment by runeimp** [comment]
Just to be clear, I used to be a Windows user and freelance tech many years ago. I switched to OS X in 2007 and have been happily avoiding Windows except for gaming ever since. But as the Systems Integration Engineer are my current company I'm dealing with Windows much more often now and I'm looking for cross platform solutions. Write once, with conditional logic where necessary, and deploy to Linux, macOS, and Windows.

So, adding an additional syntax, just for Windows, does not help me. I already have a batch file that simulates what I was doing in my Makefile. Maintenance is a pain. Maintenance is much easier with a single solution. Even if it has conditional logic to avoid the inevitable differences between OSs that all supposedly support the POSIX standards. `make` is a POSIX standard. It is not included in Cygwin or any of it's derivatives by default. I don't believe even Ubuntu for Windows Linux Subsystem has it installed by default. Though I could be wrong about that. I can work around all of those issues. But I'd rather do it all with `just` as part of my deploy cycle prior to setup. It's so close to being that solution. I need Git Bash installed already so that dependency is no issue.

**Comment by runeimp** [comment]
My apologies if that all sounds a bit pissy. Wife is sick and I'm trying to get ready for work so I'm rushing a bit. Just trying to be as clear and concise as possible. I really do love how `just` works and appreciate all the work that goes into a project like this. Especially with people like me saying "what about this, and this." all the time.  👼

**Comment by casey** [comment]
Gotcha, yeah, I guess that being able to write recipes with `cmd.exe` as the shell wouldn't solve your use case.

No worries! I'm super happy to try to support your use case. Hope your wife is well soon :–)

I have no idea if it'll work, but if you're still having the same problem, try this binary: https://github.com/casey/just/releases/download/v0.3.4/just-v0.3.4-x86_64-pc-windows-gnu.zip

It's built using the MingGW toolchain, so may not depend on whatever's missing on your system.

**Comment by runeimp** [comment]
The Gnu binary works! A little surprised It's over twice the size of the MSVC version. But not relying on external libs, so that is perfectly fine with me! Thank you, so much! 👍 😃

**Comment by casey** [comment]
Excellent! Going forward I'll probably offer the GNU binary by default.

**Comment by abonander** [comment]
Searching the error and not just the DLL name yielded [this StackOverflow answer](https://stackoverflow.com/a/33274879/1299804). The Microsoft Visual C++ runtime is a part of Windows 10 now but it may have been mistakenly linking to a partially broken redistributable installed somewhere else on the machine. If you have MSYS2 or Cygwin installed, I recommend running `ldd just.exe` (on the MSVC version) to see what it's linking to.

I recommend running the update from the Microsoft knowledgebase article anyway as it might fix other software on the machine in the process, or prevent possible errors in the future.

**Comment by runeimp** [comment]
Sorry to reply so late. But finally ran `ldd just.exe` from within Cygwin and got back

```
	ntdll.dll => /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffe2f0c0000)
	KERNEL32.DLL => /cygdrive/c/WINDOWS/System32/KERNEL32.DLL (0x7ffe2ec60000)
	KERNELBASE.dll => /cygdrive/c/WINDOWS/System32/KERNELBASE.dll (0x7ffe2b5c0000)
	ADVAPI32.dll => /cygdrive/c/WINDOWS/System32/ADVAPI32.dll (0x7ffe2e420000)
	msvcrt.dll => /cygdrive/c/WINDOWS/System32/msvcrt.dll (0x7ffe2dde0000)
	sechost.dll => /cygdrive/c/WINDOWS/System32/sechost.dll (0x7ffe2e4d0000)
	RPCRT4.dll => /cygdrive/c/WINDOWS/System32/RPCRT4.dll (0x7ffe2deb0000)
	SHELL32.dll => /cygdrive/c/WINDOWS/System32/SHELL32.dll (0x7ffe2c940000)
	cfgmgr32.dll => /cygdrive/c/WINDOWS/System32/cfgmgr32.dll (0x7ffe2b830000)
	ucrtbase.dll => /cygdrive/c/WINDOWS/System32/ucrtbase.dll (0x7ffe2b4c0000)
	shcore.dll => /cygdrive/c/WINDOWS/System32/shcore.dll (0x7ffe2c700000)
	combase.dll => /cygdrive/c/WINDOWS/System32/combase.dll (0x7ffe2ed10000)
	bcryptPrimitives.dll => /cygdrive/c/WINDOWS/System32/bcryptPrimitives.dll (0x7ffe2bfd0000)
	windows.storage.dll => /cygdrive/c/WINDOWS/System32/windows.storage.dll (0x7ffe2b880000)
	shlwapi.dll => /cygdrive/c/WINDOWS/System32/shlwapi.dll (0x7ffe2e170000)
	GDI32.dll => /cygdrive/c/WINDOWS/System32/GDI32.dll (0x7ffe2dff0000)
	gdi32full.dll => /cygdrive/c/WINDOWS/System32/gdi32full.dll (0x7ffe2c170000)
	msvcp_win.dll => /cygdrive/c/WINDOWS/System32/msvcp_win.dll (0x7ffe2c050000)
	USER32.dll => /cygdrive/c/WINDOWS/System32/USER32.dll (0x7ffe2c7b0000)
	win32u.dll => /cygdrive/c/WINDOWS/System32/win32u.dll (0x7ffe2c150000)
	kernel.appcore.dll => /cygdrive/c/WINDOWS/System32/kernel.appcore.dll (0x7ffe2b410000)
	powrprof.dll => /cygdrive/c/WINDOWS/System32/powrprof.dll (0x7ffe2b450000)
	profapi.dll => /cygdrive/c/WINDOWS/System32/profapi.dll (0x7ffe2b4a0000)
	VCRUNTIME140.dll => /cygdrive/c/WINDOWS/SYSTEM32/VCRUNTIME140.dll (0x7ffe254a0000)
	CRYPTBASE.DLL => /cygdrive/c/WINDOWS/SYSTEM32/CRYPTBASE.DLL (0x7ffe2ae80000)
```

`VCRUNTIME140.dll` is the main culprit. But everything in the Windows/System32 folder may have been missing after the fresh reinstall of Windows 10 64-bit. I don't have access to that machine currently to verify. Not sure how much the 64-bit version of Windows relies on the System32 folder for 32-bit apps. I expect most of it's AMD64 (which should supports 32-bit code) is in SysWOW64.
