### ISSUE TITLE
Add Description to recipe

### ISSUE THREAD

**Issue by jonringer** [casey/just#272]
If you're using just as a CLI for a project, it would be an improvement for `just --list` to also give you a description of the recipe.

Not sure what this would look like in the justfile, but you would see something like this:
```
$ just --list
Available recipes:
   build CONFIG            # build project, CONFIG=(Debug|Release)
   test TYPE               # run tests, runs all by default. TYPE=(all | unit | e2e)
```

**Comment by jonringer** [comment]
I don't feel super strongly how this would appear in a justfile, but here's my first idea:
python docstring-ish
```
##  build project, CONFIG=(Debug|Release) ##
build CONFIG:
     ........
```
The advantage of using this, is that if we were to implement bash style comments, it would still be ommited, it would just be a "special" comment.

We could also leave off the ending ##, but then it doesn't feel as "framed", like string without an ending "
```
##  build project, CONFIG=(Debug|Release)
build CONFIG:
     ........
```

The pair of ##'s could also act like raw string, in which the description could extend multiple lines, but i feel that it impacts the conciseness you got with a single line:
```
$ just --list
Available recipes:
   build CONFIG            # builds the project and places build artifacts in the build dir
                             CONFIG=(Debug|Release)
   test TYPE               # run tests, runs all by default. TYPE=(all | unit | e2e)

#justfile

##  builds the project and places build artifacts in the build dir
CONFIG=(Debug|Release) ##
build CONFIG:
     ........
```

**Comment by jonringer** [comment]
Oh wow, i feel dumb, this is already accomplished with comments before the recipe. I guess I must have looked this over, sorry.

**Comment by casey** [comment]
No worries!
