### ISSUE TITLE
Variable Assignment within Recipes

### ISSUE THREAD

**Issue by IndianBoy42** [casey/just#28]
This might be slightly outside the originally intended use-case, but I am trying to use a justfile to automate sorting of tv shows that I rip/download

Originally I had a shell script that did this, there I used sed to extract the show, season and episode info from filenames, and stored them in separate variables. However, it seems that I cannot assign to variable within recipes

```
filename = "Assigning Variables here works"

sort:
    show = "Assigning Variables here doesnt work"
    @echo {{show}} # This tells me 'error: variable `show` not defined'
```

This feels like an obvious feature to have

**Comment by casey** [comment]
Hi there!

That's right, assignment within recipes isn't currently supported. The reason they aren't is that within recipe bodies the text is totally freeform. `show = "some text"` could be calling a command called `show` with the arguments `=` and `some text`, so just doesn't try to parse it.

On thing you can do is switch to a shebang recipe and use plain shell variables:

```
sort:
    #!/bin/sh
    show="some text"
    echo $show
```

Also a shebang variable that calls the shell will have the same rules as a normal shell script, so no echoing commands and no stopping if a command fails.

**Comment by casey** [comment]
Marking this as wontfix for now. At some point in the distant future this could be implemented by writing a posix compatible shell library in rust which allows line-by-line execution.
