### ISSUE TITLE
Declaring a variable inside a recipe

### ISSUE THREAD

**Issue by rkumar** [casey/just#282]
I can declare a variable outside a recipe (top level) but am unable to do so inside a recipe. Let's say I pass in a source file name on the command line. Now i wish to create a target file name within my recipe.

    build file:
       target = "{{file}}.mp3"

The above assignment does not seem to work within a recipe.

How do i accomplish the same.

**Comment by casey** [comment]
This has come up before, and the current behavior is definitely less then ideal.

The way that just works is that it passes each line to a new instance of `sh`. So when you assign a variable as per your example, the variable is only set for that single line.

One workaround for this is to turn your recipe into a shebang recipe. Shebang recipes are extracted and then passed in their entirety to an interpreter, so you can use all the features of that interpreter as normal, like so:

```
sort:
    #!/bin/sh
    set -e
    show="some text"
    echo $show
```
