### ISSUE TITLE
zero variadic arguments

### ISSUE THREAD

**Issue by gregwebs** [casey/just#283]
I would like a command to take a variadic number of arguments, including 0 arguments. Besides this being required for my use case, I think its better to explicitly name required arguments (although I can see the appeal in some cases of avoiding this).

Is there any reason not to allow zero arguments? Should we also add a validator? i.e. `command +ARGS+1:` would require 1 or more args.

I am willing to help implement this if I can get sign-off on the design.

**Comment by casey** [comment]
You can actually already do this using default arguments; for example:

```
foo +bar="default":
  echo {{bar}}
```

```
$ just foo
echo bar
bar
$ just foo a b c
echo a b c
a b c
```

I think I should add an example to the readme, so that it's more discoverable.

**Comment by gregwebs** [comment]
nice! I would like to provide *zero* arguments to echo though. I think it works to do

```
foo +ARGS='':
    variadic_command {{ARGS}}
```

Do you want me to send a PR with these 2 examples?

**Comment by casey** [comment]
Yup, that's the way to do it. I'm about to land #285 which provides an example.
