### ISSUE TITLE
dotenv support

### ISSUE THREAD

**Issue by cldershem** [casey/just#287]
I use dotenv to manage my environment variables for most of my projects when working locally. It would be great if I could have just source that file before it looks for something in the environment.

I found a few crates for dotenv support in rust, but this was the most used by far, https://github.com/purpliminal/rust-dotenv . I would be more than glad to take a look at implementing this if anyone is interested and wouldn't mind pointing me in the right direction.

**Comment by casey** [comment]
To clarify, would this be a file that `just` would source which would contain environment variables? Or would it contain `just` variables? Can you give an example of how you'd like it to work?

**Comment by cldershem** [comment]
It would contain the environment variables. `dotenv`, is just a file with environment variables that gets sourced by different things before they run. In something like `zsh` you can have it auto source it when you `cd` between directories for projects, it makes it so you don't forget and clutter up your actual environment. Essentially, `just` would check if there is  `.env` file present, if so, it would then `source` or `export` all the variables listed into the shell before it runs commands.

**Comment by casey** [comment]
Is there a compelling reason not to use `just` export variables instead? I'm not saying there isn't, but I want to make sure that this isn't best served by an existing feature before considering adding a new one.

For example:

```make
export SOME_VAR = "hello"
export SOME_OTHER_VAR = "world"
```

`SOME_VAR` and `SOME_OTHER_VAR` will both be available to all child processes.

**Comment by cldershem** [comment]
The only reason is so that I don't have to maintain the same list of environment variables in two places (giving less room for mistakes and so I can check my `justfile` into source control). `dotenv` is supported by quite a few things, it's like `.gitignore` or `.editorconfig`, is it absolutely required, no, but is it super convenient..yes.

As I mentioned before, I'd be more than happy to help make his happen, but I might need to be pointed in the right direction. I have a pretty good idea of how the feature should work, I just haven't had a chance to read through all of the `just` code yet.

**Comment by casey** [comment]
I think those things are reasonable, but I don't think that `rust-dotenv` is ready for primetime. The errors do not distinguish between a `.env` being missing (which is totally normal, as some users wont' have one) and syntax errors in a `.env` file.

Also, I'm unsure about loading dotenv supplied variables into the `just` processe's environment, as opposed to just child process environments.

Given that, I don't think that I'm comfortable adding a dependency on `rust-dotenv`.

**Comment by cldershem** [comment]
That's completely understandable, I was really just hoping to show the usefulness with the merge request, more-so than hoping to get it accepted. I just got a little busier than I'd hoped last night and didn't get to finish it up. I also ran into the same thing with the errors, which is why I was having trouble writing proper tests.

It really shouldn't be an incredible amount of work to implement by hand. Check if `./.env` exists, check each line against your `overrides_re`, load it into `overrides`. At least, that's how I'm readying the code. I'm of the opinion that whatever environment variables are closest the command should take precedence, meaning that if a variable is defined in `justfile` it would override the one in `.env`.

I will hopefully have some time this weekend to take a look into implementing this. If you've got and advice or opinions, please let me know. I've been into Rust for a while, but haven't contributed a whole lot of Rust code to other projects.

**Comment by casey** [comment]
I'm a little worried though that if `rust-dotenv` is what the rust community at large uses, then inconsistencies between it and whatever implementation `just` uses will be confusing or annoying.

I just opened https://github.com/purpliminal/rust-dotenv/issues/74 to see if they would be amenable to exposing the variables before loading them. The other issue I was worried about can be worked around, since we can just check for `std::io::ErrorKind::NotFound` if the file wasn't found.

**Comment by runeimp** [comment]
It's been almost two months since the issue was submitted to `rust-dotenv` with no response from them. Any chance on internally sourcing the file automatically? I'm doing that for now via `sh` scripting the recipe.

**Comment by casey** [comment]
Just pinged the issue again! If I can't get the feature upstream, then I guess I'll add it to a fork.

**Comment by ekrizdis** [comment]
I've opened a PR which adds the features needed to integrate dotenv support.

**Comment by casey** [comment]
I've opened a PR which adds the features needed to integrate dotenv support.

**Comment by casey** [comment]
Dotenv changes were merged upstream, and the feature has been implemented in #306!

**Comment by casey** [comment]
I just published a new version with the latest changes to cargo. Prebuilt binaries will be available here once they're built: https://github.com/casey/just/releases/tag/v0.3.9
