### ISSUE TITLE
When == isn't equality

### ISSUE THREAD

**Issue by runeimp** [casey/just#290]
Just want to make a note in case someone else hits this _GOTCHA_. The `#!/usr/bin/env sh` support is great. But remember that on certain Linux distros and possibly other POSIX systems that even though `sh` usually is a reference to Bash it is sometimes a reference to Dash or other shells with a more _traditional_ syntax where `if [ 'this' == 'that' ]` is not allowed and `if [ 'this' = 'that' ]` is the proper syntax. And of course you can specify `#!/usr/bin/env bash` specify in almost all cases (including Git BASH on Windows). But `sh` is more portable and using a single `=` is also supported in all versions of Bash for testing equality. Just wanted to put that out there.  👼

**Comment by casey** [comment]
There are slight differences between `[[...]]` and `[...]`, but you're right that `=` is more portable, since you might get dash, or bash might not be installed. (Or on the BSDs you might get ash.)
