### ISSUE TITLE
Unknown start of token error when using CRLF line endings on Windows

### ISSUE THREAD

**Issue by casey** [casey/just#291]
Reported by @runeimp in #3:

> In Windows 10 Pro with just v0.3.5 I get
> 
> ```
> error: Unknown start of token:
>   |
> 1 | #
>   | ^
> ```
> 
> This only happens when the file is using CRLF instead of just LF. This suggests that just is currently not EOL agnostic.
> 
> To some give context, the Justfile is being created on macOS 10.12.6. But in Git BASH on Windows there is an automatic conversion from LF to CRLF. If I make changes and commit back the default is to convert the file back to LF when pushed to a remote server, if I'm not mistaken. That can be disabled but it is the default as I understand it.
> 
> You can double-check, and change to and from, different line endings using Notepad++ on Windows.

**Comment by casey** [comment]
@runeimp, could you upload the justfile in question as a gist, so I can check it out and debug? Thanks!

**Comment by runeimp** [comment]
It can be as little as a hash with a newline only. Literally

```
#

```

I created a gist for you at https://gist.github.com/runeimp/7a406b9f0cc711e4622d2d2e492d57a7

Adding more characters doesn't seem to matter. Though sometimes it does works anyway in other Justfiles. Very odd. Maybe when there is a mix of CRLF and just LF somehow?

**Comment by casey** [comment]
Fixed! Looks like `$` in regexes only matches `\n` and not `\r\n`. I published a new version with the fix. Binaries will appear [on the releases page](https://github.com/casey/just/releases/tag/v0.3.6) when they're built by travis and appveyor.

Thanks for the bug report!
