### ISSUE TITLE
Exclamation in comments generates error: Unknown start of token

### ISSUE THREAD

**Issue by runeimp** [casey/just#294]
Now with v0.3.6 (worked in prior 0.3.x versions) I'm getting 

```
error: Unknown start of token:
  |
3 | # Cleanup around here!
  | ^
```

In any Justfile comment that has an exclamation in it that isn't right after the comment marker. If I have it right after the comment marker I get

```
error: `#!` is reserved syntax outside of recipes
  |
3 | #! Cleanup around here
  | ^
```

The second one makes sense, after thinking about it and realizing it's part of output. Was the change to not allow exclamations in comments intentional or is this a bug?

### Example Justfile

```
# Line 1 Comment

# Cleanup around here!
```

**Comment by casey** [comment]
Thanks for the report, and sorry it took me so long to fix it!

I just pushed out a release with the patch:
https://github.com/casey/just/releases/tag/v0.3.7

**Comment by runeimp** [comment]
Thanks @casey !  👍
