### ISSUE TITLE
Support in Kakoune editor

### ISSUE THREAD

**Issue by TeddyDD** [casey/just#298]
Hi. I just wanted to let you know that [Kakoune](https://github.com/mawww/kakoune) editor has  built-in support for justfiles (since [this](https://github.com/mawww/kakoune/commit/bc876fa4b6e493df705c07d852bfc13db9ba7f80) commit) 

![zrzut ekranu z 2018-02-01 16-56-14](https://user-images.githubusercontent.com/4397533/35772527-0e18b8a6-0941-11e8-8bed-0d86ad2df7d0.png)

Cheers 🍺

**Comment by casey** [comment]
Super rad! Thank you very much :)

**Comment by casey** [comment]
I'm going to add a mention to the readme.

**Comment by blaggacao** [comment]
Just curious if there is also a `just.kak` plugin which makes the just commands directly available in kakoune?

**Comment by casey** [comment]
I think there's only a filetype plugin, at the moment.

**Comment by blaggacao** [comment]
Interesting, I'll try instructions of that comment there: https://github.com/mawww/kakoune/commit/bc876fa4b6e493df705c07d852bfc13db9ba7f80#commitcomment-39787360

**Comment by casey** [comment]
Good luck! If you need help, feel free to ping me or create a new issue. Just supports listing recipes in a format that's intended to be amenable to shell completion scripts and other utilities. If you do `just --summary` it will print the name of every recipe, separated by a space, which might be useful if you want to introspect the contents of the justfile in a Kakoune plugin.

**Comment by blaggacao** [comment]
Nice! Is there anything similar for introspecting the arguments?

**Comment by blaggacao** [comment]
I just improved the regexes: https://github.com/mawww/kakoune/pull/3732

**Comment by casey** [comment]
Awesome!
