### ISSUE TITLE
Wait for child process to exit on SIGINT

### ISSUE THREAD

**Issue by bheisler** [casey/just#302]
Thanks for working on Just, I've found it quite useful since I started using it.

I've noticed that if the user presses Ctrl-C to kill a command while Just is running it, Just terminates immediately - without waiting for the child process to end. That leaves the child process orphaned, but still attached to the terminal. This is especially annoying if the child process doesn't handle Ctrl-C correctly and continues writing output - you have to use `ps` to find and `kill` it.

It would be nice if Just caught Ctrl-C's and waited for the current child process to terminate before exiting itself.

**Comment by casey** [comment]
Glad you like it!

Hmm, it's not clear to me why that behavior would be better. If `just` waits for the child process to exit, and the child process doesn't handle ctrl-C correctly, then you still have to `ps` and `kill` it. Or am I missing something?

**Comment by bheisler** [comment]
Well, I admit that my use-case is a little unusual here. The process in question is a unit test runner that interprets Ctrl-C as a failed test. If I run the tests from the terminal directly, I can hold Ctrl-C until it runs out of tests and exits on its own, but I can't do that if `just` terminates immediately, because that stops the Ctrl-C signal from reaching the test runner.

More generally, I think users would expect this behavior and it's generally best to conform to user expectations where reasonable. Waiting for the child process to finish makes `just` behave the same way as if I had simply run the commands myself by pasting them into the terminal. It also has the benefit of making it very clear to the user when the process finally terminates, because they don't see the terminal prompt again until it does.

**Comment by casey** [comment]
Gotcha, that sounds reasonable.

A simple implementation would be to install a signal handler that ignores SIGINT before running a recipe, and then uninstall it once that recipe is done. It looks like [Detegr/rust-ctrlc](https://github.com/Detegr/rust-ctrlc) would be good for this.

Would you be interested in submitting a PR? This would be a pretty good first issue, for you or for anyone interested in contributing to `just`.

I've actually been meaning to make a tag for good first issue, so I think I'll do that now, and also tag this issue.
