### ISSUE TITLE
dotenv variables not recognized by env_var() or env_var_or_default()

### ISSUE THREAD

**Issue by runeimp** [casey/just#309]
First thanks for the `.env` file support! :smiley:

I've found that both `env_var()` and `env_var_or_default()` act as if variables within a `.env` file don't exists. With `env_var_or_default()` overwriting variables set in my `.env`. :frowning:

**Comment by casey** [comment]
Ah, I see. I made it so that environment variables aren't loaded into `just`'s environment, only the environment of child processes. However, it seems reasonable that `env_var` / `env_var_or_default` would get environment variables in a .env file.

**Comment by casey** [comment]
Hey! Sorry, I was going to try to fix another issue really quickly before pushing a release, but I haven't gotten around to it yet, so I'll just push a release now. Binaries should appear here once they're built by CI: https://github.com/casey/just/releases/tag/v0.3.10
