### ISSUE TITLE
Is justfile-finding-when-in-symlinked-directory behavior correct?

### ISSUE THREAD

**Issue by casey** [casey/just#320]
Consider this!

```
$ mkdir foo
$ printf "default:\n  echo foo" > foo/justfile
$ mkdir foo/bar
$ ln -s foo/bar baz
$ printf "default:\n  echo outer" > justfile
$ cd baz
$ just
echo foo
foo
```

Here, even though the users shell will show `baz` as the current working directory, just uses the justfile in foo, since just follows `..` to go upwards to the justfile.

This behavior is surprising to me, and I'm considering changing it to pop elements off of the current working directory, which would lead to finding the outer justfile instead.

**Comment by joshuawarner32** [comment]
Maybe you already know all this, but let me try and add some color here:

Working directories are complicated.

On all three major platforms (windows, mac, linux), the current working directory (cwd) is actually tied to an inode on disk (err... a vnode in memory), not a path - which means that when you `cd baz`, the _actual_, _real_ ("physical") working directory, as far as the operating system is concerned, is `foo/bar`.  In fact, you can do crazy things like launch a process and then `mv` it's cwd somewhere else - the process will continue working, and all it's relative path accesses will be relative to the _new_ location!

Some shells _also_ set the PWD variable to be the "logical" working directory (`baz`, in this case) - and will sometimes display this in place of the "physical" working directory, as would be returned by the getcwd syscall.

You can see the difference between physical and logical with the `pwd -P` and `pwd -L` commands.  All `pwd -L` does is `echo $PWD`, but `pwd -P` actually calls the `getcwd` syscall.

The kernel will always use the physical cwd to resolve relative paths, never the logical one - which means if you would have to implement your own ".." path resolution.

Note, not all shells consider the logical and physical cwd differently.  For example, my favorite shell, `fish`, aggressively sets the PWD variable to the result of `getcwd()`, and so when _I_ run your example, my shell shows `foo/bar` as the cwd at the end.

**Comment by casey** [comment]
Hmmm, given the complexity, I'm thinking that `just` trying to do something different is probably a bad idea, even if it can be reasonably argued to be better behavior.

Working directory behavior is weird, but at least it's consistent and there's a model you can use to understand why it's weird.

**Comment by casey** [comment]
Current OS behavior sucks, but trying to buck the trend is probably hopeless, so I'm going to close this.

Thanks again @joshuawarner32 for the nice explanation!
