### ISSUE TITLE
Subshell Parsing Errors

### ISSUE THREAD

**Issue by runeimp** [casey/just#327]
I'm getting several errors because of a bash subshell I'm launching in my Justfile. If I have

```sh
BIN_VERSION = "$(grep -E '^__version__' my_script.py | cut -d"'" -f2 | cut -d\" -f2)"
```

 I get

```sh
error: Unknown start of token:
  |
4 | # BIN_VERSION = "$(grep -E '^__version__' my_script.py | cut -d\" -f2 | cut -d\' -f2)"
  |                             ^
```

when I simply run `just` on the command line. Also noticed that `cut -d"'" -f2` is getting translated to `cut -d\" -f2`. Probably just normalized output for backtrace but thought I'd point it out.

If I change it to

```sh
BIN_VERSION = "$(grep -E '^__version__' my_script.py | cut -d\" -f2 | cut -d\' -f2)"
```

I get

```sh
error: `\\'` is not a valid escape sequence
  |
4 | BIN_VERSION = "$(grep -E '^__version__' my_script.py | cut -d\" -f2 | cut -d\' -f2)"
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If I try using backticks instead of POSIX `$()` with

```sh
BIN_VERSION = "`grep -E '^__version__' my_script.py | cut -d"'" -f2 | cut -d\" -f2`"
```

I get

```sh
error: Unknown start of token:
  |
6 | # BIN_VERSION = "`grep -E '^__version__' my_script.py | cut -d\' -f2`"
  |                            ^
```

Traceback is truncated?

Using backticks with

```sh
BIN_VERSION = "`grep -E '^__version__' my_script.py | cut -d\" -f2 | cut -d\' -f2`"
```

I get the same error as the 2nd example.

I fixed it by calling a script instead of subshell scripting but all of the examples work on the command line. It seems like `just` may be parsing the contents of the subshell instead of running it and accepting its output? This seems to have something to do with the formatting of the cut statements. If I remove them I don't get errors. Quoting issues most likely.

This is with `just v0.3.12` on `macOS 10.13.5`. I haven't tried this on other versions or systems yet.

**Comment by casey** [comment]
Thanks for the bug report! Could you share your entire justfile, or at least enough to get the error, in a gist? I couldn't reproduce it with just a snippet. I'm using v0.3.12, so I don't think the version is the issue.

**Comment by casey** [comment]
Thank you!

Try the following:

```
BIN_VERSION = `grep -E '^__version__' my_script.py | cut -d\' -f2 | cut -d\" -f2`
```

You can use backticks to execute commands directly, without needing to do string interpolation.

I'm not 100% sure of the delimiters in my_script.py, so it may need to be tweaked.

Does that work?

```
error: `\\'` is not a valid escape sequence
```

I'll definitely do something about the extra slash in that message, since it's a bit confusing.

**Comment by runeimp** [comment]
Yep, that works! 😃

**Comment by casey** [comment]
Awesome!
