### ISSUE TITLE
Backslash in windows paths?

### ISSUE THREAD

**Issue by Boscop** [casey/just#332]
When I declare a variable in a justfile like `foo = 'C:\bar\baz'` and later use it in a recipe, e.g. in a `cp` command, it gives an error like `file 'C:barbaz' not found` because it removed the backslashes for some reason.

It works when I replace backslashes by forward slashes but what's the right way to use backslashes?

**Comment by casey** [comment]
Currently, `just` uses sh, the Unix shell to execute commands, which on Windows comes with a compatibility layer to translate unix-style forward slash delimited paths into windows-style backslash delimited paths. So, right now Unix style paths should be used in recipes.

For the c drive, I think it'll be at `/c`. Relative paths should work if you replace backslashes with forward slashes.

**Comment by casey** [comment]
I think the solution I'm leaning towards here is to allow a justfile-wide configuration option that determines the shell that is used to execute commands.

So you could do something like the following to use cmd.exe:

```
set shell := ["cmd.exe", "/C"]

foo:
  dir
```

So closing in favor of some combination of #361 and #326.
