### ISSUE TITLE
Running just from a justfile doesn't work. just.exe hangs at full cpu usage

### ISSUE THREAD

**Issue by Boscop** [casey/just#333]
I have a recipe like this:
```
reamap_proj_dir = 'D:/projects/vstplugins/reamap'
reamap_just_install = reamap_proj_dir + '/install'

reamap: reacfg-install
    just {{reamap_just_install}} # build and install dll

[...]
```
But it hangs with the spawned just.exe using full cpu of one core, and never finishes. Why?

Also, how can I use backslashes in the path above? I get "error: `\p` is not a valid escape sequence"..

**Comment by casey** [comment]
I think you'll need to double up backslashes, as in `\\`.

I believe what's happening here is that `reamap_just_install` doesn't contain a justfile, so `just` is looking upwards, finding the current justfile, and calling itself recursively in an infinite loop.

**Comment by Boscop** [comment]
No, the current justfile is not upwards of that. It's a separate sister dir.
And `reamap_proj_dir` contains the justfile. `install` is the name of the recipe it should execute.
Any idea why it's not working then :)

**Comment by casey** [comment]
Hmmm, try `just -v` for verbose output. Hopefully it'll give a clue as to what it's doing.
