### ISSUE TITLE
How to set RUSTFLAGS env var only for one recipe?

### ISSUE THREAD

**Issue by Boscop** [casey/just#335]
How to set RUSTFLAGS env var only for one recipe? (Not for all)

(On Win 8.1)

**Comment by Boscop** [comment]
I tried
```
prod: web-deploy
    RUSTFLAGS="-Ctarget-feature=+crt-static -Ctarget-cpu=haswell"
    cargo build --release
```
but the resulting .exe **STILL** links dynamically to vcruntime140.dll!

I also tried:
```
prod: web-deploy
    export RUSTFLAGS="-Ctarget-feature=+crt-static -Ctarget-cpu=haswell"
    cargo build --release
```
same result :/

**Comment by casey** [comment]
Good question! This seems to come up a bit, so the behavior of `just` is not particularly intuitive. `just` executes each line with a separate shell, so exported variables don't persist from one line to the next. You have a few options:

To export the same flags to all recipes:

```make
export RUSTFLAGS="-Ctarget-feature=+crt-static -Ctarget-cpu=haswell"

prod: web-deploy
    cargo build --release
```

To export the same flags to a single recipe:

```make
prod: web-deploy
    RUSTFLAGS="-Ctarget-feature=+crt-static -Ctarget-cpu=haswell" cargo build --release
```

**Comment by casey** [comment]
One option is to turn it into a shebang recipe, like so:

```
prod: web-deploy
    #!/usr/bin/env sh
    export RUSTFLAGS="-Ctarget-feature=+crt-static -Ctarget-cpu=haswell"
    cargo build --release
    # more lines here
```

Shebang recipes are extracted into a file and run with the given interpreter, not line-by-line, so exports will affect all later lines.

**Comment by Boscop** [comment]
Does that work on Windows, too? (GitShell / Powershell from GitHub Desktop for Windows)

**Comment by casey** [comment]
I'm not sure, but I think it should. Let me know if it doesn't and I can hopefully help debug. I don't have a Windows box though, so my ability to test is limited.

**Comment by Boscop** [comment]
Btw, if one recipe depends on multiple others, should they be separated by spaces 
(like `package: cfg prod`)?

**Comment by casey** [comment]
Yup, that's right.
