### ISSUE TITLE
Command evaluation with backticks is not supported for recipe arguments

### ISSUE THREAD

**Issue by steveej** [casey/just#336]
This could either be a bug report or a feature request, depending if this was meant to be supported already or not :laughing: In any case(y), thanks for writing just!

### Recipe

```make
mwe arg=`echo another default value`:
    echo {{arg}}
```

### Output
```bash
$ just mwe        
error: Expected string or raw string, but found backtick
   |
46 | mwe arg=`echo another default value`:
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by casey** [comment]
Puns are always appreciated! And you are very welcome ^__^

Thank you for the issue!

I believe that when I originally added default values I kept it to strings and raw strings just to be conservative. I'm not opposed to adding it, although I'm grinding really hard on another project, so I'll be unlikely to do it myself, unfortunately. I'm quite happy to mentor and help as needed, and I think this would make a great first issue.

Can you describe your use case for this? It might give me a better idea of how the feature would be used, and if there might be a better or different alternative.

I think the implementation is straightforward. Recipes with parameters may not be depended upon by other recipes, so they always run first or not at all, backticks in parameters can just be evaluated from left to right, before the recipe starts executing.

**Comment by casey** [comment]
Fixed in #400, cutting a release soon!

**Comment by steveej** [comment]
@casey yay, really looking forward to using this! thank you!

**Comment by casey** [comment]
You're totally welcome!
