### ISSUE TITLE
Multiple justfiles in same dir?

### ISSUE THREAD

**Issue by Boscop** [casey/just#339]
Is it possible to have multiple justfiles in the same dir? How to disambiguate them?

**Comment by casey** [comment]
Just supports `-f` / `--justfile` for selecting which justfile should be used, which must be paired with `--working-directory` to set the working directory. So, if you have `foo.justfile`, you can invoke it with `just -f foo.justfile -d .`

I'm not entirely sure I made `--justfile` require `--working-directory`, so let me know if that's too annoying.

**Comment by Boscop** [comment]
Thanks. Yeah, I think it should default to `.` as working directory if the arg is not specified.
