### ISSUE TITLE
Allow `--justfile` without `--working-directory`

### ISSUE THREAD

**Issue by casey** [casey/just#340]
Currently, the `--justfile` requires the `--working-directory` flag to also be passed. I think I did this out of an overabundance of caution. It should be changed so that the working directory defaults to same directory the `justfile` passed with `--justfile` is in.

This is a great first issue ^__^

**Comment by mattg-sigsci** [comment]
is this done now? looks like there are a few commits and a test to verify that --working-directory is optional.

**Comment by casey** [comment]
The current test only checks that the flag is optional, it needs a test that verifies that the working directory when --working-directory isn't passed is correct, i.e. the same as the directory the justfile is in.

**Comment by casey** [comment]
This just landed in #392. I'm going to wait until #390 lands to cut a release, since it's super close.
