### ISSUE TITLE
It is not obvious how (or possible at all?) to escape a literal '{{' and '}}' inside a recipe

### ISSUE THREAD

**Issue by rollcat** [casey/just#352]
Couldn't find anything in the readme, and all the possible attempts at `\{{` and so on have failed (single quotes, double quotes, one backslash, two, more backslashes, etc).

This is problematic when combining with other tools that use `{{ }}`, such as inline Jinja or Go templates (the latter extensively used by Docker).

**Comment by casey** [comment]
Out of curiosity, what's your use-case?

**Comment by rollcat** [comment]
> Out of curiosity, what's your use-case?

A `Justfile` in my home directory is pushing away the old `Makefile` ;) one of my recipes pulls latest tags on each known Docker image:

```makefile
docker-update:
       docker image list \
               --format '{{.Repository}}{{if ne .Tag "<none>"}}:{{.Tag}}{{end}}' \
               | xargs -r -n1 docker pull
```

I tend to push a lot of `make` to automate the mundane parts of maintaining Docker stuff, and the `{{` & `}}` stuff crops up all over the place - the alternative is usually to write twice as much `sed` and `awk`.

> You can do `{{ '{{' }}` or `{{ "{{" }}`.

Cool, this works, but it's getting extremely verbose and unreadable even with this trivial example:

```makefile
docker-update:
	docker image list \
	--format '{{"{{"}} .Repository {{"}}"}} {{"{{"}} if ne .Tag "<none>" {{"}}"}}:{{"{{"}} .Tag {{"}}"}}{{"{{"}} end {{"}}"}}' \
		| xargs -r -n1 docker pull
```

Honestly I don't know what would be the best solution here, but for reference:
- Go's template package has the same problem, and seems to choose to ignore it.
- Jinja additionally supports `{% raw %} ... {% endraw %}` blocks, but the `{% ... %}` syntax is a core part of the language already. Django has something similar.

I love it how `just` applies only very little magic, and wherever it happens (like with `#!`), it feels natural and only adds flexibility. The `!raw` magic would kill it:

```makefile
!raw
docker-update pattern:
	docker image list \
		--format '{{.Repository}}{{if ne .Tag "<none>"}}:{{.Tag}}{{end}}' \
		| grep '{{ pattern }}' \
		| xargs -r -n1 docker pull
```

**Comment by casey** [comment]
Yeah, I agree, `{{ '{{' }}' is grody >_<

I just tried it, and `just` ignores an unmatched `}}`, so I think you can use `}}` directly as-is.

So that leaves `{{` >:]

Interestingly enough, the just parser already rejects empty interpolation sequences: `{{}}` in a recipe produces an error. This means that we could also translate `{{}}` to `{{`. So `{{}}}}` in a recipe would become `{{}}`. This is preeeeeeetty weird though. I'm also tempted to consider this a bug, since a user might delete the contents of an interpolation, or write a placeholder interpolation or something, while editing a recipe, and having just reject the justfile seems silly. On the other hand, an empty interpolation might be a sign of a bug in a user's recipe, or that they wanted the literal text `{{}}`, but will get nothing instead.

Of the other options, I think doubling is probably the least bad: `{{{{` -> `{{`. Like I said, this would mean that you couldn't put `{{` at the beginning inside of an interpolation, and `{` is often used for dictionary syntax. However, you could always just put a space `{{ {{`, so that's not much of an issue. And also, `{{..` would be, I guess, a dictionary with a dictionary key: `{{a:b}: 2}` which is not at all common.

So that would mean that your recipe would look like this:

```make
docker-update:
       docker image list \
               --format '{{{{.Repository}}{{{{if ne .Tag "<none>"}}:{{{{.Tag}}{{{{end}}' \
               | xargs -r -n1 docker pull
```

Which feels pretty good. What do you think?

**Comment by casey** [comment]
Also, I just opened #354, to make having a user-level justfile easier (as opposed to project-level). This would make it easier to call you user-level justfile, without having to pass the `-f` and `-d` flags, or having the user-level justfile conflict with project-level ones. Let me know if you think it'd be useful!

**Comment by rollcat** [comment]
Oh, found the perfect solution:

```makefile

docker-update:
	docker image list \
	--format '{{ '{{ .Repository }} {{ if ne .Tag "<none>" }}:{{ .Tag }}{{ end }}' }}' \
		| xargs -r -n1 docker pull
```

Sometimes you just have to sleep on it :) Nested single quotes confuse syntax highlighters, but so far looks like the best trade-off.

By the way, unbalanced braces will upset almost every single editor out there ;)

**Comment by casey** [comment]
That's definitely better. I'll add another note to the readme. I'm still thinking that `{{{{` should translate to `{{`. If unbalanced braces are a problem, we could also translate `}}}}` to `}}`, and forbid unmatched `}}`, but that would be a breaking change.

**Comment by rollcat** [comment]
> If unbalanced braces are a problem, we could also translate `}}}}` to `}}`, and forbid unmatched `}}`, but that would be a breaking change.

I can imagine this being a big problem if someone's recipe contained lots of nested dictionaries.

Random idea, it would be cool if we could somehow pull all public Justfiles in existence and parse each one; then build a regression test suite against that. I think Rust/Cargo are doing something similar on a much bigger scale already with their crates.

**Comment by casey** [comment]
Totally agreed! Check out #251. Rust's is called [Crater](https://github.com/rust-lang-nursery/crater). I want to call just's version Caldera.

Just's lexer is really gross, and I don't know if I'll ever rewrite it, but such a tool would be useful to ensure that the rewrite didn't introduce any bugs.

It would be even more of a breaking change, but another option would be to change interpolation to use single curly brackets `{...}`, and escape them via doubling: `{{` and `}}`. This is something that would go on the "`just` 1.0" pile though.

**Comment by casey** [comment]
Another possible solution is to allow recipes with no interpolation:

```
[raw]
foo:
  {{blah blah blah}}
```

**Comment by casey** [comment]
I just released v0.8.5, which allows escaping a `{{` by writing `{{{{`, so this should be much better now.

**Comment by mnieber** [comment]
It would be nice to support a file-level directive at the top of the file such as 

```
# just-open-interpolation('[[')
# just-close-interpolation(']]')
```

**Comment by rollcat** [comment]
> It would be nice to support a file-level directive at the top of the file such as
> 
> ```
> # just-open-interpolation('[[')
> # just-close-interpolation(']]')
> ```

I haven't been keeping up with new features in Just for a while, but that sounds like it would require a two-stage lexer: first to process the grammar directives, second to perform the actual token matching.

Jinja2 (for example) implements this by having a separate configuration step, which has a strict API - feature flags for non-existent functionality will fail to initialise the parser.

Introducing lexer/parser directives through comments is a recipe for disaster. For an older release, this would silently change the meaning of existing directives until an upgrade to a newer release. Sounds like a nightmare.

Directives such as these should be introduced as explicit constructs that will fail early and loud.

**Comment by maximiliankolb** [comment]
Just FYI: I ran into the same issue. This is what works for me:

```justfile
show-container-image:
  podman image list --format {{"{{.Repository}}:{{.Tag}}"}} | grep _My_Container_Image_
```

Relevant docs: https://just.systems/man/en/expressions-and-substitutions.html#escaping-
