### ISSUE TITLE
Add `--user-justfile` flag to use justfile in users's home directory

### ISSUE THREAD

**Issue by casey** [casey/just#354]
@rollcat mentioned that he used a makefile in his home directory. If this is a common enough use-case, it might be good to support it directly.

I'm imagining a `--user-justfile`/`-u` flag, that uses a justfile from a well-known location and uses that instead. It might be `~/.justfile`, `~/.config/just/justfile`, `%APPDATA%/just/justfile`, or `$XDG_CONFIG_HOME/just/justfile`, depending on the platform and environment variables.*

Since the config file might be in different subdirectories, depending on the platform, `just`'s working directory should probably be set to the user's home directory. Recipes that need to access the current directory can use the `invocation_directory()` function.

If you want this or would use this, thumbs-up this issue!

* If we do this, it would be nice to write a reusable crate for constructing the appropriate paths to config files, depending on the platform. It might work like this:

```
fn config_file_paths(program_name: &str, config_file_name: &str) -> Vec<PathBuf> {...}

// On MacOS and Linux:
config_file_paths("just", "justfile") -> ["/Users/cthulhu/.justfile", "/Users/cthulhu/.config/just/justfile"]

// On Windows:
config_file_paths("just", "justfile") -> ["/Users/cthulhu/AppData/just/justfile"]
```

**Comment by rollcat** [comment]
Personally, I have a new terminal on a hotkey; `Super-z` followed by `just foo` is faster and more natural to me than `just -u foo`, and I usually open a new terminal for every task I do anyway.

What *might* be useful, is a global / user Justfile, that does **not** change the current working directory; basically so I can stop dropping dozens of dirty one-liner scripts in `~/bin` ;)

Right now:
```makefile
hello:
	@echo hello from `pwd`
```
```shell
% just -f ~/Justfile -d . hello                 
hello from /tmp
```
Would be cool:
```shell
% just -g hello
```
But that can be achieved by a shell alias.

**Comment by casey** [comment]
Hmmm, yeah, I think I agree that not changing directories is probably the right thing for a user-level justfile. The home directory is just a `~` away, and unlike a project-level justfile, there's only one home directory, so there's less utility in changing to it.

**Comment by casey** [comment]
Closing in favor of #395. I think `just` getting a just-language config file is a better solution than a flag.
