### ISSUE TITLE
Can we help in releasing new versions?

### ISSUE THREAD

**Issue by valscion** [casey/just#370]
Hi there,

I've been eagerly waiting on a new release containing https://github.com/casey/just/pull/345 and now https://github.com/casey/just/pull/369 was merged and it looks awesome!

However I see you haven't tagged a new release since 19 June for [v0.3.12](https://github.com/casey/just/releases/tag/v0.3.12).

I know from experience that when releasing takes time or includes many manual steps, releases tend to not get made because maintainers have little time to do these manual tasks.

Is there something the open source community could help with releasing new versions? Perhaps there's some sort of automation that `just` project could utilize and the community could help set up?

**Comment by casey** [comment]
Hi!

I just published v0.3.13 to crates.io, and pushed [a tag](https://github.com/casey/just/releases/tag/v0.3.13) to github. Binaries should appear on that page as soon as they're built by CI.

Just uses the excellent [trust](https://github.com/japaric/trust) by japaric, so it's actually super easy to build a release, I've just been slacking :)

Thanks for poking me!

**Comment by valscion** [comment]
Thanks! Great to hear that the process is already easy :relaxed:
