### ISSUE TITLE
Chinese with README, if you want 😊

### ISSUE THREAD

**Issue by chinanf-boy** [casey/just#375]
## Translation

https://github.com/chinanf-boy/just-zh

**Comment by casey** [comment]
Nice! I'd like to include a link to your translated readme in the main readme. Would you mind translating "An unofficial Chinese translation of this readme is available [here](https://github.com/chinanf-boy/just-zh)." so that it's easy for Chinese speakers to find it?

**Comment by chinanf-boy** [comment]
Sure @casey

- "An unofficial Chinese translation of this readme is available here."

## Chinese

- "非官方中文文档,[这里](https://github.com/chinanf-boy/just-zh),快看过来"

> That `,快看过来` , english like: ",come come, over here"

**Comment by casey** [comment]
Closed by #377. Thank you!
