### ISSUE TITLE
read var; echo 

### ISSUE THREAD

**Issue by mare-imbrium** [casey/just#381]
Here is a recipe. I have an optional argument. If user does not enter then I prompt user for it. However, in such as case it is not accessible via curly braces. It is accessible using dollar.

```bash
add link='':
    #!/bin/bash
    if [[ -z "{{link}}" ]]; then
        echo -n "Enter link:"
        read link
    fi
    # this does not work if user enter link interactively
    echo "{{link}}"
```

How can I place the value of the read variable into the variable that just will use with curlies ?

thanks

**Comment by mare-imbrium** [comment]
Here is a recipe. I have an optional argument. If user does not enter then I prompt user for it. However, in such as case it is not accessible via curly braces. It is accessible using dollar.

```bash
add link='':
    #!/bin/bash
    if [[ -z "{{link}}" ]]; then
        echo -n "Enter link:"
        read link
    fi
    # this does not work if user enter link interactively
    echo "{{link}}"
```

How can I place the value of the read variable into the variable that just will use with curlies ?

thanks

**Comment by casey** [comment]
Great! And you're very welcome! I'm so glad you like it ^_^
