### ISSUE TITLE
Support recipe aliases

### ISSUE THREAD

**Issue by casey** [casey/just#389]
This was requested by @ryloric in Gitter. For example:

```
alias b = build

build BAR:
 echo 'Building {{BAR}}!'
```

Given the above `justfile`, the build recipe could be called with `build` or `b`. Although making a recipe with no body and a single dependency (i.e. `b: build`) currently works, it doesn't work if the recipe has dependencies.

Allow dependencies that take parameters, a la #289, would also be a solution, but I think that a dedicated alias feature would be better.

**Comment by ryloric** [comment]
#390 
The only difference from what you described is that `alias b` ought to be declared after `build`, else just will throw a compilation error.

**Comment by casey** [comment]
Fixed in #390 😎
