### ISSUE TITLE
Improve shell not found error message

### ISSUE THREAD

**Issue by casey** [casey/just#412]
The current error message is sadly lacking:

```
: just --shell foo
error: Backtick could not be run because just could not find `sh`:
No such file or directory (os error 2)   |
39 | version = `sed -En 's/version[[:space:]]*=[[:space:]]*"([^"]+)"/v\1/p' Cargo.toml | head -1`
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The same error is also printed when a backtick fails with a not-found error, like ```bar := `not-a-command````. This should be improved as well.

**Comment by Swordelf2** [comment]
The errors seem to be fine at the moment, don't they?

**Comment by casey** [comment]
The problem with the error is that it says "just could not find `sh`", when really the problem is that just couldn't find the custom shell the user set, in this case `foo`, so it's a bit misleading.

**Comment by hdhoang** [comment]
Hi, do you think a simple substitution to platform-neutral "subcommand" works? Like so https://github.com/hdhoang/just/commit/2fd4c85ee60a6bdcd496b67d04866dc032387d91

My environment is native windows + nushell, but I also have scoop+busybox on PATH. This complicated the stderr regex much. I hope the tests pass for other configurations, or we can remove them.

To get the literal invoked command, I think Error variants needed more fields. The most relevant filed I can see now is `token.src`. But it carries much more than command word.

**Comment by casey** [comment]
I think that "subcommand" is probably confusing, since that usually refers to subcommands of multi-command programs, like `cargo run` and `cargo build`. "the shell" is probably better, i.e. "Recipe `{}` could not be run because just could not run the shell:".

**Comment by saona-raimundo** [comment]
I am sorry but I do not understand this error.
I am running 
```
just
```
on Windows and getting back
```
error: Recipe `XXX` could not be run because just could not find the shell: program not found
```

I believe I do not have a shell installed in Windows? (for some reason)

[The documentation on shell](https://just.systems/man/en/chapter_58.html#configuring-the-shell) does not give an example on how to set the shell to `cmd` for example. I tried `--shell cmd` but this does not work.

Thanks in advance!

**Comment by starthal** [comment]
Is further work needed here?

**Comment by casey** [comment]
@starthal Nice catch! I guess someone fixed this a while ago and the issue was never closed. I added tests for the error message in #2145.
