### ISSUE TITLE
Export parameters prefixed with `$`

### ISSUE THREAD

**Issue by casey** [casey/just#419]
Allow exporting parameters that are prefixed by `$`:

```
foo $bar:
  echo $bar
```

**Comment by runeimp** [comment]
Upon reading this I was initially very happy. But thinking a bit I started asking, why?

1. As a way of creating local environment variables? If so what about when using `cmd.exe`, PowerShell, and possibly other not POSIX style operating systems? If it's an environment variable just use the standard syntax to read env vars I suspect. Which leaves us with a `$` prefix in the argument placeholder but other syntax for non-POSIX systems. What should be the expectation?
2. If it's a matter of expanding the variable into a standard syntax that's cool but I still have to ask, why? We have the current mustache like argument syntax for that. BTW, I love Mustache!

No criticisms. Just thinking out loud.  👼

**Comment by casey** [comment]
I definitely appreciate thinking out loud! And criticism, honestly. A lot of the time I'm just sort of guessing at which features would be useful and how they should be implemented, so all feedback is welcome.

1. The Just syntax would always be `$VAR`. This might be confusing for `cmd.exe` users, but since the `$VAR` syntax is common across other shells, I think users would mostly get it.

2. I think the question "Why?" is totally appropriate. Before this feature is implemented, we should think of some use-cases where it is definitely useful, and where workarounds or alternatives are ugly or error-prone. I could have sworn that I had some in mind, but they elude me at the moment 🤔

**Comment by xoac** [comment]
This issue should be probably closed by: https://github.com/casey/just/pull/773

**Comment by casey** [comment]
@xoac, good catch!
