### ISSUE TITLE
Make `--show` work with aliases

### ISSUE THREAD

**Issue by casey** [casey/just#420]
Given the justfile:

```
alias b = build

build:
  echo 'building!'
```

The following should work:

```
$ just --show b
```

**Comment by ryloric** [comment]
I've been `cat`ing my justfiles to see aliases when I forget them. I think it would be ideal if `--show` worked like this..

Given: 
```
alias b = build
build: 
    echo 'Building!'
```
```
$just --show build
build: 
    echo 'Building!'
---------------
Aliases for build: b
```
```
$just --show b
b is an alias for build
build: 
    echo 'Building!'
```
We need a better separator than a bunch of hyphens but this is close to what an average user would want to see when they use `--show`. What do you think?

If someone else isn't working on this, I can give it a shot next week/weekend.

**Comment by casey** [comment]
It's nice when the output of a command is also valid input. In the case of `--show` it would allow moving recipes to a new justfile. For example:

```
$ just --show build >> new-project/Justfile
```

So I think for `--show` it would be good to use the syntax of the original file:

```
$ just --show b
alias b := build
build: 
    echo 'Building!'
```

It seems natural to include the `alias b := build` line if a user does `--show b`, since they specifically asked about it, and displaying the `build` recipe on its own wouldn't make much sense.

I'm not entirely sure if `--show build` should also show aliases:

```
$ just --show build
alias b := build
build: 
    echo 'Building!'
```

Or not:

```
$ just --show build
build: 
    echo 'Building!'
```

What do y'all think? I'm don't feel super strongly about it, so I'm easily swayed.

**Comment by runeimp** [comment]
I think displaying the alias is appropriate. If `--show` displays details about a given recipe then it should also show any meta-details such as aliases as well, in my mind.  😁
