### ISSUE TITLE
Ignore justfile filename case

### ISSUE THREAD

**Issue by casey** [casey/just#428]
Just will currently find justfiles named `justfile` or `Justfile`.

I think that I originally restricted it to these two options for consistency, or something, but I don't see why just shouldn't also find `JUSTFILE` or `JustFile`.

On the one hand, being fully case insensitive could lead to spongebob case (JuStFiLe). On the other hand, being case-insensitive will keep behavior consistent between case sensitive and insensitive filesystems.

I think the latter is more important than the former, so I'm inclined to ignore case entirely. As a sanity check, if Just is looking for a justfile in a directory that contains multiple candidates (i.e. `JustFile` and `justfile`) it should complain and refuse to run.

**Comment by shevtsiv** [comment]
I would like to implement this feature.

**Comment by casey** [comment]
@shevtsiv Sounds good! Let me know if you need help or get stuck.

**Comment by casey** [comment]
Closed by #436.

Big thanks to @shevtsiv for implementing this!
