### ISSUE TITLE
Trying to convert Makefile to Justfile

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [casey/just#448]
I'm sorry to bother you with this but I cannot figure out how to convert this.
I have a bit of Makefile code
```Make
SHELL = /bin/bash
vim := $(if $(shell which nvim),nvim,$(shell which vim))
vim_version := '${shell $(vim) --version}'
```
It detects whether the user has neovim or vim installed, gets the version, and sets them as variables. 

Is there a way to do this with Just?

**Comment by casey** [comment]
No bother at all!

This is the best I was able to come up with:

```
VIM := `which nvim || which vim`

VIM_VERSION := `$(which nvim || which vim) --version`

default:
	echo {{VIM}}
	echo '{{VIM_VERSION}}'
```

`vim --version` prints out a message with newlines and double quotes, so I quoted it in the recipe. (Just isn't very good at variable escaping.)

Currently, nothing like `SHELL = /bin/bash` exists, although I hope to add support for it eventually. The issue, #361, is unhelpfully titled "Support justfile-wide configuration options", although setting the shell is the first such configuration option that I'd like to add.

Does that help? I'm going to close this issue, but please feel free to reopen/ping it.

**Comment by casey** [comment]
Also, some talk of adding direct support for a ternary operator is in #262, which would allow avoiding needing to do the business with `||`.

Actually, I'm thinking that there is an issue/feature needed here, which is that variables can't be substituted into backticks. What you'd really like to be able to do is:

```
VIM := `which nvim || which vim`

VIM_VERSION := `{{VIM}} --version`
```

This is definitely a feature I'd be open to adding. It would potentially break existing backticks which contained `{{`, so it could perhaps be added with a special syntax that says "I want interpolation in this backtick, like so:

```
VIM := `which nvim || which vim`

VIM_VERSION := f`{{VIM}} --version`
```

f`...` is by analogy to python's formatted string syntax, and might also be applied to strings. I'm going to make a note in #357 that if f-string syntax does get added, it should also apply to backticks.

**Comment by Th3Whit3Wolf** [comment]
Thank you so much!

I replaced my Makefile and two shell scripts I was using with one long (664 line) [Justfile](https://github.com/Th3Whit3Wolf/SS-Vim/blob/master/Justfile).

**Comment by casey** [comment]
Damn, what a beast!

Awesome, glad it helped ^_^

**Comment by casey** [comment]
@Th3Whit3Wolf Just now has proper conditional expressions, see https://github.com/casey/just/issues/696#issuecomment-716923105. However, looking at this, `which nvim || which vim` isn't too shabby.

**Comment by Th3Whit3Wolf** [comment]
Nice work!
