### ISSUE TITLE
Split current readme into readme and book/manual

### ISSUE THREAD

**Issue by casey** [casey/just#451]
The current readme is enormous, and I'm wondering if it could stand to be split into a smaller readme and a book or manual.

The new readme would contain installation instructions, a few examples showing off as many of just's features as are practical, and perhaps the table of contents + links to the longer manual, which would contain the current contents of the readme.

Edit: See this content for how to proceed here: https://github.com/casey/just/issues/451#issuecomment-1077042494

**Comment by Th3Whit3Wolf** [comment]
How would you like this to be implemented in the directory?
[Ion](https://github.com/redox-os/ion), for example, places their [mdbook](https://github.com/rust-lang-nursery/mdBook) in a manual directory inside the root directory.

Would you like to host it with Git Hub Pages?

**Comment by casey** [comment]
I think putting it in to a directory called `manual` and hosting it with GitHub pages would be good.

The readme is currently is Asciidoctor, so it would need to be converted to Markdown. (The reason I went with Asciidoctor was because it can generate a table of contents, but I assume that's something that mdbook can do.)

**Comment by Th3Whit3Wolf** [comment]
What do you think of [this](https://th3whit3wolf.github.io/just/)?

**Comment by Th3Whit3Wolf** [comment]
Mdbook has the ability to implement custom css and Javascript if you don't like 4 stocks ones, you can also set the default as well.

Also you can set the book to be published to gh-pages on after a successful ci run. 

Their example runs `mdbook -- test`
You could also add [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck) to check for broken links if you wanted to.

**Comment by casey** [comment]
I just realized that there's a constraint that prevents using mdbook: mdbook doesn't have a ROFF/man page backend. Asciidoctor does, so since I'd really like to generate a man page, we'll have to stay with Asciidoctor for now.

I'll need to extract a condensed readme from the existing readme, so I think that's the next step.

**Comment by cledoux** [comment]
Just a reminder that I have the justfile.io domain reserved for this project.  When you get github pages up and running, I can configure justfile.io as the custom domain for github pages. Every great project deserves a great vanity URL. :)

**Comment by casey** [comment]
I think the best way to approach this is to leave the readme as is, but write a script that turns the readme into a book. The script should process the readme in such a way that it can be fed into mdbook, and then written to the `docs` subdirectory and deployed to github pages.

The first pass at this can be very simple, and doesn't have to be perfect. After that, we can restructure the readme, move stuff around, etc, so that the same content works as both a readme and a book.

I think this is the best of both worlds:

- You can still ctrl-f search for stuff in the readme.
- If you want a sidebar with a table of contents, and more managable pages, you can read the book.
- We don't duplicate content in two places.
- When we eventually have a man page, we can still build it from the readme.

**Comment by casey** [comment]
The readme is now also converted into a book. I still wonder if having a massive readme is a good idea, but I'll stop worrying about that and let people complain if they don't like it.
