### ISSUE TITLE
[Feature Request] loops

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [casey/just#452]
# Are loops possible
Loops would be useful in circumstances when you want to do something to multiple files or directories

```shell
for i in $(fd -t d -d 1)
do
    echo $i
    tokei $i  
done
```

```shell
for i in $(fd -e rs)
do
    echo $i
    wc -l $i
    rustfmt $i
    wc -l $i
done
```

**Comment by casey** [comment]
Loops are possible! You have a few options:

You can write it all on one line:

```
loop:
	for i in `ls .`; do echo $i; done
```

You can escape the newlines with slashes:

```
loop:
	for i in `ls .`; do \
		echo $i; \
	done
```

Or you can use a shebang recipe:

```
loop:
	#!/usr/bin/env sh
	for i in `ls .`; do
		echo $i
	done
```

Shebang recipes are not run line by line, so you can use multi-line constructs in them without restriction.

How to write multi-line constructs like for/if/while comes up frequently, so I think I'll add a section to the readme.

**Comment by casey** [comment]
I added examples with `if`, `for`, and `while`, both because they're tricking in just, and, let's be real, nobody remembers how to write them, including me :P Hope it covers your use case!

**Comment by Th3Whit3Wolf** [comment]
Oh I see, my mistake. Thank you! You are the man.

**Comment by casey** [comment]
Not at all, and you are most welcome! I think there have been a few issues that have been opened regarding if/for/while, so it definitely deserves to be in the documentation.
