### ISSUE TITLE
`just --init`

### ISSUE THREAD

**Issue by casey** [casey/just#488]
A subcommand for easily creating a justfile in a new project would be nice. I'm thinking that `just --init` should create a mostly empty justfile in the project root, and launch an editor instance on that justfile.

The project root could be determined by the location of a `.git` directory, a `Cargo.toml` file or other manifest file. If those aren't found, the current directory would be used.

**Comment by runeimp** [comment]
I like this! One thought though would be the ability to define a Justfile template that `--init` used by default if it exists. Maybe even be able to specify one of a few templates with `--init TemplateID`? Oh! And have it that the `TemplateID` could just be the unique parts of the template name in a directory of templates! My mind is racing! The possibilities...

**Comment by casey** [comment]
@runeimp Those are both great ideas. To specify templates, we'll finally need a config file.

**Comment by casey** [comment]
Note to self to also add documentation for this to the readme.

**Comment by casey** [comment]
Added in #541.
