### ISSUE TITLE
Add default arguments for recipes

### ISSUE THREAD

**Issue by deckarep** [casey/just#49]
I've been looking for something along these lines for a looooong time and wanted to get your opinion on the following feature request:

How about supporting default arguments in this form:

```sh
tail-env env=green:
  @echo 'Tailing with {{env}}...'
```

This way, it could be invoked without the argument and will use the default specified like so:

```sh
$> just tail-env   #automatically uses green
```

vs

```sh
$> just tail-env blue #overrides with blue
```

**Comment by casey** [comment]
Thanks for the kind words! I'm super glad you find it useful ^__^

I think this is a good feature.

It doesn't conflict with anything in the grammar so it won't break any existing justfiles.

Not sure when I'll get to this, but it'll probably be the next feature i add.

**Comment by casey** [comment]
Done!

Looks like this:

``` make
tail-env env="green":
  @echo 'Tailing with {{env}}...'
```

It uses quotes (' or ") since bareword strings aren't supported.
