### ISSUE TITLE
Opt out of Janus monitoring?

### ISSUE THREAD

**Issue by ghost** [casey/just#503]
It seems on the surface the related Janus tool scans GitHub repositories which contain a justfile and seems to copy the files to its own repo to test against. I might have this wrong, and hoping this repo was ok to open this issue on.

In any event is there a way to opt a project out of Janus scanning and leave it up to the repo owner to manage updates to the justfile by themselves and solve any breaking changes?

I guess because there doesn't seem to be a way to opt out and it's not configurably opt in it is a bit off putting for me. What might be a better solution is letting people request this by opening an issue on the Janus repo itself, that way they can also remove their consent at any time.

**Comment by casey** [comment]
Please feel free to open issues against this repo, or against the Janus repo. There's [a note](https://github.com/casey/janus/blob/master/README.md#janus) in the readme that if you'd like your justfile not to appear in the repo, I'm happy to remove it.

I'm happy to blacklist your username, so Janus won't pick up your justfiles, if you'd like. Is `evitalis` the username you'd prefer to be blacklisted?

**Comment by ghost** [comment]
Not sure that is really sustainable. Think of those who may change their GitHub user ID or simply create a second. They may forget to let you know to opt out, which is why I suggested an opt in process instead. As an open source contributor myself I can say there are a number of people who don't read the entirety of a README, let alone that is a side repository, and won't even know about how to opt out. Basically it should be the user's choice to have their projects automatically checked versus the minor note at the bottom of the sizable README leading to a second repository.

GitLab recently pushed some telemetry on users and made it not optional and there was a large amount of backlash. I don't necessarily see Janus as telemetry for the moment, but some could or might, and will be put off. Just a thought.

**Comment by casey** [comment]
Thanks for your perspective, I'll take it into consideration. For now, I'm inclined to leave it opt-out on an individual user basis. If you're interested in opting out yourself, please let me know.
