### ISSUE TITLE
Make `--quiet` a level of verbosity

### ISSUE THREAD

**Issue by casey** [casey/just#520]
Currently, a `Config` has a `quiet` field *and* a `verbosity` field. This is somewhat silly, they should be a single `verbosity` field, with quiet being represented as `Verbosity::Quiet`.

**Comment by Celeo** [comment]
If the quiet flag is specified and also there's > 0 verbose flags, what should be the user experience? Would the verbose flags, if at all present, overwrite the quiet flag, or the other way around where having `-q` at all would force no output?

**Comment by casey** [comment]
I don't have a strong justification for it, but I think a quiet flag would override verbosity flags.
