### ISSUE TITLE
Symlinks and the working directory

### ISSUE THREAD

**Issue by dionjwa** [casey/just#538]
I use a root justfile and subdirectories use that root justfile symlinked into their subdirectory. The new version broke prior behaviour I was relying on, where $PWD referred to the invoking directory (with the symlinked justfile) not the actual (non-symlinked) justfile.

The use case is to export e.g. a `GCLOUD_PROJECT` env var for all commands, based on the directory name. Now this seems much more difficult.

Also it seems that I have to run `invocation_directory()` for every command for symlinked justfiles. :-(

**Comment by casey** [comment]
Sorry I broke this! This is definitely a bug. I'm moving tomorrow, so I'm not sure when I'll be able to release a fix, but I should be able to get to it by the 19th.

In the mean time, v0.4.5 is available on [the releases page](https://github.com/casey/just/releases/tag/v0.4.5), and can be installed with cargo with `cargo install --version 0.4.5 just`

**Comment by dionjwa** [comment]
No problem, I rolled back, thanks for confirming it wasn't my imagination. Also, good work, just is becoming a core part of my operations. Appreciate your quick response.

**Comment by casey** [comment]
I just released v0.5.1, which includes the fix in #539. I added a test that checks that a symlink to a justfile doesn't change the working directory, so regressions should be prevented in the future.

Sorry for the disruption!

**Comment by dionjwa** [comment]
Awesome! Thanks for the super fast turnaround!
