### ISSUE TITLE
Python import bug

### ISSUE THREAD

**Issue by shiimizu** [casey/just#552]
So I have this `justfile` and I'm trying to access a variable from a local library in the current directory:
```makefile
# Get the current version
version:
	#!/usr/bin/env python
	from barlibrary import __version__ as current
	print(current)
```
And here's `barlibrary/__init__.py`:
```python
from __future__ import absolute_import
from __future__ import print_function

__version__ = '0.1.3'
```

But when I run `just version`, I get this error:
```
Traceback (most recent call last):
  File "/tmp/justWPA40x/version", line 78, in <module>
    from barlibrary import __version__ as current
ModuleNotFoundError: No module named 'barlibrary'
error: Recipe `version` failed with exit code 1
```
This also happens if I run `just --justfile justfile --working-directory . version`  

I suspected it was maybe due to the `justfile` being run in `/tmp/justWPA40x/version`, but after getting the current directory in python, that doesn't seem to be the case:
```makefile
# Get the current version
version:
	#!/usr/bin/env python
	import os
	print(os.getcwd())
```
I get the correct directory, which is the current working directory:
```
/home/mizu/projects
```
I believe this is a bug because I should be able to access `barlibrary` from the python script in the `justfile`.

Currently here's a workaround:
```makefile
# Get the current version
version:
	#!/usr/bin/env bash
	current_version=$(python -c 'from barlibrary import __version__ as current; print(current, end="")')
	echo -e "$current_version"
```

**Comment by casey** [comment]
Thanks for the detailed report!

I believe this is related to the way that Python looks for imports. By default, Python searches the directories in `sys.path` for imports, which contains, among other things, the directory containing the current file, but not the current working directory.

As a workaround, you can add the current directory to `sys.path`:

```
# Get the current version
version:
	#!/usr/bin/env python
	import sys, os
	sys.path.insert(0, os.getcwd())
	from barlibrary import __version__ as current
	print(current)
```

Let me know if that works!

**Comment by shiimizu** [comment]
Thanks! It works.
