### ISSUE TITLE
Single shell and Python Virtual Environment

### ISSUE THREAD

**Issue by mortoray** [casey/just#554]
I'm trying to automate some commands that need to be run withing a python virtual environment. This doesn't work because there is no persistent shell in a justfile.

I need to do this type of command:

```
source env/bin/activate
python ...
```

So that python runs within it's virtual environment.

I don't know if there is anyway around this other than creating an actual shell and running all the commands in that. But I don't see an easy way to do this.

**Comment by casey** [comment]
Hey there, If you only need to run one command, you could put them on the same line, like so:

```make
foo:
  source env/bin/activate && python ...
```

If there are a bunch of commands to run, you use a shebang to make the recipe execute like a script, i.e. with the same shell for the whole recipe:

```make
foo:
  #!/usr/bin/env sh
  source env/bin/activate
  python foo.py
  python bar.py
```

**Comment by mortoray** [comment]
Great. Thanks.

**Comment by casey** [comment]
You bet!
