### ISSUE TITLE
musl v0.5.2 artifact is missing

### ISSUE THREAD

**Issue by jeffrey-aguilera** [casey/just#559]
just-v0.5.2-x86_64-apple-darwin.tar.gz and just-v0.5.2-x86_64-pc-windows-msvc.zip were published, but just-v0.5.2-x86_64-unknown-linux-musl.tar.gz was not. The `install.sh` script autodetects the latest version, 0.5.2 in this case, ignoring the platform.

**Comment by casey** [comment]
Thank you for letting me know! The release artifacts are built by a Travis job, but the job that was supposed to produce the v0.5.2 Linux artifact spuriously failed. I restarted the job and it just completed successfully, so the Linux/musl release binary should now be available. Sorry for the inconvenience!

**Comment by jeffrey-aguilera** [comment]
Thank you!
