### ISSUE TITLE
Cannot enable enable zsh completion

### ISSUE THREAD

**Issue by kenden** [casey/just#617]
How to enable zsh completion?

An error happens when trying to source the zsh completion code generated by just.
```zsh
$ source <(just --completions zsh)
_arguments:comparguments:325: can only be called from completion function
```

I also tried the following:
```
# disable existing zsh autocomplete (.oh-my-zsh)
$ mv ~/.zshrc{,.bak}
$ mv ~/.zprofile{,.bak}
# and open a new shell

$ mkdir just_complete
$ just --completions zsh > just_complete/_just
$ fpath=($PWD/just_complete $fpath)
$ autoload -Uz compinit && compinit -C
# -> no autocomplete
```

Note: for bash, it works:
```bash
bash-5.0$ source <(just --completions bash)
bash-5.0$ just  # + press tab to get autocompletions
```

# Versions
```bash
$ just --version
just v0.5.10
$ uname -a
Darwin cebert-mobl.redacted.com 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

**Comment by casey** [comment]
I don't usually use Zsh, but was able to get completions working thanks to heyrict. Check out their explanation here: https://github.com/casey/just/pull/606#issuecomment-599369937

Let me know if that works for you!

I opened #618 to eventually add instructions for this to the readme.

**Comment by kenden** [comment]
@casey  Thanks!
Actually my steps:
```bash
just --completions zsh > just_complete/_just
$ fpath=($PWD/just_complete $fpath)
$ autoload -Uz compinit && compinit -C
```
worked, but if there is no justfile in the directory, the autocomplete does nothing, I though it was broken.
(The bash autocomplete provides output in that case).
However, if there is a justfile in the folder, it does shows the targets.

**Comment by casey** [comment]
@kenden Awesome, good to hear. I'm going to close this, but please feel free to reopen if you have issues.

When there isn't a justfile in the current directory, does it auto-complete normal flags, like `just --help`?

**Comment by kenden** [comment]
@casey  When there isn't a justfile in the current directory, it does not auto-complete normal flags for me. Typing `just` then print tab does nothing.

**Comment by casey** [comment]
@kenden I just checked, and it will complete flags if you type a `-` and then press tab. Is this normal behavior for a completion script, or do completion scripts usually auto-complete flags with no `-`?

**Comment by kenden** [comment]
Hi @casey,

I checked `command + press tab` with various programs:   
- `cargo, go, docker, kubectl` and `git` display a list of possible sub-commands,
- `ssh` displays a list of servers previously connected to,
- `make, ls, cp, rm, cat` display the files/folders in the currently directory.
- command_doesnt_exist displays the files/folders in the currently directory.

So just, displaying nothing, currently behaves differently than all those, but that doesn't seem wrong (displaying a list of files/folders if the command does not exist seems wrong, actually).
No problem here.

**Comment by casey** [comment]
Thanks so much for checking the behavior of completions for other programs!  I agree that it's probably okay as is, although we can revisit that if for some reason another behavior is more desirable.
