### ISSUE TITLE
How to forward args? (Like `"$@"` in bash)

### ISSUE THREAD

**Issue by Boscop** [casey/just#631]
How can I forward args to a subcommand (e.g. cargo)? 
(Like `"$@"` in bash)

**Comment by casey** [comment]
Do you want to forward a fixed number of arguments, or a variable number of arguments?

All arguments can be forwarded, even if variadic:

```
bar +b:
	echo {{b}}

foo +a: (bar a)
```

But there isn't a direct equivalent of `$@`.

**Comment by Boscop** [comment]
@casey Thanks. `+a` works with forwarding, but then it requires at least one arg. How can I also accept zero args?

**Comment by casey** [comment]
If you give it the empty string as a default argument, it will accept zero args:

```
bar +b="":
	echo {{b}}
```

This is definitely somewhat cumbersome. I'm not sure why I didn't just give it this behavior to begin with, but at this point I think it would be reasonable to add `*` that accepts zero or more arguments, and evaluates to the empty string when no arguments are given.

**Comment by Boscop** [comment]
@casey I actually tried `*a` hoping that it would allow "zero or more" args. I think that would be the most intuitive. 
(Well, even more intuitive would be to not distinguish between `*` and `+` at all.)

**Comment by casey** [comment]
Agreed! I just opened #633, to add `*` with that behavior. Although I'm not sure when it'll get done, since other projects are taking all my cycles.
