### ISSUE TITLE
Ignore `@` returned from interpolation evaluation

### ISSUE THREAD

**Issue by casey** [casey/just#634]
If an interpolation at the beginning of a recipe line evaluates to a string starting with `@` the recipe will be run as if it had a `@` in front of the line:

```
$ cat justfile
foo:
  {{"@echo foo"}}
$ just foo
foo
```

This is pretty weird, so I think it should be changed so that only a literal `@` outside of an interpolation will suppress line echoing.

**Comment by rjsberry** [comment]
Closed by #636

**Comment by casey** [comment]
Thanks for remembering!
