### ISSUE TITLE
Allow introspecting justfile contents

### ISSUE THREAD

**Issue by casey** [casey/just#638]
Continuing the discussion in #298. `just --summary` prints a space-separated list of recipe names, for use in shell completion scripts and other tools.

However, this only provides recipe names, and doesn't give arguments, doc comments, variables, or dependency information.

It might be useful to provide a command that returns, in a structured, easy-to-parse format, all available information about a Justfile.

JSON is probably appropriate, since it doesn't need to be human readable or editable, and JSON is probably the most widely supported format.

The output could contain a dictionary with all information about a parsed justfile, including:

- [ ] Recipe names
- [ ] Parameter names
- [ ] Parameter types (variadic or not)
- [ ] Parameter defaults
- [ ] Recipe bodies, as a list of lines
- [ ] Entire recipes, parameters and dependencies, for display to the user
- [ ] Assignment names
- [ ] Assignment expressions
- [ ] Entire assignments, name and expression, for display to the user
- [ ] Alias names
- [ ] Alias targets

I'm inclined to wait to add this until someone needs it, so I can work with them to make sure the format and contents meets their needs. However, this isn't hard to add at all, so don't be shy!

I'd probably start with recipe names, and gradually add more information in a backwards-compatible way, as it's needed.

**Comment by casey** [comment]
@blaggacao Yo, continuing our conversation in #298. What do you think of the above? Would that be roughly what you would need? I think that JSON is probably the best format. An alternative would be a line-based format, like:

```
RECIPE0 PARAM0 PARAM1
RECIPE1 PARAM0 PARAM1
```

However, that kind of format is very hard to extend without breaking parsers. A JSON dict is easy to add information to, but I'm not sure if a JSON parser is available when writing a Kakoune plugin.

**Comment by blaggacao** [comment]
The idea of using JSON `just` rocks, since `jq` is almost ubiquitous. So piping around things should be trivially easy.

**Comment by casey** [comment]
Great! What does the summary need to contain for it to be useful? Just recipe names and argument names?

**Comment by blaggacao** [comment]
I think for command completion in kakoune, the first 4 are just enough. Maybe there is a dependency driven by desire to make it even more useful on #495 ...

**Comment by casey** [comment]
What would parameter defaults be used for? Would you want to know whether the is a default or not, or would you also want to see the expression that is the default?

**Comment by blaggacao** [comment]
I currently _think_ I'd want to show the default expression in the contextual docs within the kakoune clip pop-up window:
![image](https://user-images.githubusercontent.com/7548295/84225642-4f996480-aaa5-11ea-80e9-bdd97d9fc847.png)

Since every justfile is different, full contextual expressivity is really an edge.

**Comment by casey** [comment]
Would the output of `just --list` be better for that, since it's pre-formatted for display, and includes arguments, defaults, and doc comments?

**Comment by blaggacao** [comment]
> Would the output of just --list be better for that, since it's pre-formatted for display, and includes arguments, defaults, and doc comments?

Indeed! Thanks for the hint! - So with recipe names, param names, types and defaults, I would then rather feed the auto completion list and use `just --list` for the docs/hints. Sounds great!

**Comment by casey** [comment]
Cool, glad that works! I'm going to leave this issue open, since I can imagine future plugins and integrations that might benefit from a more structured summary. Feel free to ping it if you wind up needing it.

**Comment by casey** [comment]
Closing in favor of #989.
