### ISSUE TITLE
Unknown start of token using *ARGS

### ISSUE THREAD

**Issue by francois-pasquier** [casey/just#648]
`just v0.5.11`

using the example
```
commit MESSAGE *FLAGS:
  git commit {{FLAGS}} -m "{{MESSAGE}}"
```

I am getting this error `Unknown start of token using *ARGS`

**Comment by casey** [comment]
Sorry about that! The readme reflects current master, which has the new `*` variadic parameters. I just released v0.6.0, which has the new feature. Prebuilt binaries are building on GitHub actions, and should be available soon on the [release page](https://github.com/casey/just/releases/tag/v0.6.0).
