### ISSUE TITLE
Allow an alternative runner for shebang tasks

### ISSUE THREAD

**Issue by pfmoore** [casey/just#650]
Currently the `shell` setting lets users customise the runner for single-line commands. But this doesn't affect shebang tasks. On Windows, the default shell may not exist, so this makes shebang tasks unusable. However, the "Python Launcher" shipped with Python includes a shebang interpreter, so it would be entirely possible on Windows to say

```
set shebang_shell := ["py"]
```

at the top of the justfile to get shebang support.

This should be a different setting variable, not `shell`, as `py` doesn't handle command lines, and a shell like Powershell doesn't handle shebangs. So a single setting won't work for both.

On an unrelated note, it would be nice to have systemwide settings, so that I didn't have to set `shell` (and `shebang_shell`, if it was added) in every justfile.

**Comment by casey** [comment]
On Windows, shebang parsing and execution is actually done by Just itself, since Windows lacks native support. Is there a specific shebang you're having trouble with?

Systemwide settings are problematic, since you might use a Justfile written by someone else, and the local settings might break the justfile, by changing the default shell, for example.

**Comment by pfmoore** [comment]
Ah, I didn't spot that. The example I tried was

```
set shell := ["pwsh", "-c"]

test:
    #!py
    print(12)
```

which gives the following error:

```
>just test
error: Could not find `cygpath` executable to translate recipe `test` shebang interpreter path:
The system cannot find the file specified. (os error 2)
```

I assumed this meant that the default sh was being used, as clearly my `shell` setting isn't.

I see your point on systemwide settings, but for my use, I'm mostly just writing my own justfiles, and as I don't have a `sh` executable, shared justfiles would presumably break anyway. But it was a minor point, which is why I didn't raise a separate issue for it, so I'm fine to accept your view on the matter.

**Comment by casey** [comment]
Yeah, it's a bit confusing. Just uses the system's shebang execution mechanism on all OSs except Windows.

I'm definitely interested in some mechanism that would allow reuse between multiple justfiles, perhaps an import system, so you could, for example, do something like `include "~/.justfile"`.

**Comment by pfmoore** [comment]
Sorry, I'm a bit confused. Why did you close this? How would I get a justfile on Windows to run a task using Python (via "py"). As I demonstrated, `#!py` doesn't work - so what should I use?

**Comment by casey** [comment]
Ah, sorry, my mistake.

Can you try the full path to the `py` binary? I.e. `#!/path/to/py`.

What command on the command line where you run `just` will launch `py`?

**Comment by pfmoore** [comment]
Same error (about cygpath) with the full path, `C:\Windows\py.exe` (also if I use `C:/Windows/py.exe`) I use Powershell as my default shell, and just putting `py` on the command line runs Python (as `C:\Windows` is in my `PATH` environment variable).

The problem seems to be [here](https://github.com/casey/just/blob/master/src/platform.rs#L57), where you unconditionally try to run `cygpath` to convert the shebang from Unix form to Windows form. That's presumably in an attempt to make Unix-style paths work. (You also do the same [here](https://github.com/casey/just/blob/master/src/platform.rs#L87) which seems to be used for `invocation_directory`)

Maybe if `cygpath` doesn't exist, you should just use the path unchanged? That could still cause errors in some cases (I think it might have potential issues with WSL) but it would cover my usage.

**Comment by casey** [comment]
Hmm, this is tricky. Just thinking out loud:

Passing shebang paths to `cygpath` is done so that shebang recipes can work on both Unix and Windows with Cygwin. (For a while, installing Cygwin was the only way to get Just working on Windows, which is why this feature assumes that it will be present.

I'd rather not switch the behavior of Just depending on whether or not `cygpath` is installed, since I think that would be confusing. Users might write justfiles that work when `cygpath` is not installed, but then break when they install `cygpath`.

One ideas is that if there are no forward slashes (`/`) in a path, `cygpath` isn't invoked. I think this is safe, because `cygpath` in this case `cygpath` will be a no-op anyways. This would allow you to just write windows paths in shebang recipes.

What do you think?

**Comment by pfmoore** [comment]
That sounds reasonable to me (or at least, it would work for my use - I'm not really interested, personally, in cross-platform Justfiles, so I may not have thought of some edge cases).

Thinking some more about it, I assume that on Unix you just pass the script to the shell so `#!` lines get processed by the kernel. What do you do on Windows? Read and process the `#!` line to find the executable, and then feed the script to that exe? If so, what rules do you use? If you don't want to get awfully messy with parsing, I guess you just take everything after the #! and treat it as the executable name (i.e. no command line arguments, etc). You would *have* to allow whitespace in the path, to cover things like `C:\Program Files` - unless you wanted to get into the mess that is quoting 🙂 Hopefully you also allow commands to be found on `PATH` (so that, for example, `#!powershell` would work¹).

I don't think you're ever going to get *full* portability. If nothing else, the rules differ between Unix flavours - Linux has different rules than BSD-derived systems (Linux allows command-line arguments, BSD treats spaces as part of the shell name, IIRC - so the common `#!/usr/bin/env python` isn't portable). But I think "On Windows, if there's no `/` use the filename directly, otherwise use `cygpath` as at present" is probably going to be the simplest approach that allows both styles.

¹ Someone wanting to write a cross-platform shebang task that used Powershell Core would have real problems - on Unix they would want `#!/usr/bin/env pwsh`, whereas on Windows they would want `#!pwsh` - assuming that (a) they don't want to use absolute paths, because Powershell doesn't have a standard install location, and (b) they don't want to require Cygwin on Windows, because that's a constraint that makes the file *less* portable. Leave that complexity until someone with an actual use case asks for it 😉

**Comment by casey** [comment]
> That sounds reasonable to me (or at least, it would work for my use - I'm not really interested, personally, in cross-platform Justfiles, so I may not have thought of some edge cases).

> Thinking some more about it, I assume that on Unix you just pass the script to the shell so `#!` lines get processed by the kernel. What do you do on Windows? Read and process the `#!` line to find the executable, and then feed the script to that exe? If so, what rules do you use?

Yup, that's right. I believe I implemented parsing exactly how it's done on Unix, which means that it only processes one space. I.e. a binary and one argument. I'm not sure why Unix does it this way, it's probably a historical accident. Here's the [code](https://github.com/casey/just/blob/master/src/shebang.rs).

> You would _have_ to allow whitespace in the path, to cover things like `C:\Program Files` - unless you wanted to get into the mess that is quoting 🙂

I do process whitespace, to separate the program from the arguments, so things like `#!/usr/bin/env python3` work. It's 

> Hopefully you also allow commands to be found on `PATH` (so that, for example, `#!powershell` would work¹).

I'll have to try that, but hopefully I can make that work. I delegate to rust's `std::process::Command` for running commands, so it mostly depends on how that works.

**Comment by pfmoore** [comment]
> I do process whitespace, to separate the program from the arguments, so things like #!/usr/bin/env python3 work.

Hmm, OK. So you probably need to consider `#!"C:\Program Files\Python3.8\python.exe"` in that case (the path has spaces, so you need to quote it).

> I delegate to rust's std::process::Command for running commands, so it mostly depends on how that works.

As long as you pass what's entered, and don't convert it to an absolute path, it should work then 🙂 

> Here's the code.

I'm just learning Rust, so I'd struggle to follow that, I'm afraid! (Also, apologies that I can't provide a PR for this, for the same reason...)

**Comment by casey** [comment]
> Hmm, OK. So you probably need to consider `#!"C:\Program Files\Python3.8\python.exe"` in that case (the path has spaces, so you need to quote it).

Man, I'm really loathe to introduce weird quoting rules in the shebang. The nice thing about the shebang feature on Unix is that it works in a very obvious way with no surprises, since uses the same mechanism as standalone scripts. (Just extracts the recipe, places it in its own file, and executes it.)

I'm not sure it would be wise of me to add special quoting rules for Windows, especially it would be an entirely different string parser from the main string parser.

An alternative would be to finally add recipe annotations, and use normal just strings to specify an interpreter:

```
#[interpreter("C:\Program Files\Python3.8\python.exe")]
foo:
  print("Hello!")
```

This is probably a better long-term alternative, since it uses a general, extensible mechanism, and leverages the existing lexer and parser, instead of introducing a special purpose lexer/parser/rules for a small feature.

> I'm just learning Rust, so I'd struggle to follow that, I'm afraid! (Also, apologies that I can't provide a PR for this, for the same reason...)

No worries at all! Rust is rough, definitely the hardest language I've ever learned. Just keep at it! Writing little command line apps is a great way to learn. Just was the first program I wrote in Rust, and it started out small, delegating execution to Make, until I eventually added the custom parser and it turned into a much larger project.

**Comment by pfmoore** [comment]
> The nice thing about the shebang feature on Unix is that it works in a very obvious way with no surprises

Hoo, boy, you haven't lived yet! I've worked on a number of Python packages (pip and virtualenv in particular) that deal with shebangs, and the Unix behaviour is *incredibly* inconsistent 🙂 Some Unix systems have a limit on the length of the shebang, some silently ignore everything after a space, some treat the whole line as an executable name, whitespace and all. If you stick to Linux, the rules are consistent (because the kernel handles it) but I'm not even sure MacOS works the same. But in practice, things work for 99% of the uses people make of them, so it's good enough.

> I'm not sure it would be wise of me to add special quoting rules for Windows

Well, technically of course, Unix is just as capable of having spaces in pathnames as Windows. It's just that Unix users typically don't do this, and are willing to accept that their utilities are broken if they encounter paths with spaces in them 😉 But yeah, the reality would be that you'd be adding yet another set of quoting rules just for the Windows case, and you'd inevitably end up slightly different than everyone else 🙁 

Off-topic anecdote - I heard somewhere that one of the original people who developed Unix had a directory that they kept for testing, containing 254 files, each with a one-character name, every valid character in a Unix filename (`\0` and slash aren't allowed). That's the sort of test-to-destruction attitude I can respect!!! 🙂 

> An alternative would be to finally add recipe annotations, and use normal just strings to specify an interpreter

That sounds like a much better solution in the long term, TBH.

**Comment by casey** [comment]
> Hoo, boy, you haven't lived yet! I've worked on a number of Python packages (pip and virtualenv in particular) that deal with shebangs, and the Unix behaviour is _incredibly_ inconsistent 🙂 Some Unix systems have a limit on the length of the shebang, some silently ignore everything after a space, some treat the whole line as an executable name, whitespace and all. If you stick to Linux, the rules are consistent (because the kernel handles it) but I'm not even sure MacOS works the same. But in practice, things work for 99% of the uses people make of them, so it's good enough.

I've never run into a cross-platform issue with shebangs, so I didn't know any of that. Yikes!

> That sounds like a much better solution in the long term, TBH.

A lot of improvements are kind of waiting for annotations, since they seem to be the best way to add a wide variety of features without coming up with a whole lot of custom syntaxes.

I opened https://github.com/casey/just/pull/652 that skips cygpath translation for shebang paths if the interpreter path doesn't contain a `/`. Would you be interested in trying it out and seeing if it works for your use cases? It doesn't support quoting, unfortunately, but `#!powershell` should work.

**Comment by casey** [comment]
I just made some modifications to the github actions config to build and package all tags (previously, only new release tags would be built). If the modification is correct, binaries with the change in this PR should be build and uploaded automatically to this tag: https://github.com/casey/just/releases/tag/cygpath-test

(In case you don't have the rust toolchain installed and would prefer to download prebuilt binaries to test.)

**Comment by pfmoore** [comment]
> Would you be interested in trying it out and seeing if it works for your use cases?

Absolutely! Thanks so much for doing this. It may be a few days before I get a chance to test, but I'll get back to you.

> It doesn't support quoting, unfortunately, but #!powershell should work.

My two main use cases would be `#!powershell`/`#!pwsh` and `#!py`, so that's fine for me. With path searches working, quoting is *far* less important.

**Comment by casey** [comment]
> Absolutely! Thanks so much for doing this. It may be a few days before I get a chance to test, but I'll get back to you.

You bet!

> My two main use cases would be `#!powershell`/`#!pwsh` and `#!py`, so that's fine for me. With path searches working, quoting is _far_ less important.

One vague worry I have is that `#!python3` will potentially work on Windows, but not Unix. I could make it work on Unix too, but I think at that point I'll probably add an `#[interpreter(…)]` annotation which works consistently across all platforms.

**Comment by pfmoore** [comment]
> One vague worry I have is that #!python3 will potentially work on Windows, but not Unix.

Nope, there's no `python3` command by default on Windows. Users can opt into adding Python to `PATH` so that `#!python` would work (but likely be Python 3 on Windows, whereas Unix seems to often pin this to Python 2). But the default install behaviour wouldn't give any overlap with Unix.

> binaries with the change in this PR should be build and uploaded automatically to this tag

Thanks for that. I gave it a quick try, and immediately caught one pretty bad issue. The problem is that the Python launcher `py` includes a shebang parser of its own, to handle things like `#!/usr/bin/python3` in cross-platform scripts. Unfortunately, that interacts *very* badly with your parser, as you run py on the script, which parses the shebang and itself runs py, which in turn parses the shebang...

It took me a while to work out why my laptop was slowing down. I don't know how many `py.exe` processes I had when I killed it 🙁 

To be honest, I think this is probably sufficiently bad that I'd suggest abandoning this idea altogether. Better to wait for a more robust solution using recipe annotations.

This is actually a problem with the `cygpath` parsing as well. I tested by adding cygwin to my `PATH`, and I get the same behaviour with the release version of just. Here's a reproducer:

```
test_py:
    #!py
    print(12)
```

In this case, though, I'd not worry too much as clearly it's not something that's causing people actual issues (using a Unix-style construct to run a Windows-only command isn't a common thing for people to do 🙂 )

**Comment by casey** [comment]
> It took me a while to work out why my laptop was slowing down. I don't know how many `py.exe` processes I had when I killed it 🙁

Ah, interesting. So I guess the py launcher just isn't intended to be used in a shebang.

> To be honest, I think this is probably sufficiently bad that I'd suggest abandoning this idea altogether. Better to wait for a more robust solution using recipe annotations.

It's definitely annoying, but it still seems like the PR is somewhat nice for windows users, since they can at least do `#!powershell`.

**Comment by pfmoore** [comment]
> it still seems like the PR is somewhat nice for windows users

Absolutely! My assumption was that you'd not want to have to deal with users saying "My PC locked up because I accidentally spawned a million Python processes", but if you're OK with treating that as user error, and "not likely to happen" (at least now that I know better than to try it again 😉) then I'd be fine with that.

**Comment by casey** [comment]
It's definitely unfortunate that `py` works this way, but it's only indirectly related to the change. I.e. the PR just makes it so that `cygpath` isn't always needed, so I think with `cygpath` installed, infinite recursion is still possible if you try to use `#!py`.

**Comment by casey** [comment]
I just merged #652. Let me know if you'd like me to cut a release! (Not sure if you needed one, since `py` doesn't work.) I'm going to close this issue, since I think the underlying problem is fixed.

**Comment by pfmoore** [comment]
Thanks for this! A release would be nice (I have some other things I'd like to try with it) but it's far from urgent, so don't put yourself out to cut a new release, I can easily wait.

Once again, many thanks 🙂

**Comment by casey** [comment]
No worries, releases are easy. I just cut v0.6.1, available [here](https://github.com/casey/just/releases/tag/v0.6.1). It looks like the Linux and Mac artifacts are done, and Windows binaries should be done soon. Let me know if you run into any issues!
