### ISSUE TITLE
`--list` option that lists recipes the order defined in the Justfile

### ISSUE THREAD

**Issue by rossmacarthur** [casey/just#671]
It would be really nice if I was able to do the equivalent of `just --list` but instead of alphabetical order the recipes are listed in the order that they are defined in the `Justfile`.

**Comment by casey** [comment]
This is actually already possible! (Although I didn't do a good job of documenting it, which I just did in #672.)

You can pass `--unsorted` to `just --list` or `just --summary` to get it to print recipes in the order they appear in the Justfile.

**Comment by rossmacarthur** [comment]
:tada:
