### ISSUE TITLE
@: command not found (on Windows)

### ISSUE THREAD

**Issue by runeimp** [casey/just#677]
Today I tried using a Justfile on Windows 10 that I'd created on macOS and got this error:
`C:\Users\RuneImp\AppData\Local\Temp\justSQWDNT\_build-windows: line 39: @: command not found`
This happens on every line that the first non-whitespace character is an @ symbol. The recipe has the shebang line `#!/bin/sh` I'm using Git Bash (git version 2.28.0.windows.1) and the error happens for Just 0.7.1 and 0.7.2.

**Comment by casey** [comment]
Thanks for the report! Can you share the justfile, or an example that exhibits the bug?

**Comment by runeimp** [comment]
Here ya go.  :wink:

### Justfile

```

run:
	#!/bin/sh

	@ # Ignore this line

	echo "run ran"

```

### Command Line

```
$ just
C:\Users\RuneImp\AppData\Local\Temp\justoZekuV\run: line 6: @: command not found
run ran
```

**Comment by casey** [comment]
Ah, okay. Did this ever work? `@` is only supported non-shebang recipes. In shebang recipes, the whole recipe body, including leading `@`s, are extracted and passed to the interpreter as a script.

**Comment by casey** [comment]
It might be that the `sh` installed on the mac ignores leading `@`, but the one on windows doesn't.

**Comment by runeimp** [comment]
Oh, yeah, good point. Hm, seems like that worked before, but really it shouldn't. No worries.
