### ISSUE TITLE
@ doesn't work when a shebang is used

### ISSUE THREAD

**Issue by K4rakara** [casey/just#678]
Heya, when I try to do:
```makefile
@rule:
     #!/usr/bin/sh
    echo "Hello world!";
```
The output is:
```
#!/usr/bin/sh
echo "Hello world!";
Hello world!
```
When it should be:
```
Hello world!
```

**Comment by casey** [comment]
When the `@` is used on normal recipes it suppresses echoing commands as they're executed. But, the default for shebang recipes is to not echo anything. So `@` on shebang recipes changes that, and makes it echo the whole script. So, quite confusingly, `@` has opposite effects on shebang and normal recipes. Sorry for this strange behavior! It seemed like a good idea at the time ;)

Anyways, to make a long story short, you can remove the `@` to only print `Hello world!`.

**Comment by K4rakara** [comment]
Ah, ok, thanks. :smile:

**Comment by casey** [comment]
You're most welcome. This behavior definitely doesn't make a whole lot of sense, but it feels minor enough that I'm disinclined to change it, since it would be an issue for existing justfiles that rely on it.
