### ISSUE TITLE
Run parametrized dependencies

### ISSUE THREAD

**Issue by awildturtok** [casey/just#682]
I'm trying to write a justfile where multiple steps are their own target, but there is a target to run them all. They however all take a parameter which would have to be passed into them, I am getting errors with either syntax:

```
write x y:
  echo {{x}} > {{y}}

 cleanup y:
  rm {{y}}


full x y: write x y cleanup x y
  echo done

# or

full x y: write {{x}} {{y}} cleanup {{x}} {{y}}
  echo done
```

I am running the latest build on a CentOS machine.

**Comment by casey** [comment]
Passing parameters requires parentheses, like this:

```make
write x y:
  echo {{x}} > {{y}}

 cleanup y:
  rm {{y}}

full x y: (write x y) (cleanup x y)
  echo done
```

I didn't test the above snippet, so hopefully I got it right!
