### ISSUE TITLE
handle braces substitution in dependencies with args

### ISSUE THREAD

**Issue by jaki** [casey/just#683]
Quoting the README,

> To pass arguments to a dependency, put the dependency in parentheses along with the arguments:

I noticed braces substitution doesn't work for the arguments to a dependency.  Here's a small repro of the issue.

```make
main arg: (func {{arg}})

func arg:
	echo {{arg}}
```

```sh
just --list
```

```
error: Expected backtick, identifier, '(', cooked string, or raw string, but found '{{'
  |
1 | main arg: (func {{arg}})
  |
```

I would like for braces substitution to work in these situations.

**Comment by casey** [comment]
Thanks for opening this issue! I'm not sure I understand, can you do the same thing without braces, like so:

```make
main arg: (func arg)

func arg:
	echo {{arg}}
```

**Comment by jaki** [comment]
Thanks, that works!

**Comment by casey** [comment]
Awesome!
