### ISSUE TITLE
how to run a command in another terminal?

### ISSUE THREAD

**Issue by matthiasdebernardini** [casey/just#684]
Hi I am in the process of writing a server and a client. 

My flow is to make an edit, recompile, run the server and then open up a new terminal (either using tmux or the terminals tab manager or something) and then fire up the client and see if it works or not. 

The step between running the server and the client is always the same and I was curious if this tool is able to offer something to automate this? 

Its a really minor inconvenience but its something I'm doing hundreds or thousands of times per project (for a server client) so even a 1% improvement is helpful.

**Comment by casey** [comment]
I'm not sure if it fits your workflow, but one good tool for this is [entr](http://eradman.com/entrproject/). It watches for changes to files and runs commands when they occur. You could have the server rebuild and launch whenever a file changes, and do the same for the client. For rust projects, I do this with `cargo-watch`, but that's rust-specific, whereas `entr` can be used with any kind of project.

**Comment by matthiasdebernardini** [comment]
Thank you very much for the suggestion. 

Quick question, how come you recomended this over watchexec(in the readme for the project)?

**Comment by casey** [comment]
> Thank you very much for the suggestion.

You're totally welcome!

> Quick question, how come you recomended this over watchexec(in the readme for the project)?

I was thinking that maybe entr was more mature or widely supported, but it looks like watchexec is very popular, so that would also be a good choice.
