### ISSUE TITLE
Possible bug in backtick evaluation

### ISSUE THREAD

**Issue by casey** [casey/just#694]
Quoting @kenden from https://github.com/casey/just/issues/674#issuecomment-705680520:

> I have another example where conditional logic would help.
> 
> Here, I would like to define `TAG_HASH` at the beginning of the justfile.
> This variable is reused in many targets so I don't want to re-set it in each target: it should be set once.
> 
> ```makefile
> # if running in jenkins, set the tag to the git sha of the folder, else, create a hash of the folder
> FOLDER_HASH := `find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
> FOLDER_GIT_SHA := `git log -1 --oneline docker/myfolder | cut -d' ' -f 1`
> TAG_HASH := `[[ "{{JENKINS_URL}}" != "" ]] && echo {{FOLDER_GIT_SHA}} || echo {{FOLDER_HASH}}`
> ```
> 
> That last line is already not very readable, but `{{JENKINS_URL}}`, `{{FOLDER_GIT_SHA}}` and `{{FOLDER_HASH}}` are empty in the line above.
> (because the variables inside `{{ }}` are not replaced by their values (this happens only at the beginning of the file, it works in targets. Could it be a bug?).

Thanks for posting this! Could you elaborate on what's happening here? Backticks in variables outside of recipes are evaluated before any recipe runs. Is that not happening?

**Comment by kenden** [comment]
Backticks in variables outside of recipes are evaluated before any recipe runs, yes, but it doesn't seem possible to use the result of this evalation inside other backticks. Here is a simpler example:

Here is a justfile:
```make
var1 := 'Hello'
var2 := `echo World`
var3 := `echo {{var1}} {{var2}}!`

debug:
```

And the execution:
```make
$ just --evaluate
var1 := "Hello"
var2 := "World"
var3 := "{{var1}} {{var2}}!"
```

I would have expected the result:
```make
$ just --evaluate
var1 := "Hello"
var2 := "World"
var3 := "Hello World!"
```

**Comment by casey** [comment]
Ah, okay, gotcha. I would like to come up with a backwards compatible way to use interpolations inside of strings and backticks. I think copying python's f-strings would be a good idea:

```
var1 := 'Hello'
var2 := `echo World`
var3 := f`echo {{var1}} {{var2}}!`
```

Only strings and backticks prefixed with `f` for "format" would be interpolated. I updated #11 (from all the way back in 2016!) to track this.
