### ISSUE TITLE
zsh autocomplete issue tabbing after passing --set VAR value

### ISSUE THREAD

**Issue by kenden** [casey/just#695]
There is an issue with the 
zsh autocompletion when pressing tab after 
`just --set VAR value `
It displays a block of error.

### Load autocompletion in your terminal
`$ source <(just --completions=zsh)`

### Create a justfile 

```make
GREET_WORD := 'Hello'
greet name:
  @echo {{GREET_WORD}} {{name}}!
```
### Use it

```make
$ just greet Robert
Hello Robert!
```
### Use it with autocompletion

If we want to set the variable GREET_WORD from the command line using `--set`, we would enter:  
`$ just --set GREET_WORD ` then press Tab  
---> It autocompletes to:  
`$ just --set GREET_WORD greet`  
here, it should not autocomplete with a target, or anything, just wait for the user to enter a value.

But, if we type a correct content for the variable:  
`just --set GREET_WORD Hola ` then press Tab
----> we get:
```bash
$ just --set GREET_WORD Hola …error: The argument '--set <VARIABLE> <VALUE>' requires a value but none was supplied

USAGE:
    just --color <COLOR> --set <VARIABLE> <VALUE> --shell <SHELL> --shell-arg <SHELL-ARG>... <--choose|--completions <SHELL>|--dump|--edit|--init|--evaluate|--list|--show <RECIPE>|--summary|--variables>

For more information try --help
error: The argument '--set <VARIABLE> <VALUE>' requires a value but none was supplied

USAGE:
    just --color <COLOR> --set <VARIABLE> <VALUE> --shell <SHELL> --shell-arg <SHELL-ARG>... <--choose|--completions <SHELL>|--dump|--edit|--init|--evaluate|--list|--show <RECIPE>|--summary|--variables>

For more information try --help
error: The argument '--set <VARIABLE> <VALUE>' requires a value but none was supplied

USAGE:
    just --color <COLOR> --set <VARIABLE> <VALUE> --shell <SHELL> --shell-arg <SHELL-ARG>... <--choose|--completions <SHELL>|--dump|--edit|--init|--evaluate|--list|--show <RECIPE>|--summary|--variables>

For more information try --help
```
-> Here, it should have autocompleted with a target.

You can see the steps above in this recording:
![just-autocomplete-zsh-issue](https://user-images.githubusercontent.com/480586/95529527-6ad89a00-09db-11eb-97ee-42aefd536194.gif)

## Note

It would be nice to be able to set parameters with --set using space OR `=`, e.g.  
`just --set GREET_WORD Hola greet Robert`  
or  
`just --set GREET_WORD=Hola greet Robert`  
or  
`just --set=GREET_WORD=Hola greet Robert`  
or (with quotes, even):
`just --set="GREET_WORD=Hola" greet Robert`
(just mentioning this because using a = sign would not trigger this issue)

## Versions
`just v0.8.0`
`zsh 5.7.1 (x86_64-apple-darwin19.0)`

**Comment by casey** [comment]
Thank you for the detailed report!

There's actually an alternative syntax for setting variables:

```
just GREET_WORD=Hola
```

If an initial argument is of the form `.*=.*`, just will interpret it as a set. Is that a viable workaround? This is still definitely a bug.

@heyrict, I was wondering you had an idea for a quick fix for this? If not, no worries!

**Comment by kenden** [comment]
@casey Thanks! I prefer using `just --set` for setting variables because:
- on the command line, pressing tab after `just --set ` will autocomplete with variables from the justfile, I don't need to remember them,
- in a script/CI config, it makes it (IMHO!) clearer that we are setting a variable.
(except that in `just --set GREET_WORD Hola greet Robert`, it's hard to see what is a variable, what it a target and what is a target's parameter, another reason why allowing an `=` with `--set` would be would be nice to have. Other programs often allow both, ex `docker run --env=http_proxy --env https_proxy`).

Also, pressing tab after `just GREET_WORD=Hola ` there is also an error: 
```bash
just GREET_WORD=Hola …Justfile does not contain recipe `GREET_WORD=Hola`.
Justfile does not contain recipe `GREET_WORD=Hola`.
Justfile does not contain recipe `GREET_WORD=Hola`.
```
---> It should have autocompleted with a target.

**Comment by heyrict** [comment]
I'll publish a patch later today.
