### ISSUE TITLE
Choosing multiple items for execution

### ISSUE THREAD

**Issue by gergelyk** [casey/just#699]
This would be great to select multiple recipes after invoking just with `--choose` option. Note that fzf supports `-m` option and returns items in the same order as they were selected by the user.

**Comment by gergelyk** [comment]
I also added [this](https://github.com/junegunn/fzf/issues/2207) feature proposal to `fzf`, which would make integration with `just` even better.

**Comment by casey** [comment]
Good suggestion! This was super easy to add: #700

I checked out your FZF feature request, and wanted to note that it might not work with just the way you were thinking. If the same recipe is passed to Just multiple times on the command line, it will still only run once. So `just test test test` will only run the `test` recipe once.

**Comment by gergelyk** [comment]
Thanks for super fast implementation and for the notice!
