### ISSUE TITLE
The same recipe called multiple times

### ISSUE THREAD

**Issue by gergelyk** [casey/just#703]
Based on [this](https://github.com/casey/just/issues/699#issuecomment-706632570) notice, I presume that this may be a bug:

```
gergelyk@anarchy ~/tmp/hello % cat justfile 
hello:
  echo 'Hello world!'
gergelyk@anarchy ~/tmp/hello % just --version
just v0.8.0
gergelyk@anarchy ~/tmp/hello % just hello hello
echo 'Hello world!'
Hello world!
echo 'Hello world!'
Hello world!
```

I find it useful though. Let's consider this as a feature :)

**Comment by casey** [comment]
Ahh, I must have been mistaken. Recipes dependences are deduplicated, but I guess recipes given on the command line aren't. Nobody's ever complained about this, so I think it's safe to consider it a feature, and not a bug.
