### ISSUE TITLE
Recipes completion?

### ISSUE THREAD

**Issue by Nicolab** [casey/just#706]
Hello,

First, thanks for this great project. It makes life more comfortable :+1: 

I installed the completions script, it does the job for _just_ command but not for recipes (like _make_). 
Normal or I forgot something?

**Comment by casey** [comment]
Thanks for the kind words!

The scripts are auto-generated, so only some of them, which have been hand modified, auto-complete recipe names. I believe the ZSH, PowerShell, and Bash scripts have modifications to complete recipe names. Which shell are you using? Also, do you know which version of Just, and which version of the completion scripts you're using?

**Comment by Nicolab** [comment]
Thanks for your reply.

Bash (Ubuntu 18.04 - GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu))
just v0.7.3

I generated the completion scripts yesterday with just v0.7.3.
Today I tested with _just_ v0.8.0, I re-generated the completions scripts. There is no recipe completion.
In my .bashrc: `source ~/.just.bash`

**Comment by ilourt** [comment]
Hello,

I think what means @Nicolab  is to have an autocompletion like make. Where it autocomplete the name of the recipe.

For example if I have a the following justfile:
```
echo:
  echo "OK"

ls:
  ls
```

If I type `just e` and then hit <tab> it should autocomplete to write this : `just echo`.

Thank you for your work, it makes a big improvement from using make ;)

**Comment by casey** [comment]
Ah, sorry, I was confused because although the completion script was improved to complete recipe names, it hadn't made it into a release.

I just cut [v0.8.1](https://github.com/casey/just/releases/tag/v0.8.1), which has the improved completion script. It's been published to crates.io, and prebuilt-binaries are building on CI, and should be added to the tag soon.

**Comment by Nicolab** [comment]
Oh thanks @casey, it works well!

**Comment by casey** [comment]
Awesome! Thanks to @vikesh-raj for contributing the improved completion script!

**Comment by lud** [comment]
Homebrew is still in `0.7`. Could you update it here as well?

**Comment by casey** [comment]
> Homebrew is still in `0.7`. Could you update it here as well?

Are you sure? I just checked, and Just on homebrew is v0.8.3.

**Comment by lud** [comment]
Yep sorry I was out of sync!

**Comment by casey** [comment]
> Yep sorry I was out of sync!

No worries, glad you're able to get the latest version!
