### ISSUE TITLE
Document Feature Flags

### ISSUE THREAD

**Issue by CosmicHorrorDev** [casey/just#708]
Sorry if it's already documented and I missed it, but from the `Cargo.toml` file I see there are feature flags for `help4man2man` and `summary`, but I don't see anywhere that explains what these do.

**Comment by CosmicHorrorDev** [comment]
From a bit more digging (with some blame) I see that `help4man2man` is having a generated `man` page that doesn't look to great hence keeping it behind a feature flag, and `summary` is used by Janus.

**Comment by casey** [comment]
Good idea, they're not super useful, but it's good to document them nonetheless. I added comments to all the flags in Cargo.toml in #709.
