### ISSUE TITLE
How to use variable in backticks?

### ISSUE THREAD

**Issue by Boscop** [casey/just#731]
How can I do this?
```sh
foo := `echo {{bar}} | tr '[:upper:]' '[:lower:]'`
```
Or this:
```sh
version := `sed -En 's/version[[:space:]]*=[[:space:]]*"([^"]+)"/v\1/p' {{foo}}/Cargo.toml | head -1`
```

When I do this, they are not substituted.

**Comment by casey** [comment]
This isn't currently supported, but there's an open issue for it: #11

The design I currently favor, to avoid breaking backwards compatibility, is to require strings and backticks inside of which interpolation is desired to be proceeded by a `f`, so:

```
foo := f`echo {{bar}} | tr '[:upper:]' '[:lower:]'`
```
