### ISSUE TITLE
Syntax Highlighting for VS Code

### ISSUE THREAD

**Issue by casey** [casey/just#732]
This was mentioned as a pain point in #730. I don't use VS Code, so I probably won't be able to do this, but I wanted to create an issue in case someone is feeling  motivated.

It won't be perfect, but a great first step for this would just be reusing VS Code's `make` syntax highlighting.

**Comment by johnthethird** [comment]
I have been using this and it works great, it is mentioned in your readme  https://github.com/skellock/vscode-just

**Comment by casey** [comment]
Whoops, I totally forgot that existed 😅 Thanks for reminding me!
