### ISSUE TITLE
Pkg for Raspberry Pi

### ISSUE THREAD

**Issue by jschank** [casey/just#739]
This is a feature request.

It would be nice if there were pre-built binaries for Raspberry Pi.
Which could be installed via apt.

**Comment by casey** [comment]
Thanks for opening this issue!

I would definitely like Just to be available for the Pi. I guess this would mean having packages for Raspbian OS. Do you happen to know how Raspbian gets its packages? Do they just mirror Debian packages, or is there an extra step or separate package repository?

**Comment by jschank** [comment]
Hi Casey,
I'm not certain about the details for how Raspbian gets its goodies. I just don't have the linux experience.
But I do know a couple things:
1. Raspbian is a fork of debian
2. The Pi uses apt to get its packages
3. I THINK - the /etc/apt/sources.list defines how the pi gets its packages

my pi has this in its sources.list
```
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb https://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
```

Being able to install *just* via apt would be ideal.
But a good second place would be for the build pipeline to cross compile for the Pi, and then post a binary that can be downloaded.

**Comment by casey** [comment]
That all makes sense. I'm assuming that packages come from Debian by default, and then are automatically available for the Pi. #429 tracks packaging Just for Debian package, but I'll leave this open in case there are extra steps.

For now, creating a prebuilt binary that can run on Raspberry Pi sounds like the right next step. 

This means building and packaging a binary for `aarch64-unknown-linux-gnu`. I'm not sure the right way to do this. Currently we use GitHub Actions to build Linux, Mac, and Windows binaries, but only for x86.

I don't thing GitHub Actions supports ARM, so we would have to cross-compile ARM binaries, which I know very little about.

I'm not sure I'll have the chance to tackle this soon, so if anyone feels like jumping on this, go right ahead!

The relevant files are the GitHub Actions workflow definition:

https://github.com/casey/just/blob/master/.github/workflows/build.yaml

And the `package` shell script, which runs on tags to upload release archives to GitHub:

https://github.com/casey/just/blob/master/bin/package

**Comment by bburns** [comment]
Just seconding the request for a pi version 👍 

I'm using just for managing all kind of things on my mac for a project, and would like to use it on a pi as well. Is it difficult to build manually?

**Comment by casey** [comment]
I started building for ARM, but I'm not sure if the binary will work on Rasp Pi, since it's 64 bit.

Could someone try the binary here and see if it works?

https://github.com/casey/just/releases/download/v0.9.4/just-v0.9.4-aarch64-unknown-linux-gnu.tar.gz

(If it doesn't, I can start also building 32 bit ARM binaries.)

**Comment by contagon** [comment]
I know this is a stale topic, but just gave it a shot on my Raspberry Pi 3B+, which appears to be 32bit, and the 64bit ARM binary didn't work. 

Would love to have a 32bit prebuilt ARM binary as well!

**Comment by runeimp** [comment]
Even though Raspberry Pi 3 and greater use 64-bit hardware the Raspian OS is still 32-bit. Though they are working on a 64-bit version it hasn't been much of a priority.

**Comment by casey** [comment]
@contagon I opened PR #1028, which adds a 32bit ARM build. Would you mind trying out the binary, and seeing if it works for you? Here's a link:

https://github.com/casey/just/releases/download/refactor-build-tag-4/just-refactor-build-tag-4-armv7-unknown-linux-gnueabihf.tar.gz

**Comment by casey** [comment]
I went ahead and merged PR #1028. The release action should now build 32- and 64-bit ARM binaries. Try them out and let me know if they work!

They should be uploaded here for the latest release as they're built:

https://github.com/casey/just/releases/tag/0.10.4

**Comment by contagon** [comment]
@casey Sorry for the delay, just got a chance to try it and worked like a charm. Thanks! I appreciate the quick response, and thanks for all your work and this awesome project.

**Comment by casey** [comment]
@contagon No worries at all! Awesome, glad the binaries worked.
