### ISSUE TITLE
Windows behaviour of just without arguments.

### ISSUE THREAD

**Issue by epogrebnyak** [casey/just#746]
Keeping using great just runner and coming with better workflows. Thanks for this parogram!

I noticed on Windows simply `just` invokes the first command from justfile. Is this an intended behaviour or some Windows glitch?

**Comment by casey** [comment]
> Keeping using great just runner and coming with better workflows. Thanks for this parogram!

You bet!

> I noticed on Windows simply `just` invokes the first command from justfile. Is this an intended behaviour or some Windows glitch?

This intended behavior. The first recipe in the justfile is run if you don't provide a recipe.

I usually make whichever recipe is most frequently run the default, like running tests, but if there isn't something like that, I'll make it list the recipes instead:

```
default:
  just --list
```
