### ISSUE TITLE
recipe "default: @just --choose" produces error

### ISSUE THREAD

**Issue by imawhale** [casey/just#749]
The first recipe in my Justfile is:

```
default:
    @just --choose
```

However, both "just" and "just default" return an error.

```
error: Found argument '--choose' which wasn't expected, or isn't valid in this context

USAGE:
    just [FLAGS] [OPTIONS] [--] [ARGUMENTS]...

For more information try --help

```

**Comment by casey** [comment]
What version of Just are you using? I think `--choose` was added in `v0.7.3`, so it's relatively recent.

**Comment by imawhale** [comment]
Thanks, that looks like it.

I had installed using brew and ran brew upgrade just, but that only got me to just version 0.5.8.

Will upgrade brew itself and then upgrade just. Closing issue.

**Comment by casey** [comment]
Nice, glad you got it working! I'm not sure under what circumstances it happens, but I think homebrew sometimes fails to update itself, and installs stale versions.
