### ISSUE TITLE
Generate help documentation 

### ISSUE THREAD

**Issue by deckarep** [casey/just#75]
As a justfile grows in commands and complexity it would be cool if we were able to generate help text like:  `just --browse`

And maybe this could sweep the justfile and print a quick summary of all the commands and their arguments in a sorted fashion.

**Comment by casey** [comment]
I've added a few options recently that can help with this:
- `--list`: Prints the names of all recipes
- `--dump`: Print the entire justfile
- `--evaluate`: Print evaluated variable values
- `--dry-run`: Print what just would do without doing it
- `--show RECIPE`: Print RECIPE

I'm thinking about adding doc comments for recipes and a `--summary` option to print recipes with their comments, see #84.

Does that cover what you're looking for?

**Comment by deckarep** [comment]
Ok, this is great...I'm not a computer right now but will try out the different help flags. I think you probably nailed it if at least one of the help flags shows the args needed to satisfy the recipe.

Also thanks for the quick work on the default args!  This project is great.

**Comment by casey** [comment]
That's actually a good point, none of the existing options show recipes with arguments in a concise way. I'll add `--summary` that does that, although doc comments for that will have to wait.

**Comment by casey** [comment]
I added `--summary`, but then decided that it's probably more useful than `--list`, so I swapped the names, so `--list` will display recipes with arguments one per line, and `--summary` will just print recipe names.

**Comment by deckarep** [comment]
Just tried it out, this is perfect.

**Comment by casey** [comment]
Sweet :)
