### ISSUE TITLE
Change current working directory?

### ISSUE THREAD

**Issue by xingheng** [casey/just#751]
Justfile:
```
run:
    cd {{invocation_directory()}}/.. && pwd;
    pwd
```

Output:
```
cd /Users/me/work/.. && pwd;
/Users/me
pwd
/Users/me/work
```

My initial *current working directory* is `/Users/me/work`, it seems the second `pwd` doesn't work there, why and how?

Please forgive me this may be a stupid question, close this if it is, I just wanna the expected answer.

**Comment by xingheng** [comment]
Resolved.

```
run:
    #!/usr/bin/env bash
    set -euxo pipefail

    cd {{invocation_directory()}}/.. && pwd;
    pwd
```

**Comment by casey** [comment]
Sorry for not getting to this sooner! This is definitely not a stupid question at all, and is a common point of confusion.

I just opened #752 to explain why this happens, and how to work around it.
