### ISSUE TITLE
Changing working directory in shebang line doesn't work

### ISSUE THREAD

**Issue by elkarouh** [casey/just#755]
>With the above shebang, just will change its working directory to the location of the script. If you’d rather leave the working directory >unchanged, use #!/usr/bin/env just --working-directory . --justfile

This doesn't work.

**Comment by casey** [comment]
I just tried it, and it worked for me. I created the following justfile:

```
#!/usr/bin/env just --working-directory . --justfile

default:
  pwd
```

And made it executable. When I execute it, it prints the directory that I was in, and not the directory that contains the script.

Let me know if you're getting some other behavior!

**Comment by elkarouh** [comment]
Hi,

It works on MacOs but on my linux machine. I put the above contents in a file called hello.just and made it executable.
When running: 
`./hello.just`

I get the following error message:
/usr/bin/env just --working-directory . --justfile: No such file or directory

When i run the same file in the following way:
`/usr/bin/env just --working-directory . --justfile hello.just`
it works.

**Comment by casey** [comment]
> It works on MacOs but on my linux machine.

Ah, okay. Linux splits shebang lines differently from macOS, which must be causing this issue.

Can you try the following:

```
#!/usr/bin/env -S just --working-directory . --justfile

default:
  pwd
```

The `-S` argument to env should fix this.

**Comment by elkarouh** [comment]
The -S option is not available on my Linux machine (this is at work, i have no possibility to upgrade).

I instead tried to use the complete path to the 'just' executable

`#!/auto/home/user245/.local/bin/just --working-directory . --justfile`
 
and i get another error message:
```
error: The following required arguments were not provided
             --justfile <JUSTFILE>

USAGE: ...

```

EDIT: apparently, the Linux kernel treats everything following the first “word” in the shebang line as a single argument.

**Comment by casey** [comment]
> The -S option is not available on my Linux machine (this is at work, i have no possibility to upgrade).

Ah, hat sucks. I added a note to the readme that shebang splitting works differently across different platforms, and you might need to use the `-S` flag on Linux: #757

> EDIT: apparently, the Linux kernel treats everything following the first “word” in the shebang line as a single argument.

That's my understanding as well.

**Comment by casey** [comment]
Sorry that I don't have a good fix for this. It's surprisingly hard to work around shebang line splitting inconsistencies.
