### ISSUE TITLE
Add recipe annotation to prevent cd-ing to justfile

### ISSUE THREAD

**Issue by casey** [casey/just#762]
_Proposed along with a few other features in #761, moving into its own issue to track separately._

It might be nice to have a recipe annotation that makes just use the invocation directory as the current working directory for that recipe, like so:

```
#[no_cd]
foo:
  pwd # will print invocation directory, not justfile directory
```

**Comment by jchook** [comment]
Just a stylistic suggestion: perhaps `#[cwd]` is more idiomatic than `#[no-cd]`

**Comment by tcassaert** [comment]
Until this is implemented, you can add
```
#!/usr/bin/env bash
cd -
```
which will take you back to the directory where you executed the `just` command.

**Comment by casey** [comment]
I can't get this to work:

```
foo:
  #!/usr/bin/env bash
  pwd
  cd -
  pwd
```

```
$ just foo
/Users/rodarmor/tmp/cd
/var/folders/b5/q2c4mxk534v6kwdtx2mpw91m0000gn/T/justF2cWhz/foo: line 4: cd: OLDPWD not set
/Users/rodarmor/tmp/cd
```

**Comment by tcassaert** [comment]
Hmmm, I can only get it to work when my Justfile is located in `$HOME/Justfile`. Didn't pay attention to that...

**Comment by casey** [comment]
We have recipe attributes now, so this was very simple to implement. It's available on master if you want to give it a shot!
