### ISSUE TITLE
Support variable replacement in backtick expressions

### ISSUE THREAD

**Issue by ipsingh06** [casey/just#788]
First of all, great project! I recently discovered Just and it looks super useful.

I'm looking to derive a variable from another variable like so, but it looks like variable substitution isn't supported inside backticks.

```bash
list := "a b c"
derived1 := `for item in {{list}}; do echo -n "$item, "; done`
derived2 := `for item in a b c; do echo -n "$item, "; done`
```
```bash
just --evaluate
derived1                := "{{list}}, "
derived2                := "a, b, c, "
list                    := "a b c"
```

Please let me know if there's another way to do this. If not, I think it'd be a great addition. Thanks.

**Comment by casey** [comment]
Hi Inderpreet, thanks for the kind words! This isn't currently possible, and is tracked in #11. It's a bit tricky to do, which is why it's taken so long to add.
