### ISSUE TITLE
How to interpolate a Just variable inside a command evaluated inside another Just variable?

### ISSUE THREAD

**Issue by davideliseo** [casey/just#798]
For example, how, if possible, can I do something like this:

```
UUID := "<some UUID here>"
deviceName := `blkid -U {{UUID}}`
```

If I run my `justfile` with those two lines I get this error:

```
error: Backtick failed with exit code 2
  |
2 | deviceName := `blkid -U {{UUID}}`
  |               ^^^^^^^^^^^^^^^^^^^
```

When the expected result is, for example, `deviceName := "/dev/sda"`.

If it's not possible, is there any workaround? I'm using those two variables separately in different recipes. I also want to avoid writing the `UUID` directly into the `blkid` command.

Thanks for any help!

**Comment by casey** [comment]
Unfortunately this currently isn't possible, although hopefully will be soon. See #11 for details of how this would work.
