### ISSUE TITLE
How can I merge these two similar rules?

### ISSUE THREAD

**Issue by edaqa-uncountable** [casey/just#801]
I have the following two rules in a justfile:

```
pytest target="site/test/app":
    python -m pytest --rootdir=site/test -c site/test/pytest.ini {{target}}

pytest-pattern target pattern:
    python -m pytest --rootdir=site/test -c site/test/pytest.ini {{target}} -k {{pattern}}
```

I'd prefer to have just a `pytest target="site/test/app" pattern=''` target and conditionally add the `-k` part.

I'm using two rules since I couldn't figure out how to optionally expand the `-k {{ pattern }}` bit.   Using if...then didn't work since it can't interpolate {{pattern}} inside the blocks.

I'm trying to avoid resorting to a bash script.

**Comment by casey** [comment]
Thanks for the issue!

You could do this:

```
pytest-pattern target="site/test/app" pattern="":
    python -m pytest --rootdir=site/test -c site/test/pytest.ini {{target}} {{ if pattern == "" { "" } else { "-k " + pattern } }}
```

It's pretty gross though. This has come up a few times, I think. It would be nice if there was a better way to do this, like:

```
pytest-pattern target="site/test/app" pattern="":
    python -m pytest --rootdir=site/test -c site/test/pytest.ini {{target}} {{ pattern && "-k " + pattern }}
```

Although that's a bit weird. I'm going to leave this issue open, to provide a place to discuss how best to solve this.

**Comment by nigels-com** [comment]
Works well enough for me.
