### ISSUE TITLE
Allow choosing the dotenv filename with a command line flag

### ISSUE THREAD

**Issue by casey** [casey/just#802]
Requested by a user in Discord, allow setting the dotenv filename with a flag, for example:

```
$ just --dotenv-name .env-test
```

I'm not sure if this should be called `--dotenv-name` or `--dotenv-filename`.

**Comment by bddap** [comment]
`--dotenv-file`?

**Comment by casey** [comment]
> `--dotenv-file`?

I'm imagining that there might be one flag that takes a filename, and one that takes a full path, which is why I'm leaning towards `--dotenv-filename` and `--dotenv-path`. If it's `--dotenv-file` and `--dotenv-path`, it would be a big ambiguous which is which.

**Comment by bddap** [comment]
From the readme:

> just will load environment variables from a file named `.env`. This file can be located in the same directory as your justfile or in a parent directory.

Ah. I see. So `--dotenv-filename` would not accept a path as `--dotenv-path` might.

`just --dotenv-filename .env-test` and `just --dotenv-path .env-test` would both be valid but the first invocation would also check parent directories for files named `.env-test`.

**Comment by casey** [comment]
Yup, that's right.

**Comment by casey** [comment]
And maybe if people want it, `--dotenv-dir` will set the directory to start looking for a dotenv file.

**Comment by Celeo** [comment]
If the user specifies `--dotenv-path` and that path doesn't resolve to a file, should an error be returned, or should the search for the environment file "fall back" to looking for an `.env` file?

**Comment by casey** [comment]
Fixed in #941.
