### ISSUE TITLE
Autoformatter/prettifier for justfiles

### ISSUE THREAD

**Issue by kwshi** [casey/just#817]
Same idea as `pretty` for JS/CSS/HTML and `black` for Python, but for justfiles.  It looks like `just`'s syntax tree representation is pretty comprehensive already and simple enough that it shouldn't be too hard to write a `Module -> String` pretty-printer that can be used to autoformat justfiles.  Also I think it would be a nice to have.

**Comment by casey** [comment]
This would be great!

I would suggest making it a subcommand of Just, invoked with `just --fmt`, that rewrites the justfile in place with a formatted version.

`Justfile` already implements `Display`, and produces a valid justfile. However, it strips comments, and doesn't preserve the order of recipes in a justfile.

So giving `Module` a `Display` implementation, or a `pretty_print` method, would probably be the way to go.

**Comment by casey** [comment]
This was done in #837.
