### ISSUE TITLE
#!powershell.exe does not works

### ISSUE THREAD

**Issue by sigoden** [casey/just#825]
```
set shell := ["powershell.exe", "-c"]

default:
    #!powershell.exe
    Write-Host Hello-World
```
We cannot create powershell shebang because "just" will create tmp script file without any ext

Powershell cannot run script without `.ps1` extension.

Maybe we should support custom extension to created script file.

**Comment by casey** [comment]
Does `pwsh.exe` exist, and does it behave differently?

I have `pwsh` on my mac, and it doesn't require an extension.

I'm still inclined to fix this for `powershell.exe` either way, so I'm mostly asking out of curiosity.

**Comment by sigoden** [comment]
`pwsh.exe` doest not exist on my pc. I never here it. Maybe I will try it later.

**Comment by sigoden** [comment]
`pwsh.exe`  is able to run script file without `.ps1` extensions.

**Comment by dmringo** [comment]
I think as of https://github.com/PowerShell/PowerShell/pull/15859, which is in PowerShell Core 7.2, recipes with a `pwsh` shebang need a `.ps1` extension too.

**Comment by casey** [comment]
@dmringo Thank you for reporting this! Reopening.

**Comment by runeimp** [comment]
`powershell.exe` is PowerShell Desktop, Windows only. `pwsh.exe` (Windows) or `pwsh` (everywhere else) is PowerShell Core (cross-platform) is PowerShell Version 6/7+ (version 6 was not made public to my knowledge). PowerShell Desktop is version < 6.

**Comment by casey** [comment]
@dmringo I don't think we ever actually checked if this doesn't work. I checked the code, and it looks like a `.ps1` extension is used whenever the interpreter matches `powershell.exe` or `pwsh.exe`, so this should work. Please reopen if running a shebang recipe using a powershell shebang line fails.

**Comment by dmringo** [comment]
> @dmringo I don't think we ever actually checked if this doesn't work. I checked the code, and it looks like a `.ps1` extension is used whenever the interpreter matches `powershell.exe` or `pwsh.exe`, so this should work. Please reopen if running a shebang recipe using a powershell shebang line fails.

It definitely works for me now. I've been happily using Powershell recipes since #1027 made it into the release.
