### ISSUE TITLE
aarch64 binaries in release

### ISSUE THREAD

**Issue by kapilt** [casey/just#840]
just a request for linux arm 64 binaries

**Comment by casey** [comment]
Thanks for opening this! Just because I'm curious, and to make sure the binaries that I produce actually work for your use case, what computer are you targeting?

**Comment by casey** [comment]
This actually wasn't so bad. I was able to get cross-compilation working on GitHub actions without too much of a fuss.

Could you give the binary here a try:

https://github.com/casey/just/releases/download/cross-test/just-cross-test-aarch64-unknown-linux-gnu.tar.gz

I don't have an arm machine to test on.

**Comment by kapilt** [comment]
fwiw, i'm targeting aws ec2 graviton instances (neoverse v1) - https://www.anandtech.com/show/15578/cloud-clash-amazon-graviton2-arm-against-intel-and-amd.

thanks!, i'll check out the binaries shortly.

**Comment by kapilt** [comment]
works great, thanks!
