### ISSUE TITLE
export keyword outside recipes not setting environment variable

### ISSUE THREAD

**Issue by beckend** [casey/just#854]
```
export DIR_CURRENT := justfile_directory()
PROJECT_NAME := `basename ${DIR_CURRENT}`
```

`just my-test-recipe`

```shell
sh: line 1: DIR_CURRENT: unbound variable
error: Backtick failed with exit code 127
  |
2 | PROJECT_NAME := `basename ${DIR_CURRENT
```

**Comment by casey** [comment]
This should be documented, but it's working as intended.

Normally, `just` knows which assignments depends on which other assignments, and can thus evaluate them in order:

```
# `bar` will be evaluated before `foo`, since the value of `foo` depends on the value of `bar`
foo := "hello " + bar
bar := "world"
```

However, when using the `export` keyword and backticks that use exported variables, `just` doesn't know which variables depend on which others:

```
export DIR_CURRENT := justfile_directory()
# `just` doesn't understand shell, so it doesn't know that the following backtick depends on `DIR_CURRENT`
PROJECT_NAME := `basename ${DIR_CURRENT}`
```

So, to avoid the order of variable evaluation mattering, which might change unpredictably, `just` does not make export variables to backticks in the same scope.

**Comment by casey** [comment]
I just documented this in #856. It's in-progress, but the best bet for doing what you want is #822, which allows interpolation in backticks, so you could do:

```
export DIR_CURRENT := justfile_directory()
PROJECT_NAME := f`basename {{DIR_CURRENT}}`
```
