### ISSUE TITLE
latest release doesn't have a v prefix

### ISSUE THREAD

**Issue by 06kellyjac** [casey/just#873]
The latest release doesn't have a `v` prefix. I'm happy with it either way but I just want to know if it's intentional and will be the same going forward or a mistake? :slightly_smiling_face:

**Comment by casey** [comment]
Yes, I removed the `v` prefix from release tags. It simplified some things, and was consistent with what I noticed other rust projects doing. I hope it wasn't too disruptive, I was worried that I'd break some scripts.

**Comment by 06kellyjac** [comment]
No it wasnt disruptive at all really. I just needed to remove the v and run the update script again, very little effort required, only added an extra second or two 😅
