### ISSUE TITLE
Recipes with variable numbers of arguments?

### ISSUE THREAD

**Issue by IndianBoy42** [casey/just#874]
Is there any way/plan to allow making recipes that can take any number of arguments?

I love using Justfiles for collecting what would be small one off scripts into one organized file (along with common variables and dependencies). 

The only thing stopping me from essentially fully replaces normal scripts is the ability to take multiple arguments.
If I could do that then pretty much all command line scripts can be run from Justfile instead

**Comment by casey** [comment]
Yup, there is, you can put `*` before an argument to accept zero or more arguments:

```
foo *args:
  echo {{args}}
```

Or `+` to accept one or more arguments:

```
foo +args:
  echo {{args}}
```

Be careful with quoting! You might want to use [positional arguments](https://github.com/casey/just/#positional-arguments) if your arguments contain spaces.

**Comment by IndianBoy42** [comment]
Thanks, i don't know how I missed that in the documentation

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by casey** [comment]
You bet!
