### ISSUE TITLE
Function Ideas

### ISSUE THREAD

**Issue by casey** [casey/just#876]
Since functions are self-contained, easy to add, and provide useful functionality, I think it would be a good idea to add more of them. Also, they make for great first issues.

Currently, functions must take and return strings.

Some ideas for functions:

- `uppercase(s)`: Convert `s` to uppercase
- `lowercase(s)`: Convert `s` to lowercase
- [Bash string manipulation operations](https://tldp.org/LDP/abs/html/string-manipulation.html)
- `replace(s, from, to)`: Replace occurrences of `from` in `s` to `to`.
- `trim(s)`: Remove leading and trailing whitespace from `s`

**Comment by mattbailey** [comment]
Would love to see more functions like string manipulations on iterable targets like Make has; would make (hur) this tool a much more compelling replacement.

One of my primary reasons for using Make is that it has a wide variety of string functions that replicate a lot of functionality people normally use `sed` and `awk` for, except in a far more portable way. Since I have users on macOS, linux, and WSL2, I strictly avoid these tools because of the differences between BSD and GNU implementations.

**Comment by casey** [comment]
@mattbailey What kinds of functions would be helpful? Adding functions is very easy, so if they're useful, it's an easy win.

One potential challenge is Just's type system. The only type is strings, and variadic arguments are kind of hack and don't work everywhere like you'd expect, because there's no list type.

**Comment by mattbailey** [comment]
Make's wildcard(), filter(), filter-out(), etc... basically make's text functions (https://www.gnu.org/software/make/manual/html_node/Text-Functions.html#Text-Functions) and filename functions (https://www.gnu.org/software/make/manual/html_node/File-Name-Functions.html#File-Name-Functions) are very useful.

There's also a common pattern of a psudeo-templated-heredoc in make where you do something like

```make
define SOME_FILE
contents of file, maybe with some $(vars)
endef

export SOME_FILE
target.file.txt:
	@echo $$SOME_FILE > $@
```

which is certainly a hack in Make, but a very useful one, and could be a more explicit tool in `just`

**Comment by casey** [comment]
The `define SOME_FILE … endef` will be supported eventually via format strings:

```
x := f'''
  contents of file, maybe with some {{vars}}
'''
```

This is in-progress, although it's a big change, so it might be a little while before it lands.

Agreed that all those make functions would be very useful. Functions which take and return strings are easy to add, but functions that take and/or return lists of strings are harder, since lists of strings don't exist in `just`'s type system.

**Comment by tomprince** [comment]
It would be nice to have a function that shell escapes an argument.

**Comment by casey** [comment]
> It would be nice to have a function that shell escapes an argument.

For a long time, I thought this would be extremely hard, since different shells have different quoting behavior. However, I found a semi-portable quoting algorithm [here](http://www.etalabs.net/sh_tricks.html).

The idea is to replace every single quote in a string with `'\''` and surround the result with `'`. This seems to work for most shells.

**Comment by casey** [comment]
#1022 adds a `quote` function that implements this algorithm.

**Comment by funkyfuture** [comment]
currently i could use a function that takes a variable as input and replaces all occurrences of `{{…}}` references in it with the values of the referenced variables.

would that be of interest or tends it too much to over-engineering?

use-case is to render a small metadata file that needs to be updated on releases.

amendment: #822 👀

**Comment by funkyfuture** [comment]
ah, i just noticed that @mattbailey proposes something similar.

**Comment by shreve** [comment]
> would that be of interest

I came here looking for exactly that, so it's of interest to me, at least. I want the following to work for building multiple dockerfiles from the same directory:

```
IMAGE := "0000000000.dkr.ecr.us-east-1.amazonaws.com/{{which}}-ci:{{tag}}"

build which tag="latest":
    echo docker build {{which}}/ -f Dockerfile.{{which}} -t {{IMAGE}}

run which tag="latest" cmd="bash":
    docker run --rm -it --privileged -v $(pwd):/ci {{IMAGE}} {{cmd}}
```

With certainly more functions where repeating the image URL inline is painful.

**Comment by nk9** [comment]
Just a note that most of the originally imagined functions have now been implemented:
- `lowercase()`
- `uppercase()`
- `replace()`
- `trim()` and friends

There are plenty of Bash string functions like `index` and `match`, although many involve the probably-not-trivial regex. Is it time for a new bug, or maybe just an updated (first) comment enumerating the ones we'd like in just?

**Comment by casey** [comment]
> There are plenty of Bash string functions like index and match, although many involve the probably-not-trivial regex. Is it time for a new bug, or maybe just an updated (first) comment enumerating the ones we'd like in just?

I think we can close this, and just add new functions as people want them. Definitely feel free to open issues with any functions you want / think would be interesting.
