### ISSUE TITLE
recipe command line arguments do not handle arguments with spaces

### ISSUE THREAD

**Issue by jmcantrell** [casey/just#887]
When passing arguments to a recipe that accepts a variable number of arguments, `just` does not preserve the quoting.

In `justfile`:
```just
test *args:
    ./test.sh {{args}}
```
In `test.sh`:
```sh
#!/usr/bin/env sh

for arg in "$@"; do
    echo "$arg"
done
```

The output of `just test a "b c"` is:
```
./test.sh a b c
a
b
c
```

I tried quoting the `{{args}}` in the justfile, but that just made it one string of "a b c".

**Comment by casey** [comment]
This is definitely a downside of the way `just` works. `just` doesn't know anything about the contents of recipes, and just directly inserts the text value of arguments directly into recipes.

The best way to work around this is to set the `positional-arguments` setting, which causes `just` to pass arguments as positional arguments to recipes, then you can use the `"$@"` notation as usual:

```
set positional-arguments

test *args:
  test.sh "$@"
```

Does this work for your use-case?

**Comment by jmcantrell** [comment]
It works.
