### ISSUE TITLE
Create a tree sitter parser for highlighting Justfiles

### ISSUE THREAD

**Issue by IndianBoy42** [casey/just#889]
This should give better performance than vim-just. 

I could start working on it, do you have a 'formal specification' of the language anywhere that I could look at?

**Comment by casey** [comment]
Nice! You might want to check out [GRAMMAR.md](https://github.com/casey/just/blob/master/GRAMMAR.md), it's mostly complete, although some things, like indentation, are described precisely.

**Comment by IndianBoy42** [comment]
Just an update: 

I have implemented the parser in [this repository](https://github.com/IndianBoy42/tree-sitter-just.git). It is able to parse a whole file with a lot of features used.

I still have to write the queries that make it able to do highlighting and folding in nvim, which will probably entail refactoring the parser a bit. Write now its mostly a direct copy from `GRAMMAR.md`, but I had to change some things around to work in treesitter

**Comment by casey** [comment]
Very nice! Let me know when it's ready for users, and I'll mention it in the readme.

**Comment by IndianBoy42** [comment]
Hey btw the plugin is somewhat usable, it does the highlighting and even folds and textobjects through treesitter works. I'd love feedback on if the highlight groups are defined correctly. There are a very few bugs in the parser left.

I think its ready to be shown to users, having more eyes on it, who may be inclined to help would be great.

**Comment by casey** [comment]
Awesome, very cool! I opened a PR to mention it in the readme: #951

Let me know if I should re-open this issue, but I think it's reasonable to close, now that it's in semi-beta.
