### ISSUE TITLE
Unable to install or upgrade to 0.9.8 using Linuxbrew

### ISSUE THREAD

**Issue by yonkeltron** [casey/just#899]
Hey,

Huge fan of Just over here, using it instead of make and loving life. Thanks for all of your hard work!

Just letting you know that as of `0.9.8` I am unable to install or upgrade Just using Linuxbrew. Please find below the relevant snippets:

```text
$ brew install just                                                                                                           16:55:51
==> Downloading https://github.com/casey/just/archive/0.9.8.tar.gz
==> Downloading from https://codeload.github.com/casey/just/tar.gz/0.9.8
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: dbb0bec2ccda354e07d25eb5bdd98151edb84ca7a763a2cfb885841b7578f0a4
  Actual: 0c464c3a06d40e68e1014e583ec1733aa16bca5796fb42874438dec9f4a464a4
    File: /home/yonkeltron/.cache/Homebrew/downloads/fa9732e84bb6b6b083e65f45b878b31be38b4379832167bf66116c60663b5ebd--just-0.9.8.tar.gz
To retry an incomplete download, remove the file above.
```

I tried this on another box and got an identical error.

Unfortunately, I don't have a macOS device to test this on right now in order to confirm a more widespread problem.

Here's some info about my environment:

```bash
$ uname -a                                                                                                                    16:55:58
Linux penguin 5.4.109-26094-g381754fbb430 #1 SMP PREEMPT Sat Jun 26 21:31:00 PDT 2021 x86_64 GNU/Linux
$ brew --version                                                                                                              16:59:29
Homebrew 3.2.1
Homebrew/homebrew-core (git revision d006c656f0d; last commit 2021-07-06)
```

Is there additional information I can provide to help out?

Thanks,
+Jonathan

**Comment by casey** [comment]
Hi Jonathan,

Sorry for the inconvenience! There was an issue with the 0.9.8 GitHub release, and I had to delete and recreate the release. Linuxbrew must have picked up the release before I deleted it, and still has the hash of the older version.

I was going to open an issue in Linuxbrew, but the issue template requires a bunch of output from the `brew` command, which I can't provide because I don't have a linux box.

Would you mind opening an issue there? I'll include what I was going to write below.

Best,
Casey

---

Hi there,

I'm the maintainer of `just`, and I had some difficulties recently with the 0.9.8 release, which I fixed by deleting and re-creating the release binaries. I think that the current `bottle` for `just` has the hashes of the deleted binaries, and so needs to be updated.

Sorry for the inconvenience!

Best,
Casey

**Comment by casey** [comment]
And thank you for the kind words!

**Comment by nandahkrishna** [comment]
Thanks for the report `@yonkeltron` and the clarification `@casey`. `@cho-m` created a pull request to fix this, and it has been merged, so this should be resolved now (may take a few hours for the Linuxbrew repository to be updated with the fix).

**Comment by casey** [comment]
@nandahkrishna Thank you! I'm really curious, how do new versions of `just` get picked up by Linuxbrew? Is it a manual process, or does it happen whenever a new GitHub or crates.io release is published?

**Comment by casey** [comment]
@yonkeltron Let me know when you're able to install the new version, and I'll close this.

**Comment by nandahkrishna** [comment]
> I'm really curious, how do new versions of `just` get picked up by Linuxbrew? Is it a manual process, or does it happen whenever a new GitHub or crates.io release is published?

When a new release of `just` is created on GitHub, a Homebrew contributor creates a pull request to the homebrew-core repository (this is often automated using a GitHub Actions workflow that detects new releases – see Homebrew/homebrew-core#80539). The Linuxbrew formula repository (linuxbrew-core) is synced with homebrew-core by a maintainer everyday (hence the delay in propagating the fix).

There's an ongoing effort by the maintainers to merge the linuxbrew-core and homebrew-core repositories, which should be complete in the coming weeks/months, so when a formula is updated, macOS and Linux users of Homebrew get the updates at the same time.

**Comment by casey** [comment]
@nandahkrishna Dope, thanks for the the info!

**Comment by yonkeltron** [comment]
Wow what a great writeup from @nandahkrishna!

In terms of this specific issue, I can now install Just (0.9.8_1) on my ChromeOS device using Linuxbrew:

```
$ brew install just
...snip...
==> Pouring just--0.9.8_1.x86_64_linux.bottle.tar.gz
...snip...
```

Ok so I am going to close this issue now and leave it be but keep testing on other devices as they become available to me just to make sure. Hope this sounds reasonable!

Thanks,
+Jonathan

**Comment by casey** [comment]
@yonkeltron Great, thanks!
