### ISSUE TITLE
Is there a way to access Just variables in a backtick command evaluation

### ISSUE THREAD

**Issue by IndianBoy42** [casey/just#905]
I want to have a global Just variable CC for which C compiler to use, I have to extract the corresponding C++ compiler (gcc -> g++). Simple if statements in bash should be good enough for the common compilers, but I can't figure out how to get the value of the CC variable.

There are a few other use cases, like using which to get the absolute value of a global just variable (and put it into another global just variable)

I guess the reason this isn't easy/available is that it would make it unclear what order the global just variables should be evaluated, although line order and/or command evaluations non commands should suffice for most use cases

**Comment by casey** [comment]
This is definitely something that I'd like to support! I think this is the same as #11, and there's an in-progress PR that implements this: #822. If you had something different in mind, feel free to reopen this issue.
