### ISSUE TITLE
Just Failed to activate virtualenv

### ISSUE THREAD

**Issue by danieltomasz** [casey/just#912]
After trying to activate virtualenv and run an jupyter instance  from it ( pyenv's shim approach works by adding a directory to  $PATH)

```
pyenv activate assr

Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.

error: Recipe `jupyter` failed on line 4 with exit code 1
```

Is there a way to receive all variables from the current she'll for just recipe?

EDIT after  including before starting virtualenv

```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

```
Error is 
```
(eval):13: precmd_functions[(r)_pyenv_virtualenv_hook]: parameter not set
```

**Comment by danieltomasz** [comment]
Worked when I added `  #!/bin/sh` 🤦 . Thanks for making `just`!

**Comment by casey** [comment]
Nice, glad you got it working!
