### ISSUE TITLE
Allow conditional export of variables

### ISSUE THREAD

**Issue by casey** [casey/just#922]
Something like:

```
export FOO := "hello" if "a" == "b"
```

The just variable `FOO` would always be defined, but would only be exported if the condition evaluated to true.

This syntax is quite weird, but it's the best I could come up with.

**Comment by casey** [comment]
cc @soenkehahn

**Comment by soenkehahn** [comment]
So the `just` variable `FOO` would always be defined, because `just` wouldn't allow variables that may dynamically be set or unset?

If that's true, the syntax would ideally reflect that. Not sure how to do that though...

**Comment by casey** [comment]
Yeah, exactly.

**Comment by casey** [comment]
Other weird ideas:

```
export(if x == y) NAME := EXPRESSION
```

```
(if x == y export) NAME := EXPRESSION
```

**Comment by soenkehahn** [comment]
And this:
``` just
NAME := EXPRESSION
if x == y {
  export NAME
}
```

**Comment by casey** [comment]
I wrote a PR! I started it because I thought it would be easy, but then it turned out that there were all these things I forgot I would have to do.

I'm leaning towards the `export(if x == y) NAME := EXPRESSION` syntax:

- The condition is parenthetical, which kind of indicates that it's optional.
- It's next to the `export` so it's more obvious that it only affects the export.
- It can be parsed in a single item, so it doesn't need a consistency check, which you would need if they assignment and the conditional export were separate, and the conditional export referred to the assignment by name.

What do you think?

**Comment by casey** [comment]
We discussed this a bit offline, and came to the conclusion that the syntax and semantics were pretty weird, especially that `just` variables are always available, whether or not they're exported, and it was important that the syntax reflect that, but we couldn't come up with a good way to do that, so we should give up on this for now.
