### ISSUE TITLE
Default justfile name

### ISSUE THREAD

**Issue by asdf8dfafjk** [casey/just#930]
Hello, would you happen to be open to consider another name for the default justfile? Having too many files in a directory can be distracting so I've taken to using `.just` as my default name but this causes certain features to be unavailable. (e.g. running recipes from parent directories).

(Whether I'm not able to do something isn't really a basis but I'm wondering if removing clutter could be a basis for you to rename? Or making it a configurable list in the proposed config?)

**Comment by casey** [comment]
I think `.justfile` would be a reasonable additional name for `just` to look for when searching for a `justfile` to run.

There are some downsides I can think of:

- You might be able to trick someone into running recipes from a `.justfile` that they didn't know was there, e.g. in cloned repo.
- Users might get confused when `just` starts running recipes from a `.justfile` that they didn't see.

But I don't think those downsides are too bad, so I'm definitely open to it.

**Comment by asdf8dfafjk** [comment]
Cool.

Btw, I added the icon support to broot (https://github.com/Canop/broot/pull/299/) so I definitely know a tiny bit of rust and can help you with the config work. Can you tell me what the current status or the work is (and any pointers to code) and then I'll try to help.

**Comment by asdf8dfafjk** [comment]
Oh I just noticed that you're talking about making it hardcoded [ `justfile` `.justfile` ] and not configurable. Why not configurable I wonder? Then the blame lies squarely on user? :rofl:

**Comment by casey** [comment]
> Oh I just noticed that you're talking about making it hardcoded `[ justfile .justfile ]` and not configurable. Why not configurable I wonder? Then the blame lies squarely on user? 🤣

I do like the idea of avoiding blame, but:

- Hard-coding it is an easier, smaller change.
- `just` doesn't have a config file, so allowing configuration of the justfile name would require passing a flag, which would be annoying to remember.
- I don't think I've gotten another request for custom justfile names, so I don't know if there's a use-case for arbitrary configuration.
- Being able to hide a justfile seems generally useful, so supporting it out-of-the-box would be nice, and would mean that everyone would use the same name for hidden justfiles by default.

@soenkehahn What do you think of making `just` look for files called `.justfile`, in addition to files named `justfile`? My primary concerns are around security and confusion, i.e. users execute recipes in justfiles they don't know exist, which are either malicious, or just unexpected. I think those worries are relatively minor, and supporting hidden config files seems so common for tools, so it seems worth doing to me, but I wanted to get another opinion.

**Comment by soenkehahn** [comment]
> @soenkehahn What do you think of making `just` look for files called `.justfile`, in addition to files named `justfile`? My primary concerns are around security and confusion, i.e. users execute recipes in justfiles they don't know exist, which are either malicious, or just unexpected. I think those worries are relatively minor, and supporting hidden config files seems so common for tools, so it seems worth doing to me, but I wanted to get another opinion.

I agree that these concerns seem fairly minor. I feel the way `just` works, you should only execute it in directories that you trust anyways. So this would seem fine to me. Some other questions though:

- What would happen if both `justfile` and `.justfile` exist?
- For @asdf8dfafjk: If `just` would hardcode this and allow `.justfile` but not `.just` would this solve your problem? Or are you relying on these files being called `.just` for some reason?
- Also for @asdf8dfafjk: I'm assuming that you're using the `-f .just` flag. Are you mostly interested in saving yourself from typing that flag, or are you mostly interested in being able to run recipes from parent directories with `.just` files? Depending on what you want to solve, there could also be other solutions.

**Comment by casey** [comment]
> * What would happen if both `justfile` and `.justfile` exist?

If they exist in the same directory, `just` would refuse to run and print out a warning. (It already does this if, on a case-sensitive file system, justfiles exist with multiple cases.) If one is in a closer ancestor than the other, it would find the closer one first and use that one.

**Comment by soenkehahn** [comment]
> If they exist in the same directory, `just` would refuse to run and print out a warning. (It already does this if, on a case-sensitive file system, justfiles exist with multiple cases.) If one is in a closer ancestor than the other, it would find the closer one first and use that one.

Strictly speaking, this would then be a breaking change. In case someone has both a `justfile` and a `.justfile` in a directory.

**Comment by asdf8dfafjk** [comment]
@soenkehahn To answer the questions you asked:

1) I only want to hide, `.just` is not a hard requirement for me. (could be .justrecipes as well e.g.)

2) I want to be able to use parent directory's recipes seamlessly. Since all my recipes are in `.just` and not `justfile`, `just` doesn't look for them.

**Comment by soenkehahn** [comment]
@asdf8dfafjk: Thanks for the answers!

Yeah, then there's also alternative solutions:

1. Make `just` look for the filename that's passed in through `-f`, even in parent directories. So you can do `just -f .justfile` and it would look in `.justfile`, but also `../.justfile`, `../../.justfile`, etc. This is really weird though. First, when passing in a `-f` flag, I would strongly expect for this to be interpreted as a relative filepath to the working directory and nothing else. Secondly, what should happen when users pass in e.g. `-f something/justfile`? Would it also look in `../something/justfile` and `../../something/justfile`? That'd be really weird.
2. Introduce another flag, e.g. `--justfile-name` or `--justfile-pattern`. That would allow to pass in a pattern that will be looked for in the current directory and all parents.

After writing down these alternatives I actually think that the original idea of teaching `just` to accept `.justfile` as an alternative to `justfile` is probably best. Sorry for the noise. Hope this helps to think this through and make a decision.

**Comment by casey** [comment]
@soenkehahn Thanks for thinking through it! I really appreciate the second opinion. I often don't full trust myself when thinking about whether a features might have unintended consequences, or not be the right way to do things, so the noise is greatly appreciated.  I agree with what you wrote, `--justfile-name` is also a reasonable solution, but just accepting `.justfile` is probably just nicer. I just merged #931, which adds `.justfile` to the filenames that `just` will look for.

I'll release `0.10.0` soon, version bumped because this is technically a breaking change, although not one that I expect to be disruptive.

**Comment by casey** [comment]
Fixed in #931.

**Comment by casey** [comment]
@asdf8dfafjk I just released 0.10.0, which includes this feature. It's published on Cargo, and binaries are available on [the release page](https://github.com/casey/just/releases/tag/0.10.0).
