### ISSUE TITLE
Add preview and command-line argument support for default chooser

### ISSUE THREAD

**Issue by terror** [casey/just#947]
When `--chose` is invoked without specifying a chooser, it uses `fzf` with recipe names present in the projects `justfile` without a preview window for currently highlighted recipes. If a recipe is selected it invokes `just` with that recipe name without prompting the user to pass in any command-line arguments. 

Consider adding a preview window to display the recipes contents during the search in addition to being able to pass in command-line arguments to recipes that take them.

Here's a rough idea for how this may look like:

[![asciicast](https://asciinema.org/a/eNi5cZw4BZLcplHq4Ae1aN8nN.svg)](https://asciinema.org/a/eNi5cZw4BZLcplHq4Ae1aN8nN)

**Comment by casey** [comment]
This is a great idea. I think this should be added once we switch to skim (#939) as the default chooser. It'll be easier to add features to the choosing command if we know for sure what chooser we're invoking.

This will require some tweaks to how the command works. Currently, the choose subcommand can only take recipes, to take arguments, it'll have to invoke the `run` command.

**Comment by Qeole** [comment]
Looks like this was implemented in https://github.com/casey/just/pull/1539?

**Comment by casey** [comment]
Nice, yup, this can be closed.

**Comment by XBagon** [comment]
Am I missing something? It stills explicitly filters out recipes with arguments, which I don't understand why it does in the first place, as they execute fine if you just type out the argument. (Which requires typing the whole recipe name as well, but at least it supports in finding the recipe)
https://github.com/casey/just/blob/abec307f69e5355254e7e7791c73b0ff3dea8d81/src/subcommand.rs#L201
Also I cannot find the here proposed feature and am unsure how it relates to https://github.com/casey/just/pull/1539.

**Comment by casey** [comment]
I think this issue was about adding a preview window, which it now does.

> which I don't understand why it does in the first place, as they execute fine if you just type out the argument

Don't they not work? If I have a recipe with a mandatory argument, after I hit return, won't it fail since the argument isn't provided?

**Comment by XBagon** [comment]
> I think this issue was about adding a preview window, which it now does.

[Add preview and **_command-line argument support_** for default chooser](https://github.com/casey/just/issues/947)
I guess this is a two part issue, which I didn't even realize until now.
The video showcases the imagined argument support pretty well at the end. After selecting `run`, you can type in the arguments.

>Don't they not work? If I have a recipe with a mandatory argument, after I hit return, won't it fail since the argument isn't provided?

I could have sworn it did work with an optional argument (as recipes with mandatory arguments aren't shown), but I cannot reproduce it now.

**Comment by casey** [comment]
It definitely does work with optional arguments. If it's filtering out recipes which can take zero arguments, that's definitely a bug.

**Comment by XBagon** [comment]
It is shown, but I cannot put the argument after and then successfully execute.
Which I thought I managed to do, but I take that back :sweat_smile:.

Also note the run command in the example, which does have mandatory arguments and is still shown.
So I'd still like this to happen, maybe it needs a new issue?

**Comment by casey** [comment]
I'm not sure that `just` can help with this, isn't it up to the chooser whether it lets you type in an argument value or otherwise modify the command line before execution?

**Comment by XBagon** [comment]
Most choosers are probably limited to searching and picking items from a list, this sounds very specialized.
So after selecting, it could either:
- drop the user back into the terminal with `just recipe ` (probably not so easy)
- implement its own argument form (probably not worth the effort)
- well, just print out the current command. (easy and can help at least a little bit)

I think it just bugs me recipes with arguments are hidden. 😄 

Especially when you then accidentally click on one with defaults and wonder why and what it just did, without asking for further instructions. 
The list could list recipes with written out default args or maybe just remove all recipes with ANY argument. Then it's clear the user needs to create separate recipes for easy access.
