### ISSUE TITLE
if-else is not doing string substitution

### ISSUE THREAD

**Issue by edaqa-uncountable** [casey/just#954]
I can't seem to get string substitution to work inside a conditional.  Here is the simplified target I'm trying to write:

```
pytest pattern="all":
    {{ python }} -m pytest {{ if pattern == "all" { "" } else { "-k {{pattern}}" } }}
```

If I run `just pytest something` it produces the command-line `python -m pytest -k {{pattern}}` and not the desired `python -m pytest -k something`.

----

As a workaround to my immediate need I've resorted to two conditionals.

```
    {{ python }} -m pytest {{ if pattern == "all" { "" } else { "-k" } }} {{ if pattern == "all" { "" } else { pattern } }}
```

**Comment by casey** [comment]
Sorry you're running in to this! Interpolation doesn't yet work in strings, there's an open pr #822, but it's stalled at the moment.

For now, you could try concatenation with `+`:

```
pytest pattern="all":
    {{ python }} -m pytest {{ if pattern == "all" { "" } else { "-k " + pattern } }}
```
