### ISSUE TITLE
need help installing on WSL

### ISSUE THREAD

**Issue by epogrebnyak** [casey/just#960]
I run bash on Ubuntu/WSL and install just as:

```
curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to .
```

this creates file called `just`, but when running just I get:

```
# just
just: command not found
# ls -l just
-rwxrwxrwx 1 root root 4594672 Sep 10 17:12 just
```

Any idea what am I doing wrong?

**Comment by epogrebnyak** [comment]
Same effect if I drop a binary from releases

**Comment by epogrebnyak** [comment]
Perhaps different issue but cargo fails to build just with follwoing error:

```
error[E0658]: use of unstable library feature 'str_split_once': newly added
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/just-0.10.1/src/shebang.rs:36:8
   |
36 |       .rsplit_once(|c| matches!(c, '/' | '\\'))
   |        ^^^^^^^^^^^
   |
   = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information
```

**Comment by casey** [comment]
Hi @epogrebnyak!

> this creates file called `just`, but when running just I get:

I think you'll need to call just with `./just` if it's in the current directory. To run it as `just` you'll have to add it to that is in your `PATH` variable. For example:

```
mkdir ~/bin
curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
export PATH="$PATH:$HOME/bin"
just --help
```

Does that work for you?

> Perhaps different issue but cargo fails to build just with follwoing error:

Which version of Rust is giving you this error?

**Comment by twiebe** [comment]
> > Perhaps different issue but cargo fails to build just with follwoing error:
> 
> Which version of Rust is giving you this error?

@casey I'm seeing the exact same error on an Ubuntu 18.04 with rustc 1.51.0.

**Comment by casey** [comment]
> @casey I'm seeing the exact same error on an Ubuntu 18.04 with rustc 1.51.0.

Thanks for confirming. I opened #966 to properly define Just's MSRV going forward.

**Comment by epogrebnyak** [comment]
> ```
> mkdir ~/bin
> curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
> export PATH="$PATH:$HOME/bin"
> just --help
> ```

This work perfectly, thank you - maybe I could make PR to README.md?

**Comment by casey** [comment]
> This work perfectly, thank you - maybe I could make PR to README.md?

Excellent. Good idea, I just added detailed instructions in #978.
