### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by xonixx** [casey/just#963]
The experpt from [README](https://github.com/casey/just#environment-variables-1). Is it just me or the line  `export FOO := "world"` should be `export WORLD := "world"`?

----
Exported variables and parameters are not exported to backticks in the same scope.

```
export FOO := "world"
# This backtick will fail with "WORLD: unbound variable"
BAR := `echo hello $WORLD`
```

**Comment by casey** [comment]
Nice, good catch!
