### ISSUE TITLE
Overriding variables from the command line does not survive nested `just` calls

### ISSUE THREAD

**Issue by hendrikmaus** [casey/just#965]
Using `just 0.10.1`, given the following `justfile`:

```
set dotenv-load := false

some_bool := "true"

build:
  #!/usr/bin/env bash
  set -euo pipefail

  if [[ {{some_bool}} == "false" ]]; then
    echo "some_bool: false"
    exit 0
  fi

  echo "some_bool: true"

test:
  just build
  echo "more work here"
```

I encountered that the nested `just` call in the `test` recipe will not pass on any overridden variables given by the original call. I.e.:

```shell
$ just some_bool=false test
just build
some_bool: true
echo "more work here"
more work here
```

The fix is quite obvious:

```diff
test:
-   just build
+   just some_bool={{some_bool}} build
```

However, I would be keen to hear some thoughts on this. I suppose it is not easily fixable, as nested `just` calls will likely cause the parent process to shell out to a child (tbh. I haven't read the code on it yet).

**Comment by casey** [comment]
Thanks for detailed issue!

Depending on what your actual use-case is, you might be able to make use of subsequent dependencies. Given the following justfile:

```
bar:
  @echo bar

baz:
  @echo baz

foo: bar && baz
  @echo foo
```

Executing `foo` will run `bar`, then `foo`, then `baz`:

```
$ just foo
bar
foo
baz
```

(The `@` are just there to suppress recipe line echoing, and don't affect execution.

Does this work for your usecase?

There are a lot of usecases that this doesn't help with, for example if you need to run a recipe in the middle of a recipe, if you need to run a recipe conditionally, or if you need to feed input into the recipe.

> I suppose it is not easily fixable, as nested just calls will likely cause the parent process to shell out to a child.

This is correct, just doesn't look at recipe bodies, so it just executes `just` like it would any other command. I've thought about ways to get this to work, like passing `just` variables to nested calls in environment variables, but a `just` invocation has a lot of state, including command-line arguments, settings, and variables, and making sure that these are all passed to child processes would be complex and error-prone.

**Comment by hendrikmaus** [comment]
Thanks for the prompt and insightful response @casey. 

Your suggestion comes to the rescue for my usecase 👍🏻

**Comment by casey** [comment]
Awesome, glad that worked!
