### ISSUE TITLE
Define MSRV and enforce on CI

### ISSUE THREAD

**Issue by casey** [casey/just#966]
Just currently doesn't build with rust versions prior to 1.52, due to the use of `str::rsplit_once` in `shebang.rs`, reported in #960.

We should define a MSRV policy, and enforce it on CI so we don't accidentally break supported Rust versions.

The use of `str::rsplit_once` isn't crucial, so I'll revert it, and see how much work it is to get Just working with older versions of Rust. Once we get to a version that would require too much work to support, the version after that will be declared the MSRV.

I'm not sure how the MSRV will be increased moving forward. I'll try to be conservative, but if there are shiny new language features that would greatly benefit the codebase, or if an important dependency bumps its MSRV, that will probably mean that Just's MSRV will get bumped.

MSRV bumps will not be reflected in Just's version.

**Comment by casey** [comment]
With some not-so-painful changes, I was able to get everything working on 1.46, so that will be the MSRV going forward.

**Comment by epogrebnyak** [comment]
What is MSRV btw?

I found

MSRV | Modified Semi-Solid Rappaport Vassiliadis (microbiology)
MSRV | Multiple Sclerosis-Associated Retrovirus
MSRV | Message Switch Rekeying Variable (US DoD)
MSRV | Multi Sensor Relief Valve

**Comment by casey** [comment]
MSRV stands for "minimum supported Rust version", so just the earliest version of the Rust compiler that the project works with.
