### ISSUE TITLE
unknown start of token when using docker inspect --format

### ISSUE THREAD

**Issue by rizary** [casey/just#971]
here is my code:

```bash
just x:
  docker inspect --format "{{json .State.Health.Status }}" $(docker-compose ps -q)
```

The pointer is pointing at `.` in the `.State`

**Comment by casey** [comment]
`{{` is treated specially within recipe bodies, since they start interpolations. See [this section of the readme](https://github.com/casey/just#escaping-) for some options for dealing with this.

The easiest way to fix this is probably to use `{{{{`:

```
just x:
  docker inspect --format "{{{{json .State.Health.Status }}" $(docker-compose ps -q)
```
