### ISSUE TITLE
argument using a just variable not showing

### ISSUE THREAD

**Issue by tomikais** [casey/just#972]
Hi @casey,

first of all I wanna thank you for all your work and this awesome tool. I have an issue and don't know if it's a bug or my fault^^

```just
@hello_world: (_print "{{string}}! 123")

string := 'hello world'

@_print VALUE:
    echo {{VALUE}}
````
When executing `just` it's printing: "{{string}}! 123" 

Kind regards, Thomas

**Comment by casey** [comment]
Hi Thomas,

Thank you for the kind words!

At the moment, string interpolation is only supported in recipe bodies, not inside string literals. #822 is open to fix this, but it's stalled at the moment.

You can use concatenation with `+` instead:

```
@hello_world: (_print string + "! 123")

string := 'hello world'

@_print VALUE:
    echo {{VALUE}}
```

Hope that works!

**Comment by tomikais** [comment]
Thank you for your fast and helpful reply! :-)
