### ISSUE TITLE
How to use positional arguments inside a string with single quotes and bracket?

### ISSUE THREAD

**Issue by max-block** [casey/just#973]
```
set positional-arguments

print_name name:
    echo '{input: $1}'
```
`just print_name max` outputs: `{input: $1}`

How to fix it to outputs `{input: max}`?

P.S. In my real case I have to use single quotes. Thank you!

**Comment by casey** [comment]
Could you close and re-open the quotes around the variable? Like so:

```
set positional-arguments

print_name name:
    echo '{input: '$1'}'
```

**Comment by max-block** [comment]
Thank you, it works!

**Comment by casey** [comment]
Great!
