### ISSUE TITLE
--color never doesn't seem to work

### ISSUE THREAD

**Issue by psibi** [casey/just#975]
Example snapshot reproducing it:

![just-color](https://user-images.githubusercontent.com/737477/134290641-08b4a3c5-d91b-49a5-b510-7da4bc068b71.png)

Version used:

```
❯ just --version
just v0.9.1
```

**Comment by casey** [comment]
It looks like you're running `just -list` from a recipe in your justfile, like this:

```
default:
    just --list
```

In this case, the sub-invocation of just have access to the outer invocation's `--color` flag, so it defaults back to `--color auto`.

You could try this instead:

```
default:
  just --list --color never
```

Does that work?

**Comment by psibi** [comment]
Yeah, silly me. Thanks!

**Comment by casey** [comment]
No worries! Glad you got it working.
