### ISSUE TITLE
Global justfile not work?

### ISSUE THREAD

**Issue by hustcer** [casey/just#980]
I have linked a `~/.global.justfile` according to the manual in readme [here](https://github.com/casey/just#non-project-specific-justfile), but it does not work:
```bash
➜  git:(feature/push) ll ~/.global.justfile
lrwxr-xr-x  1 abc  staff    49B Sep 29 12:30 /Users/abc/.global.justfile -> /Users/abc/github/nu/Justfile
➜  git:(feature/push) just --justfile ~/.global.justfile --working-directory .
error: No justfile found
```

**Comment by casey** [comment]
I just tried it out and it works for me, so I suspect something else is wrong.

Can you try doing:

```
echo foo: > ~/.global.justfile
just --justfile ~/.global.justfile --working-directory . --verbose
```

It should print `===> Running recipe `foo`...`

Also, what version of `just` are you using?

**Comment by hustcer** [comment]
@casey Thanks, it works. I have found that It's caused by my justfile:
```
# List available commands by default
default:
    @just --list --list-prefix '··· '
```
