### ISSUE TITLE
Support --justfile in completions

### ISSUE THREAD

**Issue by lud** [casey/just#982]
Hi, 

I don't know if that is even possible, but I would like to know if the completions scripts (I use zsh) could understand that a `--justfile myfile` option is given and list commands from that file instead of from the justfile in the current directory.

Thank you.

**Comment by casey** [comment]
This isn't yet supported, unfortunately. Closing as a dupe of #936, feel free to reopen if you had something else in mind.

**Comment by lud** [comment]
Indeed it is a duplicate !
