### ISSUE TITLE
Can we make path join() func accepts a variable number of arguments?

### ISSUE THREAD

**Issue by hustcer** [casey/just#986]
I want to make my `Justfile` run on both Windows and macOS, for the following lines:
```bash
_termix := env_var('TERMIX_DIR')
# Used to handle the path separator on different OS
_s := if os_family() == "windows" { '\' } else { '/' }
AGE_SCRIPT :=  join(_termix, 'git' + _s + 'age.nu')
```
If `join()` func accepts a variable number of arguments, that would be much easier:
```bash
_termix := env_var('TERMIX_DIR')
AGE_SCRIPT :=  join(_termix, 'git', 'age.nu')
```
The actual path of my script is like `/Users/abc/termix-nu/git/age.nu` on mac and `D:\work\termix-nu\git\age.nu` for Windows. 
Thanks.

**Comment by casey** [comment]
I wouldn't be opposed to this. `join` should probably accept two or more arguments.

For now, you can do `join(a, join(b, join(c)))` but that's pretty gross.
