### ISSUE TITLE
Inline just variable in backtick invocation

### ISSUE THREAD

**Issue by mihaigalos** [casey/just#995]
Hi,

So I'm trying to use a `just` variable inside a backtick invovation using the following syntax:
```bash
bazel_remote_cache_port := "9091"
remote_cache := `nc -zvw3 $DEVELOPER_PC_IP {{bazel_remote_cache_port}} && echo --remote_cache=http://$DEVELOPER_PC_IP:{{bazel_remote_cache_port}} || echo -n ""`
```

Is this a limitation atm?

**Comment by casey** [comment]
Hi Mihai, that is indeed not possible at the moment. This is a feature that I definitely want to implement, and there's a PR implementing it, but it's a bit stalled at the moment. See #11 for the issue and #822 for the PR.
